### ISSUE TITLE
[FEATURE] Allow customization of TLS parameters

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1046]
**Is your feature request related to a problem? Please describe.**
Currently, TLS parameters like ciphers and options (no-sslv3, etc), are not user-configurable during the installation of Harvester. This can cause issues in certain environments which require a specific set of ciphers, or which explicitly need to exclude deprecated and insecure versions like TLS 1.0.

**Describe the solution you'd like**
Make TLS parameters configurable from the Harvester deployment method. In the k3os version that could be achieved by using the configuration data passed on by config_url.

**Comment by janeczku** [comment]
This relates to the ability to configure TLS options for the Harvester API HTTPS endpoint via the `config-create`.

**Comment by johnliu55tw** [comment]
Waiting for https://github.com/harvester/harvester/issues/761 so that we could configure TLS settings of Ingress, not rancher itself.

**Comment by guangbochen** [comment]
The PR for #761 is merged, will need to add a new setting of the TLS support, @johnliu55tw can please help to follow it, thanks.

**Comment by n313893254** [comment]
Hi，@johnliu55tw. UI has merged the PR, you can use the latest UI to verify the issue.  If you have any problems, please let me know. thx

**Comment by johnliu55tw** [comment]
@n313893254 UI LGTM, I'll move this to ready for testing, thanks!

**Comment by johnliu55tw** [comment]
Please see https://github.com/harvester/harvester/pull/1615 for how to change SSL parameters.

**Comment by lanfon72** [comment]
Verified the feature will work as expected when the input is totally correct, otherwise, the dashboard will break and can't reach anymore.

For **Protocols**, UI lists as below, but actually in 2021, only `TLSv1.2` and `TLSv1.3` will work on modern browser.
(`TLSv1.0` and `TLSv1.1` has been deprecated in most browsers since 2020)
![image](https://user-images.githubusercontent.com/5169694/145427269-40b245f4-4ab1-4cf8-8f43-08f34b8b853a.png)
![image](https://user-images.githubusercontent.com/5169694/145431404-c4ac622f-1bd1-4824-a5b8-ca13b1615e11.png)

For **Ciphers**, It is just a input box to input anything without validation, although we expect users to edit this field carefully, but we even didn't notify user that ciphers should be separated by colon(`:`), not comma (`,`), or space.

Base on those reasons described above, I would tend to request some changes lists below:
1. remove deprecated protocols or add `(deprecated)` after the line
2. add a regex to validate cipher format, or change to use option list with all usable ciphers instead.
3. add some caveats in description or document for recovering.

Here is the sample validator
![image](https://user-images.githubusercontent.com/5169694/145440967-7e4b3740-ef4a-4cf3-8814-5fbece7f8b85.png)

Steps for recovering from error configured `ssl-parameters`:
1. Login to one of the server node
2. Execute `kubectl edit settings ssl-parameters`
3. Modify the last line of `value: '{....}'` into `value: '{}'`

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: master-655c251a-head
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to Advanced Settings, then edit `ssl-parameters`
3. Select **Protocols** `TLSv1.3`, then save
4. execute command `echo QUIT | openssl s_client -connect <VIP>:443 -tls1_2 | grep "Cipher is"`
5. Output should contain `error...SSL routines...` and `Cipher is (NONE)`
6. execute command `echo QUIT | openssl s_client -connect <VIP>:443 -tls1_3 | grep "Cipher is"`
7. Output should contain `Cipher is <one_of_TLS1_3_Ciphers>`[^1] and should not contain `error...SSL...`
8. repeat Step 2, then select **Protocols** to `TLSv1.2` only, and input **Ciphers** `ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256`
9. execute command `echo QUIT | openssl s_client -connect <VIP>:443 -tls1_2 -cipher 'ECDHE-ECDSA-AES256-GCM-SHA384' | grep "Cipher is"`
10. Output should contain `error...SSL routines...` and `Cipher is (NONE)`

[^1]: TLSv1.3 supported cipher suites: `TLS_AES_128_GCM_SHA256`, `TLS_AES_256_GCM_SHA384`, `TLS_CHACHA20_POLY1305_SHA256`, `TLS_AES_128_CCM_SHA256`, `TLS_AES_128_CCM_8_SHA256`

**Comment by lanfon72** [comment]
As I tested, in the **Step 8**, 2 ciphers (`ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256`) are assigned, but latter cipher `ECDHE-RSA-AES128-GCM-SHA256` will cause handshake failure, I'm not sure whether it is deprecated by nginx or should be a bug?

@guangbochen as we are going to release RC2 and current implementation already satisfy the original request, please check my concern in previous comment and move this issue to implement if we still have time to enhance it.

**Comment by guangbochen** [comment]
thanks @lanfon72, in regards to the above issues, I think it is better to add the following enhancement: cc @johnliu55tw @n313893254 
- [ ] add `(deprecated)` for those deprecated the TLS versions. - UI
- [ ] add a regex to validate cipher format -UI
- [x] document the recovering steps on the https://docs.harvesterhci.io/v1.0/settings/settings/ page, thanks. - Docs

**Comment by johnliu55tw** [comment]
Added recovering steps for SSL parameters settings to PR https://github.com/harvester/docs/pull/84

**Comment by lanfon72** [comment]
@guangbochen, I think we should also mark SSL as deprecated.
SSLv2 has been deprecated in [RFC6176](https://tools.ietf.org/html/rfc6176), and SSLv3 in [RFC7568](https://tools.ietf.org/html/rfc7568); and both of them have security concern ([CVE-2016-0800](https://nvd.nist.gov/vuln/detail/CVE-2016-0800) and [CVE-2014-3566](https://nvd.nist.gov/vuln/detail/CVE-2014-3566))

@n313893254 would you mind to add an additional checker to make sure the (ciphers) line will not start with colon(:)? the regex didn't filter out the colon, so some input like `:TLS_AES_128_GCM_SHA256` will pass the validator.

**Comment by guangbochen** [comment]
good catch, @n313893254 can u please help to add `SSLv2` and `SSLv3` as deprecated as well, thanks.

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head. Verified as fixed.
## Test Steps
1. Created self signed cert using `sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./harvester-selfsigned.key -out ./harvester-selfsigned.crt`
2. uploaded certs to Harvester
3. Verified that new certs were showing up in browser
![Screenshot from 2021-12-15 15-19-24](https://user-images.githubusercontent.com/83787952/146284379-397dd4b9-49fd-4597-98a2-a540fb7d6060.png)

**Comment by alexdepalex** [comment]
Is this also configurable through the harvester install configuration file? Or only in the UI?

**Comment by lanfon72** [comment]
this should be configurable via `system_settings` such like https://github.com/harvester/harvester/issues/761#issuecomment-993060101 did.
