### ISSUE TITLE
[BUG] iPXE installer kernels pull incorrect ISO during manual installation

### ISSUE THREAD

**Issue by antonym** [harvester/harvester#1129]
**Describe the bug**
When starting harvester from iPXE using the kernels, if harvester.install.automatic=true is dropped to force a manual install with the installer GUI, the ISO retrieved is from k3os repo instead of https://releases.rancher.com/harvester/v0.2.0/harvester-amd64.iso.

**To Reproduce**
1. Using these options (without harvester.install.automatic=true) k3os.mode=install console=ttyS0 console=tty1, run through a manual install of creating a cluster, the ISO retrieved comes from the k3os repo instead of the proper one for the release.

**Expected behavior**
The installer should pull the proper ISO for the installer kernels or allow the ability to set the ISO from the kernel command line.

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure: Proxmox KVM testing installation

**Comment by bk201** [comment]
Thanks for reporting!

Harvester 0.2.0 is based on k3os and it shares some kernel parameters with it. That's why k3os ISO is used by the installer if ` harvester.install.automatic=true` is not provided.

We'll switch to a new OS in the 0.3.0 release. k3os parameters will not work then.
The good news is[ we'll keep the configuration file format](https://docs.harvesterhci.io/v0.2/install/harvester-configuration/), so users should still use the same config in 0.2.0.

**Comment by guangbochen** [comment]
close in favor of the v0.3.0 release, please feel free to re-open it if u have countered any issues, thanks.
