### ISSUE TITLE
[BUG] dashboard metrics is incorrect

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1147]
**Describe the bug**

1. the dashboard capacity metric is not correct, it is `used `instead of `reserved`.
![image](https://user-images.githubusercontent.com/4569037/131866423-575a2ac2-8c62-4bf5-b8fe-93f6e0d93427.png)
2. get disk metrics from the longhorn nodes CRD instead as it is more accurate

**Environment:**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Close this as I verified it shows `Used` instead of `Reserved` now.
![image](https://user-images.githubusercontent.com/5169694/133406130-45baea62-d3cb-4c56-9821-22542d19f0f8.png)

Test Information
----
* Environment: Laptop, Vagrant, iPXE install
* Harvester Version: [v0.3.0-preview1](https://github.com/harvester/harvester/releases/tag/v0.3.0-preview1)
Verify Steps:
  - Clone https://github.com/harvester/ipxe-examples/commit/5e99d35b399e148caadef63c2ee93a49c01dda1f and modify settings.yml for 2 nodes
    (amount of Node is not a matter)
  - After Installed, browse dashboard and check it should display `Used` in capacity metric.
  - open `kubectl shell` then use `kubectl -n longhorn-system get lhn -oyaml` to check values in **storageAvailable** and **storageMaximum**.(it displayed as KB)
  - Check `storageMaximum/1024^3` should close to the displayed Max value, and `storageAvailable/1024^3` should close to the displayed `Max-Used` value.
    (In my Test Environment, `storageAvailable=4613734400, storageMaximum=19453001728`)

**Comment by weihanglo** [comment]
Sorry for leading you astray. For disk size there is a [`DiskStatus`] recording the info in longhorn Node CRD. Anyway, it's fixed now 🎉 

[`DiskStatus`]: https://github.com/longhorn/longhorn-manager/blob/393784c85b55a5498fe2cff80a0a3574ed543947/types/resource.go#L420-L427
