### ISSUE TITLE
[FEATURE] Disk devices used for VM storage should be globally configurable

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1241]
The user should be able to specify, during the installation, (e.g. as part of the create-config or join-config) the list of disk devices (e.g. by device path) that should be used for VM storage capacity across all nodes (given they share a consistent hardware configuration of course).
This should also cover the ability to exclude the root disk from the VM storage. Use case for excluding the root disk include:

-  use of a (cheaper) small capacity root disk
-  ensure isolation of IO resources between Harvester critical processes and VM workloads.

The current approach of having to configure additional disks post-install via the ui/api for each and every Harvester server separately does not work well for automated rollouts.

**Possible Implementation Details:**

The new option should be both supported in the create-config and join-config (the latter overriding the value specified in the former).
The option could either be a list of device paths (e.g. /dev/nvme0n1,/dev/nvme0n2) or a regex matcher.
When this option is specified by the user, the OS disk device configured in the install.device option is no longer added to the LH storage unless it's specifically included via the new option.

**Comment by janeczku** [comment]
The preferred implementation would be a configuration option that allows the user to define a conclusive list of all disks to use for LH storage where each list item can be either a regex expression or a fully qualified device name.

`storage_devices`: `/dev/nvme0*, /dev/sdb`

**Comment by johnliu55tw** [comment]
To add additional disks to Harvester right after installation, I'm thinking of utilizing Node Disk Manager (NDM):
- During the installation, create GPT with one EXT4 partition **with a certain label (e.g. `HARV_DISK_*`)** for those additional disks user specified.
- After installation and Harvester is up and running, NDM will scan the block devices. If it sees the partition has a label `HARV_DISK_*`, it automatically adds necessary spec fields (`provisioned`, `forceFormatted`, `mountPoint`, ...) and create corresponding CRD
- The disk should be added to Harvester during the reconciliation of NDM controller

@weihanglo @guangbochen please help to check if this is a feasible way to add disks automatically, thanks!

**Comment by johnliu55tw** [comment]
**2021-10-26 Update**: No need to add this functionality to the Installer UI. For now we could only implement this feature for PXE/Remote config installation.

**Comment by johnliu55tw** [comment]
# High-level design
## Some notes
- Seems like Longhorn always expects one default path to exist. We can change the path, but cannot disable it during the installation [REF](https://longhorn.io/docs/1.2.2/volumes-and-nodes/multidisk/#configuration)
  > By default, `/var/lib/longhorn` on the host will be used for storing the volume data. You can avoid using the default directory by adding a new disk, then disable scheduling for `/var/lib/longhorn`.
- Other than the method I mentioned in [my previous comment](https://github.com/harvester/harvester/issues/1241#issuecomment-950690838), we could also use Node Labels and Annotations to tell Longhorn to add additional disks as storage [REF](https://longhorn.io/docs/1.2.2/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes). However IMO we already have NDM for such tasks so I would prefer the NDM way. Besides I'm not sure whether NDM would work correctly with disks added by Longhorn itself.

## Brief flow
### If additional disks are specified:
- During the installation:
  1. Create GPT and one EXT4 partition for each disk
  2. Pick one disk and label its EXT4 partition with `LH_DISK_DEFAULT`
  3. For other disks, label their EXT4 partition with `LH_DISK_X`, where `X` is an integer to prevent duplicated labels
  4. Mount the `LH_DISK_DEFAULT` partition to `/var/lib/longhorn`
  5. Proceed with the usual installation process
- After installation and the system rebooted
  1. NDM should pick up those partitions labeled `LH_DISK_X` (except the `DEFAULT` one) and add them automatically.

### Other cases
- If there are no additional disks specified, the installation process is identical to the current one
- If users want to include the "root device" (the disk where Harvester is installed) to be one of the Longhorn storage disks, then the installer **will not** label any partition as `LH_DISK_DEFAULT` and will not mount any partition to `/var/lib/longhorn`. In this way, the default Longhorn storage disk would be the root device.

## Misc. stuff
- We could rely on cOS-toolkit to create partitions and filesystems [REF](https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/cloud_init/#stagesstage_idstep_namelayout).
- Instead of regex, I think Shell glob (wildcard matching) would be more intuitive and easier to use? @janeczku
  - `/dev/sd.*` vs. `/dev/sd*`

@guangbochen @weihanglo @bk201 any comments are welcome!

**Comment by bk201** [comment]
Another idea is to store rules in new/existed CR or configmap and let NDM checks if new BlockDeivces match the rules.
As a user, I feel it's much easier to manage storage in Harvester GUI.

Similar concepts in other storage:
- DriveGroup in DeepSea (Ceph)
  - https://documentation.suse.com/ses/6/single-html/ses-deployment/index.html#ds-drive-groups  
  - https://docs.ceph.com/en/pacific/cephadm/osd/#advanced-osd-service-specifications
- Storage selection in Rook
  - https://rook.io/docs/rook/v1.7/ceph-cluster-crd.html#storage-selection-settings

**Comment by guangbochen** [comment]
+1, I reckon using the `deviceFilter` is a good idea as it can be stored and configured later as a new setting config, the NDM should auto-provisioning and mount those volumes as an additional data volume if the value is specified. cc @weihanglo can help to add this feature if needed.
- for the longhorn's default `volume path` if it is not easy to config the additional volume as the default one during the ISO installation, we may just allow users to update it after the installation.

**Comment by johnliu55tw** [comment]
@guangbochen Indeed it's a bit tricky to use other disks as Longhorn's default volume path. I think I'll skip this part for now and focus on NDM part.

@bk201 Good idea. I could use other rules in addition to the filesystem label. I will look into this.

**Comment by weihanglo** [comment]
The design sounds reasonable to me. We can rollout something like `deviceFilter` at this moment. 
@johnliu55tw feel free to ping me if you need anything.

**Comment by johnliu55tw** [comment]
## Plans
- [ ] Add `--auto-add-path=/dev/sd*` feature to NDM
  - Specify a glob pattern, and NDM will add the disks/partitions match the pattern automatically to LH 
  - If a pattern matches both Disk and Partition, use the Disk first
- [ ] Add a new Harvester Setting to store NDM auto-add-path config global to the cluster
- [ ] Configure the Harvester Setting auto-add-path from installer config
- [ ] Reload NDM when ConfigMap changes
  - Probably implement this feature in Harvester controller

**Comment by guangbochen** [comment]
> ## Plans
> * [ ]  Add `--auto-add-path=/dev/sd*` feature to NDM
>   
>   * Specify a glob pattern, and NDM will add the disks/partitions match the pattern automatically to LH
>   * If a pattern matches both Disk and Partition, use the Disk first
> * [ ]  Create a ConfigMap to store NDM auto-add-path config for each Node
> * [ ]  Automatically adding Node specific auto-add-path to the ConfigMap while the Node is joining the cluster
>   
>   * `hostPath` volume to read Node-local config stored by Installer, and use a Job to add the Node-local config to ConfigMap
> * [ ]  Reload NDM when ConfigMap changes
>   
>   * Probably implement this feature in Harvester controller
>     Reload NDM when ConfigMap changes
>     Harvester Controller

- Prefer to store the default `path_filter` in the `settings.harvesterhci.io` CRD as this is a global setting and will be consistent on the UI page.
- We don't need to support per node config as the NDM is a Daemonset and also the default path filter should be consistent across all nodes
- Trigger NDM to restart from the Harvester controller LGTM when the `path_filter` value is changed.

**Comment by johnliu55tw** [comment]
@guangbochen If we don't support per-node config, we will wipe the matching disks on every Node and add them to Harvester/LH. I'm a bit worried about this behavior as some disks that were not meant to be used will be added accidentally.

But not supporting per-node config would make it much easier to implement, indeed.

**Comment by guangbochen** [comment]
IMO, a default `path_filter` means that `a list of disks should be included as an additional data volumes if the path is matching`, we can specify it on the setting's description to help users understand it properly. 

Additionally, users can use the regular expressions to specify the `path_filter` which should be able to include the majority of the cases. cc @weihanglo

**Comment by weihanglo** [comment]
> IMO, a default `path_filter` means that `a list of disks should be included as an additional data volumes if the path is matching`, we can specify it on the setting's description to help users understand it properly.

Actually, it's the opposite. `path_filter` at this moment _excludes_ all listed paths. But this can be tuned to our needs.

> Additionally, users can use the regular expressions to specify the `path_filter` which should be able to include the majority of the cases. cc @weihanglo

Agree. I am more likely to adopt bash-like glob, which is also common in path manipulations. Both ok for me though.

**Comment by weihanglo** [comment]
> - [ ] Add --auto-add-path=/dev/sd* feature to NDM
>    - Specify a glob pattern, and NDM will add the disks/partitions match the pattern automatically to LH
>    - If a pattern matches both Disk and Partition, use the Disk first

After reading the materials @bk201 provided, it seems that this is a common solution. I wonder that we may encounter naming inconsistent issue with only the simple `sda` device path.

> Reload NDM when ConfigMap changes

If we decide to go in ConfigMap way, why don't just put it inside NDM as its custom resource?

**Comment by johnliu55tw** [comment]
> > IMO, a default `path_filter` means that `a list of disks should be included as an additional data volumes if the path is matching`, we can specify it on the setting's description to help users understand it properly.
> 
> Actually, it's the opposite. `path_filter` at this moment _excludes_ all listed paths. But this can be tuned to our needs.

We could replace the function name `Exclude` with `Match` or something alike, so it makes sense in both cases. The filter only tells the caller whether it matched or not, then it's up to the caller to take care of the rest.

> > Additionally, users can use the regular expressions to specify the `path_filter` which should be able to include the majority of the cases. cc @weihanglo
> 
> Agree. I am more likely to adopt bash-like glob, which is also common in path manipulations. Both ok for me though.

@guangbochen just to confirm again, I also prefer shell glob compared to regex. I think we should support glob pattern here.

> If we decide to go in ConfigMap way, why don't just put it inside NDM as its custom resource?

@weihanglo From my perspective, the NDM should only take either env. variables or CLI arguments to keep it simple.

**Comment by johnliu55tw** [comment]
For anyone testing this feature, please check https://github.com/harvester/harvester/pull/1532

**Comment by TachunLin** [comment]
Verified **partial fixed** on master-b7e562d3-head. 

Verify disk storage auto provisioning config under the following scenarios. 
Only machine with BIOS firmware with MBR enabled can provision disk correctly according to pattern 
The other two scenario can't provision disk correctly and have some error. 

### Test Scenario: 
(Checked means verification `PASS`)
1. - [x] `BIOS` firmware + `No MBR` (Default) + Auto disk` provisioning config  
2. - [x]  `BIOS` firmware + `MBR` + Auto disk provisioning config
3. - [x]  `UEFI` firmware + `GPT` (Default) +  Auto disk provisioning config 

### Machine Setup
* **Scenario 1**: 
  Node type: `Create`
  |Firmware|Harvester install|Auto provision|
  |-----|--------|--------|
  |BIOS|No MBR|set|

  Node type: `Join`
  |Firmware|Harvester Install|Auto provision|
  |-----|--------|--------|
  |BIOS|No MBR|No set|
   
* **Scenario 2**: 
  Node type: `Create`
  |Firmware|Harvester install|Auto provision|
  |-----|--------|--------|
  |BIOS|MBR|set|

  Node type: `Join`
  |Firmware|Harvester Install|Auto provision|
  |-----|--------|--------|
  |BIOS|MBR|No set|

* **Scenario 3**: 
  Node type: `Create`
  |Firmware|Harvester install|Auto provision|
  |-----|--------|--------|
  |UEFI|GPT|set|

  Node type: `Join`
  |Firmware|Harvester Install|Auto provision|
  |-----|--------|--------|
  |UEFI|GPT|No set|


### Storage Setup on VM

  - 150GB IDE storage (IDE: /dev/sdb) -> Harvester
  - 60GB SATA storage (SATA: /dev/sda)
  - 30 GB SCSI storage  (SCSI: /dev/sdc) 

### Result 

#### Scenario 1: BIOS + GPT + Auto provisioning  (`FAILED`) 
* Additional /dev/sda and /dev/sda can be provision and scheduled correctly
* But harvester disk /dev/sdb `can't be` provisioned and have error 
![image](https://user-images.githubusercontent.com/29251855/143454800-888511cc-fa14-4354-ac9d-67802a6e6c6d.png)

![image](https://user-images.githubusercontent.com/29251855/143454941-5cf5b348-3a85-480d-919d-b3005dc87765.png)



#### BIOS + MBR + Auto provisioning (`PASS`)
* Additional /dev/sda and /dev/sda can be provision and scheduled correctly
* But harvester disk /dev/sdb can be provisioned correctly
* All disk auto provisioned correctly on second `join` node
![image](https://user-images.githubusercontent.com/29251855/143453846-ca64d2be-3fb4-424f-96c0-ddf24d979517.png)

![image](https://user-images.githubusercontent.com/29251855/143420327-ced95fe2-81d6-4c3a-884d-2fa13c0f4797.png)

![image](https://user-images.githubusercontent.com/29251855/143427652-fa16fc40-82c3-4898-8322-d5ed6c0a7a3b.png)



#### UEFI + GPT + Auto provisioning  (`FAILED`) 

Disk usage information: 
1. `/dev/sdb`: Used for harvester installation (150GB IDE)
2.  `/dev/sda`: Additional disk for auto provision (50GB SATA)
3. `/dev/sdb`: Additional disk for auto provision (30GB SCSI)
![image](https://user-images.githubusercontent.com/29251855/143806604-afc409db-18a9-4e5a-8a2a-47c074b2cfad.png)


* Additional /dev/sda and /dev/sda can be provision and scheduled correctly
* `No` harvester disk /dev/sdb display 
* /dev/sda and /dev/sdb display with `failed to mount` error

![image](https://user-images.githubusercontent.com/29251855/143432459-f81a6cd0-d2e6-4ffa-8361-8840fa030958.png)

![image](https://user-images.githubusercontent.com/29251855/143439475-2bb9dd59-b562-4f08-abbd-7e2b2157ffaa.png)

### Test Information
* Test Environment: 2 nodes harvester on local kvm machines (create + join)  
* Harvester version: master-b7e562d3-head

### Verify Steps

1. Prepare server and storage according to different scenario
2. ISO install harvester
3. Send `ctrl+alt+F2` key change to console 
4. Login with rancher/rancher
5. Run `lsblk` to check all available disks
6. Run `gdisk /dev/sda or /sdb`
7. Press `W` to create GPT table
![image](https://user-images.githubusercontent.com/29251855/143419997-1d55ddd7-d7a7-4e3d-b3a2-2b4b9a42239f.png)
8. Prepare a lightweight http server 
9. Create a harvester-config.yaml file add the following lines content 
  ```
  system_settings:
    auto-disk-provision-paths: /dev/sd*
  ```
9. put harvester-config on http server 
10. Send `ctrl+alt+F1` key back to iso installation
11. Input harvester config url (e.g http://192.168.1.106:8080/harvester-config.yaml) 
12. Wait for harvester installation complete
13. Access harvester and open Host page
14. Check all /dev/sda , /dev/sdb and /dev/sdc are provisioned and mounted correctly 

### Additional context
To simulate UEFI, please use `zypper install qemu-ovmf-x86_64` 
Then select `/usr/share/qemu/ovmf-x86_64-code.bin` firmware while creating VM
![image](https://user-images.githubusercontent.com/29251855/143432509-352ef2f3-ac42-4deb-b161-9e358011496c.png)

**Comment by johnliu55tw** [comment]
@TachunLin The issue you saw with BIOS+GPT might be caused by this bug: https://github.com/harvester/harvester/issues/1382

**Comment by TachunLin** [comment]
Check the GPT table on extra disk /dev/sda, /dev/sdb again and reproduce again. 
The `UEFI + GPT` can auto provision disks on both create and join mode correct 

* Disk usage information: 
  1. `/dev/sdb`: Used for harvester installation (150GB IDE)
  2.  `/dev/sda`: Additional disk for auto provision (50GB SATA)
  3. `/dev/sdb`: Additional disk for auto provision (30GB SCSI)

On `Create` harvester node:
![image](https://user-images.githubusercontent.com/29251855/143812832-22a464d7-71fc-480c-bacd-2e60c704030b.png)

On `Join` harvester node: 
![image](https://user-images.githubusercontent.com/29251855/143820670-106c05d5-f741-4e64-b26d-c07a726ee866.png)

Update the test result 
1. - [ ] `BIOS` firmware + `No MBR` (Default) + Auto disk` provisioning config  
2. - [x]  `BIOS` firmware + `MBR` + Auto disk provisioning config
3. - [x]  `UEFI` firmware + `GPT` (Default) +  Auto disk provisioning config 

Since the the `BIOS+GPT` test scenario requires #1382 to fix. Move this issue to implement pipeline for further check later.

**Comment by johnliu55tw** [comment]
@TachunLin BIOS+GPT issue should be fixed with the latest NDM. Please help retest this issue with the latest master ISO.

**Comment by weihanglo** [comment]
Thank for @TachunLin found another issue: when joining a node into existing cluster, NDM might be deployed earlier than Longhorn, and then NDM starts to auto-provision disks but Longhorn node doesn't exist. Thus, NDM cannot find a valid Longhorn Node to provision it.

Will do the fix on NDM side. Thanks.

**Comment by TachunLin** [comment]
Verified the remaining test scenario on master-f6bc010b-head. `Did not pass` the final test scenario. 

- [ ]  `BIOS` firmware + `No MBR` (Default) + `Auto disk provisioning` config

   - [x] `PASS` the auto disk provisioning on harvester `Create` node 
   - [ ]  `FAILED` the auto disk provisioning on harvester `Join` node 

The failed result may caused by the NDM issue as above comment. Suggest to move to implement for further check
Thanks @weihanglo for guiding me through the troubleshooting process, 

### Result

* Disk usage information:
  - /dev/`sdb`: Used for harvester installation (150GB IDE)
  - /dev/`sda`: Extra disk for auto provision (60GB SATA)
  - /dev/`sdb`: Extra disk for auto provision (40GB SCSI)

On the 2nd harvester node (Join mode). Extra disk `sda` and `sdc` both display error message
```
failed to mount the device /dev/sdc1 to path /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b, error: Failed
to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net mount -t ext4 -o
journal_checksum,journal_ioprio=0,barrier=1,errors=remount-ro,relatime /dev/sdc1 /var/lib/harvester/extra
disks/2bf5824103011662c7c505aa26dc372b], output , stderr, mount: /var/lib/harvester/extra
disks/2bf5824103011662c7c505aa26dc372b: /dev/sdc1 already mounted on /var/lib/harvester/extra
disks/2bf5824103011662c7c505aa26dc372b.
, error exit status 32
```
![image](https://user-images.githubusercontent.com/29251855/144076347-be8c4ee0-2684-46be-b7a2-417580d0f4d4.png)


### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-f6bc010b-head

### Verify Steps

Harvester Create Node
1. Prepare VM server and storage according to above `Disk usage information`
2. ISO install harvester
3. Send `ctrl+alt+F2` key change to console 
4. Login with rancher/rancher
5. Run `lsblk` to check all available disks
6. Run `gdisk /dev/sda or /sdb`
7. Press `W` to create GPT table
8. Create a harvester-config.yaml file add the following lines content 
  ```
  system_settings:
    auto-disk-provision-paths: /dev/sd*
  ```
9. put harvester-config on http server 
10. Send `ctrl+alt+F1` key back to iso installation
11. Input harvester config url (e.g http://192.168.1.106:8080/harvester-config.yaml) 
12. Wait for harvester installation complete
13. Access harvester and open Host page
14. Check all /dev/sda , /dev/sdb and /dev/sdc are provisioned and mounted correctly 

Harvester Join Node
1. Follow step 1 ~ 7 to install harvester in join mode
2. Select join to install harvester during iso installation
3. Don't provide harvester config file
4. Wait for harvester installation complete
5. Access harvester and open Host page
6. Check all /dev/sda , /dev/sdb and /dev/sdc are provisioned and mounted correctly 

### Additional Context
* Support bundle
[supportbundle_e68d4c1e-3c6f-4752-af42-ea68bc905cb6_2021-11-30T10-45-31Z.zip](https://github.com/harvester/harvester/files/7627003/supportbundle_e68d4c1e-3c6f-4752-af42-ea68bc905cb6_2021-11-30T10-45-31Z.zip)

* `kubectl -n longhorn-system get bd 2ec6b9241bbfb96a57e6ea93b71b8806 -oyaml` output
```
harvester-create-i1241:/home/rancher # kubectl -n longhorn-system get bd 2ec6b9241bbfb96a57e6ea93b71b8806 -oyaml
apiVersion: harvesterhci.io/v1beta1
kind: BlockDevice
metadata:
  creationTimestamp: "2021-11-30T08:48:09Z"
  finalizers:
  - wrangler.cattle.io/harvester-block-device-handler
  generation: 6
  labels:
    kubernetes.io/hostname: harvester-join-i1241
    ndm.harvesterhci.io/device-type: part
    ndm.harvesterhci.io/parent-device: 5d4b21d5e1c49cae560aef651c395bbb
  name: 2ec6b9241bbfb96a57e6ea93b71b8806
  namespace: longhorn-system
  resourceVersion: "19129"
  uid: 4d0ffaa1-652b-4e46-8d00-fc9fd21c25f9
spec:
  devPath: /dev/sdc1
  fileSystem:
    forceFormatted: true
    mountPoint: /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b
    provisioned: true
  nodeName: harvester-join-i1241
status:
  conditions:
  - lastUpdateTime: "2021-11-30T08:48:13Z"
    message: |-
      failed to mount the device /dev/sdc1 to path /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b, error: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net mount -t ext4 -o journal_checksum,journal_ioprio=0,barrier=1,errors=remount-ro,relatime /dev/sdc1 /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b], output , stderr, mount: /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b: /dev/sdc1 already mounted on /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b.
      , error exit status 32
    reason: Error
    status: "False"
    type: Mounted
  - lastUpdateTime: "2021-11-30T08:48:13Z"
    message: Done device ext4 filesystem formatting
    status: "False"
    type: Formatting
  - lastUpdateTime: "2021-11-30T08:48:13Z"
    message: 'failed to provision device 2ec6b9241bbfb96a57e6ea93b71b8806 to node
      harvester-join-i1241 on path /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b:
      nodes.longhorn.io "harvester-join-i1241" not found'
    reason: Error
    status: "False"
    type: AddedToNode
  deviceStatus:
    capacity:
      physicalBlockSizeBytes: 512
      sizeBytes: 64422412288
    details:
      deviceType: part
      driveType: HDD
      partUUID: ad985f71-0fec-460b-b950-49a8b6b11abd
      storageController: SCSI
    fileSystem:
      LastFormattedAt: "2021-11-30T08:48:13Z"
      mountPoint: /var/lib/harvester/extra-disks/2bf5824103011662c7c505aa26dc372b
      type: ext4
    parentDevice: /dev/sdc
    partitioned: false
  state: Active
```

**Comment by TachunLin** [comment]
@johnliu55tw , @weihanglo 
I create a new issue #1599 to manage and track above failure result.

**Comment by TachunLin** [comment]
Verified the fixed all the test scenarios on `v1.0.0-rc1` 

- [x]  `BIOS` firmware + `No MBR` (Default) + `Auto disk provisioning` config

   - [x] `PASS` the auto disk provisioning on harvester `Create` node 
   - [x] `PASS` the auto disk provisioning on harvester `Join` node 

### Result
Both create and join mode can auto provision extra disks correctly without error

#### create node
![image](https://user-images.githubusercontent.com/29251855/144438438-59b40943-ec66-424f-9291-de1dc2b05d88.png)


#### join node

![image](https://user-images.githubusercontent.com/29251855/144438351-b137934a-ec0c-4338-bf18-29485d8601fa.png)




* Disk usage information:
  - /dev/`sdb`: Used for harvester installation (150GB IDE)
  - /dev/`sda`: Extra disk for auto provision (60GB SATA)
  - /dev/`sdb`: Extra disk for auto provision (40GB SCSI)




### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `v1.0.0-rc1`

**Comment by TachunLin** [comment]
Trying to find some `physical disks` to verify some of the test scenario from personal machine on hand.

**Comment by TachunLin** [comment]
Passed the addition testing on bare machine with  `v1.0.0-rc1`. Close this issue.

- [x]  `UEFI` firmware + `GPT` (Default) + `Auto disk provisioning` config

   - [x] `PASS` the auto disk provisioning on harvester `Create` node 

### Result
Create mode can auto provision extra disks correctly without error

![image](https://user-images.githubusercontent.com/29251855/144747366-6b4f7502-286e-4768-9a6a-d7d4383a9d86.png)


* Disk usage information:
  - /dev/`sdc`: Used for harvester installation (500GB SSD)
  - /dev/`sda`: Extra disk for auto provision (500GB SSD)

![image](https://user-images.githubusercontent.com/29251855/144750883-9f003251-a7e8-4650-8d47-e8300b5e8a34.png)


### Test Information
* Test Environment: 1 nodes harvester on local bare machines (8 core, 12GB ram)
* Harvester version: `v1.0.0-rc1`

![image](https://user-images.githubusercontent.com/29251855/144751004-9838edbb-ac1d-403f-b44e-bc86beffd572.png)

![image](https://user-images.githubusercontent.com/29251855/144751018-d134517b-a1d6-4225-a515-e44c19b5e149.png)

### Additional Context

* Disk information after installation

```
rancher@harvester-bare-100rc:~> lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
loop0 7:0 0 3.2G 1 loop /
sda 8:0 0 465.8G 0 disk
└─sda1 8:1 0 465.8G 0 part /var/lib/harvester/extra-disks/2750d3d72f330cf9398581ac0c2d46a0
sdb 8:16 0 465.8G 0 disk
├─sdb1 8:17 0 47M 0 part
├─sdb2 8:18 0 50M 0 part /oem
├─sdb3 8:19 0 15G 0 part /run/initramfs/cos-state
├─sdb4 8:20 0 8G 0 part
├─sdb5 8:21 0 80G 0 part /usr/local
└─sdb6 8:22 0 362.7G 0 part /var/lib/longhorn
sdc 8:32 0 50G 0 disk /var/lib/kubelet/pods/a863b9e6-37fc-488a-af5c-e4fb14f93474/volume-subpaths/pvc-f594d274-93a5-4448-a46b-ea6b30c90e9b/prometheus/2
sdd 8:48 0 10M 0 disk /var/lib/kubelet/pods/8be5c0e9-1ad5-4f3f-bb29-7425fac2df03/volumes/kubernetes.io~csi/pvc-60be9057-fb38-469a-89be-47337882aaa4/mount
```
 
* FYI: Also I have tried auto provision config by using pxe install on provo bare machines, but auto provision not work on this case.
