### ISSUE TITLE
[BUG] The interface names are unpredictable in UEFI-booted systems

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1267]
**Describe the bug**

The interface names are unpredictable in UEFI-booted systems.

**To Reproduce**
1. Booting a system in UEFI mode.
2. The installer displays interface names with unpredictable styles: `eth0`

![image (1)](https://user-images.githubusercontent.com/1691518/134613257-2d414ef7-82e1-434e-9a7a-e40ce7454259.png)

**Expected behavior**
The interface names should be something like `ens5` or `ens192`
**Support bundle**

**Environment:**
 - Harvester ISO version: `harvester-v0.3.0-preview1-amd64.iso`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 

**Additional context**
The UEFI boot doesn't use syslinux bootloader menu, we need to patch `<ISO>/loader/entries/cos-x86_64.conf` to include the `net.ifnames=1` parameter.
This might also be the cause that a USB installation media doesn't have this parameter: https://github.com/harvester/harvester/issues/1200

**Comment by guangbochen** [comment]
verified using the `master-48c97ea7-head`, @noahgildersleeve can u please check to confirm if we can close this issue, thanks.
1. boot from a USB device with UEFI installation mode
![image](https://user-images.githubusercontent.com/4569037/134792304-3c2b2e11-47ed-4167-8068-d8ca41c9994b.png)
2. the NIC name is shown as en* instead of `ethx`
![image](https://user-images.githubusercontent.com/4569037/134793369-c7d6fcac-9d7b-43cb-afc6-631eb29c9eb3.png)
3.  reboot the system and confirm the NIC name is persisted
```
rancher@harv-sm:~> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: en01: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master harvester-mgmt state UP group default qlen 1000
```

**Comment by yasker** [comment]
close as verified per https://github.com/harvester/harvester/issues/1267#issuecomment-927223611
