### ISSUE TITLE
[BUG] nodes are not being deleted on the backend when a cluster is deleted through rancher

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1306]
backport https://github.com/rancher/rancher/issues/34946

**Comment by yasker** [comment]
It's hard to reproduce this issue now. Move to v1.0.0.

**Comment by guangbochen** [comment]
**To Test:** (and should be synced to https://github.com/rancher/rancher/issues/34946)
- spin up the rancher-v2.6.3-rc1, bump the node-driver manually via `Drivers -> Node Drivers -> Edit Harvester Node Driver`
   - Edit the down URL and replace the version with `v0.3.4` and remove the `checksum`
- provision some cluster(s) (rke1/rke2) via the harvester node driver
- deleting one of the clusters at some point while it is provisioning or after it comes to active state
- both cluster and VM should be removed successfully after a period of time.

**Comment by TachunLin** [comment]
Verified `fixed` on master-d577bb6c-head with rancher v2.6.3-rc1 (node driver v.0.3.4)
Delete the RKE2 cluster while in provisioning and after it already deployed in active state.
Both the cluster and all VMs will be removed on rancher and harvester dashboard

### Result 
Delete 3 nodes RKE2 cluster while provisioning
![image](https://user-images.githubusercontent.com/29251855/142847357-e66839d7-4ed2-43b8-aca4-2dd943da0fe2.png)

All VMs will be removed on harvester
![image](https://user-images.githubusercontent.com/29251855/142847399-6f4795c5-b12a-4261-a67c-b45aeecd9a12.png)

And if we delete cluster after deployment finished. All cluster and VMs will be deleted as well. 

### Test Information
* Rancher version: v2.6.3-rc1
* Node driver: v0.3.4
* Harvester version: master-d577bb6c-head

### Environment Preparation
1. Install Rancher v2.6.3-rc1
2. Update ui-dashboard-index and ui-offline-preferred in global settings
3. Import harvester 
4. Edit harvester node driver and set to v0.3.4
![image](https://user-images.githubusercontent.com/29251855/142832462-e0df52c5-2ff0-48a0-8780-a8ddee5924b5.png)
5. Create cloud credential


### Verify Steps

1. Environment preparation as above steps
2. Create 3 nodes RKE2 cluster 
![image](https://user-images.githubusercontent.com/29251855/142839767-6d12a4ec-b384-4862-9b63-295c849f7b1e.png)
3. Wait for all RKE2 VMs running on harvester 
4. Remove entire cluster from Rancher 
5. Check both cluster and VMs can be removed correctly
10.Create a 3 nodes RKE2 cluster again
11. Wait for cluster finish deploy in running status
12. Remove entire cluster from Rancher 
13. Check both cluster and VMs can be removed correctly


### Additional Context
When the 3 nodes rke2 cluster in provisioning status, delete one node of cluster in rancher will not actually remove it.
The node status in rancher will change from `Deleting` then resume to `provisioning`
The rke2 node vm in harvester will change from  `terminate` to `starting`
Confirmed it's the expected behavior, just memo down these information for reference. 

Delete one of the node in rke2 cluster from rancher dashboard
![image](https://user-images.githubusercontent.com/29251855/142840587-4baf76fc-7021-4b9f-9084-e677ff327ab2.png)

rke2 node vm was being terminated on harvester
![image](https://user-images.githubusercontent.com/29251855/142840726-cbc923e2-cdb4-4e9c-b723-ae41dafc4dba.png)

But resume to start new rke2 vm on harvester
![image](https://user-images.githubusercontent.com/29251855/142840832-c555d0e6-54b4-4227-808b-ff55c4a39411.png)
