### ISSUE TITLE
harvester authentication

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#132]
**Description:**
need to add authentication to the harvester-ui, e.g, using the k8s dashboard way
![image](https://user-images.githubusercontent.com/4569037/92853723-bae72f80-f422-11ea-9505-8cd424f4ab6e.png)
reference:
https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md

**Comment by DaiYuzeng** [comment]
Hi all, there is a discussion. Do we need to add a logout API? Because, jwetoken in Cookie is HTTP-Only, it cannot remove from the front end. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
![image](https://user-images.githubusercontent.com/15041915/94326014-ff9ec900-ffd3-11ea-91ca-b73b4688f89f.png)

**Comment by guangbochen** [comment]
@DaiYuzeng the backend is merged, can u please help to add `logout` action in the UI, thanks.

**Comment by gitlawr** [comment]
The kubeconfig method has some limitations, can we add a note in the UI so that users are not confused when they bring a valid kubeconfig but can not get access.
e.g., add a tip that can pop up the following message:
`Kubeconfig Authentication method does not support external identity providers or basic authentication.`
WDYT @aiwantaozi @DaiYuzeng

**Comment by gitlawr** [comment]
Validated
