### ISSUE TITLE
[FEATURE] Show vendor and product of NICs 

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1328]
**Is your feature request related to a problem? Please describe.**

It can be hard to know which nic is which, and therefore a hint would be to display the MAC address after the name

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/759887/135356016-61aa1312-3e47-4b02-b1eb-d63472f6868b.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Jellyfrog** [comment]
Or maybe better.. print the description like debian:

![image](https://user-images.githubusercontent.com/759887/135359240-69731c06-e8e7-4eec-b068-6dff5605d89c.png)

**Comment by yaocw2020** [comment]
![image](https://user-images.githubusercontent.com/7421463/135407454-dd62faaa-b5ec-491c-9572-3ab4d8a02c0d.png)

**Comment by yasker** [comment]
We also need to add mac address to the nic description.

**Comment by guangbochen** [comment]
verified using the master-head ISO build, both the mac address and NIC status are shown properly, in regards to the long text content it will be supported in the next version due to the current console UI limitation.
![image](https://user-images.githubusercontent.com/4569037/136648375-dcd69c9e-788b-463f-aa98-cba626194a3e.png)
