### ISSUE TITLE
Dont see Rancher in setting

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#1332]
Hello, since Version 0.3.0 prev and rc1 I have no Rancher in Settings. I use Harvester with KVM with 6 Cores and 12G Ram

**Comment by guangbochen** [comment]
Starting from the Harvester v0.3.0, we recommend running the Rancher server separately either via a VM or following the Rancher recommendations https://rancher.com/docs/rancher/v2.6/en/installation/.

This is because from Rancher v2.6.1(will be released soon), we will be able to provide the multi-cluster and multi-tenant feature of Harvester clusters via a built-in integration of `Virtualization Management`, so a decoupled installation is preferred.
![image](https://user-images.githubusercontent.com/4569037/135404469-6cd69dd9-7829-44c9-aeee-af338a65593e.png)

**Comment by jrlittlefoot64** [comment]
Thank you
