### ISSUE TITLE
task: reorg the `harvester/tests` to include test documents

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1399]
Need to have a discussion regarding what we can do to improve our test effort and documents.

One thing we can learn from Longhorn is to check-in manual and automation tests as code. See https://longhorn.github.io/longhorn-tests/integration/ and https://longhorn.github.io/longhorn-tests/manual/ for example.

The ultimate goal is to have all the test cases in code, so we can also consider using the pydoc instead of MD for documentation, so it will be easier for us to translate test steps into code.

And adding integration test code will be a requirement for any feature in the future. 

REF: https://github.com/longhorn/longhorn-tests

**Comment by lanfon72** [comment]
@yasker I would suggest we can just renamed `harvester/tests` to `harvester/api-tests` as it is testing on API-based; and keep `harvester/tests` for documents. (so that we won't mess up git commit logs)

> The ultimate goal is to have all the test cases in code, so we can also consider using the pydoc instead of MD for documentation, so it will be easier for us to translate test steps into code.

For long term plan, I would suggest to use [RobotFramework](https://github.com/robotframework/robotframework) for (UI-based) testing, here is the [demo repo](https://github.com/robotframework/WebDemo), [report.html](http://robotframework.org/WebDemo/report.html) and [log.html](http://robotframework.org/WebDemo/log.html)

Although Robot Framework also provides [tool](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#testdoc) to generate documents from test suites (snapshot below),  but considered the availability of documents, I thought we still need a repo to organize them.

[Documents of Test Cases]
![image](https://user-images.githubusercontent.com/5169694/137449954-32648b0a-ab92-4742-87fc-4d8ed808cf88.png)

**Comment by noahgildersleeve** [comment]
@yasker @guangbochen  If we're going to do that please let me know soon. I'm currently in the middle of migrating all of the tests and I have all of the git commits based on the tests repo locally in a feature branch, and there's a lot of tests.

**Comment by noahgildersleeve** [comment]
It might make sense to standardize off of what we are doing in Longhorn. which is to keep both of the tests (manual and automated) in the same repo. https://github.com/longhorn/longhorn-tests . I was going to ask @guangyee about a refactor to use the same directory structure when I was done importing the current test cases.

**Comment by noahgildersleeve** [comment]
Updated tests repo with docs, worked with @guangyee and updated the workflows so that on any PR merge to main that changes the docs directory it will auto-deploy to the GitHub pages branch and update the static site.
