### ISSUE TITLE
[BUG] Harvester 0.3 does not allow CPU-overprovisioning

### ISSUE THREAD

**Issue by ugar-ugar** [harvester/harvester#1429]
**Describe the bug**
 Harvester 0.3 does not allow CPU-overprovisioning

**To Reproduce**
1. Create a 8 Core Harvester 0.3 node
2. Create a 4 Core VM on this node
3. VM will not start with "insufficient CPU" as hint

**Expected behavior**
a 4 Core VM should run on a 8 core node

**Support bundle**
is attached

**Environment:**
 - Harvester ISO version: 0.30 
 - Underlying Infrastructure:
cluster with 3x  Virtual Machine with 8 cores, 16 GB RAM, 128 GB Disk
[supportbundle_0463918b-0ee5-438f-880d-0f87183552f0_2021-10-14T15-52-18Z.zip](https://github.com/harvester/harvester/files/7347576/supportbundle_0463918b-0ee5-438f-880d-0f87183552f0_2021-10-14T15-52-18Z.zip)
 Virtual Machine with 8 cores, 16 GB RAM, 128 GB Disk
.

**Comment by lanfon72** [comment]
ref to #1376

**Comment by yasker** [comment]
We need to support overprovisioning by default.

**Comment by weihanglo** [comment]
FWIW there are some interesting configs in KubeVirt. 

For CPU overcommitment, there are two related cluster-wide config on KubeVirt CR

- `spec.configuration.cpuRequest`: set the global default CPU request [if a request is send without specifying CPU][cpurequest]. Default to 100m
-  `spec.configuration.developerConfiguration.cpuAllocationRatio`: a ratio that [controls CPU allocation amount][cpuallocratio]. 10 means allocates 1/10 of the request. Default to 10.

For memory there are both cluster-wide and instance-level config. We can set

- `spec.configuration.developerConfiguration.MemoryOvercommit` to [control cluster-wide memory resource request][memoryovercommit]. It's also a ratio, 100% means committing exactly the same amount that guest VM uses. 200% mean the guest VM would request half of it actually uses.

There is also per-instance memory overcommit setting but not for CPU at this moment. Please refer to KubeVirt official guide ["Node overcommit"](https://kubevirt.io/user-guide/operations/node_overcommit/).

[cpurequest]: https://github.com/kubevirt/kubevirt/blob/b6156e522dc1d77fefd57564c09cf20803a64c73/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L339-L348
[cpuallocratio]: https://github.com/kubevirt/kubevirt/blob/b6156e522dc1d77fefd57564c09cf20803a64c73/pkg/virt-controller/services/template.go#L860-L875
[memoryovercommit]: https://github.com/kubevirt/kubevirt/blob/b6156e522dc1d77fefd57564c09cf20803a64c73/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L328-L335

---

For the implementation side, supposed adding harvestersetting for cluster-wide CPU overcommit ratio is very straightforward, we can go this way first. If a user wants to overcommit CPU for specific instance, then maybe asking for a feature request in KubeVirt is better.

The UI is also need to update if Harvester wants to support instance-level CPU/memory overcommit, there are plenty of CPU configurations we can tweak.

**Comment by guangbochen** [comment]
Having a cluster-wide overcommit setting is sufficient enough at the current stage, also make sure we add an additional setting of storage overcommit and sync it with LH's config accordingly, thanks.

**Comment by weihanglo** [comment]
After some investigations,  there is a limitation that makes something cannot be done via KubeVirt's configs: We cannot specify `resources.limits` and let KubeVirt calculate the overcommitted values. 
The overcommit feature in KubeVirt only cares `domain.cpu` and `domain.memory` to calculate `resource.requests`. If we specifiy `resources.limits`, it would behave like what K8s does in Pods: fill `resources.requests` with values from `resources.limits`.

Supposed `resources.limits` is somehow important in Harvester as a VM orchestration platform, ditching it may not be an option. I propose two solutions:
1.  Add a mutation webhook like [what KubeVirt does] and implement our own overcommit logic when both requests and limits are missing.
1. Calculate these values in dashboard UI frontend.

However, if we think `resources.limits` can be dropped, we can just drop it and it's good to go.

[what KubeVirt does]: https://github.com/kubevirt/kubevirt/blob/b6156e522dc1d77fefd57564c09cf20803a64c73/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L296-L351

**Comment by guangbochen** [comment]
@weihanglo currently we set the VM `resource.limits` by default is because when the users specify the project resource quota on the Rancher UI as part of the multi-tenant feature then the `limits` config is required when creating a VM pod.

IMO, we should add mutation webhook validation on our side serve to support the overcommit feature, and it will make the API behave consistently across the different client calls. cc @WuJun2016 which means the UI may leave the `resource.limits` as empty as the webhook server will count the overcommit value properly upon `resource.request`.
![image](https://user-images.githubusercontent.com/4569037/139185098-9d2e665b-3483-4161-9fb7-7c2fbabb62e9.png)

**Comment by weihanglo** [comment]
Probably we need an update for default [`overcommit-config`] setting value and [a removal of the `resources.limits`].
 on [the UI dashboard]? 
 
[`overcommit-config`]: https://github.com/harvester/harvester/blob/8241c1647d2d98f722e1d742e0e55e52f376e460/pkg/settings/settings.go#L32
[a removal of the `resources.limits`]: https://github.com/weihanglo/dashboard/commit/b0b43f1765fb68fd8d49d73bdd3a3a01d6059a53
[the UI dashboard]: https://github.com/harvester/dashboard/blob/5a81f5413fd2cfbd8b51b6d5b2e43663832e7648/config/settings.js#L91-L101

**Comment by guangbochen** [comment]
@WuJun2016 can u please help to add a new setting named `overcommit-config` that allows users to config resource overcommit in percentage. Also, as per @weihanglo's above comment, we can now ignore the `resource.limits` value during VM creating and the webhook will add it upon the overcommit value automatically.

**Comment by lanfon72** [comment]
@weihanglo, @WuJun2016 I will put this back to _implement pipeline_ due to several reasons below:
```python
# overcommit-config
{
  "cpu": 1600,
  "memory": 150,
  "storage": 200
}
```
1. broken VM creation, as issue #1534 mentioned.
    When Creating a VM with **7 GiB** RAM, the RAM will be reset to **4.67 GiB**, and **CANNOT** reconfigure it to exceed initial setting.
![image](https://user-images.githubusercontent.com/5169694/141254515-11cde36b-3fb3-49ed-b719-4d09ea64c840.png)

2. Inconsistent YAML content between outside(click options -> edit YAML) and inside(click options -> edit config -> edit as YAML).
    Here is the yamls: [yamls.zip](https://github.com/harvester/harvester/files/7518597/yamls.zip), and if save yaml inside (without modify anything), the VM broken.  Unable to _Edit Config_ again, viewing shows:
![image](https://user-images.githubusercontent.com/5169694/141258247-d27e9765-f8de-47c6-b5ac-06a73812ae33.png)

3. CPU able to provisioning to max, but not over-committing.
[max provisioning]
![image](https://user-images.githubusercontent.com/5169694/141259388-94e30891-f03f-4e48-baaf-626ac10bdfd9.png)
![image](https://user-images.githubusercontent.com/5169694/141260763-014e27d6-8f91-417e-964e-ebc42920f80a.png)
[over-committing]
![image](https://user-images.githubusercontent.com/5169694/141259133-81042f34-ae7a-4cbc-90a1-7a434e1888fe.png)
![image](https://user-images.githubusercontent.com/5169694/141259191-61cce5d8-5c7d-4148-aa10-79894fecad4c.png)
    Compare to _**virt-manager**_'s behaviors:
![image](https://user-images.githubusercontent.com/5169694/141259582-3702f463-21c0-43b6-80ad-71f164930924.png)
![image](https://user-images.githubusercontent.com/5169694/141259620-d4648d64-79e3-4bf7-b390-bca5b900cbca.png)

@weihanglo, as this issue is focus on `CPU's over-provisioning`, I think we should create other issues to track memory/storage's feature. cc @guangbochen


Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: **master-119c2c48-head**
* **ui-source** Option: **External**

**Comment by weihanglo** [comment]
The overcommit feature here is quite simple: What you specify becomes `resources.limits` and Harvester calculates `resources.requests` for you.[^1] Under this circumstance, oh yes, we cannot "overcommit" beyond physical limits. 

Although I am uncertain about overcommitting over physical resources, it's not hard to make it work: Just set `resources.limits` as the calculated `resources.requests` and we can overcommit as much as we want. 

[^1]: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits

**Comment by guangbochen** [comment]
@lanfon72 I think both the 1st and 2nd issues are related to the UI bug and will be fixed accordingly with the correct size calculation, for the 3rd issue which is an over-committing, we are not virtualizing the actual physical resources, but users can deploy more VMs than the original 1:1 physical resource mapping through the overcommit config. A good example can be referred to https://docs.openstack.org/arch-design/design-compute/design-compute-overcommit.html, thanks.

**Comment by lanfon72** [comment]
>  but users can deploy more VMs than the original 1:1 physical resource mapping through the overcommit config.

Yes, consider to the default configuration for CPU is **1600%**, I think overcommit is not work, I can't create the VM with 18 cores in the case(7/24 reserved).  Or am I misunderstaing something? :thinking: 

For the origin comment, it more similar to #1376 (so the origin bug already be fixed), but following content in comments aren't.
I think we can track them on other issues, but I didn't find any related feature issues.

**Comment by weihanglo** [comment]
## Consistency of reserving memory overhead for guest

Per the discussion with @guangbochen and @WuJun2016, we are going to move guest memory reservation logic from frontend to backend, as well as the backend start ignoring `resource.requests` and derive them from `resources.limits`. This is quite straightfoward than current impl.

However, to deal with addtional overhead is somehow tricky, the logic in the frontend[^1] reserves 10% for each VM. That means if one specifies the VM with 1GiB memory via dashboard UI, they gets a VMI with

- `domain.resource.limits.memory = 1G`
- `domain.resource.requests.memory = 683MiB` (150% overcommitted by default)
- `domain.memory.guest = 921M` (if we reuse the frontend logic in backend)

In addition, KubeVirt has a feature that adding additional guest memory overhead[^2] on virt-launcher pod on each VM based on `resources.requests`. As a result, the actual memory requests and limits on the pod would be more than a user's specified.

That is to say, if a user specify 1GiB memory for a VM via dashboard, they will get

- VM/VMI
  - `resources.limits.memory = 1GiB`
  - `resources.requests.memory = 683MiB` (150 %overcommitted by default)
  - `domain.memory.guest = 921M` (if we reuse the frontend logic in backend)
- virt-launcher pod
  - `resource.limits.memory = 12xxMiB` (guest overhead added by KubeVirt)
  - `resource.requests.memory = 8xxMiB` (guest overhead added by KubeVirt)

The actual pod memory limit/request would be difference from user's expectation. And it may lead to a inconsistency between a user's overcommit calculation then actual requested resources on K8s cluster. 

Thanfully, we can turn guest-overhead off[^3] but it means we need to calculate the overhead on our own, because 10% for a 1GiB VM might not be enough[^4] [^5] [^6].

So, the questions is, can Harvester tolerate this inconsistency? If not, then how much memory should Harvester expect to reserve? By which way should harvester reserve memory, reducing guest memory allocation like old frontend way or adding additional overhead on pods?

Note that this also affects consistent view of resource quota management https://github.com/harvester/harvester/issues/1455. 


[^1]: https://github.com/harvester/dashboard/blob/171f5efdde2fd37f09e67f102a6ad86cbb8ed1a5/mixins/harvester-vm/index.js#L431-L436
[^2]: https://github.com/kubevirt/kubevirt/blob/ee4d9d87b206b00e70adb36dfb4b3d778d08a3d7/pkg/virt-controller/services/template.go#L1828-L1900
[^3]: https://kubevirt.io/user-guide/operations/node_overcommit/#overcommit-the-guest-overhead
[^4]: https://github.com/kubevirt/kubevirt/issues/4560
[^5]: https://github.com/kubevirt/kubevirt/issues/5958
[^6]: https://github.com/harvester/harvester/issues/1234

**Comment by WuJun2016** [comment]
the logic in the frontend reserves 100Mib for each VM.

**Comment by lanfon72** [comment]
Verified CPU over-commit works as expected, and related bugs described in https://github.com/harvester/harvester/issues/1429#issuecomment-966072587 also fixed.

Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: ** master-45e25939-head**
* **ui-source** Option: **External**
* **overcommit-config** Setting:
```py
{
  "cpu": 1600,
  "memory": 150,
  "storage": 200
}
```

### Verification
bugs described in https://github.com/harvester/harvester/issues/1429#issuecomment-966072587
- [x] Fixed, extending CPU/mem resources in created VM works correctly.
- [ ] not fixed, as it is not related to CPU over-commit feature, moved to #1564
- [x] Fixed, over-committing has been implemented correctly. 

https://user-images.githubusercontent.com/5169694/142607277-1c13e984-747e-42b8-9af3-7c4310c26bef.mp4
