### ISSUE TITLE
[FEATURE] Change the default option of `ui-source` from Auto to Bundled

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1485]
### The problem
The default option of `ui-source` is **Auto**, which equals to **External**, the problem is:
 1. Require additional external connection
 2. Hard to address UI issues if user didn't change the option to **Bundled**.

### The Solution
Change the default option **Auto** to point to **Bundled**, or change the default option from **Auto** to **Bundled**.
(Actually I thought we might not need **Auto** option, bit confusing that it is pointed to which option)

### The Alternatives
Let it become configurable when installing.  (both ISO and config file)

### Additional Context
Bundled UI should have a regularly build, as PR of dashboard repo would not trigger installer to build new iso, a weekly trigger would be nice for verify UI issues.

**Comment by guangbochen** [comment]
The Harvester UI follows the same pattern as the Rancher UI does:
1. By default the `ui-source` option is `Auto`, it will use the embedded UI when the server version is started with `v*` tag, otherwise it will default to fetch from the remote server.
2. The `master-head` harvester image has already packaged the latest Harvester UI as the bunded one. https://github.com/harvester/harvester/blob/master/package/Dockerfile#L18
     - you can check via `$ kubectl -n harvester-system exec -it $harvester node` && `cat /usr/share/harvester/harvester/index.html` to check it current packaged version.

**Comment by lanfon72** [comment]
@guangbochen
> 1. By default the ui-source option is Auto, it will use the embedded UI when the server version is started with v* tag, otherwise it will default to fetch from the remote server.

We will need a note for air-gapped environment in case of we release some master-head version for customers to testing in the future.
