### ISSUE TITLE
[BUG] Edit Advanced Setting option `server-url` will redirect to inappropriate page.

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1489]
### Describe the bug
When editing `server-url` option in _Advanced Settings_, click either **Save** or **Cancel**, will not back to the origin setting page but another setting page which we didn't expose.

The Link in the title also redirect to that page we didn't exposed.

### To Reproduce
1. Open dashboard and navigate to **Advanced** -> **Settings**
2. Click Edit Setting of `server-url`
     - Click **Cancel** -> be redirected to `/management.cattle.io.setting`
     - Click **Save**    -> be redirected to `/management.cattle.io.setting`
     - Click Link **Advance Setting:**    -> be redirected to `/management.cattle.io.setting`
     - Click browser's previous page => original setting page `/harvesterhci.io.setting`

### Expected behavior
We didn't expose the page of `/management.cattle.io.setting` in dashboard, so the routing should be the same as where user step in.

## Environment:
 - Harvester ISO version: **master-d05a6cc7-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**
 - dashboard `ui-source`: Bundled

### Additional context
[origin setting page]
![image](https://user-images.githubusercontent.com/5169694/139201337-ce03f3f2-9285-4164-b18a-9cfca390856d.png)

[editing `server-url`]
![image](https://user-images.githubusercontent.com/5169694/139201148-7d635a88-f801-47ee-aa2b-50d55d764844.png)

[hyperlink of `advanced setting`]
![image](https://user-images.githubusercontent.com/5169694/139201890-9d5eb251-1a80-4cd9-8e83-2bc6aa72a400.png)

**Comment by noahgildersleeve** [comment]
Tested in master-d05a6cc7-head. Still not navigating to the correct URL The issue seems to be that the URL path for the advanced settings page and the edit server-url page aren't the same and when you click cancel it's just removing the last part of the URL for the server-url edit page.
![Greenshot 2021-11-01 13 25 35](https://user-images.githubusercontent.com/83787952/139737505-6f2de4ac-a9b9-42b6-a8db-867135eabaca.png)
![Greenshot 2021-11-01 13 25 45](https://user-images.githubusercontent.com/83787952/139737509-19d569f2-eb19-4990-8b75-5027061cea4f.png)
![Greenshot 2021-11-01 13 25 51](https://user-images.githubusercontent.com/83787952/139737510-b01c7171-b8ab-4ded-9e00-3194b63c5789.png)

**Comment by n313893254** [comment]
Verify Steps:
- Install harvester
- Access harvester
- Edit server-url form settings
- Check `server-url` save, cancel, and back.
Additional context:
![image](https://user-images.githubusercontent.com/18737885/140492691-969380aa-dbed-4999-9e90-e589dd93e4e4.png)

**Comment by noahgildersleeve** [comment]
Tested in master-d21b9161-head. fixed.
Verify Steps:

1. Install harvester
2. Access harvester
3. Edit server-url form settings
4. Check server-url save, cancel, and back.
