### ISSUE TITLE
[BUG] VM memory shows NaN Gi

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1613]
It happens in the following cases:

case 1: Import Harvester to Rancher v2.6.2 and provision an RKE2 cluster using Harvester node driver.
case 2: Create a VM using the API:
```
$ kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
```

**Environment:**
 - Harvester ISO version: v1.0.0-rc1

**Additional context**
UI gets the value from resource limit according to the change in https://github.com/harvester/harvester/issues/1429
For compatibility, we should show the CPU/memory info correctly when the limit is missing.

**Comment by WuJun2016** [comment]
According to the previous discussion, the limit value should always exist regardless of the VM deployed in any way.  cc @guangbochen

**Comment by guangbochen** [comment]
Yes as it should be automatically filled by the mutation webhook, I'm wondering why it was missing with `kubectl apply`

**Comment by slickwarren** [comment]
I've also hit this issue in the following case on v2.6.3-rc3, however in my case it seems that harvester is no longer provisioning any VMs through harvester UI nor through rancher -> virtualization mangement -> harvester. Nodes are stuck in `Guest VM is not reported as running` state:
* import harvester into rancher's virtualization dashboard
* through rancher -> harvester, create a VM
  * in rancher, memory shows up as correct value


<img width="960" alt="Screen Shot 2021-12-03 at 6 13 26 PM" src="https://user-images.githubusercontent.com/16691014/144693371-fe638476-a3f3-486e-8a81-d15b573992ee.png">

* visit the harvester cluster through harvester UI (instead of rancher)
  * memory shows up as NaN

<img width="971" alt="Screen Shot 2021-12-03 at 6 13 34 PM" src="https://user-images.githubusercontent.com/16691014/144693370-1a009b2e-290d-4a35-9ebf-0f08e447fd29.png">

**Comment by weihanglo** [comment]
Need to confirm the behaviors on different scenarios:

- User provides `resources.requests` only: Fill limits with that requests value.
- User provides no limits nor requests: Invalid operation.

Any comment? @guangbochen @WuJun2016

**Comment by TachunLin** [comment]
@weihanglo, @guangbochen,
I have also tried this issue both on rancher `v2.6.3-rc2` and `v2.6.3-rc3`
I found on `v2.6.3-rc2` the default node driver version is `v0.3.2` 

![image](https://user-images.githubusercontent.com/29251855/144799771-2f7c81b1-87f2-4075-a2b7-dd35bc986e73.png)

I tried to remove builtin and manual edit node driver to `v0.3.4` , it can provision rke2 cluster correctly. 

Also I double confirmed on `v2.6.3-rc3`, the built in node driver have already use `v0.3.4` and can also provision rke2 correctly

Provide my test result to improve troubleshooting.

**Comment by guangbochen** [comment]
@weihanglo I think we also include `User provides resources.limits only: Fill limits with that value and auto-fill the resources.request.` ?
And @TachunLin it is correct that the supported Harvester node driver is `v0.3.4`, so prefer to ask users to test using the current latest Rancher `v2.6.3-rc3` or above.

**Comment by noahgildersleeve** [comment]
tested in master-655c251a-head with Rancher v2.6-head. I imported the testvm by config and provioned VMs with RKE1 and RKE2. The RKE1 and RKE2 VMs showed correctly. The 
> case 2: Create a VM using the API:
> 
> $ kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
VM showed as having valid memory in Harvester UI, but `NaN` when looking through the harvester dashboard in virtualization management in Rancher.
![Screenshot from 2021-12-10 17-59-49](https://user-images.githubusercontent.com/83787952/145660134-93cc5b2d-79cf-4160-ba0b-5ac1ac6da07b.png)

**Comment by guangbochen** [comment]
@noahgildersleeve this is fixed in the single Harvester UI and haven't been merged to the upstream yet, for validation purpose can we just replace the Rancher UI index on the `Rancher dashboard -> Global Settings -> ui-dashboard-index` with `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`, thanks
![image](https://user-images.githubusercontent.com/4569037/145751238-0ee1a6b5-fafe-4cc2-b99b-c90e272f6532.png)

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head. Verified as fixed.
## Test Steps

1. Create new VM via `$ kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml` in harvester
2. Set ui-dashboard index to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
3. Set `ui-offline-preferred` to `Remote`
4. Bring up virtualization management and open dashboard
5. Open VM list
6. Verify size
![Screenshot from 2021-12-15 13-58-12](https://user-images.githubusercontent.com/83787952/146271920-65735e79-6eff-412e-876d-4b43d1b4e0eb.png)
