### ISSUE TITLE
[BUG] sometimes, memory of VMs is reported as ~1/1.5 of the original value through harvester

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1622]
**Describe the bug**

if a user provisions a 4gb VM, it is reported as 2.7gb for a time after provisioning

**To Reproduce**
1. provision a vm through harvester
2. once the VM is up, view the reported memory

**Expected behavior**

memory should match what the user enters when provisioning the VM

**Support bundle**

[supportbundle_147f1b83-cdc7-432c-9a01-7b12448d236a_2021-12-02T18-37-29Z.zip](https://github.com/harvester/harvester/files/7644455/supportbundle_147f1b83-cdc7-432c-9a01-7b12448d236a_2021-12-02T18-37-29Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dolphins (baremetal)

**Additional context**
after some time, the correct number is reported. 

<img width="726" alt="Screen Shot 2021-12-02 at 8 22 22 AM" src="https://user-images.githubusercontent.com/16691014/144486478-2f60e488-eae6-422d-9fbe-1d82c3ae35d3.png">

**Comment by WuJun2016** [comment]
Waiting for upstream pr merge:  https://github.com/rancher/dashboard/pull/4697

**Comment by WuJun2016** [comment]
Hi， @slickwarren  Sometimes the code in harvster/dashboard is not merged into rancher/dashboard in time, so some bugs are fixed in single cluster, but not in multiple clusters.  If you want to test the latest features and bug fixes of harvester, you can replace `ui-dashboard-index` in settings with: `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`.

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Verified as fixed by creating multiple VMs and checking displayed memory.
