### ISSUE TITLE
[BUG] `harvester` wasn't set as default storage class inside Rancher provisioned cluster

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1629]
It should be set as the default storage class. Otherwise any workload defines PVC with no storage class cannot be deployed.

To test: deploy `wordpress` using default value from Bitnami (add `https://charts.bitnami.com/bitnami` to the chart repo.)

**Comment by guangbochen** [comment]
Currently only RKE1's chart will set the `harvester` as the default storage class. 
For the RKE2 cluster, users can modify it manually via clicking the `cluster -> More resources -> StorageClasses` and set the `Harvester ` SC as the default one in the RKE2 cluster.
![image](https://user-images.githubusercontent.com/4569037/146111073-cf63ad34-ab3f-4d65-a95d-7448fe1f2d8d.png)

**Comment by yasker** [comment]
Is it possible to set the default storage class in RKE2 as well? if we cannot do it in this release, we need to add the release note to it and fix it in the next release.

**Comment by guangbochen** [comment]
nope, the RKE2 uses an embedded chart and it is already released in Nov. before we add this change, will bump the embedded chart version of the next RKE2 release. cc @yaocw2020 

Also the workaround is easy and will document it on the release note, thanks.

**Comment by yasker** [comment]
I've checked with upstream RKE1 deployment and confirmed that `harvester` storage class was set as default for RKE1 cluster.

Move this issue to v1.0.1 for validation of RKE2 cluster in December release.

**Comment by TachunLin** [comment]
Verified `not fixed` on rancher `v2.6.3` and `v2.6-head`.
Move the issue to `ice-box` pending for rancher side update to `v1.22.5+rke2r1`

### Result
The latest RKE2 version to provision harvester cluster on rancher 2.6.3 is `1.22.4+rke2r2` which is not yet bumped harvester cloud provider and harvester csi driver. 

Thus the provisioned RKE2 cluster still not set `harvester` as default storage class 

![image](https://user-images.githubusercontent.com/29251855/148735610-e811a210-7ae6-4278-93f1-41b6a380d6ba.png)

![image](https://user-images.githubusercontent.com/29251855/148735441-a6eb5503-d2ce-4891-bc48-cc66ea973767.png)

![image](https://user-images.githubusercontent.com/29251855/148735149-fa2af2b5-3736-44ae-a26e-62397cb08bd0.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-82c4225b-head (22/01/10)
* Rancher version: v2.6.3, v2.6-head

### Environment Preparation
1. Docker install rancher v2.6.3 or v2.6-head
2. Install harvester, create image and virtual network

### Verify Steps

1. Environment preparation as above steps
2. Import harvester to rancher
3. Create cloud credential
4. Provision a RKE2 harveter cluster 
5. Wait for provision complete
6. Access RKE2 cluster 
7. Check the Cloud provider and CSI driver in Installed Apps
8. Check the StorageClasses under Storage

### Additional Context 
https://github.com/rancher/rke2/releases 
![image](https://user-images.githubusercontent.com/29251855/148749522-49bc195f-2741-4bd0-9a78-a593aa19fa13.png)

**Comment by rebeccazzzz** [comment]
Moving this issue to ready for testing since https://github.com/rancher/kontainer-driver-metadata is released with newer version which contains the rke2 release that is needed for this issue.

**Comment by TachunLin** [comment]
Verified **not fixed** on master-b09e3233-head (02/14) and rancher `v2.6.4-rc3`.
We already have harvester set as default storage class, however we are not able to deploy wordpress since the CSI driver have DaemonSet not ready. Move this issue back to implement stage

![image](https://user-images.githubusercontent.com/29251855/154276722-8d6bdc15-b2a5-4185-905f-c2babb968da5.png)


### Result
In rancher `v2.6.4-rc4`, it provide 1.22.6+rke2r1 as the default kubernetes version which already have bumped CCM and CSI chart.

![image](https://user-images.githubusercontent.com/29251855/154254542-0f27d8d0-ef8e-4529-99bd-0cdba847ed7c.png)
 
After provisioning guest RKE2 cluster in harvester and set `harvester` as default storage class

![image](https://user-images.githubusercontent.com/29251855/154270809-f3285732-2375-49fc-862b-f5f048424ba3.png)

However while we deploy wordpress apps, it keeps in the pending status
![image](https://user-images.githubusercontent.com/29251855/154273372-58b96951-178e-4172-917b-5c1f7746742a.png)

Since the `Daemon Set` is not ready in CSI driver apps
![image](https://user-images.githubusercontent.com/29251855/154273620-73a23cd2-8f6a-4259-b521-83227b162cc9.png)

![image](https://user-images.githubusercontent.com/29251855/154273711-942ea7a0-b249-4b7b-a48b-c84800ec7f4e.png)

Above issue have been reported in #1895, I would suggest we should fix this blocker issue to make this feature complete.

### Test Information

- Test Environment: 1 nodes harvester on local kvm machine
- Harvester version: master-b09e3233-head (02/14)
- Rancher version: v2.6.4-rc3

### Verify Steps

1. Environment preparation as above steps
2. Import harvester to rancher
3. Create cloud credential
4. Provision a RKE2 harveter cluster
5. Wait for provision complete
6. Access RKE2 cluster
7. Check the Cloud provider and CSI driver in Installed Apps
8. Check the StorageClasses under Storage


### Additional Context
When we change Cloud config file path to /var/lib/rancher/rke2/etc/config-files/cloud-provider-config, 
the harvester-csi-driver can be deployed without error.
![image](https://user-images.githubusercontent.com/29251855/154276212-951c0e59-d6ea-41d1-a7e3-0e3ac266ceed.png)

**Comment by noahgildersleeve** [comment]
I tested this in Rancher v2.6-head with build number 948355c (today) and Harvester master-45182389-head. I refreshed the kubernetes metadata in drivers under cluster management and it assigned harvester as the default storage driver when provisioning RKE2 clusters.
![Screenshot from 2022-02-16 14-04-31](https://user-images.githubusercontent.com/83787952/154365606-8e3ea37d-5dd0-45ef-92cd-5d05a928f3bc.png)

![Screenshot from 2022-02-16 14-07-23](https://user-images.githubusercontent.com/83787952/154365605-31eb4358-e454-4dea-87cf-25da776e85f4.png)
[supportbundle_48cb77d5-07f1-4f65-a880-0ddd0edb7661_2022-02-16T22-36-31Z.zip](https://github.com/harvester/harvester/files/8084100/supportbundle_48cb77d5-07f1-4f65-a880-0ddd0edb7661_2022-02-16T22-36-31Z.zip)

**Comment by guangbochen** [comment]
Since the `harvester` storageClass is already set as default, we may close this one and track the `CSI pod failed to start` on the https://github.com/harvester/harvester/issues/1895 accordingly.

**Comment by TachunLin** [comment]
Close this issue, since the original requirement have been fixed. 
Focus on tracking the failed to deploy CSI pod on RKE2 cluster in #1895
