### ISSUE TITLE
[BUG] Regression: The installer and dashboard are always displayed on tty1

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1648]
Harvester 1.0-rc1

Regression of https://github.com/harvester/harvester/issues/485

Using PXE boot entry such as:

```
label install
  kernel harvester/vmlinuz
  append initrd=harvester/initrd ip=dhcp net.ifnames=1 rd.cos.disable console=tty1 console=ttyS1,115200 root=live:http://192.168.200.19/harvester/rootfs.squashfs harvester.install.automatic=true  harvester.install.config_url=http://192.168.200.19/harvester/config-harvey.yaml
```

Expectation:
Installer is displayed on both tty1 and ttyS1

Actual:
Installer is only shown on tty1 (see left side on screenshot). ttyS1 (right side on screenshot) shows a `rancher` login prompt.

<img width="901" alt="Screenshot 2021-12-08 at 16 33 52" src="https://user-images.githubusercontent.com/3813921/145237187-568a8b3a-6b02-4ea9-92ca-8e065b0b0fbf.png">

**Comment by bk201** [comment]
This is not a regression of https://github.com/harvester/harvester/issues/485
https://github.com/harvester/harvester/issues/485 displays the installer on the TTY specified in the **last** `console=` parameter.

I've changed the implementation to show the installer only on the TTY specified in the **first** `console=` parameter. Because important kernel messages are output to the last one. In some cases, users may want to capture kernel messages.

Showing installer on **all** specified TTYs is also not a good idea at this moment because the network installation works are done in the installer. If there are multiple instances, they will all do the same work.

**Comment by bk201** [comment]
@janeczku Feel free to re-open the issue if this impacts users and needs some adjustment.
