### ISSUE TITLE
[BUG] Installation fails when doing a manual PXE install

### ISSUE THREAD

**Issue by roncterry** [harvester/harvester#1649]
**Issue**
When installing manually after booting via PXE the OS image is installed and reboots successfully but no container images were installed causing the Harvester install to not function. It appears that the container image test/install is either being skipped or failing during the installation process.

**Steps to Reproduce**
To reproduce, boot via PXE but do not provide a yaml config file. Follow all prompts as you would when doing a manual install booting from ISO.

**Expected behavior**
Manual installation should function the same where booting from ISO or from PXE.

**Support bundle**
No support bundle is possible as the Harvester environment was not actually deployed.

**Environment:**
 - Harvester ISO version: 0.3.0 and 1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal and virtual machine

**Additional context**
(none)

**Comment by johnliu55tw** [comment]
At the last stage of installation, the installer would preload the container images stored in ISO into the installed system. For **automatic** PXE installation, the ISO will be downloaded and mounted using the URL from [config `install.iso_url`](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#installiso_url). However, for **manual** PXE installation, because `install.iso_url` is not given (via Installer UI), the installer cannot preload those container images.

Most of the images can be pulled from the internet after installation, except for one crucial image: `harvester-cluster-repo`. It's used to bootstrap Harvester and it only exists in ISO currently.

A workaround for now would be to find a place to serve the ISO on an HTTP server, then manually provide the necessary `install.iso_url` config by remote config:
```
install:
  iso_url: http://192.168.123.234/harvester-v1.0.0-amd64.iso
```

**Comment by johnliu55tw** [comment]
@bk201 @guangbochen I think we could fix it two ways:
- Publish `harvester-cluster-repo` to container registry so it can be pulled from the internet if preloading failed.
- The text UI would force users to enter ISO URL if the installation environment is PXE + Manual.

Or we could do both ;)

**Comment by bk201** [comment]
@roncterry Could you see if applying https://github.com/harvester/harvester/issues/1649#issuecomment-1016219574 fix the issue? We don't have the plan to publish harvester-cluster-repo image, thus providing an ISO in the config is needed in PXE boot installation.

**Comment by roncterry** [comment]
Providing the remote config containing the iso_url does work. 

It would be nice to be able to pass harvester.install.iso_url= in at boot time by appending it to the kernel line in the ipxe config. That does not currently appear to work.

The docs should probably be updated to reflect the currently working method of doing this.

**Comment by bk201** [comment]
@roncterry  Specifying kernel parameters like`harvester.install.iso_url= ` only works in full PXE boot mode ([with `harvester.install.automatic=true`](https://github.com/harvester/harvester-installer/blob/d763b37dc24a5ec2377f41896fbe74b42c779249/pkg/console/install_panels.go#L60-L66)), we'd suggest using this mode to do unattended installation.

**Comment by bk201** [comment]
@roncterry `install.iso_url` is needed in his situation, could you see if that work for you?

**Comment by bk201** [comment]
@roncterry We'll close this issue, please let us know if specifying `install.iso_url` doesn't work for you.
