### ISSUE TITLE
[FEATURE] bump Harvester CCM & CSI chart of RKE2 v1.22

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1659]
**Describe the solution you'd like**
Need to bump Harvester CCM & CSI chart of RKE2 v1.22+ releases, and fix the default CSI bug https://github.com/harvester/harvester/issues/1629 on RKE2 v1.22+ versions

**Additional context**
related issue: https://github.com/harvester/harvester/issues/1629

**Comment by TachunLin** [comment]
Verified `not fixed` on rancher `v2.6.3` and `v2.6-head`.
Move the issue to `ice-box` pending for rancher side update to `v1.22.5+rke2r1`

### Result
The latest RKE2 version to provision harvester cluster on rancher 2.6.3 is `1.22.4+rke2r2` which is not yet bumped harvester cloud provider and harvester csi driver. 

![image](https://user-images.githubusercontent.com/29251855/148751307-2d15be8e-db11-47b8-b79c-5cf4fc9ac7d3.png)

https://github.com/rancher/rke2/releases 
![image](https://user-images.githubusercontent.com/29251855/148749522-49bc195f-2741-4bd0-9a78-a593aa19fa13.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-82c4225b-head (22/01/10)
* Rancher version: v2.6.3, v2.6-head

### Environment Preparation
1. Docker install rancher v2.6.3 or v2.6-head
2. Install harvester, create image and virtual network

### Verify Steps

1. Environment preparation as above steps
2. Import harvester to rancher
3. Create cloud credential
4. Provision a RKE2 harveter cluster
5. Check the available kubernetes version list

**Comment by rebeccazzzz** [comment]
Moving this issue to ready for testing since https://github.com/rancher/kontainer-driver-metadata is released with newer version which contains the rke2 release that is needed for this issue.

**Comment by TachunLin** [comment]
Verified `not fixed` on `master-b09e3233-head` (02/14) and rancher `v2.6.4-rc3`. 
Since issue #1629 is not completely fixed. move it to implement pipeline

### Result
In rancher v2.6.4-rc3, it provide 1.22.6+rke2r1 as the default kubernetes version which already have bumped CCM and CSI chart. 

![image](https://user-images.githubusercontent.com/29251855/154254542-0f27d8d0-ef8e-4529-99bd-0cdba847ed7c.png)

However the CSI driver is not completely deployed since the DaemonSet service is not ready. 
This issue have been tracked in #1895 
![image](https://user-images.githubusercontent.com/29251855/154279042-5e8581dc-8263-455e-bf67-78bbf98dfa84.png)

![image](https://user-images.githubusercontent.com/29251855/154410737-2c00b291-e801-423e-aecb-860481350903.png)

### Test Information

- Test Environment: 1 nodes harvester on local kvm machine
- Harvester version: master-b09e3233-head (02/14)
- Rancher version: v2.6.4-rc3

### Verify Steps
1. Environment preparation as above steps
2. Import harvester to rancher
3. Create cloud credential
4. Provision a RKE2 harveter cluster
5. Wait for provision complete
6. Access RKE2 cluster
7. Check the Cloud provider and CSI driver in Installed Apps
8. Check the StorageClasses under Storage

**Comment by guangbochen** [comment]
I think we can aggregate and track the the `CSI DaemonSet pod failed to start` on the https://github.com/harvester/harvester/issues/1895

**Comment by TachunLin** [comment]
Close this issue and focus on tracking the `CSI DaemonSet pod failed to start` at #1895
