### ISSUE TITLE
[FEATURE] one time boot option for ISO installation

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1662]
**Is your feature request related to a problem? Please describe.**
In Harvester UI, if we're installing a VM via ISO, after the installation is completed the ISO will be booted up again, which normal is undesired.

**Describe the solution you'd like**
Give an option to set temporarily boot order, so once the ISO installation is completed, we will boot from the main drive instead.

**Describe alternatives you've considered**
Change the VM config after the installation is completed. But it's more cumbersome to the user.

**Additional context**

**Comment by bk201** [comment]
@yasker @guangbochen  Normally this is achieved by invoking the `ipmitool` command or any other out-of-band tools to set the boot order after an installation.

We now have [installer webhooks](https://github.com/harvester/harvester-installer/pull/57) (unfortunately I think it's undocumented) that can be used at some installation points (e.g, installed successfully) to notify infrastructure services to do OOB management.

Another idea is to add the ability to execute custom scripts at those installation points. Do you think this might help?

**Comment by yasker** [comment]
@bk201 Sorry there is a misunderstanding. I was referring to installing a VM using ISO in Harvester, not the Harvester installer. I agree if we're installing Harvester on bare metal nodes, it would be the admin for the node to ensure the correct boot order. I don't think we need to do OOB mgmt there.

**Comment by weihanglo** [comment]
Did some research on this topic with three major Linux distros in virt-manager. I installed them via the GUI of virt-manager with option "Local install media (ISO image or CDROM)".

<img src="https://user-images.githubusercontent.com/14314532/163774555-b9eecd53-58c7-421c-a391-3890cf086f00.png" width="400px">

- **openSUSE Leap15.3**: There is a "boot from disk" on their ISO as the first option, so that if user forget to eject the ISO, it'll skip booting from the IOS automatically after a timeout.
- **Fedora 35 server**: First boot option of the ISO is installation even after the installation.
- **Ubuntu 20.04.4 server**: Tell user to moreve the installation medium from CD-FROM after the installation before reboot.

In fact, virt-manager handles all the boot order and boot options. If user use the GUI wizard to install from an ISO, it will temporarily put the ISO in a highest order. And after the installation, it removes the medium from boot options even if the installation did not succeed. [Here is the code][has_install_phase] it determine whether it's in an install phase and permitted to conduct special stuff. This seems to be an one-time option, if you install an OS first and later use the ISO to install the second time, none of the boot related options would be changed.

[has_install_phase]: https://github.com/virt-manager/virt-manager/blob/78e24fc986a3f43b2a26f678b5b63d80e1a578ed/virtinst/install/installer.py#L497-L507 

For harvester, we can have the a similar mechanism. That might be: 

1. Add an annotation for VirtualMachine CR to indicate that the VM is in install phase
    - If the controller detects the annotation, it will change the CD-ROM to the first boot device temporarily.
    - When the VM reboot or shutdown, the controller removes the annotation from the VirtualMachine CR.
1. In the Harvester dashboard, add a checkbox to let use enable "Eject CD-ROM after installation".

There is a technical difficulty. If an VM is shutted down or  rebooted from inside, our controller might not be notified. Will continue investigating this part.

**Comment by chrisho** [comment]
After testing, set `bootorder` to 1 for the primary disk and ISO to 2. If the main disk does not have a system boot on the first boot, it will automatically boot the second one, and reboot will boot the main disk after installing the system.

eg:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/3347460/179653508-ef5ad070-c7b8-4814-b308-0717c547a047.png">

Does this solve your scenario? @yasker

**Comment by yasker** [comment]
@chrisho Great! That works. 

Can we document it?

**Comment by chrisho** [comment]
> After testing, set `bootorder` to 1 for the primary disk and ISO to 2. If the main disk does not have a system boot on the first boot, it will automatically boot the second one, and reboot will boot the main disk after installing the system.

Yeah, I'll add details to the document later

**Comment by lanfon72** [comment]
close as resolved.

Tested on `v1.1.0-rc2`, use `bootorder` to control one-time boot work as expected.
