### ISSUE TITLE
[FEATURE] Allow Longhorn to use another disk other than the root disk during installation

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1728]
**Is your feature request related to a problem? Please describe.**

In many hardware setups involving multiple disks per server a dedicated physical disk will be used for Harvester installation.
It should be possible to exclude that disc from being used to store VMs for several reasons:

- hard storage IO separation between harvester system and VM workloads
- root install disk may have a different performance than the disks dedicated for VM storage (e.g. SSD vs NVMe)

**Expected UX**

There is a global setting to disable Longhorn default storage path creation on the install disc.

**Comment by guangbochen** [comment]
By default, `/var/lib/longhorn` on the host will be used for storing the volume data. We can avoid using the default directory by adding a new disk, then disable scheduling for `/var/lib/longhorn` of both Harvester installer and PXE installation.

**Comment by johnliu55tw** [comment]
@guangbochen I'm actually thinking of a simpler way to achieve this: **Mount the additional disk (partition) to `/var/lib/longhorn` so it would be the default storage**. This has a few benefits:

- Still works when there's only one Harvester node
    - Longhorn won't decommission the default directory (`/var/lib/longhorn`) after disabling scheduling if there are not enough replicas. With only one node, it's almost not possible for Longhorn to create enough replicas. Of course, we could force Longhorn to remove the default directory once the new disk is added, but it would increase the complexity.

- No need to wait for NDM to provision the additional disk
    - NDM would require some time to provision the additional disk. Users might have to wait a while to see all data being migrated to the additional disks.

**Comment by guangbochen** [comment]
@johnliu55tw Longhorn supports [default disk customization](https://longhorn.io/docs/1.2.3/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes) that we can leverage to customize the default data path of the node. Also, I'm fine to use the default path and mount it to additional disks.

**Comment by johnliu55tw** [comment]
**This design is obsoleted. See [HEP Select another disk to store VM data during installation](https://github.com/harvester/harvester/blob/master/enhancements/20220120-select-another-disk-to-store-vm-data-during-installation.md)**
# Brief Design (Obsolete)
## User Interface
- Add a new installer config `install.vm_data_disk` to specify the disk to be used as the default VM storage (Longhorn) disk.
```
install:
  vm_data_disk: /dev/sda
``` 

- Add config `install.vm_data_disk` to Installer UI to let users select one of the detected storage devices.

## System
The installer would perform the following steps in order to use the specified disk as the default VM storage device:
1. Create a GPT partition (which also wipes the data) and create **one** partition
2. Create EXT4 filesystem on the partition
3. **Add label `HARV_LH_DEFAULT` to the partition**
4. Ensure [`cos-rootfs.yaml`](https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/cos-rootfs.yaml) has correct settings to mount the partition to `/var/lib/longhorn`, which will be used by Longhorn as the default disk.
    - We have a config `no_data_partition` that might conflict with `vm_data_disk`.

As long as Longhorn uses `/var/lib/longhorn` as the default data path, we don't need to change any settings, annotations, labels, etc. of Longhorn in order to use the extra disk as default Longhorn storage.

cc @guangbochen @bk201

**Comment by yasker** [comment]
I don't recommend using `/var/lib/longhorn`. If the disk contains that directory failed, then we will have a problem since that directory contains Longhorn engine binaries as well. It's better for `/var/lib/longhorn` to be on the root disk but have a separate path for the Longhorn data disk. It's better if we preconfig Longhorn to use a different directory for the default data path (which is doable in the Longhorn config).

Also, it seems `vm_` in `vm_data_disk` is unnecessary. Just call it `data_disk`(or `default_data_disk`) should be fine.

Are we allowing multiple disks?

**Comment by johnliu55tw** [comment]
That's a valid point. I'll see how I could utilize [Configuring Defaults for Nodes and Disks](https://longhorn.io/docs/1.2.3/advanced-resources/default-disk-and-node-config/) in order to separate the binaries and data.

As for multiple disks support, I think we could leverage the Node label `node.longhorn.io/default-disks-config: <config>` to tell Longhorn how to set up the default disks when the Node created/joined the cluster (Need some PoC here).

The other thing is we need to make sure everything still works when users are upgrading from an older version of Harvester, with all the configs we made to Longhorn.

**Comment by johnliu55tw** [comment]
**This design is obsoleted. See [HEP Select another disk to store VM data during installation](https://github.com/harvester/harvester/blob/master/enhancements/20220120-select-another-disk-to-store-vm-data-during-installation.md)**

# Brief Design V2 (Obsolete)
Supporting multiple disks requires additional efforts. I will discuss them separately.

## Supporting one disk to be used as Longhorn default disk
We could slightly adjust the [first design](https://github.com/harvester/harvester/issues/1728#issuecomment-1009567014) to address the [Longhorn binaries](https://github.com/harvester/harvester/issues/1728#issuecomment-1011424547) issue:
1. Change the Longhorn setting `defaultDataPath` to `/var/lib/longhorn_data`.
    - It can be any path except `/var/lib/longhorn`. The data disk will be mounted onto this path.
    - It's possible to change this setting during the zero-downtime upgrade.
2. Create an EXT4 filesystem on the disk (partition or partitionless) with label `HARV_LH_DEFAULT`
3. Ensure [`cos-rootfs.yaml`](https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/cos-rootfs.yaml) has correct settings to mount the filesystem onto `/var/lib/longhorn_data` (Instead of `/var/lib/longhorn`), which will be used by Longhorn as the default disk due to the setting we changed at step 1.

Not much needs to change here. However, it's a different story for supporting multiple disks to be Longhorn disks.

## Supporting multiple disks to be used as Longhorn default disks
Longhorn supports creating multiple default disks with Node-wise settings:
- Change the Longhorn setting `createDefaultDiskLabeledNodes` to `true`.
- Add a label to the Node: `node.longhorn.io/create-default-disk="config"`, indicating default disks on this Node should be created with a Node-wise config.
- Add an **annotation** to the Node: `node.longhorn.io/default-disks-config=<disks config in JSON>` to specify the Node-wise config.

Then Longhorn would follow the `<disks config in JSON>` to create default disks [REF](https://longhorn.io/docs/1.2.3/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes).

What really matters here is **[we can't add annotations to the Node during installation](https://github.com/k3s-io/k3s/issues/2626)**. It's possible to add labels, but not annotations.

Luckily, the labels and annotations could be added to the Node after it has joined the cluster. Longhorn would follow the annotation to create default disks once it appears, **as long as default disks have never been created on the Node**. Therefore, we should be able to rely on NDM or other controllers to help add the labels and annotations after it joined the cluster, but it requires extra effort.

I'm thinking can we only support the **one disk as default disk** use case, and let NDM's auto-provisioning feature handles adding other disks as Longhorn storage? @yasker @guangbochen

**Comment by yasker** [comment]
Thanks @johnliu55tw. LGTM.

Unable to predefine annotation is a bit annoying... I am fine with only supporting one disk as the default disk at the time of installation for now. We will see if it's necessary to add multiple disks support during installation later.

**Comment by johnliu55tw** [comment]
@yasker @guangbochen

Changing Longhorn setting `defaultDataPath` would have a side-effect: **A 1.0.0 Node joining a 1.0.1 cluster would cause the Longhorn data on the 1.0.0 Node unable to persist across system reboots**. Here's the reason:
- In `1.0.0`, the `defaultDataPath` is `/var/lib/longhorn`. This path is configured to be persistent across reboots, either because it's the mount point of _Longhorn Data Partition_, or we configured it to be persistent in [cOS rootfs layout](https://github.com/harvester/harvester-installer/blob/c7401343efb945edfbbbef1c67440ee4577aba77/pkg/config/templates/cos-rootfs.yaml#L26) if `NoDataPartition` config is `true`.
- In `1.0.1`, we would change the `defaultDataPath` to `/var/lib/longhorn_data`. When a fresh installed `1.0.0` node is joining a `1.0.1` cluster, Longhorn would set up `/var/lib/longhorn_data` as the default disk on the Node, which does not configure as persistent volume for `1.0.0` Nodes.

> **NOTE: This only affects fresh installed Node (ISO or PXE). The upgrading process is not affected**, as all the Nodes in an existing cluster should already have default disks configured.

To me this sounds like a reasonable limitation: You can't create an older version of Node and try to join it into a newer version cluster. However, we don't have a mechanism to validate the version mismatch yet.

cc @bk201

**Comment by guangbochen** [comment]
IMO, all of the nodes in a Harvester cluster should be the same version. It might be a mixed environment during the upgrade, but in the end, all of the nodes will have the same version.
- For a new joined node, users should only use the same image version of the management node.
- If users upgrade their cluster from `v1.0.0` to `v1.0.1`, the existing node's default path will remain unchanged(i.e,`/var/lib/longhorn`), and for newly joined nodes with a separated data disk, they will use the `/var/lib/longhorn_data` as the default path.

**Comment by TachunLin** [comment]
Verified **PASS** for `Case 1` test scenario in https://github.com/harvester/tests/issues/151 

### Case 1: Machines with two or more disks can assign the data disk

- [x] The data disk `/dev/sdb` is mounted to `/var/lib/harvester/defaultdisk/` as the default disk

  ```rancher@harvester-one-220301:~> lsblk
  NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  loop0    7:0    0   3.2G  1 loop /
  sda      8:0    0   150G  0 disk 
  ├─sda1   8:1    0   960K  0 part 
  ├─sda2   8:2    0    48M  0 part /oem
  ├─sda3   8:3    0    14G  0 part /run/initramfs/cos-state
  ├─sda4   8:4    0   7.5G  0 part 
  └─sda5   8:5    0 128.5G  0 part /usr/local
  sdb      8:16   0   150G  0 disk /var/lib/harvester/defaultdisk
  sdc      8:32   0    10M  0 disk /var/lib/kubelet/pods/b5cb433f-daf3-4e0b-8b97-b5955ed1ac9b/volumes/kubernetes.io~csi/pvc-ca280b19-a372-4ab4-ba8
  sdd      8:48   0    50G  0 disk /var/lib/kubelet/pods/6584f86b-2789-4161-b389-0d6d3b5fbeb7/volume-subpaths/pvc-208b31d0-4ae8-46e9-a906-4c8a4523
  sr0     11:0    1  1024M  0 rom
  ```

- [x] Create a VM and verify Longhorn is storing data into /var/lib/harvester/defaultdisk/

  ```
  rancher@harvester-one-220301:/var/lib/harvester> ls /var/lib/harvester/defaultdisk/
  backing-images	longhorn-disk.cfg  lost+found  replicas  tmp
  ```

- [x] Create a huge file in the VM and see the space of /dev/sdb is getting consumed.

  ```
  rancher@harvester-one-220301:/var/lib/harvester> df -BG /dev/sdb
  Filesystem     1G-blocks  Used Available Use% Mounted on
  /dev/sdb            147G   13G      128G   9% /var/lib/harvester/defaultdisk
  ```

- [x] /var/lib/longhorn still exists, and Longhorn binaries are stored here.

  ```
  rancher@harvester-one-220301:~> ls -l /var/lib/longhorn/engine-binaries
  total 4
  drwxr-xr-x 2 root root 4096 Mar  2 03:26 longhornio-longhorn-engine-v1.2.3
  ```

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `master-e214d829-head` 03/01


### Verify Steps
1. Create a VM with two hard disk (Both 150GB)
2. ISO install harvester
3. Select /dev/sda as the installation OS disk 
4. Select /dev/sdb as the default data disk
  ![image](https://user-images.githubusercontent.com/29251855/156288353-b8785d89-f62a-4ccb-956b-374a6a9d534b.png)
  ![image](https://user-images.githubusercontent.com/29251855/156288531-907fade4-41eb-4aa9-acb4-3b8ad7fdc3ef.png)
5. ssh to harvester node 
6. Run `lsblk`
7. Create a openSUSE leap 15 VM 
8. ssh to suse VM
9. Create a 10GB large file 
  `dd if=/dev/zero of=./largeFile.img bs=4k iflag=fullblock,count_bytes count=10G`
10. Back to suse VM
11. Run `ls /var/lib/harvester/defaultdisk/` 
12. Run ` df -BG /dev/sdb`

**Comment by TachunLin** [comment]
Verified **PASS** for Case 2 test scenario in https://github.com/harvester/tests/issues/151 

### Case 2: Machines with two or more disks can choose the same disk as OS and data disk

- [x] A partition labeled `HARV_LH_DEFAULT` is created on the OS disk `/dev/sda` and mounted to `/var/lib/harvester/defaultdisk/`

  ```
  rancher@harvester-one-220301:~> lsblk -o name,mountpoint,label,size,uuid
  NAME   MOUNTPOINT                                                                     LABEL            SIZE UUID
  loop0  /                                                                              COS_ACTIVE       3.2G d946c118-f622-4e76-87eb-92813b93e33b
  sda                                                                                                    150G 
  ├─sda1                                                                                                 960K 
  ├─sda2 /oem                                                                           COS_OEM           50M 9dfa20cf-7875-4bd9-864a-176c5b728996
  ├─sda3 /run/initramfs/cos-state                                                       COS_STATE         15G 59bfceaa-c021-4db5-8fc6-23af6c1024aa
  ├─sda4                                                                                COS_RECOVERY       8G e15f5756-e438-42e8-8a2b-c0d1983c7b3a
  ├─sda5 /usr/local                                                                     COS_PERSISTENT    50G a13b76fe-1248-4658-9af7-6c7b40ea5a4e
  └─sda6 /var/lib/harvester/defaultdisk                                                 HARV_LH_DEFAULT   77G b9f23b8e-0168-4772-a8cb-22a218d424eb
  sdb                                                                                                    150G 
  sdc    /var/lib/kubelet/pods/b0f96fae-3c97-4609-ad52-8c1ea83b08e5/volumes/kubernetes.                   10M 
  sdd    /var/lib/kubelet/pods/bddbe63b-9cf3-48fd-bbc7-40c9c037fead/volume-subpaths/pvc                   50G 
  sr0                                                                                                   1024M
  ```
- [x] `/var/lib/longhorn` still exists, and Longhorn binaries are stored here.
  ```
  rancher@harvester-one-220301:~> ls -l /var/lib/longhorn/engine-binaries
  total 4
  drwxr-xr-x 2 root root 4096 Mar  2 09:04 longhornio-longhorn-engine-v1.2.3
  ```
### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `master-e214d829-head` 03/01


### Verify Steps
1. Create a VM with two hard disk (Both 150GB)
2. ISO install harvester
3. Select /dev/sda as the installation OS disk 
4. Select `/dev/sda` as the default data disk
  ![image](https://user-images.githubusercontent.com/29251855/156320029-b019e9d0-8905-47f8-89f6-06f1b0101f0d.png)
  ![image](https://user-images.githubusercontent.com/29251855/156320361-062e29fe-36dd-4232-9fda-1dea4c814910.png)
5. ssh to harvester node 
6. Run `lsblk -o name,mountpoint,label,size,uuid`
7. Run `ls -l /var/lib/longhorn/engine-binaries`

**Comment by TachunLin** [comment]
Verified **PASS** for Case 3 test scenario in https://github.com/harvester/tests/issues/151 

### Case 3: Machines with only one disk cannot choose data disk

- [x] A partition labeled `HARV_LH_DEFAULT` is created on the OS disk `/dev/sda` and mounted to `/var/lib/harvester/defaultdisk/`

  ```
    rancher@harvester-one-220301:~> lsblk -o name,mountpoint,label,size,uuid
  NAME   MOUNTPOINT                                                                     LABEL            SIZE UUID
  loop0  /                                                                              COS_ACTIVE       3.2G 95604d74-b11d-428b-ba71-517047b1de82
  sda                                                                                                    150G 
  ├─sda1                                                                                                 960K 
  ├─sda2 /oem                                                                           COS_OEM           50M e4565134-b71e-4526-ace8-d3f213803c05
  ├─sda3 /run/initramfs/cos-state                                                       COS_STATE         15G 477b126e-6a6b-491b-9a0a-ef103f367266
  ├─sda4                                                                                COS_RECOVERY       8G d1b72b16-e751-4b0e-8501-9969f1c698cf
  ├─sda5 /usr/local                                                                     COS_PERSISTENT    50G a618097e-47b8-4e9d-b439-46c08bef3e7f
  └─sda6 /var/lib/harvester/defaultdisk                                                 HARV_LH_DEFAULT   77G 43f3a6b9-0f40-4ece-a13e-8fb0e8dde402
  sdb    /var/lib/kubelet/pods/abc699a7-0080-4584-a313-8b022425828d/volumes/kubernetes.                   10M 
  sdc    /var/lib/kubelet/pods/b059f127-0645-4062-be1c-f7ed806ee77b/volume-subpaths/pvc                   50G 
  sr0                                                                                                   1024M
  ```
- [x] `/var/lib/longhorn` still exists, and Longhorn binaries are stored here.

  ```
  rancher@harvester-one-220301:~> ls -l /var/lib/longhorn/engine-binaries
  total 4
  drwxr-xr-x 2 root root 4096 Mar  3 06:47 longhornio-longhorn-engine-v1.2.3
  ```
  
### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `master-e214d829-head` 03/01


### Verify Steps
1. Create a VM with one hard disk (150GB)
2. ISO install harvester
3. Select /dev/sda as the installation OS disk 
  ![image](https://user-images.githubusercontent.com/29251855/156510110-86b3457b-465f-4e3d-94b4-603767e3cd5d.png)
  ![image](https://user-images.githubusercontent.com/29251855/156510236-87ef79d7-dbe2-42f4-90cd-ef762ae5ab3d.png)
4. ssh to harvester node 
5. Run `lsblk -o name,mountpoint,label,size,uuid`
6. Run `ls -l /var/lib/longhorn/engine-binaries`

**Comment by TachunLin** [comment]
### Case 4: Test the validator

Both OS disk and data disk share the same validation criteria: **Soft limit = 140G and hard limit = 60G:**

#### ISO installer scenarios
|  | OS Disk  | Data Disk |
| ------------- | ------------- | ------------- |
| < Soft limit | Test 4-1: `PASS` | Test 4-2: `PASS` |
| < Hard limit | Test 4-3: `PASS` | Test 4-4: `PASS` |

- [x] Test 4-1: installer will show a warning message, but users can still proceed after pressing Enter again
- [x] Test 4-2: Same as above
- [x] Can install harvester with OS and data disk in `Soft limit` 
  ![image](https://user-images.githubusercontent.com/29251855/156540291-f69c5841-7229-4f00-9fcf-28c7627ec68c.png)
  ![image](https://user-images.githubusercontent.com/29251855/156540342-b5e29d77-a059-430d-b907-a7e047846720.png)
- [x] Test 4-3: installer will block the installation. Users must choose another disk that fulfills the criteria in order to proceed.
- [x] Test 4-4: Same as above
  ![image](https://user-images.githubusercontent.com/29251855/156542994-09cb3c50-434b-4e9d-9fc2-966dd51be4f1.png)
  ![image](https://user-images.githubusercontent.com/29251855/156543800-10cf2930-2279-44f1-a0d9-cad0db91e23a.png)

#### PXE config scenarios
|  | OS Disk  | Data Disk |
| ------------- | ------------- | ------------- |
| < Hard limit | Test 4-5:  | Test 4-6:  |

- [x] Test 4-5: only the hard limit would be established
  installer would stop the installation if the **`os disk`** is smaller than 60G. (e.g 55G) 
  ![image](https://user-images.githubusercontent.com/29251855/157861721-a94cac34-5205-41a4-add4-2f97eff531f6.png)
 

- [x] Test 4-6: PXE boot will stop installation on node when **`data disk`** is smaller than hard limit (e.g 55G)
  ![image](https://user-images.githubusercontent.com/29251855/157859210-cc86cc99-e3e8-45d9-a246-9f79fb4be9e4.png)

**Comment by TachunLin** [comment]
Verified **PASS** for `Case 5` test scenario in https://github.com/harvester/tests/issues/151 

### Case 5: Assigning data disk using install.data_disk Harvester config

- [x] Can assign data disk `/dev/vdb` from harvester create-config file 

- [x] The data disk `/dev/sdb` is mounted to `/var/lib/harvester/defaultdisk/` as the default disk

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # lsblk
  NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  loop0    7:0    0   3.2G  1 loop /
  sda      8:0    0    50G  0 disk /var/lib/kubelet/pods/b10328cb-0c9f-4af2-ab6d-e5c99b9d987f/volume-subpaths/pvc-2d73bbb4-468c-4488-882b-caf91bbef46a/prometheus/2
  sdb      8:16   0    10M  0 disk /var/lib/kubelet/pods/2a0c1b27-da6e-4a02-a30c-d6480dcf9dee/volumes/kubernetes.io~csi/pvc-0889f577-5cf1-4a80-9cc4-506e79128ba3/mount
  vda    253:0    0   150G  0 disk 
  ├─vda1 253:1    0    47M  0 part 
  ├─vda2 253:2    0    47M  0 part /oem
  ├─vda3 253:3    0    14G  0 part /run/initramfs/cos-state
  ├─vda4 253:4    0   7.5G  0 part 
  └─vda5 253:5    0 128.5G  0 part /usr/local
  vdb    253:16   0   150G  0 disk /var/lib/harvester/defaultdisk
  ```

- [x] Create a VM and verify Longhorn is storing data into /var/lib/harvester/defaultdisk/

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk #  ls /var/lib/harvester/defaultdisk/
  longhorn-disk.cfg  lost+found  replicas  testfile.img
  ```

- [x] Create a huge file in the VM and see the space of /dev/sdb is getting consumed.

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # df -BG /dev/vdb
  Filesystem     1G-blocks  Used Available Use% Mounted on
  /dev/vdb            147G   12G      129G   8% /var/lib/harvester/defaultdisk
  ```

- [x] /var/lib/longhorn still exists, and Longhorn binaries are stored here.

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # ls -l /var/lib/longhorn/engine-binaries
  total 4
  drwxr-xr-x 2 root root 4096 Mar  4 10:38 longhornio-longhorn-engine-v1.2.3
  ```

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `master-dba85940-head` 03/03


### Verify Steps
Example: Verified **PASS** for `Case 5` test scenario in https://github.com/harvester/tests/issues/151 

### Case 5: Assigning data disk using install.data_disk Harvester config

- [x] Can assign data disk `/dev/vdb` from harvester create-config file 

- [x] The data disk `/dev/sdb` is mounted to `/var/lib/harvester/defaultdisk/` as the default disk

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # lsblk
  NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
  loop0    7:0    0   3.2G  1 loop /
  sda      8:0    0    50G  0 disk /var/lib/kubelet/pods/b10328cb-0c9f-4af2-ab6d-e5c99b9d987f/volume-subpaths/pvc-2d73bbb4-468c-4488-882b-caf91bbef46a/prometheus/2
  sdb      8:16   0    10M  0 disk /var/lib/kubelet/pods/2a0c1b27-da6e-4a02-a30c-d6480dcf9dee/volumes/kubernetes.io~csi/pvc-0889f577-5cf1-4a80-9cc4-506e79128ba3/mount
  vda    253:0    0   150G  0 disk 
  ├─vda1 253:1    0    47M  0 part 
  ├─vda2 253:2    0    47M  0 part /oem
  ├─vda3 253:3    0    14G  0 part /run/initramfs/cos-state
  ├─vda4 253:4    0   7.5G  0 part 
  └─vda5 253:5    0 128.5G  0 part /usr/local
  vdb    253:16   0   150G  0 disk /var/lib/harvester/defaultdisk
  ```

- [x] Create a VM and verify Longhorn is storing data into /var/lib/harvester/defaultdisk/

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk #  ls /var/lib/harvester/defaultdisk/
  longhorn-disk.cfg  lost+found  replicas  testfile.img
  ```

- [x] Create a huge file in the VM and see the space of /dev/sdb is getting consumed.

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # df -BG /dev/vdb
  Filesystem     1G-blocks  Used Available Use% Mounted on
  /dev/vdb            147G   12G      129G   8% /var/lib/harvester/defaultdisk
  ```

- [x] /var/lib/longhorn still exists, and Longhorn binaries are stored here.

  ```
  harvester-node-0:/var/lib/harvester/defaultdisk # ls -l /var/lib/longhorn/engine-binaries
  total 4
  drwxr-xr-x 2 root root 4096 Mar  4 10:38 longhornio-longhorn-engine-v1.2.3
  ```

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: `master-dba85940-head` 03/03


### Verify Steps
Example: https://github.com/bk201/ipxe-examples/commit/e8683d917e7ab531a91008fccbd05026e151f04a
1. Clone ipxe example project https://github.com/harvester/ipxe-examples 
2. Edit Vagrantfile add the following content
  ```
  libvirt.storage :file,
            size: '150G',
            type: 'qcow2',
            bus: 'virtio',
            device: 'vdb'
  ```
3. Edit settings.yml update ens5 and ens6 to ens6, ens7
  ```
  cluster:
      - ip: 192.168.0.30
        mac: 02:00:00:0D:62:E2
        cpu: 6
        memory: 16384
        disk_size: 150G
        vagrant_interface: ens6
        mgmt_interface: ens7
  ```
4. Set harvester_cluster_nodes: 1
5. PXE install harvester and wait completion
6. Create a 10GB large file 
  ```
  cd /var/lib/harvester/defaultdisk
  dd if=/dev/zero of=./largeFile.img bs=4k iflag=fullblock,count_bytes count=10G
  ```
7. Run `ls /var/lib/harvester/defaultdisk/` 
8. Run ` df -BG /dev/sdb`

1. Clone ipxe example project https://github.com/harvester/ipxe-examples 
2. Edit Vagrantfile add the following content
  ```
  libvirt.storage :file,
            size: '150G',
            type: 'qcow2',
            bus: 'virtio',
            device: 'vdb'
  ```
3. Edit settings.yml update ens5 and ens6 to ens6, ens7
  ```
  cluster:
      - ip: 192.168.0.30
        mac: 02:00:00:0D:62:E2
        cpu: 6
        memory: 16384
        disk_size: 150G
        vagrant_interface: ens6
        mgmt_interface: ens7
  ```
4. Set harvester_cluster_nodes: 1
5. PXE install harvester and wait completion
6. Create a 10GB large file 
  ```
  cd /var/lib/harvester/defaultdisk
  dd if=/dev/zero of=./largeFile.img bs=4k iflag=fullblock,count_bytes count=10G
  ```
7. Run `ls /var/lib/harvester/defaultdisk/` 
8. Run ` df -BG /dev/sdb`

**Comment by TachunLin** [comment]
Case 6 test scenario in https://github.com/harvester/tests/issues/151 is blocked.
since currently the zero downtime upgrade from 1.0.0 GA is pending on  `Job has reached the specified backoff limit`

Move issue back to read to test pipeline and verify this test scenario again in the next zero downtime attempt.  

![image](https://user-images.githubusercontent.com/29251855/157440850-b2bb837c-a769-4406-b0f8-c64d3acfd460.png)

### Case 6: Upgrade

1. Create a 1.0.0 cluster
2. Upgrade it using master branch code
3. Verify Longhorn setting default-data-disk has been updated to /var/lib/harvester/defaultdisk

**Comment by TachunLin** [comment]
Verified **PASS** for `Case 6` test scenario in https://github.com/harvester/tests/issues/151 

### Case 6: System Upgrade

- [x] Verify Longhorn setting default-data-disk has been updated to /var/lib/harvester/defaultdisk 
  ```
  hpd8s7:~ # kubectl get -n longhorn-system setting.longhorn.io default-data-path
  NAME                VALUE                            AGE
  default-data-path   /var/lib/harvester/defaultdisk   3h51m
  ```
### Verification Steps
1. Create a 3 nodes harvester cluster with 1.0.0 release
2. Perform zero downtime upgrade without VM and image exists on cluster
3. Wait for System upgrade finish 
  ![image](https://user-images.githubusercontent.com/29251855/157843102-9df6fbe2-49c0-4cfd-b859-bfc3505cb0e3.png)
4. ssh to harvester node
5. Run `kubectl get -n longhorn-system setting.longhorn.io default-data-path`

### Test Information
- Test Environment: 3 nodes harvester on provo bare machines
- Harvester version: master-fd872c99-head (03/06)

**Comment by TachunLin** [comment]
All test scenarios listed in https://github.com/harvester/tests/issues/151 have been verified `PASS`. Close this issue.
