### ISSUE TITLE
[BUG] Dashboard Monitoring not working for Cluster Member 

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1775]
**To Reproduce**
1. Add a user as "Cluster Member" to Virtualization -> Harvester -> Edit -> Member Roles
2. Login as that user and navigate to Virtualization -> Harvester

**Expected behavior**
Monitoring graphs are visible on Virtualization Dashboard

**Actual behavior**

- Monitoring graphs are missing
- Capacity info is broken

**Environment:**
Harvester 1.0.0
Rancher 2.6.3
<img width="1679" alt="Screenshot 2022-01-05 at 14 50 02" src="https://user-images.githubusercontent.com/3813921/148229006-22dcb23a-a667-4583-8747-9032250260a0.png">
<img width="1583" alt="Screenshot 2022-01-05 at 14 51 25" src="https://user-images.githubusercontent.com/3813921/148229152-ac72c971-53dc-47e9-b144-dfd15ad2fa24.png">

**Comment by gitlawr** [comment]
Cluster members has no permissions to view monitoring metrics. This is consistent with Rancher monitoring in native k8s.

Cluster members can view nodes. I think they should be able to view node metrics by default. Here's the upstream ticket to track that(https://github.com/rancher/rancher/issues/36116).

Admin can grant additional permissions to cluster members so that they can view monitoring metrics

1. In Rancher UI, go to Global - Users & Authentication - Roles
2. Click the `Cluster` tab
3. Click `Create Cluster Role`
4. Input a name, e.g., `View Monitoring Metrics`.
5. Add the following permissions:
   - get,list,watch for `services/proxy`
   - get,list,watch for `apps` in `catalog.cattle.io` apigroup
   - get,list,watch for `nodes` in `metrics.k8s.io` apigroup
   - get,list,watch for `nodes` in `longhorn.io` apigroup
6. Save the role.
7. Edit the Harvester cluster, In `Member Roles`, bind the `View Monitoring Metrics` role to the cluster member users.

**Comment by guangbochen** [comment]
This issue is partially addressed via https://github.com/rancher/rancher/pull/36493 with adding node metrics view capability to cluster members using rancher v2.6.4-head.

Cluster members will not be able to view monitoring metrics by default by the admin can grant additional permission per https://github.com/harvester/harvester/issues/1775#issuecomment-1010555971.

**Comment by joshmeranda** [comment]
I could verify that it is possible to grant a user additional privileges to view the monitoring graphs. From my testing the exact steps provided by the above [comment](https://github.com/harvester/harvester/issues/1775#issuecomment-1010555971).

Adding `get`, `list`, and `watch` for resource `nodes` and api-group `metrics.k8s.io` does allow for capacity info to flow as expected.

If you grant a user access to all verbs, all resources, and all api-groups the monitoring the monitoring graphs begin to flow as expected. I will look into exactly which resources / api-groups are needed to allow this to work as expected.

**Comment by joshmeranda** [comment]
Looks like the steps defined actually do work as expected I was working with a bad harvester deployment.

It turns out we only need a subset of the described permissions to get the graphs to render AND populate with data:

![rancher-metrics-test-permissions](https://user-images.githubusercontent.com/43455015/158456546-81696b07-af90-4c28-99d3-d795ebab12eb.png)

 There is another error that pops up but does not seem to effect any of the graph functionality, and disappears quickly:

![rancher-grafana-services-proxy-error](https://user-images.githubusercontent.com/43455015/158456777-98fc8a92-8aee-4802-b2df-54e8a590dde5.png)
