### ISSUE TITLE
[BUG]Unable to delete RKE2 cluster from Rancher UI when the underlying Harvester cluster is inaccessible/deleted

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1799]
**Describe the bug**
If a Rancher RKE2 cluster is created via Rancher node driver, there's no way to delete it from Rancher UI after the imported Harvester cluster is de-registered and no longer accessible. Deletion stuck at "Waiting for machine [Harvester VM name] to delete".

**To Reproduce**
1. Import Harvester cluster into Rancher.
2. Create a new RKE2 cluster via Rancher node driver.
3. Delete the Harvester cluster from Rancher.
4. Now try to delete the RKE2 cluster after Harvester cluster is deleted and no longer accessible.

**Expected behavior**
There should be a way to easily cleanup the RKE2 cluster from Rancher UI, even after the Harvester cluster is no longer accessible.

**Support bundle**

**Environment:**
 - Harvester ISO version: latest master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): N/A

**Additional context**
![image](https://user-images.githubusercontent.com/1808417/149009163-b190d80a-8ab7-409a-a8b8-f389063c04d9.png)

### Test plans

**Can't delete cloud credential if there is an RKE2/k3s cluster rely on it**
1. Import Harvester cluster to Rancher v2.6-head.
2. Create a cloud credential for Harvester.
3. Create RKE2/k3s clusters on Harvester.
4. Try to remove Harvester's cloud credential. It can't be removed.
5. Remove RKE2/k3s clusters.
6. Remove Harvester's cloud credential. It can be removed now.

**Remove harvester cluster if there is an RKE2/k3s cluster rely on it**
1. Import Harvester cluster to Rancher v2.6-head.
2. Create a cloud credential for Harvester.
3. Create RKE2/k3s clusters on Harvester.
4. Remove the Harvester cluster in Virtualization Management page. Harvester cluster can be removed.
7. Remove RKE2/k3s clusters in Rancher. RKE2/k3s clusters can be removed, but related VMs are still running in Harvester because Rancher can't connect to the Harvester cluster.
8. Remove related VMs in Harvester. They can be removed.
9. Remove Harvester's cloud credential. It can be removed.

**Comment by FrankYang0529** [comment]
I can reproduce this issue, but we cannot fix this issue from Harvester side if Rancher already can't access Harvester cluster. I think we should separate this issue into two cases:

* Harvester is inaccesible: this may be caused by network issue, so we can do best effort to delete RKE2 cluster. Also, we can provide documents to manually delete VMs in Harvester and CR objects in Rancher.
* Harvester is deleted: we should have a webhook to prevent users delete `management.cattle.io/v3/cluster` CR in Rancher if there is a RKE2 cluster running on Harvester.

**Comment by FrankYang0529** [comment]
For different cases, I can get different results.

* Harvester is shutdown and inaccessible: we will get error message in deleting machine job if we try to remove RKE2 cluster. So RKE2 cluster will be stuck in `Removing` in Rancher.
![Screen Shot 2022-01-26 at 11 04 58 PM](https://user-images.githubusercontent.com/4927361/151189372-701bf9f3-387d-4d47-9ed6-770869af46d8.png)
* Harvester is up but its CR is deleted in Rancher: we can remove RKE2 cluster in Rancher, but VMs will still remain in Harvester.

**Comment by FrankYang0529** [comment]
I think we need to separate this issue into 3 cases:
* Harvester is inaccessible (network issues, harvester shutdown): in this case, we will get errors in removing RKE2 machine jobs like the following. I think it is fine. We can just do best effort to remove the RKE2 cluster because we can't connect to the Harvester cluster.
![](https://user-images.githubusercontent.com/4927361/151189372-701bf9f3-387d-4d47-9ed6-770869af46d8.png)

* Cloud Credential is deleted: in this case, we will get error messages in Rancher. Also, all providers have this issue, we need a validation webhook to prevent it.

```
2022/01/27 03:15:33 [ERROR] error syncing 'fleet-default/rke2-in-aws-pool1-7c09ec84-8jv8n': handler machine-provision-remove: secrets "cc-k4t8n" not found, requeuing
```

* Harvester CR is deleted in Rancher: Harvester is a special provider because it is also a cluster in Rancher. If we create an RKE2 cluster on Harvester, it is like a cluster in Rancher relying on another cluster in Rancher. From Harvester side, although this is a special case in Rancher, I would prefer to have a validation webhook for it. Also, even it's fine to delete Harvester CR in Rancher, we still have a running cluster-agent deployment in Harvester. Not sure whether we also need to clean this in Rancher handler function.

cc @guangbochen @gitlawr WDYT? Thank you!

**Comment by noahgildersleeve** [comment]
Tested in Rancher `v2.6-1d2b7468851553f4b89f8af99d74305af9d1b594-head` on docker instance and Harvester `master-9ecb4f9d-head` in single node KVM environment.
## Verification Steps
1. Imported Harvester into Rancher
2. Created cloud credentials
3. Created RKE2 cluster
4. Waited for RKE2 to provision
5. Deleted Harvester cluster
6. Deleted RKE2 cluster
