### ISSUE TITLE
[BUG] 1.0.1 opensuse/SLE change of qemu-guest-agent

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1833]
**Describe the bug**
Currently, openSUSE uses qemu-ga which we use in the OS automation in Harvester

**To Reproduce**
1. Create VM
2. Select OS, openSUSE
3. Currently it will try and enable qemu-ga, it should use qemu-guest-agent.service instead.

**Expected behavior**
By the time of 1.0.1 we will have moved to qemu-guest-agent.service

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure: R620

**Comment by WuJun2016** [comment]
https://github.com/harvester/harvester/issues/1871

**Comment by WuJun2016** [comment]
- https://github.com/harvester/harvester/issues/1871

**Comment by noahgildersleeve** [comment]
Tested in master-1a861fc1-head
## Validation steps
1. Create new VM with openSUSE image
2. Select openSUSE from OS Type in advanced settings
3. Check cloud config for qemu agent package

It currently is using `qemu-ga`
![Screenshot from 2022-01-31 13-20-05](https://user-images.githubusercontent.com/83787952/151875526-110276b1-55ad-44dc-8d20-6bee6725c167.png)

I checked the [commit](https://github.com/harvester/dashboard/pull/234/commits/2e730ee8ca33744f57b5f04fc736dec2a9673b34) and it looks like we removed `qemu-guest-agent.service` instead of `qemu-ga`. According to the ticket we should be using `qemu-guest-agent.service`

**Comment by WuJun2016** [comment]
Hi, @abonillabeeche ,   My understanding is that the `qemu-guest-agent.service` in `runncmd` and `qemu-guest-agent` should be equivalent, right?

**Comment by abonillabeeche** [comment]
SLES15-SP4 and SLES15-SP3-QU2 + or patched openSUSE use the new service name.

**Comment by noahgildersleeve** [comment]
Tested in harvester `master-45182389-head`. 
## Verification Steps
1. Create a new VM
2. Select opensuse live image
3. Select openSUSE from advanced settings
4. Boot VM
5. Check for running Service
![Screenshot from 2022-02-16 16-49-14](https://user-images.githubusercontent.com/83787952/154382902-2ed70ecb-2a9c-49f1-8c5d-0af72865b469.png)

**Comment by noahgildersleeve** [comment]
Moving to docs to verify that docs have been created.

**Comment by noahgildersleeve** [comment]
Tested in `master-45182389-head`. 
## Verification steps
1. Create new VM
2. add new file
3. create backup
4. edit file and add new files
5. create backup
6. edit second new file and create new file
7. Create backup
8. Restore to backup1
9. Verify that  only original file1 exists

**Comment by WuJun2016** [comment]
@noahgildersleeve   Documentation has been added.   https://github.com/harvester/docs/pull/125

**Comment by noahgildersleeve** [comment]
Looks good but is pending merge of [PR](https://github.com/harvester/docs/pull/125)

**Comment by guangbochen** [comment]
@noahgildersleeve The doc PR is merged, thanks.

**Comment by noahgildersleeve** [comment]
Validated docs were updated at https://docs.harvesterhci.io/v1.0/vm/create-vm/ .
