### ISSUE TITLE
[FEATURE] same vlan once taged/native

### ISSUE THREAD

**Issue by chifu1234** [harvester/harvester#1858]
**Is your feature request related to a problem? Please describe.**

Currently it is not possible to have the same VLAN (once as native) the other as taged vlan.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tjjh89017** [comment]
Hi @chifu1234 
Could you help us to describe this scenario with more detail?

By the way, if you configre the outgoing port with PVID 100 (native) and VID 100, it will always send out traffic without vlan 100 tag. This is correct beahvior and couldn't be change

Thanks a lot

**Comment by chifu1234** [comment]
Hi @tjjh89017,
Sorry I opened that issue a bit too quick ;).

I have to following setup:
On my switch I've configured vlan 10 and vlan 20.
Vlan 10 has the following ip 10.124.0.0/24. Vlan 20 has the following ip 10.124.1.0/24.
The default Vlan to the harvester node is Vlan 20. The VM running ontop of the harvester node is running in vlan 20 but tagged.
Now the vm running in vlan 20 tagged does not have any connectivity.

Thanks, Kevin

**Comment by tjjh89017** [comment]
Hi Kevin

First, let me confirm with you
Harvester-mgmt connects to switch with Vlan20 w/o tagged (native vlan)
(If possible, you could post the config of that port on the switch to us to confirm)

If so,
Because you setup vlan 20 for harvester mgmt port with untagged vlan 20.
And inside harvester, it will setup PVID as 1 on harvester-mgmt and harvester-br0.
So any untagged packet will act as VLAN 1 inside harvester.
Please config your VM VLAN network with VLAN 1 setting.

If vlan1 didnt work, we need to check you switch config.

Tks
Regards
Date
________________________________
寄件者: Kevin Klopfenstein ***@***.***>
寄件日期: Monday, January 24, 2022 6:29:12 PM
收件者: harvester/harvester ***@***.***>
副本: Date Huang ***@***.***>; Mention ***@***.***>
主旨: Re: [harvester/harvester] [FEATURE] same vlan once taged/native (Issue #1858)


Hi @tjjh89017<https://github.com/tjjh89017>,
Sorry I opened that issue a bit too quick ;).

I have to following setup:
On my switch I've configured vlan 10 and vlan 20.
Vlan 10 has the following ip 10.124.0.0/24. Vlan 20 has the following ip 10.124.1.0/24.
The default Vlan to the harvester node is Vlan 20. The VM running ontop of the harvester node is running in vlan 20 but tagged.
Now the vm running in vlan 20 tagged does not have any connectivity.

Thanks, Kevin

**Comment by tjjh89017** [comment]
Please refer to docs page [VLAN Network Best Practice](https://docs.harvesterhci.io/v1.0/networking/best-practice-vlan-aware-switch/)
If you have further question, feel free to re-open this ticket
thanks a lot
