### ISSUE TITLE
[Question] Is the harvester support hybrid clusters

### ISSUE THREAD

**Issue by gricuk** [harvester/harvester#1884]
Hi, I haven't found any info in documentation, therefore I create this question.

Could you please clarify the possibility of setup hybrid k8s clusters? For example:
I want to create k8s cluster via rke2 and harvester with master nodes only(master nodes will be VMs in harvester) and then add to k8s cluster bare-metal servers as workers (without adding this nodes to harvester)

**Comment by yasker** [comment]
If you're creating the setup via Rancher, that won't be possible since Rancher will going to use the Harvester nodes to create VMs for all of your clusters.

But since RKE2 can be set up on any nodes, you can do it by manually starting VMs in Harvester, forming the master nodes, then adding additional nodes to the RKE2 cluster. It doesn't matter if you want to use bare metal nodes or VM nodes for any node in the cluster in this way. Just to make sure they can be connected via the network.

**Comment by gricuk** [comment]
@yasker great thanks for the explanation.

**Comment by yasker** [comment]
Close the issue per the user's response. Feel free to open a new issue if needed.
