### ISSUE TITLE
Add custom service

### ISSUE THREAD

**Issue by samuel-odinware** [harvester/harvester#1890]
I was wondering what the best approach is to add a custom service to a host. I have written a custom fan controller service for systemd that I would like to have the daemon running in  Harvester but am unsure how to approach this. Thank you.

**Comment by guangbochen** [comment]
Harvester is developed by using the k8s as its infrastructure component, so u can turn your custom-service into a container workload and deploy it via https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/. And since this is a custom service so the Harvester team will not provide any support for it, thanks.

**Comment by samuel-odinware** [comment]
Thank you for pointing me in the right direction.
