### ISSUE TITLE
[BUG] Console not accessible when VM is still in status "not ready"

### ISSUE THREAD

**Issue by meysholdt** [harvester/harvester#1938]
**Describe the bug**

The "Open in Web VNC" and "Open in Serial Console" buttons are not accessible when the VM is in status "not ready"

<img width="185" alt="image" src="https://user-images.githubusercontent.com/239422/155210451-809b9eda-860f-417b-888a-ce7e3c481e74.png">

**To Reproduce**
1. create a VM with a Kubernetes readiness probe 
2. start the VM
3. when the VM left the status "starting", while the VM is in status "Not Ready" and before the VM is in status "Running", try to open the console. Observe that the drop-down menu does not open.

**Expected behavior**
The console should be accessible.

**Support bundle**
(none)

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure: VM on CentOS on bare-metal hetzner.com server

**Additional context**
In case it is technically possible to have the console already while the VM is still in "starting", that would be more awesome.

I'm filing this as a bug because if no readiness probe is configured, the consoles can access the VM. Consequently, a workaround for this bug is to remove the readiness probe. 

This bug is hurting me atm because I have a failing readiness probe and I can't access the console output to analyze why it's failing.

**Comment by weihanglo** [comment]
Thanks for filing this! 

My impression is that it's [the dashboard web UI blocking users from accessing the dropdown menu](https://github.com/harvester/dashboard/blob/0cdb8432d9a194ea7e13450cd81e0572a3f4bbbb/components/VMConsoleBar.vue#L69-L70). KubeVirt indeed [supports accessing non-running VMs](https://github.com/kubevirt/kubevirt/pull/5399), so IMHO Harvester should provide the same functionality.

To circumvent this issue before the fix landed, you can use [virtctl], a client tool to operate virtual machine, and execute `virtctl console <vm>` to access serial console. Otherwise, you can watch kubernetes event to check probe failures by running command like `kubectl get events --watch`.


[virtctl]: https://kubevirt.io/user-guide/operations/virtctl_client_tool/

Ref: https://github.com/kubevirt/kubevirt/blob/v0.50.0/docs/probes.md

**Comment by weihanglo** [comment]
Hello, @WuJun2016. Is it possible to relax the criteria of disabling the `VMConsoleBar` dropdown? I've tested preserving the web VNC window when the VM is stopped. And it shows only "This Virtual Machine is down" without breaking anything.

![image](https://user-images.githubusercontent.com/14314532/156122552-50f9371f-d330-4de3-97de-ef2ccddf05fd.png)

**Comment by WuJun2016** [comment]
@DaiYuzeng   Please help to see in what state websocket can connect.

**Comment by lanfon72** [comment]
Verified this bug should be fixed.

Base on weihang's comment: https://github.com/harvester/harvester/issues/1938#issuecomment-1055098118 and Dai's change: https://github.com/harvester/dashboard/pull/293, I only test the console is able to start up.

I'm not sure it is fully fixed the bug, so if you still encountered it, feel free to reopen this issue.
(and please attach more information for us to reproduce it, thanks.)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-b20a3b47-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Install Harvester with Any nodes
- Create the Image for VM creation
- Create a VM `a`
- When VM is not in **stop** state, console of `Open in Web VNC` and `Open in Serial Console` should be accessible
