### ISSUE TITLE
[Question] Any work around for Issue 1356 | failed to install harvester using USB

### ISSUE THREAD

**Issue by Shaharyar-Shaukat** [harvester/harvester#1959]
I face similar issue [1356](https://github.com/harvester/harvester/issues/1356) while trying to install harvester using USB stick.
After installing Harvester  and enabling UEFI, the hard drive does not show up as a boot option in the boot menu. 
 

Machine Used:-
Celsius M730 Xeon E5-2650v2 2.60GHz

**Comment by bk201** [comment]
@Shaharyar-Shaukat After Harvester is installed, could you bring up the boot menu of BIOS and select try select the ESP (by unplugging the USB stick first)?
It might look like: https://docs.harvesterhci.io/v1.0/install/usb-install/#when-booting-from-a-usb-installation-flash-drive-a-grub-_-text-is-displayed-but-nothing-happens
The key is to select the partition, not the disk.

If there is still no luck, can you boot the USB again, switch to the second TTY (CTRL + ALT + F2) and log in with rancher/rancher.  Output of these two commands might help, thanks!
- `sudo blkid`
- `sudo lsblk`

**Comment by Shaharyar-Shaukat** [comment]
@bk201 In the boot menu, there is no option for UEFI boot partition on the USB device, there is only option for  USB device itself.

**Comment by mannp** [comment]
I have a similar issue when trying to install harvester from a USB stick, created from the iso.

Install appears to work, but the resulting install drive does not appear to be bootable.

Grub does not appear when the install drive is selected to boot.

**Comment by kosiek** [comment]
Hi,

I've been able to find a workaround for the issue on my hardware. In my case, the Harvester was installing just fine, but the drive was not detected as UEFI-bootable. I can't guarantee that it will work on any hardware, but I guess it's worth a try. What I've done to troubleshoot and fix was:

1. Get a USB stick with Live linux. I've used openSUSE 15.3 XFCE Live (`openSUSE-Leap-15.3-XFCE-Live-x86_64-Build9.403-Media.iso`).
2. Boot that OS, **do it on the machine that you intend to run the Harvester on**, start the root shell session in a Terminal.
3. Run `efibootmgr`. It will PROBABLY show only entries for the Live OS itself and PXE-boot interface (if you enabled it).
4. If so, then you need to add the entry for the hard drive. Run disk management utility of your choice to show the partition list on your system. I've used `parted -l`. The EFI partition will be something like `/dev/sdX1` (/dev/sdX partition 1) and after mounting, the path to the EFI file will probably be `/your/mount/path/EFI/BOOT/BOOTX64.EFI`. Please make sure what it is precisely, because it will be used later.
5. Fix the EFI by adding the entry yourself: `efibootmgr --create --disk=/dev/sdX --part=1 --label="UEFI: Harvester" --loader='EFI\BOOT\BOOTX64.EFI'`.
6. Run `efibootmgr` again and validate the `BootOrder` variable to make sure that the Harvester entry is on top of the boot order. If not, correct the order.
7. Reboot the system, remember to remove the Live Linux OS media.

The expected result should be that the Harvester boots up and the GRUB bootloader starts successfully.

In case of any problems, I've found [This Linuxconfig guide](https://linuxconfig.org/how-to-manage-efi-boot-manager-entries-on-linux) very helpful.

Good luck!
