### ISSUE TITLE
The image should be able to be retrieved after correcting the image URL

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#213]
**Steps to reproduce:**
1. Add an image using an invalid URL
2. Edit the image and correct the URL using a valid URL and save it

**Result:**
The image is not retrieved though the image URL has been updated
![image](https://user-images.githubusercontent.com/57614736/97857410-a9424a00-1d38-11eb-8fbd-4552968efd16.png)

**Comment by WuJun2016** [comment]
@guangbochen   This problem may need to be dealt with in the backend。 When the URL is changed, the backend does not reset the message.

And I think it's better not to change the image. If the result of a request fails due to a service problem, then if the image is changed at this time, will there be any problem with the relationship between the image and the VM

**Comment by guangbochen** [comment]
if the updated URL is valid and once the download is complete the previous error message should be gone. @gitlawr will help to check it, thanks.

**Comment by guangbochen** [comment]
addressed in https://github.com/rancher/harvester/pull/246
