### ISSUE TITLE
[BUG] Block device volume failed to unmount when it is detached unexpectedly

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2137]
**Describe the bug**
backport issue https://github.com/longhorn/longhorn/issues/3778

**To Reproduce**
- https://github.com/longhorn/longhorn/issues/3778#issuecomment-1077089425

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
The goal is to add the workaround: https://github.com/longhorn/longhorn/issues/3778#issuecomment-1085219265
- Probably add in the Harvester helm chart. We need to verify if the ds can be deleted in the future if the ds is removed in the helm chart templates. If this doesn't work, we need to manually remove the ds during a future upgrade.
- Use an alternative image than `alpine:3.12` if possible.
- Check if the ds hurt something, looks fine to me since it only checks stale backing files.

**Comment by lanfon72** [comment]
Verified this bug has been fixed. (with workaround)


Test Information
----
* Environment: **qemu/KVM single node and 3 nodes**
* Harvester Version: **master-0eab7caa-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to console, execute `kubectl get daemonsets -n longhorn-system`
3. Daemonset `longhorn-loop-device-cleaner` should exists. (the workaround)
4. Login to dashboard
5. Create an image for VM creation
6. Create VM `v1` then login and execute `echo hello > world`
7. Login to console, execute `kubectl get pod -o=custom-columns=NODE:.spec.nodeName,NAME:.metadata.name -n longhorn-system | grep instance-manager-e`
8. Delete the pod which VM hosted by executing `kubectl delete pod -n longhorn-system instance-manager-e-<THE_RANDOM_CHARS>`
9. Wait until the VM state changed, start the VM
10. Login to VM, execute `cat world` should displays **hello**
