### ISSUE TITLE
[FEATURE] Storage Tiering

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2147]
**Is your feature request related to a problem? Please describe.**

- Requirement to use mixed storage hardware of different performance levels to optimize cost
- Using heterogeneous storage devices on Harvester nodes leads to unpredictable performance today because there is no control over what device tier will back a specific volume/replica.

**Describe the solution you'd like**
Harvester should allow admins to define storage tiers based on at least:
- Node label selectors
- Disk label selectors

**Comment by janeczku** [comment]
Requirement: It should be possible to define the number of replicas per storage tiers.

https://github.com/harvester/harvester/issues/2511

**Comment by abonillabeeche** [comment]
Can we have an update on this feature request? It's in Roadmap but don't yet see PRs or a discussion around it.

**Comment by futuretea** [comment]
@abonillabeeche 
design PR: https://github.com/harvester/harvester/pull/2335
backend PR: https://github.com/harvester/harvester/pull/2358
UI PR: https://github.com/harvester/dashboard/pull/415

**Comment by irishgordo** [comment]
@futuretea 
I've been working to try to validate this.

Following some of the [testing steps](https://github.com/harvester/harvester/pull/2358#issue-1263010285) that have been highlighted, I've encountered this error when trying to upgrade from v1.0.3 - v1.1.0-rc1.  Following [upgrading harvester via more of an air-gapped method](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade)

```
suse-workstation-team-harvester➜  tests : vm-import-controller ✘ :✭ ᐅ  kubectl --kubeconfig ~/.kube/vm_harvester_v103_on_supermicro.yaml get bundle -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; configmap.v1 longhorn-system/longhorn-storageclass missing
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   0/1                       ErrApplied(1) [Cluster fleet-local/local: another operation (install/upgrade/rollback) is in progress]
fleet-local   mcc-rancher-monitoring                        1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1                       
suse-workstation-team-harvester➜  tests : vm-import-controller ✘ :✭ ᐅ  

```

As I started with a v1.0.3 single-node cluster, created a vm w/volume & some images - to check backwards compatibility like highlighted.
Then went to upgrade, creating a `version.yaml` like:
```
buildserver@buildserver:~/temp-server$ cat version.yaml 
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: v1.1.0-rc1
  namespace: harvester-system
spec:
  isoChecksum: 'd5729f01ac8b202750ac35a4f571f07b7410a8e76a15fd75fcbf78e468392c2884f8aa6fb9e81f385a6f2d0b38d6bbebec29f7055b6d0d247cb9cc4d3909e8d2'
  isoURL: http://192.168.1.239:8383/harvester-v1.1.0-rc1-amd64.iso
  releaseDate: '20220922'
```
That was hosted on a simple-http server with python: `python3 -m http.server 8383 &` within the directory that houses the `version.yaml` & `harvester-v1.1.0-rc1-amd64.iso`

The `Download Upgrade Image` seems stuck at 77%.
All VMs are shutoff on the single-node as well.
The single-vm node (running harvester v1.0.3):
- 24355 MiB memory
- 16 CPU

Support Bundle:
[supportbundle_f86ed3c8-4596-494a-a31a-ea88476d47d3_2022-09-26T18-36-47Z.zip](https://github.com/harvester/harvester/files/9648806/supportbundle_f86ed3c8-4596-494a-a31a-ea88476d47d3_2022-09-26T18-36-47Z.zip)

Additional Screenshots:
![simple-http-server](https://user-images.githubusercontent.com/5370752/192354598-4a5df06e-5e93-4a8f-999f-f375179e49a5.png)
![upgrade-caused-internal-error-for-harvester-system](https://user-images.githubusercontent.com/5370752/192354606-f51138bd-c484-4b90-85f8-216f21efabce.png)
![upgrading](https://user-images.githubusercontent.com/5370752/192354610-f9b19b97-38cf-44fb-80ab-e3574cf94032.png)
![upgrade-still-present](https://user-images.githubusercontent.com/5370752/192354612-e87c224f-cf59-4e9e-9763-8c06b735ce8e.png)
![upgrade-available](https://user-images.githubusercontent.com/5370752/192354614-c893ba73-c908-4e39-bb30-1ad841dd36be.png)
![upgrade-button-found](https://user-images.githubusercontent.com/5370752/192354616-f877efb9-6808-4ea2-bd7b-0ab872eb2b49.png)
![upgrade-manual](https://user-images.githubusercontent.com/5370752/192354617-187c2bd7-8f2d-4e26-b04f-aaa4aef68e75.png)
![uploaded-some-images-to-v103](https://user-images.githubusercontent.com/5370752/192354618-f65e6979-d343-480a-bb1d-47517156a334.png)


## I did manage to get it to work via:
(removing the `version.yaml` that was applied to the node directly in the prior attempt)
Then trying the more complex approach.  To patch upgrade from v1.0.3 to 
The setup was:
- private docker registry created via:
```
# build auth part
mkdir -p ~/your_directory/temp_docker_registry/auth
# build auth for private registry within ~/your_directory/temp_docker_registry
docker run \
  --entrypoint htpasswd \
  httpd:2 -Bbn temp-user temppass > auth/htpasswd
# run docker registry
docker run -itd \
  -p 5000:5000 \
  --name registry \
  -v "$(pwd)"/auth:/auth \
  -e "REGISTRY_AUTH=htpasswd" \
  -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
  registry
```
- [manually modify scripts/package since there seems to be no auth functionality](https://github.com/harvester/harvester/blob/master/scripts/package#L29-L37) to add:
```
# before this line of: docker --config=${DOCKER_CONFIG} push "${IMAGE_PUSH}"
docker login your_ip_address_or_domain_ip:5000 -u temp-user temppass
```
- then running:
   - `export REPO=localhost:5000`
   - `export PUSH=true`
   - `make`
- then on the single-harvester node, shelling in and as root:
   - then doing docker login, to other private registry
   - then pulling `docker pull your_private_registry:5000/harvester:master-head --insecure-registry=true`
   - then pulling `docker pull your_private_registry:5000/harvester-webhook:master-head --insecure-registry=true`
- then upgrading harvester node crds
- then upgrading harvester node components
- restarting harvester-webhook


#### pending validations:
- >Old version images and storageClasses and backingimages should not be changed.
- >Edit any old version image, change Description from UI

**Question: Should the `Annotation` # increase?**
When editing the image, adding a description or adding `labels` to the image that was uploaded via the UI, I noticed the `Annotations` increased from 1 to 2.
Prior to editing, the only annotation was: `harvesterhci.io/image-name`
After editing, the annotations were: `harvesterhci.io/image-name` and `harvesterhci.io/storageClassName`
Screenshots:

![storage-shows-empty-tho-harvester-longhorn-present](https://user-images.githubusercontent.com/5370752/192380466-e91e7955-4eba-4b25-a941-30a64880fdb6.png)
![storage-class-doesnt-change-when-description-added-to-v103-image](https://user-images.githubusercontent.com/5370752/192380473-e87637df-a431-47da-8c4d-eb4986e59409.png)
![adding-image-description-making-sure-storage-class-not-change](https://user-images.githubusercontent.com/5370752/192380478-a21c7ffd-2e51-41c1-9dd8-8ac7ea5e434b.png)
![storage-empty-for-v103-based-image-ubuntu-2004-after-v110rc1-upgrade](https://user-images.githubusercontent.com/5370752/192380625-91991edb-1a3f-49f3-ba7c-297101d49ba4.png)


**Question: For `Edit any old version image, add some parameters to spec.storageClassParameters` (from test plan) , when there isn't a property of `storageClassParameters` on the virtualmachineimages.harvesterhci.io ,do we need to create one to edit the parameters?**
Screenshot:
![Screenshot from 2022-09-26 13-47-19](https://user-images.githubusercontent.com/5370752/192380362-f4dd0aa9-8870-45c8-b6d5-5b802a033ed6.png)

**Question: Do we want the `Storage` section underneath `Basics` in the UI to remain blank for an Image that was uploaded on v1.0.3?**
Screenshot:
![storage-empty-for-v103-based-image-ubuntu-2004-after-v110rc1-upgrade](https://user-images.githubusercontent.com/5370752/192380658-fa6cec01-6c42-40ae-a0f2-5219d06d265e.png)

**Question: Following the Upgrade from v1.0.3 to v1.1.0-rc1 of the CRDs & Harvester Components, should the `Upgrade Status` remain in `on-going` as Upgrading Node seems hung on 0%?**
Screenshot:
![stuck-on-upgrading-node-possibly](https://user-images.githubusercontent.com/5370752/192380938-43636eb6-ce82-4d63-83e8-9445f67a0c39.png)


**Question: For 3 - 7 on the Test Plan, is there a way to do those within the UI?**
- [test plan](https://github.com/harvester/harvester/pull/2358)


Also, I was curious about - https://github.com/harvester/harvester/issues/2826 - if that is a bug dealing with using a StorageClass that has 0 replicas, it working, when you specify 3?

**Validation - Ongoing, pending more information**

**Comment by futuretea** [comment]
> Question: Should the Annotation # increase?

Yes

> Question: For Edit any old version image, add some parameters to spec.storageClassParameters (from test plan) , when there isn't a property of storageClassParameters on the virtualmachineimages.harvesterhci.io ,do we need to create one to edit the parameters?

I will add a new UI test plan to instead of this one

> Question: Do we want the Storage section underneath Basics in the UI to remain blank for an Image that was uploaded on v1.0.3?

Yes, old images didn't have the storageClass annotation and storageClassParameters 

> Question: For 3 - 7 on the Test Plan, is there a way to do those within the UI?

These tests were written for backend PR review
I will add UI test plans soon

> Question: Following the Upgrade from v1.0.3 to v1.1.0-rc1 of the CRDs & Harvester Components, should the Upgrade Status remain in on-going as Upgrading Node seems hung on 0%?

CC @bk201

**Comment by bk201** [comment]
@irishgordo We will support the upgrade in v1.1.0-rc2.

**Comment by futuretea** [comment]
@irishgordo 

**Test Plan for compatibility**
---
1. Old version images and storageClasses and backingimages should not be changed/deleted.

1. Edit any old version image via `Edit Config`, change Description from UI
The storageClass and backingimage of the image should not be changed.
get storageClass by `kubectl get sc`
get backingimage by `kubectl -n longhorn-system get backingimage`

1. Edit any old version image via `Edit Yaml`, add `spec.storageClassParameters` and add some parameters to it.
this request should be refused by harvester-webhook

**Test Plan for new feature**
--
1. Add tags to Hosts and Disks in `Hosts` >`Storage` pages
2. Create a storageClass `sc-a`, specify nodeSelector,diskSelector, number of replicas
3. Create a storageClass `sc-b`, specify nodeSelector,diskSelector, number of replicas
1. Create a new image `img-a`, specify storageClassName to `sc-a`
4. Create a new vm `vm1` use the image `img-a`
5. Check the replicas number and location of rootdisk volume in longhorn UI
6. Create a new volume `volume-a` by choose source=image `img-a`
8. Add the volume `volume-a` to vm `vm1`
9. Check the replicas number and location of volume `volume-a` in longhorn UI
10. Export the image volume `volume-a` to a new image `img-b` and specify `storageClassName` `sc-b`
11. Create a new volume `volume-b` by choose source=image `img-b`
12. Add the volume `volume-b` to vm `vm1`
13. Check the replicas number and location of volume `volume-b` in longhorn UI
14. Create a volume snapshot `snapshot-a` from `volume-a`
15. Restore the volume snapshot `snapshot-a` to a new volume `volume-restore-b` and specify `storageClassName` `sc-b`
16. Check the replicas number and location of volume `volume-restore-b` in longhorn UI

**Comment by irishgordo** [comment]
@futuretea thank you for outlining these elements for me :smile: 

### compatibility validations:

As I worked through validating this - all things related to `Test Plan for copmatiblity` look good.
I was able to validate things like trying to add the `spec.storageClassParameters` fails:
Request:
```
curl --location --request PUT 'https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer token-clw7g:j8x26swfcqvxrkqcd9889j7lzgwtctnxcqcblsjgtm8b5mgjt2lbpz' \
--data-raw '{
    "id": "default/image-zdt2d",
    "type": "harvesterhci.io.virtualmachineimage",
    "links": {
        "download": "https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d/download",
        "remove": "https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d",
        "self": "https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d",
        "update": "https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d",
        "view": "https://192.168.1.59/apis/harvesterhci.io/v1beta1/namespaces/default/virtualmachineimages/image-zdt2d"
    },
    "actions": {
        "upload": "https://192.168.1.59/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-zdt2d?action=upload"
    },
    "apiVersion": "harvesterhci.io/v1beta1",
    "kind": "VirtualMachineImage",
    "metadata": {
        "annotations": {
            "field.cattle.io/description": "testing",
            "harvesterhci.io/image-name": "openSUSE-Leap-15.3.x86_64-NoCloud.qcow2",
            "harvesterhci.io/storageClassName": "harvester-longhorn"
        },
        "creationTimestamp": "2022-09-26T17:38:04Z",
        "fields": [
            "image-zdt2d",
            "opensuse-leap-15.3.x86_64-nocloud.qcow2",
            570884096,
            "27h"
        ],
        "finalizers": [
            "wrangler.cattle.io/vm-image-controller"
        ],
        "generateName": "image-",
        "generation": 6,
        "labels": {
            "harvesterhci.io/imageDisplayName": "opensuse-leap-15.3.x86_64-nocloud.qcow2",
            "testlabel": "testing"
        },
        "managedFields": [
            {
                "apiVersion": "harvesterhci.io/v1beta1",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:metadata": {
                        "f:annotations": {
                            ".": {},
                            "f:field.cattle.io/description": {},
                            "f:harvesterhci.io/image-name": {},
                            "f:harvesterhci.io/storageClassName": {}
                        },
                        "f:finalizers": {
                            ".": {},
                            "v:\"wrangler.cattle.io/vm-image-controller\"": {}
                        },
                        "f:generateName": {},
                        "f:labels": {
                            ".": {},
                            "f:harvesterhci.io/imageDisplayName": {},
                            "f:testlabel": {}
                        }
                    },
                    "f:spec": {
                        ".": {},
                        "f:checksum": {},
                        "f:displayName": {},
                        "f:pvcName": {},
                        "f:pvcNamespace": {},
                        "f:sourceType": {},
                        "f:url": {}
                    },
                    "f:status": {
                        ".": {},
                        "f:conditions": {},
                        "f:progress": {},
                        "f:size": {},
                        "f:storageClassName": {}
                    }
                },
                "manager": "harvester",
                "operation": "Update",
                "time": "2022-09-27T21:31:41Z"
            }
        ],
        "name": "image-zdt2d",
        "namespace": "default",
        "relationships": null,
        "resourceVersion": "490085",
        "state": {
            "error": false,
            "message": "Resource is current",
            "name": "active",
            "transitioning": false
        },
        "uid": "5b90fef3-944c-4ee9-8696-38d569addb86"
    },
    "spec": {
        "checksum": "",
        "displayName": "opensuse-leap-15.3.x86_64-nocloud.qcow2",
        "pvcName": "",
        "pvcNamespace": "",
        "sourceType": "upload",
        "url": "",
        "storageClassParameters": {}
    },
    "status": {
        "conditions": [
            {
                "error": false,
                "lastUpdateTime": "2022-09-26T17:38:25Z",
                "reason": "Imported",
                "status": "True",
                "transitioning": false,
                "type": "Imported"
            },
            {
                "error": false,
                "lastUpdateTime": "2022-09-26T17:38:04Z",
                "reason": "Initialized",
                "status": "True",
                "transitioning": false,
                "type": "Initialized"
            }
        ],
        "progress": 100,
        "size": 570884096,
        "storageClassName": "longhorn-image-zdt2d"
    }
}'
```
Response `422 Unprocessable Entity`:
```
{
    "type": "error",
    "links": {},
    "code": "Invalid",
    "message": "admission webhook \"validator.harvesterhci.io\" denied the request: storageClassParameters of the VM Image cannot be modified",
    "status": 422,
    "type": "error"
}
```
The backwards compatibility looks good with all elements.

### new feature testing:

1. PASS
2. PASS
3. PASS
4. PASS
5. FAIL


By the time I reached step 5 - I noticed the same issue as:
https://github.com/harvester/harvester/issues/2832

Had originally created tags like:
![Screenshot from 2022-09-27 12-53-22](https://user-images.githubusercontent.com/5370752/192643240-850ae6cf-53a1-40b4-a208-d6e4ffb113d8.png)

But when incident occurred with FAIL on 5:
![validation-failed](https://user-images.githubusercontent.com/5370752/192643412-f5e48539-a7b4-461d-9e44-cb0e41d5f826.png)

The `pvc` errors are:
```
│ Name:          img-a-vm-disk-0-tbuwy                                                                                                         │
│ Namespace:     default                                                                                                                       │
│ StorageClass:  longhorn-image-4t97b                                                                                                          │
│ Status:        Pending                                                                                                                       │
│ Volume:                                                                                                                                      │
│ Labels:        <none>                                                                                                                        │
│ Annotations:   harvesterhci.io/imageId: default/image-4t97b                                                                                  │
│                harvesterhci.io/owned-by: [{"schema":"kubevirt.io.virtualmachine","refs":["default/img-a-vm"]}]                               │
│                volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io                                                             │
│                volume.kubernetes.io/storage-provisioner: driver.longhorn.io                                                                  │
│ Finalizers:    [kubernetes.io/pvc-protection]                                                                                                │
│ Capacity:                                                                                                                                    │
│ Access Modes:                                                                                                                                │
│ VolumeMode:    Block                                                                                                                         │
│ Used By:       virt-launcher-img-a-vm-mvg7d                                                                                                  │
│ Events:                                                                                                                                      │
│   Type     Reason                Age                 From                                                                                    │
│   Message                                                                                                                                    │
│   ----     ------                ----                ----                                                                                    │
│   -------                                                                                                                                    │
│   Warning  ProvisioningFailed    2m59s (x3 over 3m)  driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9 │
│   failed to provision volume with StorageClass "longhorn-image-4t97b": rpc error: code = Internal desc = Bad response statusCode [500]. Stat │
│ us [500 Internal Server Error]. Body: [message=specified disk tag sda does not exist, code=Server Error, detail=] from [http://longhorn-back │
│ end:9500/v1/volumes]                                                                                                                         │
│   Normal   Provisioning          67s (x9 over 3m)    driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9 │
│   External provisioner is provisioning volume for claim "default/img-a-vm-disk-0-tbuwy"                                                      │
│   Warning  ProvisioningFailed    67s (x6 over 3m)    driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9 │
│   failed to provision volume with StorageClass "longhorn-image-4t97b": rpc error: code = Internal desc = Bad response statusCode [500]. Stat │
│ us [500 Internal Server Error]. Body: [code=Server Error, detail=, message=specified disk tag sda does not exist] from [http://longhorn-back │
│ end:9500/v1/volumes]                                                                                                                         │
│   Normal   ExternalProvisioning  2s (x15 over 3m)    persistentvolume-controller                                                             │
│   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator   
```
Since the disk tags have disappeared.
[supportbundle_f86ed3c8-4596-494a-a31a-ea88476d47d3_2022-09-27T21-46-13Z.zip](https://github.com/harvester/harvester/files/9659868/supportbundle_f86ed3c8-4596-494a-a31a-ea88476d47d3_2022-09-27T21-46-13Z.zip)

Implementing the work-around for 5, by adding back the disk tags and retrying.
5-With-Work-Around-Readding-Disk-Tags: PASS
![Screenshot from 2022-09-27 15-03-56](https://user-images.githubusercontent.com/5370752/192645864-15bc327f-3a22-4f01-b885-786df9b2a01e.png)

6. PASS
7. PASS
8. PASS
9. PASS
10. PASS
11. PASS
12. PASS
13. PASS
14. PASS
15. FAIL
For 15, I can't seem to find a way to specify a storageClass from the GUI:
![Screenshot from 2022-09-27 15-42-51](https://user-images.githubusercontent.com/5370752/192650906-416f1177-b5ae-47de-9a32-4b05738b6104.png)
Additionally, with `volume-restore-b` I see this from the logs:
```
│ Status:        Pending                                                                                                                                                               │
│ Volume:                                                                                                                                                                              │
│ Labels:        <none>                                                                                                                                                                │
│ Annotations:   harvesterhci.io/imageId: default/image-4t97b                                                                                                                          │
│                volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io                                                                                                     │
│                volume.kubernetes.io/storage-provisioner: driver.longhorn.io                                                                                                          │
│ Finalizers:    [kubernetes.io/pvc-protection]                                                                                                                                        │
│ Capacity:                                                                                                                                                                            │
│ Access Modes:                                                                                                                                                                        │
│ VolumeMode:    Block                                                                                                                                                                 │
│ DataSource:                                                                                                                                                                          │
│   APIGroup:  snapshot.storage.k8s.io                                                                                                                                                 │
│   Kind:      VolumeSnapshot                                                                                                                                                          │
│   Name:      snapshot-a                                                                                                                                                              │
│ Used By:     <none>                                                                                                                                                                  │
│ Events:                                                                                                                                                                              │
│   Type     Reason                Age                   From                                                                                     Message                              │
│   ----     ------                ----                  ----                                                                                     -------                              │
│   Warning  ProvisioningFailed    17m (x4 over 20m)     driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9  failed to provision volume with Stor │
│ ageClass "longhorn-image-4t97b": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create volume: unable │
│  to create volume pvc-beffd803-f25d-4188-a941-4103fff44cad: failed to verify data source: cannot get client for volume pvc-c849f787-075b-4ee9-978a-94b549f699b9: engine is not runni │
│ ng, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]                                                                                                       │
│   Normal   ExternalProvisioning  4m49s (x62 over 20m)  persistentvolume-controller                                                              waiting for a volume to be created,  │
│ either by external provisioner "driver.longhorn.io" or manually created by system administrator                                                                                      │
│   Warning  ProvisioningFailed    3m41s (x7 over 19m)   driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9  failed to provision volume with Stor │
│ ageClass "longhorn-image-4t97b": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=una │
│ ble to create volume: unable to create volume pvc-beffd803-f25d-4188-a941-4103fff44cad: failed to verify data source: cannot get client for volume pvc-c849f787-075b-4ee9-978a-94b54 │
│ 9f699b9: engine is not running] from [http://longhorn-backend:9500/v1/volumes]                                                                                                       │
│   Normal   Provisioning          3m25s (x13 over 20m)  driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9  External provisioner is provisioning │
│  volume for claim "default/volume-restore-b"                                                                                                                                         │
│   Warning  ProvisioningFailed    3m25s (x2 over 20m)   driver.longhorn.io_csi-provisioner-b5595b5f9-jtv96_abcc1c5c-3ddd-4fee-b7cf-43703bd32de9  failed to provision volume with Stor │
│ ageClass "longhorn-image-4t97b": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=unable to create volum │
│ e: unable to create volume pvc-beffd803-f25d-4188-a941-4103fff44cad: failed to verify data source: cannot get client for volume pvc-c849f787-075b-4ee9-978a-94b549f699b9: engine is  │
│ not running, code=Server Error] from [http://longhorn-backend:9500/v1/volumes]       
```
16. FAIL

**Validation - Failed (5, 15, 16)**

**Comment by futuretea** [comment]
@irishgordo Sorry, For 15 and 16 , I forgot that these volumes are image volume, so they cannot be restored to another storageClass. That's expected. new test steps:
15. Create a new volume `volume-c` by choose `Source`=`New` and specify `storageClassName` `sc-a`
16. Add the volume `volume-c` to vm `vm1`
17. Check the replicas number and location of volume `volume-c` in longhorn UI
18. Create a volume snapshot `snapshot-c` from `volume-c`
19. Restore the volume snapshot `snapshot-c` to a new volume `volume-restore-c` and specify `storageClassName` `sc-b`
20. Check the replicas number and location of volume `volume-restore-c` in longhorn UI

**Comment by irishgordo** [comment]
@futuretea thanks for looking into that for me :smile: 

**Question: Should we be allowed to delete a StorageClass when there are Volumes & Images tied to that StorageClass - and also there are VMs running?**
![Screenshot from 2022-09-28 11-06-11](https://user-images.githubusercontent.com/5370752/192856605-81cdc4a7-d3ed-4a3c-bfcb-41e4aea2b8d4.png)

I was able to delete the StorageClasses, but I'm not sure if that's correct?

**Question: When multiple disks have the same tag like 'sdb-sdc' is it correct to function to store all the data on the biggest disk first then start to store on the second?  Is there a way to distribute the data between the two disks?**
![Screenshot from 2022-09-28 11-04-38](https://user-images.githubusercontent.com/5370752/192857203-eb42a294-1f01-4e8e-96c0-f0fc68b29ff6.png)
![Screenshot from 2022-09-28 11-03-02](https://user-images.githubusercontent.com/5370752/192857206-7eee9e4b-9b00-4fde-b33b-b6d46138393f.png)

15. PASS
16. PASS
17. PASS
18. PASS
19. PASS
20. PASS

**Validation - Passed**
Pending those questions I have I believe things look good :smile:

**Comment by futuretea** [comment]
> Question: Should we be allowed to delete a StorageClass when there are Volumes & Images tied to that StorageClass - and also there are VMs running?

Delete the used storageClass will not break existing vms and volumes


> Question: When multiple disks have the same tag like 'sdb-sdc' is it correct to function to store all the data on the biggest disk first then start to store on the second? Is there a way to distribute the data between the two disks?

I will check the longhorn code and docs

**Comment by irishgordo** [comment]
@futuretea 
**Question: Should we be able to add disk tags during the creation of the disk that we're adding?**
![Screenshot from 2022-09-29 12-55-51](https://user-images.githubusercontent.com/5370752/193129514-6571941a-275e-43e4-b128-6053af766f95.png)

**Comment by irishgordo** [comment]
@futuretea 
When trying to add `disk tags` in a multi-node cluster I'm noticing errors like these pop up:
>failed to provision device b76f14bc4be7d63f51077c69dea2cda8 to node harvester-node-1: Operation cannot be fulfilled on [nodes.longhorn.io](http://nodes.longhorn.io/) "harvester-node-1": the object has been modified; please apply your changes to the latest version and try again
[supportbundle_692d2476-344f-4d29-a361-320d74128d13_2022-09-29T20-06-36Z.zip](https://github.com/harvester/harvester/files/9678772/supportbundle_692d2476-344f-4d29-a361-320d74128d13_2022-09-29T20-06-36Z.zip)
![Screenshot from 2022-09-29 13-05-34](https://user-images.githubusercontent.com/5370752/193131933-7a02f013-6d3f-495b-9376-09ddbe0537b1.png)

To reproduce:
- start 3 node cluster, using `main` branch of `ipxe-examples`, edit `settings.yaml` to change ramdisk,vmlinuz, and others to point to v1.1.0-rc1 like:
```YAML
harvester_iso_url: https://releases.rancher.com/harvester/v1.1.0-rc1/harvester-v1.1.0-rc1-amd64.iso
harvester_kernel_url: https://releases.rancher.com/harvester/v1.1.0-rc1/harvester-v1.1.0-rc1-vmlinuz-amd64
harvester_ramdisk_url: https://releases.rancher.com/harvester/v1.1.0-rc1/harvester-v1.1.0-rc1-initrd-amd64
harvester_rootfs_url: https://releases.rancher.com/harvester/v1.1.0-rc1/harvester-v1.1.0-rc1-rootfs-amd64.squashfs
```
- allow all nodes to provision
- shutdown all nodes except leave ipxe-server node running
- add `sata` based disks to nodes 1-2 each, update boot order, provide serial for each
- powerback up all nodes
- wait for nodes to come online, shell into each node then `sudo -i` then `gdisk /dev/sdX` and `w` for writing (to write blank for adding the disk to the nodes)
- Hosts -> Add Disk , for each, add a `Host Tag` and a `disk tag` for the "original" disk
- Hosts -> edit config for each, add disk tags to the secondary disk(s) on each, that error will show depending

**Validation - Fail, issues**

**Comment by irishgordo** [comment]
@futuretea 
**Question: Should we "clear" out the "Disk Tags" section when you click away from the form element?**

You click off and click back into the form element and the disk tag still persists vs clearing when you click off.

https://user-images.githubusercontent.com/5370752/193147946-ce9f54c4-3be9-45f9-9d12-726c9a6cde8f.mp4

**Comment by irishgordo** [comment]
@futuretea 
I'm noticing an issue with VMs creating.
Submitted this: https://github.com/harvester/harvester/issues/2854

**Comment by irishgordo** [comment]
Closed out 2854 - as that was a configuration issue on my end, apologies there :sweat_smile:

**Comment by irishgordo** [comment]
@futuretea 
**Question: Should we be allowed to have "multiple" StorageClasses set as Default?**
![Screenshot from 2022-09-30 11-24-49](https://user-images.githubusercontent.com/5370752/193333657-079a8f19-92ae-412d-9541-e472ca2e3358.png)

#### To Reproduce:
- navigate to Storage Classes
- click on Storage Class that isn't default, then select "Set as Default"

You'll find if you have N number of Storage Classes - all of the Storage Classes from the index/list/array presented in the UI can be set as **Default**.

I wanted to ask, because I was thinking for N number of Storage Classes, you could only ever have 1 Default, not multiple.
![Screenshot from 2022-09-30 11-29-46](https://user-images.githubusercontent.com/5370752/193334152-18c7f750-8b14-4d62-bd72-2d364adf2785.png)


**Validation - Question**

**Comment by irishgordo** [comment]
> @futuretea **Question: Should we be allowed to have "multiple" StorageClasses set as Default?** ![Screenshot from 2022-09-30 11-24-49](https://user-images.githubusercontent.com/5370752/193333657-079a8f19-92ae-412d-9541-e472ca2e3358.png)
> #### To Reproduce:
> 
>     * navigate to Storage Classes
> 
>     * click on Storage Class that isn't default, then select "Set as Default"
> 
> 
> You'll find if you have N number of Storage Classes - all of the Storage Classes from the index/list/array presented in the UI can be set as **Default**.
> 
> I wanted to ask, because I was thinking for N number of Storage Classes, you could only ever have 1 Default, not multiple. ![Screenshot from 2022-09-30 11-29-46](https://user-images.githubusercontent.com/5370752/193334152-18c7f750-8b14-4d62-bd72-2d364adf2785.png)
> 
> **Validation - Question**

Created this issue to track that: https://github.com/harvester/harvester/issues/2863

**Comment by irishgordo** [comment]
@futuretea  

I've validated that on v1.1.0-rc1 today:

1. PASS
2. PASS
3. PASS
4. PASS
5. PASS
6. PASS
7. PASS
8. PASS
9. PASS
10. PASS
11. PASS
12. PASS
13. PASS
14. PASS
15. PASS
16. PASS
17. PASS
18. PASS
19. PASS
20. PASS

Since the validations pass, I can close this out - since we have #2863 covering the issue still present - should I go ahead and do that?

**Comment by bk201** [comment]
@irishgordo Yes, let's track the multiple default SC issues in #2863. Thanks!

**Comment by irishgordo** [comment]
Sounds good @bk201 !
Thanks @futuretea and everyone for your work on this!
This looks great!
And I'll go ahead and close this out :smile: !

**Comment by mmisworking** [comment]
Good to see that a lot of progress has been made. We looking forward to the new release so we are able to put Harvester in production. Our related issue is https://github.com/harvester/harvester/issues/2759 and could also be closed if the release is there.
Thanks a lot for all your efforts
