### ISSUE TITLE
[Question] Are there any plans to develop a client support package?

### ISSUE THREAD

**Issue by devadapter** [harvester/harvester#2159]
I found the go-harvester project, but he is not available in v1.0. Is there any plan to develop a harvester client?

**Comment by tlehman** [comment]
Last year there was a [hackweek project for a harvester cli](https://hackweek.opensuse.org/21/projects/a-cli-for-harvester), that project looks like a good starting point to spin out a harvester go client. I checked, and that cli tool just imports Harvester 1.0.0 directly, bypassing the go-harvester client.

What are you trying to accomplish? I'm curious because I'm trying to gauge user/customer interest in the client. If there's a good case for maintaining it, there is another hack week coming up soon and that's a great opportunity to prototype a modern (post 1.1.0) Harvester Go client.

**Comment by devadapter** [comment]
We have a scenario where we want to manage the lifecycle of a virtual machine through a program call interface, which can make the manipulation of virtual resources as easy and efficient as container orchestration.

**Comment by ibrokethecloud** [comment]
we do have the go clients generated here: https://github.com/harvester/harvester/tree/master/pkg/generated/clientset/versioned/typed/harvesterhci.io/v1beta1

i hope this helps
