### ISSUE TITLE
[BUG]  Requesting "additional-ca" and then requesting "network.harvesterhci.io.clusternetworks" will return a 503 error

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2205]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/f79521d0-b9ea-423c-b01c-61efe161420e)

**To Reproduce**
1. Go to `Setting` page
2. edit `backup-target `
3. Click on the "here" link at the bottom  （The page will jump to a new tab page）
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/d859ce82-2a7a-4944-9e52-1e71e01dc576) 
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/a37132ca-c328-4565-8007-9bd2bf79e6fc)
4. You can reopen a new page and enter `https://URL/v1/harvester/network.harvesterhci.io.clusternetworks`  （At this point the api is able to request successfully）
5. go to the previously opened `additional-ca` edit page and enter any value, click save button  (Immediately go to refresh the `https://URL/v1/harvester/network.harvesterhci.io.clusternetworks` page, the page does not respond for a long time)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by weihanglo** [comment]
Just did a simple research. If we provide a valid CA certificate, it succeeds without any error. Otherwise it behaves as what WuJun2016 described. 

I use the following commands to create a valid certificate.

```bash
openssl genrsa 2048 > ca-key.pem
openssl req -new -x509 -nodes -days 365000 -key ca-key.pem -out ca-cert.pem
```

The current backend code (harvester-webhook) only adds addition-ca to root CA for its HTTPS transport. Nothing seems weird to me so far. However, I observed some fun facts

1. Changing `additional-ca` causes the `harvester` pod terminated and restarted.
2. The timing of harvester pod starting seems like at the websocket subscription.
3. An invalid value of `addtional-ca` causes the pod restarting immediately, so the user experiences hanging and 503 error right after applying the change.

I wonder we can avoid the downtime if we leverage [`tls.Config.GetCertificate`](https://pkg.go.dev/crypto/tls#Config.GetCertificate). Will do some experiments based on these findings.

**Comment by weihanglo** [comment]
After a deeper investigation, I found that the root cause is that harvester deployment is forced to restart when additional CA cert changes [^1]. The reason to restart is that podmutator in harvester-webhook would eject and mount a volume of the certain CA certificate onto `/etc/ssl/certs` for the sake of loading as a system CA certificate. [^2]

The CA cert injection code path is used for three workloads: harvester, rancher, and longhorn's `backing-image-data-source`. Only Harvester is under our controlled, so I am going to propose a possible solution, similar to how harvester-webhook patches its own root CA [^3].

1. When the setting `additional-ca` has changed, harvester runs [`syncAdditionalTrustedCAs`](https://github.com/harvester/harvester/blob/47ea94ee0682b47217c07d9fcbde5d2cd12d8e05/pkg/controller/master/setting/additional_ca.go#L12-L28) to update backup-target and restart itself. We can change this part to patch HTTP transport instead.
2. Remove the current implementation, which ejects a volume to the pod after a restart.


As a side note, if a harvester cluster has 3 or more nodes, I guess it wouldn't have a downtime as such. This downtime issue might only occur in a non-HA cluster. Will verify my assumption later on.

[^1]: https://github.com/harvester/harvester/blob/e2985453c65193b407d47d53c3c96a249e2cf474/pkg/controller/master/setting/additional_ca.go#L12-L28
[^2]: https://github.com/harvester/harvester/blob/e2985453c65193b407d47d53c3c96a249e2cf474/pkg/webhook/resources/pod/mutator.go#L178-L183
[^3]: https://github.com/harvester/harvester/blob/e2985453c65193b407d47d53c3c96a249e2cf474/pkg/webhook/resources/setting/validator.go#L294-L303

**Comment by weihanglo** [comment]
> As a side note, if a harvester cluster has 3 or more nodes, I guess it wouldn't have a downtime as such. This downtime issue might only occur in a non-HA cluster. Will verify my assumption later on.

Verified that in a 3-node cluster, the high availability can prevent request from failure with 503 error.

> The current backend code (harvester-webhook) only adds addition-ca to root CA for its HTTPS transport

Just FYI, Consul and Nomad also use similar trick, which reloads/updates the `tls.Config` dynamically as what harvester-webhook [^1] [^2]

[^1]: https://github.com/hashicorp/consul/pull/5419
[^2]: https://github.com/hashicorp/nomad/pull/3479

**Comment by guangbochen** [comment]
Close as this behavior is expected.
