### ISSUE TITLE
[BUG] EFI boot option is not working

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2210]
Harvester 1.0.1

**To Reproduce**

1. Create a VM and under "Advanced Options" ensure that "Booting in EFI mode" is *not* ticked.
2. Check the YAML configuration of the created VM

**Expectation**

VM is configured for BIOS / legacy booting

**Actual**

VM is configured to boot in EFI mode

**Comment by WuJun2016** [comment]
Fixed in `v1.0.2-rc1`
https://github.com/harvester/harvester/issues/2128

**Comment by bk201** [comment]
@WuJun2016 is this a duplicated one to #2128?

**Comment by WuJun2016** [comment]
@bk201  Should be a duplicate, I see the description of the use of the version is v1.0.1
@lanfon72  Can you help to test the problem again?  thanks.

**Comment by lanfon72** [comment]
Confirmed the bug is duplicated in #2128.
In `v1.0.1`, VM's option __Booting in EFI mode__ will only update yaml to enable **secure boot**; and by default, the boot option will always be __EFI mode__.

The bug has been fixed in #2128. (`v1.0.2` will introduce new option __Secure Boot__ when __Booting in EFI mode__ is enabled, and the default boot mode will be __BIOS mode__)
