### ISSUE TITLE
Adding NIC to network setting crashed hosts

### ISSUE THREAD

**Issue by tfiduccia** [harvester/harvester#250]
Issue:  I'm not sure what I did to crash it... so I will give you all the steps.

Steps:
1.  Go to Settings - Network Settings
2.  Enter bad info into NIC field (111.111.111.111)
3.  Go see error message in Networks page
4.  Go back to Network Settings and try to enter a valid NIC (eth0)

Results:
The host machine crashed and I can not access the UI.

**Comment by guangbochen** [comment]
was this done using GCP? we have also tested with GCP but seems they do not support bridge host mode.

**Comment by yasker** [comment]
I think this is GCP. The demo environment. The problem here is the harvester crashed.

**Comment by guangbochen** [comment]
I have checked the GCP env and the host is currently unreachable as the bridge mode will make it losing IP connection, that's why the UI is not reachable.

For network validation, we have to do it in a bare-metal machine with support for both bridge mode and trunk mode switch. @yasker will setup the test env later in the Fremont and we can use that for network validation, thanks.

**Comment by guangbochen** [comment]
since this is an environmental issue and the GCP does not support host bridge mode so will close this now, feel free to open it if have any further questions, thanks.
