### ISSUE TITLE
[BUG] Dashboard Storage used is wrong when a node disk is warning

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2622]
**Describe the bug**

Dashboard Storage used is wrong when a node disk is warning

**To Reproduce**

1. Create a Harvester
2. Create a VM that resources over the node to make the node disk is unschedulable

**Expected behavior**

Dashboard Storage used same as the longhorn UI

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-69a6b1b2-head` (08/29). Close this issue.


### Result
Since currently on latest v1.0.3 master we no longer can create a VM that resources over the node to make the node disk is unscheduled. 

To verify this issue, we directly disable the node and volume scheduling on Longhorn UI and check the Harvester dashboard disk usage display the same with it on Longhorn dashboard page 

After disabling the node and storage scheduling on Longhorn UI. 

* The scheduled storage display 0 Bi on Longhorn dashboard 
  ![image](https://user-images.githubusercontent.com/29251855/187577965-99dc5c6f-c270-4546-8c48-d93bb462e5a7.png)
 
* And Harvester dashboard also display 0 used and scheduled in correspondence with Longhorn UI
  ![image](https://user-images.githubusercontent.com/29251855/187606026-a735994b-6527-417f-b0e3-e8da183afe73.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-69a6b1b2-head` (08/29)

### Verify Steps
1. Login harvester dashboard
2. Access Longhorn UI from url https://192.168.122.136/dashboard/c/local/longhorn 
3. Go to Node page 
4. Click edit node and disks
5. Select disabling Node scheduling
  ![image](https://user-images.githubusercontent.com/29251855/187578343-653d0235-92a9-4979-aae0-b62b606df525.png)
6. Select disabling storage scheduling on the bottom
  ![image](https://user-images.githubusercontent.com/29251855/187578175-326b5909-cd6a-4e31-a1cf-92df5e619a5c.png)
7. Open Longhorn dashboard page, check the Storage Schedulable 
8. Open Harvester dashboard page, check the used and scheduled storage size
