### ISSUE TITLE
[BUG] - Bridge mode goes back to balance-tlb after installation

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#2675]
**Describe the bug**
When you install Harvester from the Iso, and configure the bridge mode to 802.3ad, upon installation completion and after reboot, in the /oem/99_custom.yaml file, the BONDING_MODULE_OPTS shows mode-balance-tlb.  This makes the network fail after the node starts the services.  We need to edit the file to change the mode back to 802.3ad.

**To Reproduce**
1. Boot Harvester Installation Media ISO
2. When requested, choose 2 adapters and configure the mode to 802.3ad
3. Finish the installation
4. Once rebooted, the mode goes back to balance-tlb

**Expected behavior**
I would expect the mode to stays the same as the mode configured during installation

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with SuperMicro/EPYC on OVH):

**Comment by bk201** [comment]
cc @tjjh89017

**Comment by tjjh89017** [comment]
@RegisHubelia I will try to reproduce it in my lab.
Do you get same result every time?

**Comment by tjjh89017** [comment]
reproduce:
Choose 802.3ad
and check the installation options page
it will always show balance-tlb

**Comment by tjjh89017** [comment]
@RegisHubelia 
You could set the bond mode in Installation UI "twice" as a workaround.

**Comment by tjjh89017** [comment]
### Root Cause:

`mgmtNetwork.BondOptions` will `nil` until `askBondModeVConfirm` is executed first time.
`PreShow` will be executed multiple times and set BondMode back to the default value in the first time.

### Fix

While setting default bond mode, let installer set BondOptions to non-null map to avoid.
https://github.com/harvester/harvester-installer/pull/320

### Workaround

Choose bond mode twice or more to set the correct value.

### Test Plan

1. select other bond mode than default one
2. continue install option until showing all config yaml before installation
3. check installation yaml has correct bond mode.

![image](https://user-images.githubusercontent.com/2821179/185289044-086c79d6-4f9a-4ccd-83e7-37b34708991e.png)

**Comment by RegisWeduLabs** [comment]
Thank you for taking care of it - and for the workaround!

**Comment by tjjh89017** [comment]
> Thank you for taking care of it - and for the workaround!

I tested workaround in my lab and worked fine.
Does that work in your environment?
tks a lot

**Comment by RegisWeduLabs** [comment]
I'll build a new node within a few hours and will let you know ASAP.

**Comment by RegisWeduLabs** [comment]
@tjjh89017, worked fine!

**Comment by irishgordo** [comment]
![validated-that-install-doesnt-change-bond-mode](https://user-images.githubusercontent.com/5370752/185457667-5ac53bb1-96df-4b12-ad38-a85430f62998.png)

Validated that this all looks good on Harvester Master ISO: 9631b13 :smile: :+1: 

Thanks @tjjh89017 !

I'll go ahead and close this out.
