### ISSUE TITLE
[BUG] Missing update-ca-certificates

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2709]
**Describe the bug**
We use `update-ca-certificates` to add additional ca, but the command is not found in current master-head version.

**To Reproduce**
1. Start a harvester node.
2. ssh to the node.
3. Run `sudo -i`.
4. Run `update-ca-certificates`.

**Expected behavior**
The command should exist.

**Environment**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant

**Comment by tjjh89017** [comment]
PR: https://github.com/harvester/harvester-installer/pull/328

## test step

1. install harvester
2. open shell and grant root permission
3. test `update-ca-certificates` is existing

**Comment by TachunLin** [comment]
Verified **fixed** on `master-69a6b1b2-head` (08/29). Close this issue.

### Result
* Command `update-ca-certificates` exists on each Harvester node (4 nodes)
```
rancher@harvester-fd4qn:~> sudo -i
harvester-fd4qn:~ # update-ca-certificates
harvester-fd4qn:~ # which update-ca-certificates
/usr/sbin/update-ca-certificates
```

### Test Information
* Test Environment: 4 nodes harvester on dolphin bare machine
* Harvester version: `master-69a6b1b2-head` (08/29)

### Verify Steps
1. ssh to each harvester node 
2. Execute `sudo -i` 
3. Execute `update-ca-certificates`
4. Check command exist with `which update-ca-certificates`

**Comment by Martin-Weiss** [comment]
Does the command work and add the certificates from /etc/pki/trust/anchors to /etc/ssl/ca-bundle.pem? 
I thought /etc/ssl/ca-bundle.pem is read-only - but maybe I misunderstood..

**Comment by TachunLin** [comment]
The `update-ca-certificates` command can work adding the certificate from /etc/pki/trust/anchors to /etc/ssl/ca-bundle.pem in the following manner

1. When we add the certificate in the Harvester `additional-ca` settings 
![image](https://user-images.githubusercontent.com/29251855/188042419-a5cd950e-6412-4bfb-94b1-8163a099f80b.png)

2. The added certificate content located in /etc/pki/trust/anchors/additional-ca.pem
3. Harvester will use the `update-ca-certificates` and add the content to /etc/ssl/ca-bundle.pem 
![image](https://user-images.githubusercontent.com/29251855/187850374-70c0d8b4-fb5e-46b3-9278-897484128f7f.png)
4. And we also verified the added certificates still exists after we restart the current node 
5. Since during reboot, Harvester will perform the `update-ca-certificates` in the os level. 
https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/files/system/oem/09_ca.yaml

**Comment by Martin-Weiss** [comment]
In 1.0.3 I could see that /etc/ssl/ca-bundle.pem is read-only - or did I oversee something?
So when ever we add / adjust the additional CA with the UI - all nodes in the cluster need to be rebooted? 
Will this happen automatically?

**Comment by TachunLin** [comment]
Yes, once we add the additional CA with the UI, Harvester will automatically execute `update-ca-certificates` to add it to `/etc/ssl/ca-bundle.pem` without the requirement to reboot the node. 

The reboot check in step 4 just double confirm the additional CA still exists after the reboot.

**Comment by Martin-Weiss** [comment]
Ok - then we "just" have to restart all running services that are using this ca-bundle.pem (i.e. RKE2)?

**Comment by FrankYang0529** [comment]
Yes, we need to restart RKE2. We will automatically restart RKE2 after this fix https://github.com/harvester/harvester/pull/2713/commits/f860269962ff637816e2c0a34d388a008dfc48b5.
