### ISSUE TITLE
[ENHANCEMENT] Harvester supports draining the node when entering maintenance mode

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2723]
**Describe the bug**
We observed so far that VMs are migrated away from the node in maintenance mode, but such node is not drained. The expectation is that pods are drained from the node and then it gets cordoned.

Can we enhance functionality so that Maintenance mode performs this automatically?

**To Reproduce**
1. click `Enable Maintenance Mode` from the UI on the node page
2. check the VM is migrated to the other node
3. execute `kubectl get pod -A -owide` and other pods are still running on the maintenance node

**Expected behavior**
All pods runnings on that node should be drained automatically.

**Environment**
 - Harvester ISO version: v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetals

**Additional context**
- For Longhorn services, please refer to https://longhorn.io/docs/1.3.1/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime.
- VM pods should also be ignored to allow proper migration to the other nodes.

**Comment by guangbochen** [comment]
Depends on https://github.com/longhorn/longhorn/issues/4092 for a faster replica rebuild after node maintenance.

**Comment by ibrokethecloud** [comment]
## Test plan

## Single controlplane cluster:

### Common Setup:
* Create a 2 node cluster. In this scenario no node promotion will occur and first node will stay as master and second will stay as worker node
* Setup a non default storage class with 1 replica only.

#### worker drain pass scenario:
* create a VM using the default storage class
* place worker node in maintenance mode, and it should enter maintenance mode as there should be healthy replicas on controlplane node
* VM if scheduled on the worker node will be gracefully evicted to the controlplane node
* remove worker node from maintenance mode
* place controlplane node in maintenance mode, will fail, as the controller will reject the request as this is the only valid controlplane. logs of the harvester pod should reflect the same.

#### worker drain fail scenario:
* create a few VM's with the single replica storage class
* one of the replicas should schedule on the worker node
* attempt to place worker node in maintenance mode, a warning should be presenting with warning of VM's which will be impacted by the drain and `Apply` button will be disabled
* enable `Force` in the checkbox, should enable the UI, and allow `Apply` to be clicked
* drain controller will try and shutdown the impacted VM's from the warning pop-up
* drain will be unsuccessful, as longhorn will be unable to shutdown the last replica due to its PDB. logs of the harvester pod should reflect the same
* disable maintenance mode of the worker node
* place controlplane node in maintenance mode, will fail, as the controller will reject the request as this is the only valid controlplane. logs of the harvester pod should reflect the same.

## HA controlplane cluster:

### Common Setup:
* Create atleast a 3 node cluster. ensure that node promotion has been performed and we have a HA setup.
* Setup a non default storage class with 1 replica only.


#### controlplane drain pass scenario:
* create a VM using the default storage class
* assuming a 3 node cluster, all nodes will be controlplanes. place a node in maintenance mode, and this should be successful, and VM's will be gracefully migrated to other nodes in the cluster.
* attempt to place another controlplane node into maintenance mode, this should fail with message in the harvester pod logs that a controlplane is already in maintenance mode. at any point in time in a HA setup, only 1 controlplane node can be placed in maintenance mode

#### controlplane drain fail scenario 1:
* create a VM using the default storage class
* assuming a 3 node cluster, all nodes will be controlplanes. place a node in maintenance mode, and this should be successful, and VM's will be gracefully migrated to other nodes in the cluster.
* attempt to place another controlplane node into maintenance mode, this should fail with message in the harvester pod logs that a controlplane is already in maintainence mode. at any point in time in a HA setup, only 1 controlplane node can be placed in maintenance mode


#### controlplane drain fail scenario 2:
* create a VM using the single replica storage class
* assuming a 3 node cluster, all nodes will be controlplanes. try and place each node into maintenance mode one node at a time(unless we can view the node where the replica for the single replica storage class is scheduled). placing this node into maintenance mode will fail with the warning about unhealthy VM's and `Apply` button will be disabled
* enable `Force` in the checkbox, should enable the UI, and allow `Apply` to be clicked
* drain controller will try and shutdown the impacted VM's from the warning pop-up
* drain will be unsuccessful, as longhorn will be unable to shutdown the last replica due to its PDB. logs of the harvester pod should reflect the same

**Comment by lanfon72** [comment]
Hi @ibrokethecloud, the `controlplane drain pass scenario` is totally same as `controlplane drain fail scenario 1`, do we miss something?

When enable 2nd control-plane node into **maintenance mode**, It will failed silently, should we return `500` or other status code instead of `200` in API calls, and showing some error message in dashboard?

And we can still **Cordon** 2nd control-plane node, is this correct?


cc @guangbochen, @bk201

**Comment by lanfon72** [comment]
For **controlplane drain fail scenario 2**, we can **force** enable the node into maintenance mode, but it will just shutdown the VM (with 1 replica), and stuck in **Cordoned** without any further explain, is this means the node could be safe reboot?

**Comment by ibrokethecloud** [comment]
second node will get cordoned but not end maintenance mode and pods will not be evicted.

even with force enabled the behavior will be the same. but i can see the UX and i can make the change to not error out the api call itself.

**Comment by irishgordo** [comment]
@ibrokethecloud out of curiosity, will this handle taking into account vms with container disks / cd-roms ? - https://github.com/harvester/harvester/issues/3600

**Comment by irishgordo** [comment]
Working through the `worker drain pass scenario` on 2 nodes and happened to notice:
https://github.com/harvester/harvester/issues/3883
When trying to migrate the VM from the control plane node back to the worker node.

**Comment by irishgordo** [comment]
Single controlplane cluster - is looking good :smile: :+1:  on Harvester Version: master-2ba017d4-head 

Looking at HA controlplane cluster now.

**Comment by irishgordo** [comment]
I've opened up https://github.com/harvester/harvester/issues/3892 to track the edge case of forcing the worker node with single replica custom storage class - it's 'loop' with hopping between active/cordoned because of the annotations with the enable maintenance mode staying on the node

**Comment by irishgordo** [comment]
Ater testing the HA control plane cluster - this looks good :smile: :+1:  - I'll go ahead and close this out
