### ISSUE TITLE
[FEATURE] Ksmd monitoring CPU utilization

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#2743]
**Describe the solution you'd like**

Add a metrics chart of CPU utilization on the UI Dashboard page.

**Comment by connorkuehl** [comment]
I'm not 100% clear on the requirements for this issue.

The description says UI but the labels say backend. Since these metrics don't appear to be exposed from the backend already, I'm assuming this ticket is for the backend to surface these metrics so they can be presented on a dashboard, and the UI is a separate issue.

Furthermore, is it meant to be exposed to the Harvester dashboard, or to the rancher-monitoring grafana instances (+ prometheus)? Or both?

cc: @markhillgit  @bk201

**Comment by bk201** [comment]
Close until there is a clear description and need.
