### ISSUE TITLE
[FEATURE] Host/disk tags use component same as longhorn UI

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2837]
**Is your feature request related to a problem? Please describe.**

Related discuss in https://github.com/harvester/dashboard/pull/415#discussion_r975900099

**Describe the solution you'd like**

- Use component same as longhorn UI

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
@n313893254 this looks great!

I had some questions about validation - do we just want to validate the following? :
1. if node & disk tags are set in the Harvester Dashboard UI that they are also set appropriately in the embedded Longhorn UI
2. if node & disk tags are set in the embedded Longhorn UI that they are also set appropriately in the Harvester UI
3. if node & disk tags are updated in the embedded Longhorn UI that they are also updated appropriately in the Harvester UI
4. if node & disk tags are updated in the Harvester UI that they are also updated appropriately in the embedded Longhorn UI


![Screenshot from 2023-01-11 15-05-33](https://user-images.githubusercontent.com/5370752/211937063-42023853-2c73-46f3-8ed1-59490f4d111b.png)
![Screenshot from 2023-01-11 15-04-40](https://user-images.githubusercontent.com/5370752/211937064-d954c081-13d2-42fe-9d80-f0d30b636fa6.png)
![Screenshot from 2023-01-11 15-03-51](https://user-images.githubusercontent.com/5370752/211937066-34f95c42-d7f4-4f5c-8972-2dbbad6d7bf5.png)
![Screenshot from 2023-01-11 15-03-12](https://user-images.githubusercontent.com/5370752/211937068-777bc571-14ad-4ec8-bc05-94f4b8c6a1db.png)
![Screenshot from 2023-01-11 15-02-25](https://user-images.githubusercontent.com/5370752/211937070-5ee7f97f-d9bf-452c-9fb3-29ac8fef877f.png)
![Screenshot from 2023-01-11 15-09-54](https://user-images.githubusercontent.com/5370752/211937649-5349c07a-dc2d-4028-9e3d-c3f4ab95a70a.png)
 
 
If so, then I can go ahead and close this out because it does look good :smile: 

Tested on, Harvester Version: master-26b4af3f-head.

**Comment by n313893254** [comment]
@irishgordo Yes, the validation looks good to me!

**Comment by irishgordo** [comment]
sounds good, I'll go ahead and close this out :smile:  - thanks @n313893254 !
