### ISSUE TITLE
[Enhancement] Add disk space checking before upgrading

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2935]
**Is your feature request related to a problem? Please describe.**

Add a check for cluster resource before completing an upgrade.

**Describe the solution you'd like**

Add a validation webhook and reject creating an upgrade if:

- Node space is not enough. We need ~25GB of free space to preload images.
- ~CPU/memory is not enough.~ (move to another ticket, this is used to trace disk space only)
  - We need CPU allocation for additional pods (like duplicate longhorn instance-manager-e/r).
  - New resources that are needed by new components.
  - For live-migration cases, we need to check if the rest nodes can absorb VMs from a upgrading node.

**Describe alternatives you've considered**

**Additional context**

This is breaking out some of the functionality from a previous ticket [here](https://github.com/harvester/harvester/issues/2833)

- We have seen weird behavior when longhorn cannot have enough CPU to spawn new pods.

**Comment by Martin-Weiss** [comment]
Adding check is great - thanks!! But - just to be sure to be sure - please add the documentation what to do in case a check fails.. ;-)

**Comment by bk201** [comment]
@noahgildersleeve I've added more resource checking.

**Comment by bk201** [comment]
Consolidate into https://github.com/harvester/harvester/issues/3067 and close this one.

**Comment by bk201** [comment]
Reopen this for disk space checking. Add to [epic](https://github.com/harvester/harvester/issues/2935#issuecomment-1471182660).

**Comment by bk201** [comment]
One way is to use node exporter metric in Prometheus:

Query: `node_filesystem_avail_bytes{mountpoint="/usr/local"}`
```
node_filesystem_avail_bytes{container="node-exporter", device="/dev/vda5", endpoint="metrics", fstype="ext4", instance="10.10.0.11:9796", job="node-exporter", mountpoint="/usr/local", namespace="cattle-monitoring-system", pod="rancher-monitoring-prometheus-node-exporter-gz4qd", service="rancher-monitoring-prometheus-node-exporter"} | 36105703424
node_filesystem_avail_bytes{container="node-exporter", device="/dev/vda5", endpoint="metrics", fstype="ext4", instance="10.10.0.12:9796", job="node-exporter", mountpoint="/usr/local", namespace="cattle-monitoring-system", pod="rancher-monitoring-prometheus-node-exporter-p4t4f", service="rancher-monitoring-prometheus-node-exporter"} | 38456356864
node_filesystem_avail_bytes{container="node-exporter", device="/dev/vda5", endpoint="metrics", fstype="ext4", instance="10.10.0.13:9796", job="node-exporter", mountpoint="/usr/local", namespace="cattle-monitoring-system", pod="rancher-monitoring-prometheus-node-exporter-gtsnp", service="rancher-monitoring-prometheus-node-exporter"} | 38614994944
```

To query nodes <= 30G free space: `node_filesystem_avail_bytes{mountpoint="/usr/local"}<32212254720`.
But unfortunately, the monitoring stack is being converted to an optional add-on in 1.2.0.

**Comment by w13915984028** [comment]
seems data are collected from here or other flles under same path
(https://github.com/prometheus/node_exporter/blob/master/collector/filesystem_linux.go)

let `node-disk-manager` help collect the data and update to node object ?

**Comment by FrankYang0529** [comment]
Kubelet has file stats API for `/var/lib/kubelet`, so we can use its API to check the disk space.

Ref: https://github.com/cyberark/kubeletctl

**Comment by irishgordo** [comment]
**validation issue**

@w13915984028 @FrankYang0529 
Does this need to be tested with upgrading from?:

06/06/23 master-head -> 06/07/23 master-head

As I'm encountering an issue from:
06/02/23 master-head ( Version: master-5557c692-head ) -> 06/06/23 master-head due to:
https://github.com/harvester/harvester-installer/pull/492

![Screenshot from 2023-06-06 12-41-42](https://github.com/harvester/harvester/assets/5370752/3fd208e5-5820-4488-ab39-26c5996a54a4)
![Screenshot from 2023-06-06 12-41-22](https://github.com/harvester/harvester/assets/5370752/b688a489-03db-440d-a572-b9d45975ceaa)

Because from v1.1.2 -> master-head (06/06/23) the webhook does not the result of `/usr/local/` not having 30G of space as:
```
╭─mike at suse-workstation-team-harvester in ~
╰─○ ssh rancher@192.168.122.28 
The authenticity of host '192.168.122.28 (192.168.122.28)' can't be established.
ED25519 key fingerprint is SHA256:zlObPIYWaHJ/C3JG7LRQodNG6wiwpx6JrBs7B0n2GPQ.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.122.28' (ED25519) to the list of known hosts.
rancher@testv112-upgrade-no-disk:~> sudo su
testv112-upgrade-no-disk:/home/rancher # cd /usr/local
testv112-upgrade-no-disk:/usr/local # dd if=/dev/zero of=/usr/local/test.img bs=1G count=5
5+0 records in
5+0 records out
5368709120 bytes (5.4 GB, 5.0 GiB) copied, 4.19605 s, 1.3 GB/s
testv112-upgrade-no-disk:/usr/local # exit
exit
rancher@testv112-upgrade-no-disk:~> exit
logout
Connection to 192.168.122.28 closed.
╭─mike at suse-workstation-team-harvester in ~
╰─○ ssh rancher@192.168.122.28
Last login: Tue Jun  6 19:56:05 2023 from 192.168.122.1
rancher@testv112-upgrade-no-disk:~> df -h /usr/local
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda5        59G   32G   25G  57% /usr/local
rancher@testv112-upgrade-no-disk:~> 
```
Had taken place prior to upgrade, on a 200G disk.
![Screenshot from 2023-06-06 13-16-38](https://github.com/harvester/harvester/assets/5370752/cda91630-a12b-4abb-a197-7ef41d75d347)

**update:**
The upgrade hangs for multiple hours from v1.1.2 -> master-head-06-06-23.iso if the `/usr/local` doesn't have 30G:
[hvst-upgrade-djqv7-upgradelog-archive-2023-06-06T22-11-19Z.zip](https://github.com/harvester/harvester/files/11669661/hvst-upgrade-djqv7-upgradelog-archive-2023-06-06T22-11-19Z.zip)

**Comment by bk201** [comment]
@irishgordo 1.1.2 doesn't have this feature, so we need to test the upgrade from `v1.2-head` ISO to `v1.2-head` ISO.
The issue https://user-images.githubusercontent.com/5370752/243810589-3fd208e5-5820-4488-ab39-26c5996a54a4.png was fixed after we bumped the monitoring charts (previously there is a workaround to bypass the check)

**Comment by lanfon72** [comment]
Encountering this while verifying #3655, move to implement.
The error message should be more clear to point out which partition is, otherwise user will not able to free more spaces to do upgrade.

![image](https://github.com/harvester/harvester/assets/5169694/7381c0f8-d4be-4820-98ff-ccae50fcf718)
![image](https://github.com/harvester/harvester/assets/5169694/64821c07-9a9e-4648-a9b3-93a7bb1bbadb)

**Comment by w13915984028** [comment]
In Harvester doc, the description is like:

> Make sure each node has at least 30 GiB of free system disk space (`df -h /usr/local/`). If any node in the cluster has less than 30 GiB of free system disk space, the upgrade will be denied. Check [free system disk space requirement](#free-system-disk-space-requirement) for more information.

The error message in code, could also be polished to be more accurate.

**Comment by WebberHuang1118** [comment]
Updated test plan at https://github.com/harvester/harvester/issues/2935#issuecomment-1480739928

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/78e536dc-ffcf-4ff3-9055-13156cc38000)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-7a8ac2c2-head** (same version upgrade)
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade[^1] with `minFreeDiskSpaceGB` annotaiton
```yaml
  annotations:
    harvesterhci.io/minFreeDiskSpaceGB: "1024" 
```
3. Upgrade should not started with error message that point out partition space in path `/usr/local` is insufficient

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
