### ISSUE TITLE
[Question] example of creating a VM from cloned hard drive

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#3010]
I'm a little lost about creating a VM from two drives I cloned.  Both are in `qcow2` format, one was from a physical machine and another from a VM on ESXi.  Both are confirmed working in vanilla qemu+kvm. 

I have uploaded both these images via the "Images URL" upload - I added the label `harvesterhci.io/OsType: windows` to one of them after upload, which triggered a re-download from my local web server, which really irked me because the file is 46GB and I'm working with a 1Gbps network.

Anyway, none of the images are listed under Volumes to be attached as a disk to a new VM.  Also, if I am creating a new VM, according to the docs the only process by which the infrastructure recognizes creating a VM is through new installation (via ISO), is that correct?

In addition, I do not have any volumes listed under Volumes, which seems strange because during the Harvester installation process I was told the unused space installation disk would be used for VM storage. Shouldn't I have `default` namespace listed here, or the two `qcow2` images I uploaded?

More guidance would surely be appreciated.

**Comment by albertkohl-monotek** [comment]
from what i've gathered, when you migrate or upload vms, that creates an Image. so your data should be in the image section.
when setting up a windows vm, you should pick the windows iso template, delete the root disk, and add back your uploaded image volume.

i wrote a tutorial here #2950 (windows) and here #2949 (linux) from hyper-v to harvester. hopefully they are helpful.

if you are are new to all fo this much like i was, the windows one will be helpful to you in particular, because you have to go into command prompt and load the virtio drivers to get the vm to boot. 

Hopefully this'll save you a lot of research and digging on the googles

**Comment by albertkohl-monotek** [comment]
also, new thing i've learned worth mentioning i think. the backing image (that you uploaded) will not be part of any backups you take from harvester. so either a) keep it around for future reload if you ever have to restore a from a backup, or b) dont use an image, recreate the ve from scratch in harvester. 

anyone else have any pointers on getting backing images our of harvester, feel free to correct me if you know how!
