### ISSUE TITLE
[FEATURE] Collect plan secrets in support bundles

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3064]
**Is your feature request related to a problem? Please describe.**

We remove all secrets in a support bundle, but plan secrets help debug upgrades.

**Describe the solution you'd like**

Collect plan secrets in a support bundle, including the metadata value.
We can ignore the `.data` part since it contains tokens.
```
kubectl get secret -n fleet-local --field-selector type=rke.cattle.io/machine-plan -o yaml
```

**Describe alternatives you've considered**

**Additional context**

Considering SBK is a generic framework, we can include it for Harvester in https://github.com/rancher/support-bundle-kit/blob/master/hack/collector-harvester

**Comment by irishgordo** [comment]
### Summary:
This looks good :+1: :smile: - I'll go ahead and close this out.
Tested on Harvester Version: master-7c1f4a24-head 3 Node Cluster & v0.0.12 Support-Bundle-Kit

### Strategy:
Built support-bundle, waited for zip from Harvester dashboard.
Then to prep, checked out support-bundle-kit at v0.0.12 as that's the latest tag.
Then kicked off the `make` hook only after spinning up Rancher Desktop.
Validated dapper build built everything correctly, visually audited `dist/artifacts` checked timestamps on built binaries like that of `support-bundle-kit-amd64`.
Spun down Rancher Desktop, since having it up would interfere with the embedded etcd server that gets spun up with `support-bundle-kit-amd64 simulator --bundle-path ~/path/to/unzipped/supportbundle/directory/to/be/used`.

Leveraging then the `admin.kubeconfig` that gets built from support bundle kit via:
`kubectl --kubeconfig ~/.sim/admin.kubeconfig get secret -n fleet-local --field-selector type=rke.cattle.io/machine-plan -o yaml`

Was visually able to see elements and data.
Was also verifying that `secrets.yaml` within the `yamls/namespaced/fleet-local/v1` folder in the unzipped support bundle yielded. only `machine-plan` as expected.
```
cat secrets.yaml | grep -nr "type:"
secrets.yaml:81:        f:type: {}
secrets.yaml:110:  type: rke.cattle.io/machine-plan
secrets.yaml:195:        f:type: {}
secrets.yaml:210:  type: rke.cattle.io/machine-plan
secrets.yaml:289:        f:type: {}
secrets.yaml:318:  type: rke.cattle.io/machine-plan
```
Also checked for data elements:
```
cat secrets.yaml | grep -C 5 -nr "data"
```

### Supporting Screenshots:
![Screenshot from 2022-11-21 16-31-17](https://user-images.githubusercontent.com/5370752/203185926-d928f72b-4c7d-4c10-b15d-6b54fc4c9a8c.png)
![Screenshot from 2022-11-21 16-24-11](https://user-images.githubusercontent.com/5370752/203185929-20fcc08e-b0ab-46cf-86b7-61e44e404c8d.png)
![Screenshot from 2022-11-21 16-23-06](https://user-images.githubusercontent.com/5370752/203185931-bcd3e4b7-45cf-4482-a4cb-5b9c1ce8c2c4.png)
![Screenshot from 2022-11-21 16-22-46](https://user-images.githubusercontent.com/5370752/203185933-09954b22-2943-44ba-94e2-8af00b66221e.png)
![Screenshot from 2022-11-21 16-21-45](https://user-images.githubusercontent.com/5370752/203185936-3979546c-658a-4ee6-aef3-4619a86eb8f2.png)
