### ISSUE TITLE
[FEATURE] doc: add `containerd-registry` setting doc

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3090]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add the setting info and example to https://docs.harvesterhci.io/v1.1/advanced/settings

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Checked in `https://docs.harvesterhci.io/v1.1/advanced/settings/`. There's a typo. It says "an username", but because it's pronounced as a Y sound it should be "a username".

![Screenshot_20221110_104337](https://user-images.githubusercontent.com/83787952/201180009-59e07884-77d3-4cce-ab43-973c1fbb1958.png)

**Comment by noahgildersleeve** [comment]
Verified as fixed in https://docs.harvesterhci.io/v1.1/advanced/settings.
