### ISSUE TITLE
[BUG] VM will be shutdown automatically when upgrading

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3206]
### Describe the bug
When upgrading Harvester with 3 VMs(guest cluster, created by Rancher), VMs will be shutdown during the upgrade.

### To Reproduce
1. Install Harvester with 2 nodes
2. Import Harvester to Rancher v2.6.9
3. Create rke2 cluster
4. perform upgrade

### Expected behavior
VM should be migrated to other node, not shut down.

## Environment:
 - Harvester ISO version: **v1.1.0** to **v1.1.1-7c1f4a24-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360G9 2 nodes**

### Additional context
Discovered when testing 2 nodes upgrade.

**Comment by RegisWeduLabs** [comment]
Hey, does this mean we can upgrade without shuting down all VMs?  In the docs, you specify that you recommend shutting down all "Users VMs" - not sure exactly what this means, and it's not really practical if you have multiple guest clusters managed by Rancher on Harvester - shutting down all the vms prior to upgrade can cause quite a mess when trying to bring everything back up...  Before I proceed with upgrading 1.0.3 to 1.1.1 that will be coming out in the next days, I just want to check if leaving the VMs on is possible at all...

Thanks!

**Comment by lanfon72** [comment]
Hi @RegisHubelia, yes, when you upgrading to `v1.1.1`, VMs would not need to be shutting down.

**Comment by RegisWeduLabs** [comment]
Thanks @lanfon72!

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.1.0** upgrade to **v1.1.1-master-0cdb5a5b-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7.0**

### Verify Steps:
1. Install Harvester with at least 3 nodes
2. Login to Harvester Dashboard
3. Create a Image for VM creation
4. Create a VLAN network
5. Login to Rancher Dashboard
6. Navigate to _Virtualization Management_, Import Harvester
7. Navigate to _Cluster Management_, Create RKE2 cluster with 3 VMs
8. Perform Harvester upgrade [^1]
9. During the upgrade, login to one of VMs, ping another VM
10. Connection should not lost
    - VM will be migrated to another node automatically if needed


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade

**Comment by RegisWeduLabs** [comment]
Hi @lanfon72, following my comment https://github.com/harvester/harvester/issues/3206#issuecomment-1329434640, you said that the VMs would not need to be shutdown...  But from the documentation:
"Starting from version v1.1.0, Harvester brings in the new [VLAN enhancement](https://github.com/harvester/harvester/issues/2236) feature. Due to the implementation changes, all user VMs must shut down if the upgrade is from v1.0.3 to v1.1.1. Please stop the VMs before an upgrade. Upgrading from v1.1.0 to v1.1.1 doesn't have this restriction." 

I would like to clarify: can we leave the VMs on or it's not possible and I'd need to shutdown all VMs and my 4 kubernetes clusters prior to the upgrade?  Again, upgrading from 1.0.3 to 1.1.1.

Thanks!

**Comment by lanfon72** [comment]
Hi @RegisHubelia, sorry for the inconvenience.  for this issue, we will guarantee VMs will be migrated to other node while upgrade from `v1.1.0` to `v1.1.1`.

If you are not in hurry, I will check the behavior for `v1.0.3` to `v1.1.1`.


Thanks,
Lanfon

**Comment by RegisWeduLabs** [comment]
Not in a rush, there are a few features I need network wise, but if I can prevent shutting down all the guest clusters, it would be best.  It is, after all, a production environment...

Thank you very much!!

**Comment by lanfon72** [comment]
Hi @RegisHubelia, our network implementation changes will affect all nodes, so downtime is unpreventable.  to minimize downtime, you can keep all VMs up while upgrading, VMs will be shutting down during the system upgrade; then you can start your VMs after one node upgraded, VMs will be scheduled to the upgraded node.

Thanks,
Lanfon

**Comment by RegisWeduLabs** [comment]
Okay, thanks.  Is there a "good" way to do that knowing the VMs are Rancher-created kubernetes clusters with Longhorn?
I'm just worried about breaking my current clusters...

So my guess is that the behaviour will be:
- 1st node will go in maintenance mode, and VMs on that node will be shutdown.
- Once it's back up, the 2nd node will enter maintenance mode - and VMs on that node will also be shutdown.
- During that time, I can power on the VMs that were shutdown and they will start on the 1st node

Then I do that for all vms/nodes.

Ideally tough, I would like to be able to control the upgrade pacing - not sure if feasable.  Ideally I would migrate all VMs from 1 node to the 2 other nodes, then start the upgrade process.  When it's back up, I can power-off the vms on the 2nd node and power them back on so they start on the upgraded node.  Once the 2nd node is empty, the upgrade would go ahead and upgrade the 2nd node, and so on.  Is this possible or the upgrade process just goes random on the nodes?

Thanks again for checking on this.  Appreciate it.

**Comment by Martin-Weiss** [comment]
I understood, that in future Harvester versions the need to shutdown VMs will be gone and we can use "vm migration" to failover the machines during an upgrade.

So either shutdown all machines and do the Harvester upgrade or let the system do the "vm migration" automatically.

As a feature request maybe the process should be "allow manual drain" instead of "do automatic drain" - then the process of an upgrade could be done more "controlled".. but not sure if/why we would need that as "vm migration" should not cause any downtime..

**Comment by RegisWeduLabs** [comment]
Hi @Martin-Weiss, I understand that future releases won't be a problem - but I am concerned about the upgrade from 1.0.3 to 1.1.1, I know it's a one shot deal, but I have a lot at stake and a lot can go wrong, so I just want to make sure the best approach for this specific upgrade, if that makes sense?

Thanks!

**Comment by Martin-Weiss** [comment]
> Hi @Martin-Weiss, I understand that future releases won't be a problem - but I am concerned about the upgrade from 1.0.3 to 1.1.1, I know it's a one shot deal, but I have a lot at stake and a lot can go wrong, so I just want to make sure the best approach for this specific upgrade, if that makes sense?
> 
> Thanks!

Yeah - understood. 

So best and required process (required from 1.0.3 to 1.1.1 due to network changes) is to shutdown all the VMs before the upgrade and leave them off until the upgrade is completed. 
Make sure that all data in longhorn is healthy and make sure you have backups of all VMs, Images and other Volumes you have in the cluster - just to be sure to be sure.
Once all is updated - start the VMs, again.

An other option might be to have a support call open asking for standby and help or even consulting assistance... just in case..

**Comment by lanfon72** [comment]
Hi @RegisHubelia, when upgrading from `1.0.3`, network need to be reconfigured, so the progress steps would like:
- Preload image for each node
- Upgrade Harvester system service
    - shutting down all VMs before upgrade network
- Upgrade first node
    - pre-drain, post-drain, reboot
- Upgrade other nodes

So it is not possible for us to keep VMs up. (Upgrade network will affect all VMs)


Thanks,
Lanfon
