### ISSUE TITLE
[BUG]node-disk-manager should not remove the hot-plug devices from `blockdevice` CR

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#3218]
Related to issue: #3128 

It considers external devices like JBOD, SAN, or NVMEoF as the disks of `Harvester`.
We do not remove the device from the `blockdevice` CR when it is just temporarily missing (maybe a hot plugin).

If the device removes from the `blockdevice` CR, even if it comes back, it does not mount to the correct folder.
That is because provision-related parameters are reset when it add-back. (You could imagine the new device adding to the `blockdevice` CR).
We should only remove the disk from the `blockdevice` CR when we remove it directly from UI/API.

**Comment by albinsun** [comment]
Hi @Vicente-Cheng,
Tested in `v1.2-56e9844d-head` but SCSI does not work as expect.
Note that same steps works for VirtIO disk.
Following are current test plan and result, please help to check.

Thanks

## Test Environment
* Harvester
  * version: `v1.2-56e9844d-head`
  * profile: QEMU/KVM, single node
  * **ui-source**: Auto

## Verification
### Scenario: SCSI
1. Add SCSI disk with wwn
   Ref. https://github.com/harvester/node-disk-manager#appendix
3. Format disk w/ ext4
   ```
   # mkfs.ext4 /dev/sda
   ...
   # fsck.ext4 /dev/sda
   ...
   ```
4. Check `/dev/sda` discoverd by NDM as blockdevice $~~~~$ $\color{green}{\textsf{PASSED}}$
5. Add Disk on harvester-node
6. Check blockdevice **Provisioned** and **Active** $~~~~$ $\color{green}{\textsf{PASSED}}$
7. On QEMU/KVM, remove SCSI Disk
8. /dev/sda should becomes **Inactive** $~~~~$ $\color{red}{\textsf{FAILED, still Active}}$

#### supportbundle
[supportbundle-scsi_and_virtio-2.zip](https://github.com/harvester/harvester/files/11974284/supportbundle-scsi_and_virtio-2.zip)

#### test record
https://github.com/harvester/harvester/assets/2773781/0b90e65c-9f53-45f1-83fd-7ed8a66c2b7e


## Note
1. Same steps using VirtIO disk works.

**Comment by irishgordo** [comment]
During the testing with #3412 - I was utilizing a physical external USB device attached & detatched from the physical dell poweredge r720 server and was able to successfully get the "Active" -> "Inactive" status to display - but not with the SCSI disk with the wwn in the xml as @albinsun discovered

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc3`, verified as done.

Note that the abnormal disk remove behavior is an env. issue and fixed by adding a VirtIO SCSI controll to VM. Without SCSI controller, can still add disk, but VM will not receive disk remove event.
![0-vmm_scsi_controller](https://github.com/harvester/harvester/assets/2773781/88091752-9cdf-4c02-bc98-2a95e65741b1)


## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: QEMU/KVM, 3 nodes (8C/16G/250G per node)
  * **ui-source**: Auto

## Verification
1. On QEMU/KVM, plug a formatted exi4 SCSI disk with wwn
   Ref. https://github.com/harvester/node-disk-manager#appendix
   * Blockdevice is discoverd by NDM and should be **Unprovisioned** $~~~~$ :heavy_check_mark: 
   ![1-insert_scsi_disk](https://github.com/harvester/harvester/assets/2773781/e37eb794-0df1-4686-a395-fde1374be0bc)

3. Add Disk on harvester-node
   * Hosts -> Edit Config -> Storage -> Add Disk
   * Blockdevice should be **Provisioned** and **Active** $~~~~$ :heavy_check_mark: 
   * Mount path is `/var/lib/harvester/extra-disks/989754e4e66edadfd3390974a1aba3f8`
   ![2-add_scsi_disk](https://github.com/harvester/harvester/assets/2773781/b76f33e6-4f0b-4076-a9c4-788702a7cdb4)

6. On QEMU/KVM, un-plug SCSI Disk
   * Blockdevice should be **Provisioned** and **Inactive** $~~~~$ :heavy_check_mark: 
   ![3-unplug_scsi_disk](https://github.com/harvester/harvester/assets/2773781/762a337f-cc20-4715-903a-c010a6558ba4)

8. On QEMU/KVM, plug SCSI disk back
   * Blockdevice should be **Provisioned** and **Active** again $~~~~$ :heavy_check_mark:
   ![4-plug_back1](https://github.com/harvester/harvester/assets/2773781/bdc0b628-c3eb-49a2-b038-10746e67e1de) 
   * UI states are updated, mount path should still `/var/lib/harvester/extra-disks/989754e4e66edadfd3390974a1aba3f8` $~~~~$ :heavy_check_mark: 
   ![5-plug_back2](https://github.com/harvester/harvester/assets/2773781/320270a8-01bb-4431-9de2-288e311f210c)
