### ISSUE TITLE
[Question] Has any cloud provider been formed based on the Harvester?

### ISSUE THREAD

**Issue by perpi** [harvester/harvester#3226]
As I am developing a business model to launch a cloud company based on Harvester, I need to get benchmarks from businesses that provide services on Harvester. Have any harvester-based cloud service providers yet been established? I would appreciate it if you could introduce those startups/companies if there are any.

**Comment by yasker** [comment]
Hi @perpi ,

Since Harvester just reached GA in December last year, it's still relatively new. We haven't seen much Harvester-based cloud provider service yet.

But we do think this is a potential opportunity there, especially if the target user group is Kubernetes users.

If you have any questions, feel free to let us know.

**Comment by perpi** [comment]
Hey.

> especially if the target user group is Kubernetes users

Um, I'm working on a IaaS business for the demands of cloud servers! Why target Kubernetes users since Kubevirt is a tool for creating virtual machines?

**Comment by perpi** [comment]
#Up

> especially if the target user group is Kubernetes users

Would you please explain more or link me to a reference?

And, please open this topic. Thanks
