### ISSUE TITLE
[Enhancement] Upgrade: ignore Longhorn CSI pods when draining a node

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3315]
**Is your feature request related to a problem? Please describe.**

[Longhorn doc](https://longhorn.io/docs/1.3.2/volumes-and-nodes/maintenance/#updating-the-node-os-or-container-runtime) advises that users should drain a node with `--pod-selector='app!=csi-attacher,app!=csi-provisioner'`. We should follow this in the upgrade path.

**Describe the solution you'd like**

We should pass the pod selectors when draining a node.

**Describe alternatives you've considered**

**Additional context**

https://github.com/rancher/rancher/issues/40003

**Comment by bk201** [comment]
Longhorn implements using PDB to avoid draining important pods in 1.3.3: https://github.com/longhorn/longhorn/issues/3304
We can bump to a version with this feature and avoid using the pod selector.

**Comment by guangbochen** [comment]
This is backported to LH v1.4.2, and will need to wait for the new LH release.

**Comment by albinsun** [comment]
## Test Plan
1. Fresh install a 3 nodes harvester `v1.1.2`  cluster
2. Login harvester via VIP.
3. Test following on each node one by one
   1. Check `csi-attacher` and `csi-provisioner` exists
   2. Enable maintenance mode
   3. Check `csi-attacher` and `csi-provisioner` should NOT exists
   4. Disable maintenance mode
4. Upgrade harvester cluster to `v1.2.0-rc2`
6. Login harvester via VIP.
7. Test following on each node one by one
   1. Check `csi-attacher` and `csi-provisioner` exists
   2. Enable maintenance mode
   3. Check `csi-attacher` and `csi-provisioner` should still exists
   4. Disable maintenance mode

**Comment by guangbochen** [comment]
After bumping LH to v1.4.2, the PDB is created correctly. However, during the node drain, the csi-related pods will get evicted immediately without waiting for the VM's pods to be evited first(potentially due to the VM workload type is not covered in the https://github.com/longhorn/longhorn-manager/pull/1764), will consider moving this to the v1.2.1 milestone since this will require upstream dependency fix.

**Comment by innobead** [comment]
> After bumping LH to v1.4.2, the PDB is created correctly. However, during the node drain, the csi-related pods will get evicted immediately without waiting for the VM's pods to be evited first(potentially due to the VM workload type is not covered in the [longhorn/longhorn-manager#1764](https://github.com/longhorn/longhorn-manager/pull/1764)), will consider moving this to the v1.2.1 milestone since this will require upstream dependency fix.

@guangbochen Did you mean CSI pods have not been protected correctly? CSI pods will be allowed to evict when no attached volumes which means no PDB or at least one CSI pod exists if there are still volumes attached.

**Comment by guangbochen** [comment]
@innobead yes, below are my testing steps based on the VM scenario, but the volume and VM pods are both exist on the node that I want to drain.

- verify there is no PDB of csi pods
- create VM with RWX volume
- PDB is created for those csi pods
- Drain the node by `kubectl drain <node-name> --ignore-daemonsets --delete-emptydir-data --force`
- the csi pods on the drained node will get evicted immediately, and VM's pod will re-spawn on the other node but only after the csi-pods were re-created.
- the csi PDB is still exist

**Comment by PhanLe1010** [comment]
@guangbochen 

The CSI PDB [only requires that there is >=1 CSI pod in the running state](https://github.com/longhorn/longhorn-manager/blob/4a57a7222edec14a2e7fcd84e2a0fa9e3fe141da/controller/kubernetes_pdb_controller.go#L205)

If there are multiple CSI pods running on node-1, node-2, and node-3. When you drain node-1, the CSI pod on node-1 will be evicted immediately without waiting since there are still 2 running CSI pods. This is fine. Do you have any concern about this behavior @guangbochen ?

**Comment by bk201** [comment]
We don't need this on the Rancher side since LH uses PDB to guard it.
