### ISSUE TITLE
[Question] RAID setup

### ISSUE THREAD

**Issue by CC007** [harvester/harvester#3322]
I have 2 SSDs that are configured to be part of a RAID 1 array through my UEFI bios, however when I try to install Harvester (as described [here](https://docs.harvesterhci.io/v1.0/install/iso-install), I see both drives show up as individual drives. 

Which drive do I need to select during the harvester installation?

**Comment by CC007** [comment]
Also, maybe as a feature request, It would be nice if the installation docs had some instructions regarding this, so that others with the same issue wouldn't have to ask the same question.

**Comment by bk201** [comment]
@CC007 Thanks for the report. Are you using Intel RST (which needs mdadm) to create the RAID device? Harvester only supports hardware RAID as the installation disk currently.

**Comment by CC007** [comment]
I am using an AMD threadripper cpu with a Gigabyte Aorus Pro wifi motherboard. I'm using it's provided RAID configuration in the UEFI bios.

**Comment by TheAifam5** [comment]
As far I know and also I am user of AMD Threadripper, in order to get "fake" hardware RAID working on Linux a driver is required "AMD RAIDXpert" or "AMD RAIDXpert 2" which in Linux source tree does exist and there are no packages available.

A ZFS support would be great but is not supported: https://github.com/harvester/harvester/issues/2775

**Comment by CC007** [comment]
I found the AMD raid drivers and RaidXpert2 utility download link here: https://www.amd.com/en/support/chipsets/amd-socket-strx4/trx40
It specifies that it supports RHEL and Ubuntu. I don't know what harvester uses, so I don't know if it will work for Harvester.
