### ISSUE TITLE
[BUG] Unable to click the "Use the default value setting" of cluster-registration-url 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3505]
**Describe the bug**

The `Use the default value` setting is greyed and unable to click 
![image](https://user-images.githubusercontent.com/29251855/220066366-073f31f9-2736-48a9-ac9b-4d2f3447c4d7.png)

**To Reproduce**
1. Go to Settings 
2. Check the cluster-registration-url

**Expected behavior**

Can click the `Use the default value` and set to the default value

**Support bundle**

[supportbundle_c11a2728-3cab-4cf6-8942-03dcffd4f79c_2023-02-20T09-33-35Z.zip](https://github.com/harvester/harvester/files/10782871/supportbundle_c11a2728-3cab-4cf6-8942-03dcffd4f79c_2023-02-20T09-33-35Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): local kvm machine

**Additional context**

**Comment by albinsun** [comment]
Tested in `master-942e20a5-head`, verified as fixed.

Test Environment
---
* Harvester
  * Single node cluster on KVM
  * Version: `master-942e20a5-head`
  * **ui-source**: Auto
* Rancher
  * Version: `v2.6.9`

Verification Steps
---
1. Confirm the **Use the default value** button is clickable.
   ![2-click](https://github.com/harvester/harvester/assets/2773781/f58ad543-f1dd-463d-b6d1-cfd333665e0c)
1. Import Harvester into Rancher ([Ref.](https://docs.harvesterhci.io/v1.1/rancher/virtualization-management))
   ![1-before_rancher_side](https://github.com/harvester/harvester/assets/2773781/ef3301c2-aecc-4fe6-98a4-bdbb5fdd5b53)
1. Confirm the **Use the default value** button is still clickable
   ![1-before_harvester_side](https://github.com/harvester/harvester/assets/2773781/5b01e3cc-2290-4c68-aa35-ad113c9ac4d4)
1. Reset cluster-registration-url via the **Use the default value** button then **Save**
1. Confirm cluster-registration-url is set to default value (None)
   * Harvester: Successfully reset to default value
   ![4-confirm](https://github.com/harvester/harvester/assets/2773781/64c3e2cd-3a4f-4f48-8768-7dd089644033)
   * Rancher: Show expected error since registration already reset on Harvester
![4-confirm_rancher_side](https://github.com/harvester/harvester/assets/2773781/31fe3d1c-bea0-40d3-b640-6b16b1886690)
