### ISSUE TITLE
[Question] default storage classes and storage tiering

### ISSUE THREAD

**Issue by codot-fr** [harvester/harvester#3521]
Hello,

Something is unclear in my point of view when reading the documentation. I've followed the documentation to add HDD disks and create a new "hdd" storage class, and it's fine.

What's still unclear to me is:
- What is the purpose of the default storage classes (harvester-longhorn and longhorn)
- Now that I have both SSDs and HDDs, how will the default untagged storage classes behave? My guess is that they would put blocks on SSDs and HDDs undiscriminately, am I right?
- Should I tag the SSD disks and create a ssd storage class and set it as default?

Thank you.

**Comment by futuretea** [comment]
> What is the purpose of the default storage classes (harvester-longhorn and longhorn)

The default storageclass scheduling policy is to use any disk, whether ssd or hdd

> Now that I have both SSDs and HDDs, how will the default untagged storage classes behave? My guess is that they would 
put blocks on SSDs and HDDs undiscriminately, am I right?

Yes

> Should I tag the SSD disks and create a ssd storage class and set it as default?

If you only want to use SSD disks, yes
You can set it to default or manually select it when you create/add volume

**Comment by codot-fr** [comment]
Thanks for the response. Why is there both harvester-longhorn and longhorn storage classes created by default ? Do they have different purposes ?

**Comment by albertkohl-monotek** [comment]
@futuretea i've been dealing with this too. is there any way to prevent a default storage class volume (longhorn-system) from spinning up on any volume, or change/migrate a volume to a different storage class? 

my use case is i had an existing v1.1.0 cluster, after upgrading to v1.1.1 i created an HDD storage class, and used DD to clone those volumes to the new SC. but now if a volume gets rebuild that wasnt tagged, it almost always tries to place it on those HDD volumes, rather than the untagged volumes. because they are HDD drives, it tends to put the cluster into a tail-spin.

**Comment by futuretea** [comment]
>  Why is there both harvester-longhorn and longhorn storage classes created by default ? Do they have different purposes ?

storageclass `longhorn` is a hangover from an old version.

**Comment by futuretea** [comment]
> change/migrate a volume to a different storage class

https://github.com/harvester/docs/pull/278
