### ISSUE TITLE
[BUG] When you have a node in fail state no uplinks show up in add network config

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3601]
**Describe the bug**

When you have a node that is in a fail state it won't let you add any of the NICs to the network config uplink
**To Reproduce**
1. Deploy a multi-node harvester cluster
2. Put one node in fail state (I'm not super sure how to do this specifically since it was a bad deploy that caused it)
**Expected behavior**

You should be able to assign uplinks based on active nodes
**Support bundle**

[supportbundle_dbd276cf-2df2-421f-8327-f9c1d7770cde_2023-03-06T22-50-07Z.zip](https://github.com/harvester/harvester/files/10903869/supportbundle_dbd276cf-2df2-421f-8327-f9c1d7770cde_2023-03-06T22-50-07Z.zip)

**Environment**
 - Harvester ISO version: v1.1-f3472cc4-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 node DL160 setup

**Additional context**
![Greenshot 2023-03-06 15 38 07](https://user-images.githubusercontent.com/83787952/223281604-c77ce9eb-5b56-4679-969b-0087cce823ba.png)
![Greenshot 2023-03-06 14 48 07](https://user-images.githubusercontent.com/83787952/223281608-c12f97f6-50ca-48d5-8963-79ae87a72221.png)

**Comment by guangbochen** [comment]
What's your node selector config? For all node selectors, I think fixing the bad node conditions first makes sense. cc @yaocw2020 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/4569037/223311544-05aa235a-9981-44fa-a611-c0c8b228828c.png">

However, I found we only support node selectors but not affinity or anti-affinity rules; this could be a good enhancement for further versions.

**Comment by bk201** [comment]
@noahgildersleeve Do you remember what's the node selector you choose? Thanks.

**Comment by noahgildersleeve** [comment]
@bk201 I almost always select "All nodes" as my node selector.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.1.2-rc4`. Close this issue.

### Result
When we have a node that enter into failed state like `Kubelet stopped posting node status.` 
![image](https://user-images.githubusercontent.com/29251855/228300164-fef303ea-5f8c-49d9-b4bd-a77474b6e353.png)

* Then we create a network config, set the node selector to to `All nodes` , the uplink NIC shows `no matching options`
That would be reasonable since one of the node is not available 
![image](https://user-images.githubusercontent.com/29251855/228301251-2f52eb0c-028c-4948-b173-5bc3afef262a.png)

* If we create the network config, set the node selector to specify to any `active` node, the uplink NIC can display as expected
![image](https://user-images.githubusercontent.com/29251855/228301808-61d7bf17-e355-4329-b414-6e826046b0b9.png)

* Also if we create the network config and select node selector to the `non active` node, the uplink NIC shows `no matching options`

### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: `v1.1.2-rc4`

### Verify Steps
1. Provision a 4 nodes Harvester cluster 
2. Monitor the provisioning process
3. Wait the last node load images and rebooting into console UI
4. Monitor the Harvester host page and console UI
5. When the last node just join the cluster and setting up, click the `Momentary Press` to shutdown machine
![image](https://user-images.githubusercontent.com/29251855/228310963-b96b5f50-a274-4466-b420-127eeeb03eb6.png)
6. The last node would display `Unavailable` on the host page
7. Create a cluster network
8. Create a network config, select `All nodes` as the node selector and check the uplink NIC list
![image](https://user-images.githubusercontent.com/29251855/228301046-d58ced90-0741-423d-b721-bca074d3a9b7.png)
9. Create a network config, select any `active node` as the node selector, and check the uplink NIC list
![image](https://user-images.githubusercontent.com/29251855/228302127-cc3125c8-9d27-4124-9426-449e14c1a66b.png)
10. Create a network config, select the `non active node` as the node selector, and check the uplink NIC list
