### ISSUE TITLE
[Question] I've deleted fleet-local namespace can restore?

### ISSUE THREAD

**Issue by cybercoder** [harvester/harvester#3684]
I've deleted fleet-local namespace and there's error messages:

Error
Type namespace not found, unable to display list

If it was in use by harvester core why it is removable?!

Is there anyway to restore?

kubectl get namespaces shows fleet-local is stucked in termination.

**Comment by masteryyh** [comment]
Hi @cybercoder 
1. Since `fleet-local` is user-created namespace in the perspective of kubernetes itself (created by rancher automatically), it can be deleted for sure (but you should never do this in Harvester);
2. When you delete this namespace, all resources and workloads like pods will be deleted first, and then namespace it self to be deleted;
3. `fleet-local` has a finalizer so it will stuck in `Terminating` phase;
4. It's hard to recover from this so I think you can try to reinstall Harvester.
