### ISSUE TITLE
[Question] run containers side by side

### ISSUE THREAD

**Issue by michaelandrepearce** [harvester/harvester#372]
When making a havester cluster, does the cluster show in rancher/is it possible to use the k3os also as a normal kubernetes cluster with longhorn and have containers run in the same cluster? 

If so is there any docs on how?

**Comment by michaelandrepearce** [comment]
Ps. Wow great stuff !!

**Comment by guangbochen** [comment]
Although this is not our intentional goal, you can indeed deploy and manage containers by importing the Harvester cluster into your existing Rancher and using it as a traditional k8s cluster. At the same time, your VM is able to communicate with the pod through the management IP.

![image](https://user-images.githubusercontent.com/4569037/102571834-7fe15000-4125-11eb-96f0-1841b4348468.png)

**Comment by michaelandrepearce** [comment]
Thanks will try that.

Would be great if in the future that was actually all in one rancher ui and its treated so a vm and container in a havester cluster are treated at a same level, so that you can basically take a bunch on physical machines and you get a shared hci cluster for having baremetal k8s for containers and vm deploys.  

This would be a awesome on-prem experience, where out the box for provisioning all you do is run havester on a single baremetal host, and you get k8s with longhorn pvs available, s3 bucket and for legacy workloads ability to run vm, all from the same tin and from one management plane. I wonder if layer 4 loadbalancing/ip allocation can be shared with metallb or something? out the box (obviously possible to run manually) but i mean managed by havester.

**Comment by michaelandrepearce** [comment]
We see its now possible to launch rancher clusters on top of vms in havester is there any progress or plans to actually support using the underlying baremetal k3s cluster exposed to rancher ui natively so that you can run baremetal containers next to the vms, not on top of vms

**Comment by olljanat** [comment]
Btw. I just noticed that https://harvesterhci.io contains text:
> Great For
> Containers and VMS in the Same Environment

so I would understand that it means this use case to be supported.

But of course it would be nice to get some official clarification.

**Comment by w13915984028** [comment]
@michaelandrepearce @olljanat 

The Harvester itself is a K8S cluster. In the UI, the features are focusing on `VM` and `guest k8s cluster` related.

On the other hand, the `kubectl` is natively fully supported. In case you want to deploy container related jobs/deployments/..., you should be able to do it via `kubectl`. Further, when those additional `containers` need to cooperate with `VMs`, or have a collaborative robustness etc., they are on your side.

Please keep in mind: It can be used for study and experiment, but it is not formally developed and released feature at the moment. Thanks.

**Comment by TheAifam5** [comment]
Someone tried and it looks like it is not possible to install Rancher:

https://forums.rancher.com/t/install-rancher-on-a-harvester-node-not-in-a-vm/38991/4

For a single bare-metal machine that would be the ideal solution since Harvester is running on top of K8S, why not allow people to deploy Rancher UI and dependencies on it? I do not say it must be officially supported but I think it should not be blocked too. 

I would like also to share my intendet use case in my small homelab:
A machine running Harvester providing virtualization support with vGPU and Rancher with etcd and control plane.
10x RPI 4 running Rancher only for workloads connected to the Rancher as nodes.
