### ISSUE TITLE
[BUG] Create network config and specify to any Harvester node, the status keep in `Not Ready` 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3723]
**Describe the bug**

When we create network config and specify to any Harvester node, the network config will display `Not Ready` state 

  ![image](https://user-images.githubusercontent.com/29251855/227892183-228932ad-1c3f-4329-a257-ad874896aa4c.png)
  
  ![image](https://user-images.githubusercontent.com/29251855/227892229-cb2b6f15-6bf4-494c-9f4b-df09129503b3.png)

  ![image](https://user-images.githubusercontent.com/29251855/227892269-34e6ab0b-413c-4e94-a81c-048db4e5cacf.png)

**To Reproduce**
1. Set up a four nodes Harvester cluster
2. Create a new cluster network
3. Create the related network config to select one compute node.

**Expected behavior**

Create network config and specify to any Harvester node, the status should display `Ready` 

**Support bundle**

[supportbundle_07b1920c-f39c-4894-8abd-c6fa26ed5960_2023-03-27T11-25-25Z.zip](https://github.com/harvester/harvester/files/11078042/supportbundle_07b1920c-f39c-4894-8abd-c6fa26ed5960_2023-03-27T11-25-25Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes bare machines

**Comment by noahgildersleeve** [comment]
Tested in v1.1.2-rc4. Verified as fixed with external UI-source.

## Verification Steps

1. Set up a four nodes Harvester cluster
2. Create a new cluster network
3. Create the related network config to select one compute node.
![Greenshot 2023-03-27 09 38 47](https://user-images.githubusercontent.com/83787952/228007653-119ae861-73c0-4d62-9bc3-2164408be488.png)
![Greenshot 2023-03-27 09 38 51](https://user-images.githubusercontent.com/83787952/228007663-b5c79d7a-59c4-4bab-9c4b-11a764897339.png)
4. Verify that network config shows as active after creation
![Greenshot 2023-03-27 09 38 36](https://user-images.githubusercontent.com/83787952/228007688-0a0c1d3f-9b6b-4193-85eb-0d65efb82ea6.png)
