### ISSUE TITLE
[ENHANCEMENT] Enhance the image list on the Volume page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3801]
**Is your enhancement related to a problem? Please describe.**

The image list in the Volume page should include namespace information, otherwise images with the same name but different namespace cannot be distinguished

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/7564c160-6797-44c8-b863-9c76b1c23536)

**Describe the solution you'd like**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/e611101e-32da-4daf-9022-898e52149d77)

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-942e20a5-head` (05/12). Close this issue.

### Result
When we several namespace, and for each namespace we create same name images on it. 

* On volume page, image can display in namespace and name combination 
![image](https://github.com/harvester/harvester/assets/29251855/32e51f4a-039d-4aad-9817-caad8e813a75)

* We can't create volume with the same name and namespace, it the expected behavior
![image](https://github.com/harvester/harvester/assets/29251855/dbfbf144-6e75-4f9d-95b1-d656c4094af3)

* We can create volume with the same name but in different namespace
![image](https://github.com/harvester/harvester/assets/29251855/41099efb-97cd-4e38-946e-33f39da764fb)

* When we directly create another custom namespace during the image creation, the image list can still display namespace and name on volume page
![image](https://github.com/harvester/harvester/assets/29251855/5ddab4bd-ba19-44ca-a584-7584fb3864fc)
  

* On virtual machine creation page, the image list can display in namespace and name combination
![image](https://github.com/harvester/harvester/assets/29251855/57110769-a741-4fe0-88b7-c91954ee9275)

* On vm template creation page, the image list can display in namespace and name combination
![image](https://github.com/harvester/harvester/assets/29251855/314506d3-6e97-425e-862e-6c929aaf91e0)



### Test Information
* Test Environment: single nodes Harvester on local kvm machine
* Harvester version: `master-942e20a5-head` (05/12)

### Verify Steps
1. Create a custom project `test` 
2. Create a custom namespace `custom` on project `test`
3. Create image from file with the same name on different namespace of `default`, `custom` and `harvester-public`
4. Create image from URL with the same name on different namespace of `default`, `custom` and `harvester-public`
5. Create volume and select vm image
6. Check the image list on volume page 
7. Create volume which already have the same name on the same namespace 
8. Check the error message
9. Create vm and select vm image 
10. Check the image list on vm creation page 
11. Create vm template and select vm image
12. Check the image list on vm template page
