### ISSUE TITLE
[BUG] Cluster Network could be created more than 12 chars but denied by Cluster Configs

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3826]
### Describe the bug
![image](https://user-images.githubusercontent.com/5169694/234262378-34978491-1e3e-4e1e-88cc-1c58494441cc.png)

Not a UI bug, UI will block user to create Cluster Network which name > 12 chars, but API didn't.

### To Reproduce
1. Install Harvester with any nodes
2. Create Cluster Network via API `api.clusternetworks.create('0123456789012345')`
3. Create Cluster Config with the cluster network

### Expected behavior
API should also check the length of cluster network

## Environment:
 - Harvester ISO version: **v1.1-cff1d5b5-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 2 nodes**

### Additional context
Discovered by API calls.

**Comment by rrajendran17** [comment]
I could reproduce the problem locally

Logs before adding fix:

harvester-tzw4x:~ # curl -k --location --request POST 'https://172.19.108.53/apis/network.harvesterhci.io/v1beta1/clusternetworks' \
> --header 'Authorization: Bearer token-rc7nf:b6lqg42rmw9qjhv4wqtk82zpftmxwg57rgr289qnxbdpf5n26lmjw8' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "apiVersion": "network.harvesterhci.io/v1beta1",
>     "kind": "ClusterNetwork",
>     "metadata": {
>         "name": "test-clusternetwork1",
>         "namespace": "default"
>     }   
> }'
{
  "apiVersion": "network.harvesterhci.io/v1beta1",
  "kind": "ClusterNetwork",
  "metadata": {
    "creationTimestamp": "2024-08-06T18:04:11Z",
    "generation": 1,
    "name": "test-clusternetwork1",
    "resourceVersion": "9453212",
    "uid": "8d11c423-12ae-4d35-8256-1e4edd408846"
  }
}

Logs after adding the fix:

curl -k --location --request POST 'https://172.19.108.53/apis/network.harvesterhci.io/v1beta1/clusternetworks' \
--header 'Authorization: Bearer token-rc7nf:b6lqg42rmw9qjhv4wqtk82zpftmxwg57rgr289qnxbdpf5n26lmjw8' \
--header 'Content-Type: application/json' \
--data-raw '{
    "apiVersion": "network.harvesterhci.io/v1beta1",
    "kind": "ClusterNetwork",
    "metadata": {
        "name": "test-clusternetwork3",
        "namespace": "default"
    }   
}'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "admission webhook \"validator.harvester-system.harvester-network-webhook\" denied the request: Internal error occurred: could not create cluster network test-clusternetwork3 because the length of the clusterNetwork value is more than 12",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "could not create cluster network test-clusternetwork3 because the length of the clusterNetwork value is more than 12"
      }
    ]
  },
  "code": 500
}

**Comment by rrajendran17** [comment]
Fixed

**Comment by lanfon72** [comment]
reopen for QA verification.

**Comment by bk201** [comment]
@rrajendran17 Please don't close the issue directly, let's move an issue to ready for testing and QA will close it once the fix is verified.

A bug fix needs to be backported to all supported releases, I added a backport label thus our bot will create an issue. (https://github.com/harvester/harvester/issues/6339), please help fix that too (you will need to backport the change to correct branches in the network controller)

The fix to the issue is on the network controller. When you have the [PR](https://github.com/harvester/network-controller-harvester/pull/111) merge in the network controller repo, the CI will build and publish new images to Dockerhub with the tag `master-head` (`rancher/harvester-network-controller:master-head`). The repo harvester/harvester's master branch is [using this image](https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/deploy/charts/harvester/values.yaml#L354), but the change only takes effect in two situations (1) daily master ISO build (2) new changes are merged in the master branch (in harvester/harvester or harvester/harvester-installer).

Given the issue is targeting the v1.4.0 release, my suggestion is to perform these tasks before moving the issue to ready for testing:
(1) Backport the [PR](https://github.com/harvester/network-controller-harvester/pull/111#issuecomment-2287994343) to the [v0.4.0](https://github.com/harvester/network-controller-harvester/tree/v0.4.x) branch.
(2) Once the backport PR is merged, do a new tag on the network controller repo. It will publish a new image. (Of course please check with network guys if there are any changes to include before tagging).
(3) Create a PR in the harvester/harvester repo to change the [image tags ](https://github.com/harvester/harvester/blob/391cee26ad1b2795c9e81ffa619b39fa8ad75204/deploy/charts/harvester/values.yaml#L354)in the v1.4 branch. 
(4) Once the PR is merged and CI passed, we'll have a v1.4-head ISO and then we can move the issue to ready for testing.

The same process should apply to the v1.3 branch as well. Sorry for the lengthy message, please let me know if it's not clear or makes sense. cc @starbops @mingshuoqiu

**Comment by rrajendran17** [comment]
@bk201 Thanks for the detailed message on the process.Sorry I should have thought about these back ports before closing.
               I will take care of these as you suggested above.

**Comment by rrajendran17** [comment]
@bk201 I could see branch for v0.4.x, but do not see a branch for v1.3.3.Will that be created in future ?

**Comment by starbops** [comment]
Let me update the version mapping between Harvester and network controller here:

- harvester-network-controller v0.5.x branch is for Harvester v1.4 releases
- harvester-network-controller v0.4.x branch is for Harvester v1.3 releases

Please correct me if it's not the case. Thank you. cc @mingshuoqiu

**Comment by mingshuoqiu** [comment]
Yes. 0.5.x for 1.4.
0.4.x for 1.3

**Comment by rrajendran17** [comment]
@lanfon72 I see http://172.19.96.23/iso/v1.4-head/ available.Please verify the fix when you get time.Thanks

**Comment by lanfon72** [comment]
Verified this bug has been resolved.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Follow steps to reproduce in https://github.com/harvester/harvester/issues/3826#issue-1682995111
2. API will deny Cluster network creation with error message `because the length of the clusterNetwork value is more than 12`
