### ISSUE TITLE
[BUG]Encountered a "down" network card during Harvester installation

### ISSUE THREAD

**Issue by miaoyc666** [harvester/harvester#3836]
**Describe the bug**
When I was installing Harvester on NUC, during the "configure network" stage, I was asked to select a network card. However, my network card was in a "down" state, and the installation process got stuck. How can I continue the installation?

**To Reproduce**
![image](https://user-images.githubusercontent.com/2928791/234785289-48fc7ec1-261d-4dde-a481-2e5a0e36093a.png)

**Environment**
ISO version: Harvester v1.1.2 Release 
ISO filename: harvester-v1.1.2-amd64.iso
NUC product: NUC11ATKC4000
NUC memory: 16G
NUC disk: 500G

**Solution**
Simply plug in the Ethernet cable to install！

**Expect**
I want to install it without plugging in the network cable.

**Comment by miaoyc666** [comment]
**Expect**
I want to install it without plugging in the network cable.

**Comment by w13915984028** [comment]
@miaoyc666 

Suppose you do not want to plug the network cable when installing Harvester, then those network will be in `down` status, thus, you can not choose `DHCP` mode for both node management IP and VIP, you need to select `static` mode to set IP manually.

On the other hand, this may still not work, because DNS server and NTP server needs to be filled to nslookup and sync the system.

It looks, you need to make sure the network environment is ready before installing the Harvester cluster.

**Comment by w13915984028** [comment]
@ibrokethecloud Will your `factory mode` feature work when the network cards are down ? thanks.

**Comment by miaoyc666** [comment]
@w13915984028   Now I know，thanks！
