### ISSUE TITLE
[ENHANCEMENT] Revisit the max persistent partition size settings

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3842]
**Is your enhancement related to a problem? Please describe.**

The persistent partition's maximum of the size is 100GB (See https://github.com/harvester/harvester-installer/blob/57171a58585b3dc76752b69dbe6d3faf498f00db/pkg/config/cos.go#L721).
This setting is too tight for increasing local images (especially upgrade path) and could lead to garbage collection easily.
And after introducing [the user workload to bare metal cluster](https://github.com/harvester/harvester/issues/2679), this can go worse.

**Describe the solution you'd like**

We need to increase the persistent partition size.

**Describe alternatives you've considered**

**Additional context**

Here is the partition layout of a 2T disk:
```
nvme0n1     259:0    0   1.8T  0 disk
├─nvme0n1p1 259:1    0    64M  0 part
├─nvme0n1p2 259:2    0    50M  0 part /oem
├─nvme0n1p3 259:3    0     8G  0 part
├─nvme0n1p4 259:4    0    15G  0 part /run/initramfs/cos-state
├─nvme0n1p5 259:5    0   100G  0 part /var/lib/longhorn
│                                     /var/crash
│                                     /var/lib/third-party
│                                     /var/lib/cni
│                                     /var/lib/wicked
│                                     /var/lib/kubelet
│                                     /var/lib/rancher
│                                     /var/log
│                                     /usr/libexec
│                                     /root
│                                     /opt
│                                     /home
│                                     /etc/pki/trust/anchors
│                                     /etc/cni
│                                     /etc/iscsi
│                                     /etc/ssh
│                                     /etc/rancher
│                                     /etc/systemd
│                                     /usr/local
└─nvme0n1p6 259:6    0   1.7T  0 part /var/lib/harvester/defaultdisk
```

**Comment by lanfon72** [comment]
It looks the new ISO not built yet, the latest one is `v1.2-3ea43d86-head` which not include this fix.

**Comment by bk201** [comment]
The [backport PR](https://github.com/harvester/harvester-installer/pull/509) is merged after the [version](https://drone-publish.rancher.io/harvester/harvester/1073/3/2). @masteryyh we need to confirm backport BR is in then move the issue to ready-for-testing.

> It looks the new ISO not built yet, the latest one is `v1.2-3ea43d86-head` which not include this fix.

**Comment by lanfon72** [comment]
@WuJun2016, @bk201 it looks false alarm, the installation stuck on fetching config.yaml because I reduce the size `< 150Gi`, but I think we should able to enhance it to not stuck but showing some error message or fail the installation.

Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/268d6b2e-7129-4ff3-952f-68508e5291e1)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2.0-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes with configuration:
```yaml
install:
  persistent_partition_size: 155Gi
# or `persistentPartitionSize`, 150 is the minimal size, otherwise the install will stuck
```
2. Login to node, execute `lsblk`, the partition size for `/usr/local` should equals to the size defined in configuration.
