### ISSUE TITLE
[BUG] UEFI USB boot is not working

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#3866]
**Describe the bug**

Booting from UEFI USB written by BalenaEtcher with Harvester v1.1.1 ISO lands on GRUB prompt instead of Harvester option to create new cluster or join existing cluster.
<img width="861" alt="Screenshot 2023-05-01 at 8 59 39 AM" src="https://user-images.githubusercontent.com/9990804/236714314-588a5bfc-053d-4fa8-920d-2edeb592e496.png">

**To Reproduce**
Write ISO to USB with version 1.1.1 or 1.1.2 ISO and try to boot via UEFI method

**Expected behavior**

UEFI USB boot should present Harvester menu options

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R640 with BIOS 2.14.2

**Additional context**

**Comment by bk201** [comment]
@davidcassany Hi David, did you see this error before? Wondering if https://github.com/harvester/harvester/issues/2204 can help.
Some findings by @masteryyh 
> While I'm investigating this issue, I found out a workaround that may bypass this problem: use tools like rufus on Windows and use its "ISO mode" to create a bootable Harvester USB device instead of balenaEtcher or dd, which I already tested without issue.

**Comment by davidcassany** [comment]
@bk201 hi, looks like there might be something wrong with the bootloader setup. Can you share a link to the ISO that is not booting? Where I can check how it was built (e.g. elemental-cli version)?

**Comment by bk201** [comment]
@davidcassany The ISO is at https://releases.rancher.com/harvester/v1.1.2/harvester-v1.1.2-amd64.iso
The ISO is still created with `luet-makeiso`, not yet switching to `elemental`.

**Comment by irishgordo** [comment]
@bk201 @masteryyh 
I've always seen this on multiple devices - a mix of Dell PowerEdge R720 series or even just ThinkCenter Lenovo devices that I have around the apartment.

I always thought that this just might have been a limitation of the hardware possibly-not having the most recent versions of firmware ( and I hadn't updated the firmware ).
So, I was just figuring that I've "always" just been working on older hardware and it was always on my side.

In fact, because I've always seen this it's prompted me to open up:
- [3590](https://github.com/harvester/harvester/issues/3590) 
Which lead to the recent-ish PR of:
- [298 on harvester/docs](https://github.com/harvester/docs/pull/298) (I've added you both as reviewers to that now)

^ That workaround, is fairly easy to navigate, as written in that docs pr.

Also to note, the "iso" flashing utility has no noticeable effect on whether or not the issue is reproduced.
I've used:
- Balena Etcher v1.18.4
- Popsicle v1.3.0 ([pretty neat usb-flasher from the fantastic folx at Pop!_OS](https://github.com/pop-os/popsicle/releases/tag/1.3.1))

Both of those utilities can be used to reproduce the issue with ease.

![Screenshot from 2023-05-08 09-44-58](https://user-images.githubusercontent.com/5370752/236884176-1600b63b-f276-4c59-af2d-207b79305273.png)
![Screenshot from 2023-05-08 09-44-38](https://user-images.githubusercontent.com/5370752/236884182-e1b0769e-d729-4e2b-8506-97de6ce6b1e4.png)
![Screenshot from 2023-05-08 09-14-46](https://user-images.githubusercontent.com/5370752/236884189-f29c31ec-8ab7-4876-aa0f-ae68b948d82a.png)
![Screenshot from 2023-05-08 09-14-25](https://user-images.githubusercontent.com/5370752/236884192-fbf6a46c-161a-4c5a-b343-09739bb436ac.png)


However, I can not replicate this with v1.0.0.
As that immediately shows the GNU GRUB Menu with Harvester Installer v1.0.0 as an option.
The GNU GRUB version in that is 2.04 - not 2.06 like with v1.1.1

Since there is a workaround listing this as `severity/3` :
```

Sometimes using a USB to mount the Harvester ISO disk directs you to Grub2. In this case, it helps to know what to set the root partition to and the location of `grub.cfg`.

You can see the current root partition in the `grub.cfg`. To view the `grub.cfg` from the ISO, run the command `chainloader /boot/grub2/x86_64-efi/grub.efi`.

To set a new root partition, run the command `set root=(hdN,msdos1)`, where N denotes N numbers of possible drives. N should be the drive your USB is mounted to.
```

**small update: I believe this is happening more often with older Intel based platforms and less often with newer ones**

**Comment by GoodGoodJM** [comment]
When I went through the #3789  issue, I also had that situation when I was booting UEFI.

**Comment by masteryyh** [comment]
It seems fixed by issue https://github.com/harvester/harvester/issues/2204, tested with multiple platform.

**Comment by masteryyh** [comment]
Test steps:
1. Prepare an ISO built with latest code;
2. Use `dd` or `balenaEtcher` to create a USB bootable device from this ISO;
3. Try to boot with this device in both UEFI and legacy BIOS environment;
4. Both of them should boot into harvester installer without problem.

**Comment by irishgordo** [comment]
This looks great :+1: :smile:  - thanks for the fix @masteryyh - it boots directly to the installer, so no need for `set root=(hdN,msdos1)` && then `chainloader ...` - the installer launches without a problem - tested with v1.2.0-rc1 


https://github.com/harvester/harvester/assets/5370752/3a613a97-f69f-4362-aa4e-fa409aded44f


I'll go ahead and close this out.
