### ISSUE TITLE
[Doc] Document correct upgrade path

### ISSUE THREAD

**Issue by ravarga** [harvester/harvester#3911]
When Rancher is configured with Harvester, it is currently not clear what is recommended upgrade path. For example with Rancher 2.6.11 and Harvester v1.1.1 is it recommended to upgrade Rancher first? If yes, then to which version (as 2.7.x is available)?

The upgrade procedure should also consider terraform provider compatibility in order to prevent rebuilds of downstream (Harvester) workloads.

**Comment by simonflood** [comment]
Since you've mentioned specific versions, given #3860 (as noted on Harvester 1.1.2 release page), in your case I would first upgrade Harvester from 1.1.1 to 1.1.2 then upgrade Rancher to 2.6.12 (or latest 2.6.x release) and then later (allow things to settle) to 2.7.3.

I recently followed this for Harvester 1.1.1 with Rancher 2.6.3 - Harvester 1.1.2 first then Rancher to 2.7.3 via 2.6.12. My Rancher is a single-node Docker install on a Harvester VM.

**Comment by chrisho** [comment]
Hi, @ravarga 

Here is the support matrix of the upgrade path with Rancher, u can find out on this page: https://docs.harvesterhci.io/v1.1/rancher/rancher-integration and details on
https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-1-2/

**Comment by ravarga** [comment]
I believe that upgrade path information is missing. In particular, for Rancher 2.6.11/Harvester 1.1.1 it makes sense to me to upgrade Rancher first so that the Harvester node driver is recent and only then upgrade the Harvester to 1.1.2. 
Can we enhance the documentation, especially for jumps between 2.6.x-2.7.x?

**Comment by simonflood** [comment]
Commenting to keep open

**Comment by belgaied2** [comment]
There is still no answer to this.
