### ISSUE TITLE
[Question] How to use sriov function in harvester1.20

### ISSUE THREAD

**Issue by Aixleft723** [harvester/harvester#4034]
I saw that the official community has released the sriov function, and I want to know how to use the various functions of sriov。TKS

**Comment by ibrokethecloud** [comment]
harvester 1.2.0-rc1 does have a part of the sriov changes.

To use, please enable the pcidevices addon: https://docs.harvesterhci.io/v1.1/advanced/pcidevices

Once this is deployed, the UI should show a new option for SriovNetworkDevices: this basically leverages pcidevices addon to scan the nodes for nic's which are sriov capable.

Once devices sriov capable devices appear, please edit the device and define the number of VF's.

pcidevices addon will now scan the VF's and will make them available as additional pcidevices, which can not be passed through to VM's.

**Comment by Aixleft723** [comment]
Do I need to create SriovNetworkDevices manually？Or is it automatically recognized, as long as my physical network card turns on sriov。 @ibrokethecloud

**Comment by ibrokethecloud** [comment]
capable devices will show up automatically. there could be a slight lag since it the underlying reconcile is an async process.

A side note: pcidevices controller will also skip nic's already in use for management and additional cluster network configurations. So if you have sriov capable nic's used in cluster network definitions they may not show up.

**Comment by Aixleft723** [comment]
ok i know it and i am tring to test it. tks @ibrokethecloud

**Comment by Aixleft723** [comment]
had got the information that i want to know
