### ISSUE TITLE
[BUG] The VM needs at least 10 minutes to automatically recover after a host failure

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#4049]
**Describe the bug**
Create a VM in a cluster consisting of three nodes and run it. And I forced shut down the node running the VM and deleted the pod.
At this point, the VM hasn't immediately auto-restarted, which could take more than 10 minutes.

**To Reproduce**
1. Change the setting `vm-force-reset-policy` period to fewer seconds, `period: 30`.
2. Create a VM.
3. Force shutdown of the node where the VM is running.
4. Waiting for the node to change `not-ready` state.
5. While the VM automatically recovers, this takes more than 10 minutes.

**Expected behavior**
Except to use less time to recover the VM.

**Support bundle**
[longhorn-support-bundle_0654c6f1-8452-4cbf-becc-531c7a01703a_2023-06-07T03-17-55Z.zip](https://github.com/harvester/harvester/files/11683478/longhorn-support-bundle_0654c6f1-8452-4cbf-becc-531c7a01703a_2023-06-07T03-17-55Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
After investigation, we found that Kubernetes Controller-Manager must wait 6 minutes to delete the unavailable node VolumeAttachment and create a new node VolumeAttachment. 
Only after CSI detects the new VolumeAttachment will it request the longhorn Volume, fix the status, and remount it to the node where the Pod is located.
https://github.com/kubernetes/kubernetes/blob/da1f52034eb3c405de1ca2dc0e1a6163e8a48f4f/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L216-L293

Kubevirt node's heartbeat doc link:  https://kubevirt.io/user-guide/operations/unresponsive_nodes/#virt-handler-heartbeat

**Workaround**
Reduce the Node CR's heartbeat annotation by more the 5 minutes.
Delete VolumeAttachment before recreating Pod, and it can restore running within 1 minute.

**Relate issue**
LH: https://github.com/longhorn/longhorn/issues/6075

**Comment by chrisho** [comment]
Describe in the documentation more details when to perform a live migration or when to restart/reschedule.

**Comment by albinsun** [comment]
Tested in `master-973a1a9a-head` with `vm-force-reset-policy`=30

In short, in a 3 nodes KVM cluster (8cores/16G/250G for each node),  It takes
1. ~30s from system detects node `NotReady` to VM `ContainerCreating` on new node
2. ~12s from VM `ContainerCreating` to `Running`.

Will give another try with `vm-force-reset-policy`=10 to check whether we can satisfy expected behavior.

## Test Environment
* Harvester
  * version: `master-973a1a9a-head`
  * profile: KVM, 3 nodes (8core/16G/250G for each node)
  * **ui-source**: Auto
* `vm-force-reset-policy`: 30

## Verification Steps
1. Change the setting `vm-force-reset-policy` to 30
2. Create a VM
3. Check nodes and VM are both ready
4. Force power-off VM node
5. Wait system detects Node `NotReady` and record the time.
6. Wait for VM `ContainerCreating` and record the time.
7. Wait for VM `Running` and record the time.

[supportbundle_b4e3671a-465c-4890-9b22-ecd94a21c004_2023-06-28T06-36-19Z.zip](https://github.com/harvester/harvester/files/11891009/supportbundle_b4e3671a-465c-4890-9b22-ecd94a21c004_2023-06-28T06-36-19Z.zip)

## Result
Time records for 3 test rounds
| Round | Node Poweroff -> NotReady  | Node NotReady -> VM Creating | VM Creating -> Running  | |
|---    |---                         |---                           |---|---|
| 1     | ~32s                       | ~30s                         | ~10s  | |
| 2     | ~36s                       | ~30s                         | ~15s  | |
| 3     | ~38s                       | ~30s                         | ~10s  | |
| avg   | ~35s                       | ~30s                         | ~12s  | ~1m15s |

## Note
1. From backend aspect, it takes about 30s from system detects node `NotReady` to VM `ContainerCreating` on new node.
2. For total time
   From Power-off to see VM `Running` on CLI (or `Active` on UI).
   * From backend aspect, takes ~1m15s
   * From UI aspect, it takes 2~3 mins since http session may broken and user need to relogin to check status.
4. test records
   * 1st round

     [backend-test-1.webm](https://github.com/harvester/harvester/assets/2773781/f27c38aa-f0cd-4cb4-9e6a-01f306affb6e)

   * 2nd round
 
     [backend-test-2.webm](https://github.com/harvester/harvester/assets/2773781/eb85550e-3204-4ef3-b35e-3b9199d0fd50)

   * 3rd round

     [backend-test-3.webm](https://github.com/harvester/harvester/assets/2773781/289efaee-2e4b-404c-8bef-5af01fdad8ee)

**Comment by albinsun** [comment]
Tested in `master-973a1a9a-head`. By set `vm-force-reset-policy.period` to 10, VM restarts within 30s (~25.8s in average), verified as fixed.

Note that
1. `vm-force-reset-policy` controls the time to reschedule VM when its node turns to be `NotReady`. ([Ref.](https://docs.harvesterhci.io/v1.1/advanced/settings#vm-force-reset-policy))
2. VM bring-up time (Down -> Running) may vary on different hardware env.

## Test Environment
* Harvester
  * version: `master-973a1a9a-head`
  * profile: KVM, 3 nodes (8core/16G/250G for each node)
  * `vm-force-reset-policy`: `{ "enable": true, "period": 10 }`

## Verification
### Steps
1. Change the setting `vm-force-reset-policy.period` to 10
3. Create a VM
4. Check all nodes and VM are both ready
5. Force power-off VM node
6. Wait system detects Node `NotReady` and record the time.
7. Wait for VM `Running` on new node and record the time.

### Result
Time records for 5 test rounds
| Round | Node Poweroff -> NotReady | Node NotReady -> VM Down | VM Down -> Running  |
|---    |---                        |---                       |---                  |
| 1     | ~39s                      | ~9s                      | ~15s                |
| 2     | ~38s                      | ~10s                     | ~11s                |
| 3     | ~31s                      | ~10s                     | ~23s                |
| 4     | ~43s                      | ~10s                     | ~17s                |
| 5     | ~35s                      | ~9s                      | ~15s                |
| avg.   | 37.2s                     | 9.6s (matches `vm-force-reset-policy.period`)                     | 16.2s (May vary on different env.)  

### Example
[p10-1.webm](https://github.com/harvester/harvester/assets/2773781/9bd9f990-014b-47fe-9d12-778e4d4f86ba)

**Comment by Erick-shi** [comment]
@albinsun 
what's the ui,it's cool!  is it  open source ? can you share it to me?

**Comment by albinsun** [comment]
> @albinsun what's the ui,it's cool! is it open source ? can you share it to me?

Hi @Erick-shi,

Thanks for comment!
Not sure which part you are asking? :laughing: 
Basically they are all utilities on my OpenSUSE KDE desktop.
* Screen recorder is **vokoscreen**, also an opensource application
* Others
  ![image](https://github.com/harvester/harvester/assets/2773781/77c12b05-a817-43fa-945d-2dca76796024)

**Comment by Erick-shi** [comment]
@albinsun  
thank you, all tools is very cool! I can't wait to try these tools anymore      :)
