### ISSUE TITLE
[BUG] restricted  admin listed twice in RBAC user list

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4161]
**Describe the bug**

When you import a Harvester cluster with a restricted admin and then open RBAC in Virtualization management it shows the restricted admin twice

**To Reproduce**
1. Log into  Rancher as restricted admin
2. Import  Harvester into Rancher
3. Navigate to Harvester dashboard through virtualization management
4. Go to RBAC in the sidebar
5. Check for how many times you see restricted admin 
**Expected behavior**

**Support bundle**

[supportbundle_28fde15c-4b22-4193-b531-9f400d14fb46_2023-06-30T19-38-46Z.zip](https://github.com/harvester/harvester/files/11920023/supportbundle_28fde15c-4b22-4193-b531-9f400d14fb46_2023-06-30T19-38-46Z.zip)

**Environment**
 - Harvester ISO version: master-20ca0b3e-head
 - Rancher version: v2.7.5 single node Docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node libviirt VMs

**Additional context**
This doesn't seem to be an issue with admin if you add it.
![Screenshot_20230630_123142](https://github.com/harvester/harvester/assets/83787952/975cf21d-834d-4a67-826c-96a11df22e95)

**Comment by DaiYuzeng** [comment]
Hi @noahgildersleeve! I was able to reproduce the issue by following the steps you provided. I have filed a new issue upstream at: https://github.com/rancher/rancher/issues/42245. I would like to wait for a reply from upstream first. If you have any concerns, please let me know. Thank you!

**Comment by DaiYuzeng** [comment]
cc @WuJun2016 @guangbochen ^^

**Comment by torchiaf** [comment]
> Hi @noahgildersleeve! I was able to reproduce the issue by following the steps you provided. I have filed a new issue upstream at: [rancher/rancher#42245](https://github.com/rancher/rancher/issues/42245). I would like to wait for a reply from upstream first. If you have any concerns, please let me know. Thank you!

should we consider this one as a backend issue ?

**Comment by ihcsim** [comment]
This seems to be a side effect of the restricted admin's permission scope, which by default, includes admin access to all downstream clusters, per https://github.com/rancher/rancher/issues/42245. Since this role will eventually be deprecated, per Rancher's [documentation](https://ranchermanager.docs.rancher.com/v2.10/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#restricted-admin), I am not sure if it's necessary to make any changes on our end to accommodate Rancher's default behaviour.
