### ISSUE TITLE
[BUG] Add Disk Storage Doesn't Decipher Difference Between Drive & Drive's Partitions

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4198]
**Describe the bug**
When adding a disk, in Harvester, if that disk has a formatted partition available - it seems to display the disk twice.

**To Reproduce**
1. Have additional storage available to Harvester (preferably SATA)
1. On Harvester node tty - do something like `sudo fdisk /dev/sdc` - then add partition: `n`, `enter`, `enter`, `enter`, `w` (to write)
1. On Harvester node tty - format that partition, `sudo mkfs.ext4 /dev/sdc1`
1. Navigate to Harvester UI -> Hosts -> Edit Config -> Storage -> Add Disks
1. You'll notice that the disk is displayed twice

**Expected behavior**
To have something that deciphers the UI from a Disk & the Disk's partitions...

**Environment**
 - Harvester ISO version: v1.2-56e9844d-head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell R720

**Additional context**
![Screenshot from 2023-07-06 11-52-31](https://github.com/harvester/harvester/assets/5370752/e9505351-50e8-4548-92e7-0493cf1da521)

**Comment by albinsun** [comment]
Can reproduce in `v1.2.0-rc3`, will verify in `v1.2-head`.

Note that original TC in this ticket is a negtive TC since currently it will fail to add a partitioned disk as storage. (See https://docs.harvesterhci.io/v1.1/host/#multi-disk-management) Thus also add a positive TC in addtion to the original one.


## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: QEMU/KVM, single node (8C/16G/250G)
  * **ui-source**: Auto


## Note
1. May relates to [harvester#3218](https://github.com/harvester/harvester/issues/3218), check if need


## Scenario
### Positive TCs
1. Plug-in formatted disk -> Format again -> Re-Plug
    1. <details><summary>Plug-in disk (ext4 formatted)</summary>
    
       ![image](https://github.com/harvester/harvester/assets/2773781/bb1ebca4-e351-4b5c-b0a1-cbef53dc4fb6)
    
       </details>

    1. Format (mkfs.ext4 & fsck.ext4)

    1. <details><summary>Re-Plug, should have a new disk record $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/4d236e54-80cc-4361-9bf1-6af3a88821e2)
    
       </details>
    
    1. <details><summary>But UI should only see one entry $~~$ :x: $\color{red}{\textsf{See duplicated entries}}$</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/c2b2f1fd-8613-4703-8d99-2d5fcc35a359)

    1. Can add disk :grey_question: 


### Negtive TCs
1. Plug-in formatted disk -> Partition -> Format partition
    1. <details><summary>Plug-in disk (ext4 formatted)</summary>
    
       ![image](https://github.com/harvester/harvester/assets/2773781/8cc7cf32-a66e-4d59-ac41-68c3e24c1240)
    
       </details>
    
    1. <details><summary>Partition, should have new disk records $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/a50b5673-06e1-4bf8-a023-f2c313397c52)
    
       </details>
    
    1. <details><summary>But UI should only see one entry $~~$ $\color{red}{\textsf{See duplicated entries}}$</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/c81d6766-978f-479d-9846-58e8b0d7ea4f)

       </details>

    1. Should fail to add disk (Due to partitioned disk) :grey_question:

**Comment by albinsun** [comment]
Tested in `v1.2-7f87c261-head`, close as fixed.

Note that, in this scenario, original blockdevice record becomes `Inactive` redundant.
For example, in the following positive TC, device `c37a90e9670f39480f1961662bdbf812` is old / redundant / Inactive, the new / Active one is `671d7acf304775470e43b12bd996a753`. They are the same hardware disk but has different NAME due to reformat.
![image](https://github.com/harvester/harvester/assets/2773781/dcfc0b8a-ca26-47af-9883-59ba11242f96)


## Test Environment
* Harvester
  * version: `v1.2-7f87c261-head`
  * profile: QEMU/KVM, single node (8C/16G/250G)
  * **ui-source**: Auto

## Scenario
### Positive TCs
1. Plug-in formatted disk -> Format again -> Re-Plug
    1. <details><summary>Plug-in disk (ext4 formatted)</summary>
    
       ![image](https://github.com/harvester/harvester/assets/2773781/f4467c40-0f90-44df-8663-308948ad0b7e)
    
       </details>
    
    1. <details><summary>Format (mkfs.ext4 & fsck.ext4)</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/13979d29-33b0-431a-901d-a8439f78551d)
    
       </details>
    
    1. <details><summary>Re-Plug, should have a new disk record $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/c8dc397c-e3ea-4cf8-bafe-c1a246e213fd)
    
       </details>
    
    1. <details><summary>But UI should only see one entry $~~$ :heavy_check_mark: </summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/7861bdbe-bba5-4422-8f85-740cd67bb78f)
    
        </details>
    
    1. <details><summary>Can add disk $~~$ :heavy_check_mark:</summary> 
       
       ![image](https://github.com/harvester/harvester/assets/2773781/43d79daf-dc50-4e1b-b470-ff07934d546f)
    
       </details>


### Negtive TCs
1. Plug-in formatted disk -> Partition -> Format partition
    1. <details><summary>Plug-in disk (ext4 formatted)</summary>
    
       ![image](https://github.com/harvester/harvester/assets/2773781/42e56ee2-1926-4ebf-ab45-233b242d4204)
    
       </details>
    
    1. <details><summary>Partition, should have new disk records $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/11148669-992d-4ac7-a0d1-4411db809e06)
    
       </details>
    
    1. <details><summary>But UI should only see one entry $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/6c96ddcf-acfe-4c63-ac6a-c6cf61097173)
    
       </details>
    
    1. <details><summary>Should fail to add disk (Due to partitioned disk) $~~$ :heavy_check_mark:</summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/6e376cdd-3422-405b-b057-3de28fe783cb)
    
       </details>
