### ISSUE TITLE
[BUG] Fail to pack upgrade log: no space left on device

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4222]
### Describe the bug
![image](https://github.com/harvester/harvester/assets/5169694/27c6c1ae-7f80-4d05-803a-622ce94b278d)
![image](https://github.com/harvester/harvester/assets/5169694/0d98369a-f5a4-49ad-8d61-82f33bdc53b5)
![image](https://github.com/harvester/harvester/assets/5169694/341ec10c-7a91-4c7b-beb3-56ca693f44fd)

### To Reproduce
1. Install Harvester with any nodes
2. Perform upgrade[^1]
3. Download upgrade log during upgrade

### Expected behavior
Logs should able to be downloaded

## Environment:
 - Harvester ISO version: **v1.1.2** -> **v1.2.0-rc3**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **QEMU/KVM 3 nodes**

### Additional context
The upgrade started around 6 hours ago, and stuck in pre-draining status.

### Support bundle
[supportbundle_8365a58f-9f55-4480-a460-b46525cc2098_2023-07-12T12-47-59Z.zip](https://github.com/harvester/harvester/files/12028214/supportbundle_8365a58f-9f55-4480-a460-b46525cc2098_2023-07-12T12-47-59Z.zip)

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade

**Comment by bk201** [comment]
cc @starbops, should we increase the volume size? Or is there a way to set the maximum size of logs?

**Comment by starbops** [comment]
The total size of logs generated in regular upgrades shouldn't exceed 1GB, though it's just an estimation. If something is wrong with the upgrade, most of the log lines are repeated, filling up the volume. Increasing the volume size seems not a good solution. Maybe we need to process the log files at a different volume, at least other than the `log-archive` volume.

**Comment by bk201** [comment]
**update** Workaround in the doc PR: https://github.com/harvester/docs/pull/349

A temporary workaround is to expand the volume size to a bigger size (like 10G) in Longhorn GUI and re-download again.
Volume name is in the format `hvst-upgrade-xxxx-upgradelog-log-archive`.

Note if it's an upgrade from 1.1.2 to 1.2.0 and the upgrade doesn't finish yet, online resize is not supported. The user needs to delete these two pods to release the volume once:
- `hvst-upgrade-xxxx-upgradelog-downloader-yyyy`
- `hvst-upgrade-xxxx-upgradelog-infra-fluentd-0`

**Comment by starbops** [comment]
Possible fixes/enhancements are:

- Optimize the log-collecting rules to make them more condensed (get rid of that redundant metadata of each log line)
- Process the log files and store the compressed log archive files at a different volume
- Remove the previously generated log archive files
- Stop unnecessarily packaging log files after the upgrade ends (because the log collection is already stopped, no new logs will flow in), and only serve the one generated after the upgrade ends. The following download requests will result in fetching the same file.

We may also include the volume expansion workaround to make the upgrade log volume explosion less likely to happen.

**Comment by lanfon72** [comment]
I would suggest to document the workaround in `v1.2.0` then we would have more time to discuss how to enhance it.

**Comment by irishgordo** [comment]
@starbops 

This looks good from:
- v1.1-head -> v1.2-head
- v1.1.2 -> v1.2-head

I'll go ahead and close this out :smile: :+1: 

![Screenshot from 2023-08-02 17-38-20](https://github.com/harvester/harvester/assets/5370752/4887ff6a-5c53-4f8e-9378-ecc33ba2d809)
![Screenshot from 2023-08-02 17-08-14](https://github.com/harvester/harvester/assets/5370752/d04b617a-2dc5-4bbe-acdc-555bb6c758e3)
![Screenshot from 2023-08-02 16-30-21](https://github.com/harvester/harvester/assets/5370752/a9dea903-0f05-41c9-838e-76c6fb0044c6)
![Screenshot from 2023-08-02 15-10-53](https://github.com/harvester/harvester/assets/5370752/006c93b7-613a-4986-ae2f-d21e313650f8)

**Comment by starbops** [comment]
Hi @irishgordo, thanks for verifying this ticket. But the two tested upgrade paths only ensure we don't break things (regressions). We also need to test the same version upgrade, i.e., from v1.2-head to v1.2-head, to ensure the fix is working. That's because our upgrade design is a bit tricky: some changes will only take effect after the next version upgrades. Especially the changes in [phase 1 and 2](https://docs.harvesterhci.io/v1.1/upgrade/troubleshooting#diagnose-the-upgrade-flow). However, due to the release timeline, I'd suggest waiting for the RC5 to come out and test with it.

So the test plan should be changed a little bit, as following:
1. Provision a Harvester cluster (single-node is ok) **with v1.2.0-rc5 ISO image**
2. Upgrade the cluster **with the same ISO image**
3. Download the upgrade log archive by clicking the "Download Log" button on the upgrade dialog
4. Check if the content of the downloaded log files is correct
5. Download the upgrade log archive again
6. Find out the fluentd Pod and exec a shell to check the generated archive file. There should be only one archive file, which is the newest (check the timestamp on the filename):
```
$ kubectl -n harvester-system get pods -l harvesterhci.io/upgradeLogComponent=aggregator
NAME                                             READY   STATUS    RESTARTS   AGE
test-upgrade-master-upgradelog-infra-fluentd-0   2/2     Running   0          44s

$ kubectl -n harvester-system exec -it test-upgrade-master-upgradelog-infra-fluentd-0 -c fluentd -- sh

# ls /archive/
```

**Comment by irishgordo** [comment]
@starbops thanks for the insight :smile: :+1: 
Testing from v1.2.0-rc5 -> v1.2.0-rc5 looks good :+1: :smile: 
I'll go ahead and close this out:
![Screenshot from 2023-08-06 19-13-22](https://github.com/harvester/harvester/assets/5370752/3a3ac070-eea2-42b2-bc3e-ab7d8878acb3)
![Screenshot from 2023-08-06 19-08-25](https://github.com/harvester/harvester/assets/5370752/c92a8009-57ce-4e85-b65e-f8a121cd4293)
![Screenshot from 2023-08-06 19-07-56](https://github.com/harvester/harvester/assets/5370752/81d4086a-bed7-42a5-803b-8a2e4a87b578)
