### ISSUE TITLE
[Question] Where is longhorn share-manager?

### ISSUE THREAD

**Issue by cybercoder** [harvester/harvester#4233]
I need to manually ```fstrim``` the filesystem to re-calculate the volume's actual size, according to the Longhorn documentation.
I've updated the longhorn from 1.3.2 ( Harvester 1.1.1 ) to 1.4.2 manually without using UI (because of RWX pvcs).

https://longhorn.io/docs/1.4.2/volumes-and-nodes/trim-filesystem/

But I can't find out the Longhorn share-manager pod:

```kubectl get pods --all-namespaces | grep -i share```
And there's noting!

**Comment by Vicente-Cheng** [comment]
Hi @cybercoder,
Harvester is using the Longhorn volume with iSCSI instead of its RWX volume.
So you do not see the share-manager would be expected.
If you would like to do fstrim, you could try to directly fstrim with the target mountpoint.

e.g. if you have a running VM with longhorn volume as /dev/vdb, you could fstrim with the filesystem that is formatted on vdb.

Or you could share your scenario (like this volume is using with POD or VM), so we could know more about your case.

Thanks!
