### ISSUE TITLE
Change dmidecode manufacturer

### ISSUE THREAD

**Issue by cybaware** [harvester/harvester#4324]
Hi there

i have a VM/iso that queries the manufacturer via dmidecode at boot time. If the vendor/hypervisor is not supported, the image will not boot. On other hypervisors people have simply modified "the manufacturer xml" and then the ISO could be booted. Is this also possible with Harvester?

it is about skyhigh web gateway. They only allow Microsoft hypervisor or Vmware ESXI.

Best Regards
k

**Comment by connorkuehl** [comment]
Hi,

I don't believe this is possible (yet) since this functionality isn't exposed by KubeVirt which Harvester uses to create and run virtual machines.

KubeVirt doesn't seem to surface the "sysinfo" element of the libvirt domain[1][2], so Harvester has no way of supplying this information to the VM.

That said, it looks like the part of KubeVirt that generates the libvirt domain XML[3] _does_ support this field, so it's possible that a patch to KubeVirt upstream to add the "sysinfo" field to the VirtualMachine resource could enable this use-case.

[1] https://libvirt.org/formatdomain.html#smbios-system-information
[2] https://pkg.go.dev/kubevirt.io/api@v1.0.0/core/v1#DomainSpec
[3] https://pkg.go.dev/github.com/kubevirt/kubevirt/pkg/virt-launcher/virtwrap/api#DomainSpec

**Comment by cybaware** [comment]
is something like this not possible?

https://www.srm.im/2015/09/10/mcafee-webgateway-on-kvm/

BR
k

**Comment by ibrokethecloud** [comment]
the easiest way might be to use kubevirt sidecar. I have sample [here](https://github.com/ibrokethecloud/kubevirt-sidecar). This would need to be tweaked to patch the domain definition with the specific customization you need.

**Comment by cybaware** [comment]
Thanks @all.
It is over my time and skills-level to get it running in the foreseeable future. 

I have requested directly at skyhigh (vendor) if they can provide an "unsupported" ISO without vendor-lock.

For now i have installed ubuntu linux on harvesterHCI with virtualbox and run the vm's inside virtualbox. That works.
i also tried to install ESXI Server inside HarvesterHCI. But after i started the ISO inside ESXI i got always a kernel panic (with every linux ISO i tried (ubuntu, debian, kali...)) and i was not able to resolve it. So i tried with ubuntu and virtualbox.

i used the information from the link i posted above to get mcafee / skyhigh web gateway working inside virtualbox.

Best Regards
Luca

**Comment by cybaware** [comment]
i got a hint from the vendor, to bypass the vendor lock for lab purpose. thats my goal. Thank you ALL!
