### ISSUE TITLE
[Question] HA networking with two internet connections

### ISSUE THREAD

**Issue by nastynaz** [harvester/harvester#4325]
Hi all,

I'm in need of guidance on setting up a highly available internet network for an on-premise Harvester/Kubernetes cluster.

Here are the key details:

**Two internet connections:**
  - The primary connection offers a block of unique public IPv4 addresses for each k8s node without requiring NAT.
  -  The secondary connection, however, has just one public IPv4 address and hence, requires NAT.

**Bandwidth**: The primary connection is sufficient for all networking needs and is the preferred choice as long as it's up. If it fails, I want the network to continue running via the secondary internet connection.

**DNS Requirements**: DNS should function from the internet side so all services remain accessible even if the primary connection is down.

The goal is to make the setup as simple as possible while meeting the above requirements. 

So far I've tried various ideas with kube-vip and metallb but I don't understand enough about these technologies to find a working solution.

Thank you in advance!

**Comment by starbops** [comment]
Hi @nastynaz,

If I understand correctly, each node of the Harvester cluster will have a public IP according to your question, right? If that's the case, I wouldn't recommend that since it pretty much exposes a wide range of attack surfaces to the outside world. Usually, we put every node in private networks. If you got multiple NICs on those nodes, you can arrange them to form a management network, a storage network, and a VM workload network. Regarding the accessibility of the Internet, it will be the load-balancer's (or reverse proxy's) job. You can still access the cluster with a public IP. The cluster's stability and security would be much higher.

If you have other concerns, we can discuss them further. Thank you.

**Comment by nastynaz** [comment]
@starbops Thanks for the response.

How does `kube-vip` play into all of this? If I create a new cluster network, does that give me a new VIP that I can point my routers at for public access? If so, is this VIP stable so that if nodes go down it's still the same IP locally?

Do I need to install an external load balancer like MetalLB or can Harvester and the bundled `kube-vip` do what I need?
