### ISSUE TITLE
[Question] Modify image URL using `harvester_image` terraform provider resource

### ISSUE THREAD

**Issue by drmatthews** [harvester/harvester#4331]
I am building `qcow2` format images using Packer, which I would like to make available to Harvester. My workflow is as follows:

1. Build image with Packer
2. Push the `qcow2` artifact to a file server
3. Use the `harvester_image` resource from the Terraform Harvester Provider to add the image to Harvester

This works, but when I do the following:

1. Create a VM in Harvester from an image built with Packer
2. Build a new version of the image with Packer
3. Update the image URL in Harvester using the `harvester_image` resource

The image gets stuck with status "Downloading". If I destroy the VM the image gets updated.

I'm looking for suggestions for how to handle this workflow. Ideally I wouldn't need to keep adding new images every time a new version is built with Packer. And obviously I don't want to destroy VMs to update the image.

Thanks!

**Comment by connorkuehl** [comment]
I think what you're running into here is that virtual machine disks are arranged in "layers", so many virtual machines can share the same "base" and it doesn't need to be duplicated over and over.

This system is preventing any writes to the base image as long as it has virtual machines referring to it as their base since that would damage the integrity of the virtual machine disk contents. 

Because of this, I'm not currently aware of a way to avoid this:

> Ideally I wouldn't need to keep adding new images every time a new version is built with Packer.

I think even if Longhorn (the underlying storage technology for Harvester VMs) supported deleting a backing image while it's in-use and merging the base image into all of the dependent VM disks, it would probably still be more space-efficient to just accumulate all of your old base images, since merging them into their dependent virtual machine disks would be basically replicating the base image by the amount of dependent virtual machine disks (which they themselves are replicated by Longhorn as well 😅 ).

**Comment by drmatthews** [comment]
Hi @connorkuehl - many thanks for your response and the detailed explanation, makes sense.
