### ISSUE TITLE
[ENHANCEMENT] Make it possible for guest cluster Harvester VMs to have different hostnames than their Harvester VM names when using harvester-csi-driver

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4396]
**Is your enhancement related to a problem? Please describe.**

Related to: https://github.com/harvester/harvester/issues/4291

It is possible to configure a Harvester VM with a different hostname than its VM name, then install a Kubernetes distribution onto it, import it into Rancher, and install the harvester-csi-driver. For example, the cloud-init userdata could specify a hostname that is different from the VM name; the Terraform provider also allows users to specify a different hostname from the VM's name.

The trouble is, mounting volumes via the harvester-csi-driver will fail because the harvester-csi-driver will send the VM's hostname to Harvester as a way of identifying itself and Harvester assumes this hostname matches the VM's name. So if the hostname is different from the VM name, the volume hotplug will fail to attach to the expected VM.

**Describe the solution you'd like**

A cluster node running as a Harvester VM does not need its hostname to match the Harvester VM name

| namespace/vm-name | VM hostname | Expected result | Actual result | 
| - | - | - | - |
| default/k3s-1 | prod-k3s | Works | Does not work |
| default/k3s-2 | k3s-2 | Works | Works |

**Describe alternatives you've considered**

**Additional context**

**Comment by connorkuehl** [comment]
Fix is included in latest tagged release of harvester-csi-driver: https://github.com/harvester/harvester-csi-driver/releases/tag/v0.1.6, but that release is not packaged into a Helm chart anywhere, so for testing it will have to be manually installed to the guest cluster.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.

In the test we use cloud provider `Default - RKE2 Embedded` since we observe the cluster can not Active and stuck at `Updating` (`waiting for cluster agent to connect`) when using Harvester cloud provider, trace in another issue #4947.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.9`
  * Profile: Docker (1C/4G)


## Test Steps 
1. <details>
      <summary> Create RKE2 cluster <b>myrke2-embedded</b> with hostname <b>xyz</b> and cloud provider <code>Default - RKE2 Embedded</code>
      </summary>
   
   Refer to [^1]
   ![image](https://github.com/harvester/harvester/assets/2773781/1a15f0dd-7bb2-4247-85d3-caff1e60b89f)
   </details>


1. <details>
      <summary> Rancher -> <b>myrke2-embedded</b> -> Apps -> Charts -> Harvester CSI Driver -> Install (<code>harvester-csi-driver-v0.1.5</code>)
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/ecf4cd9b-6869-4fd6-9c72-1eecfd4e70f0)
   </details>


1. <details>
      <summary> Rancher -> <b>myrke2-embedded</b> -> Storage -> PersistentVolumeClaims -> Create <b>pvc015</b>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f7731d71-05dc-4594-90b5-31433a6e99ba)
   </details>


1. <details>
      <summary> Workloads -> Create -> Deployment nginx w/ <b>pvc015</b>, should FAIL due to node <b>xyz</b> not found :ballot_box_with_check: 
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/10f68f91-6c51-4569-966e-eec752030e04)
   </details>

1. <details>
      <summary> Manually <code>kubectl edit ds harvester-csi-driver -n kube-system</code>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/12bbf6cd-ef72-429c-8837-b616e2117dc5)
   ```
   ...
      image: rancher/harvester-csi-driver:v0.1.6
      imagePullPolicy: Always
   ...
   ```
   </details>


1. In **myrke2-embedded**, manually delete pods `harvester-csi-driver-*` and `harvester-csi-driver-controller-*` and let them redeploy automatically.


1. <details>
      <summary> Check harvester-csi-driver version is <code>v0.1.6</code>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/01a0b25b-bb1c-481a-90ce-1ebdcc9e6f69)
   </details>

1. <details>
      <summary> Rancher -> <b>myrke2-embedded</b> -> Storage -> PersistentVolumeClaims -> Create <b>pvc016</b>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/a031f2b4-8745-481a-b62f-6dd172642452)
   </details>


1. <details>
      <summary> Workloads -> Create -> Deployment nginx w/ <b>pvc016</b>, should SUCCESS :ballot_box_with_check: 
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/5cd4a265-374c-486c-8b1a-abfa79597fb1)
   ![image](https://github.com/harvester/harvester/assets/2773781/38fb7736-44f1-4e89-83bd-66b92d582ed2)
   </details>


[^1]: https://docs.harvesterhci.io/v1.2/rancher/csi-driver#install-csi-driver-manually-in-the-rke2-cluster

**Comment by innobead** [comment]
https://docs.harvesterhci.io/v1.3/rancher/cloud-provider#prerequisites Item 3 in the prerequisites is outdated. This behavior has changed after the introduction of this improvement.

@albinsun can you help with the doc update?
