### ISSUE TITLE
[ENHANCEMENT] Document how to add CSI Driver/Cloud Provider to guest clusters without using Rancher

### ISSUE THREAD

**Issue by andyrue** [harvester/harvester#4446]
**Is your enhancement related to a problem? Please describe.**
There doesn't seem to be a documented way to deploy the Harvester CSI Driver or the Cloud Provider to guest clusters without using the Rancher GUI. I'm trying to avoid running Rancher. We have a small on-prem cluster, and don't have an HA Cluster elsewhere to run Rancher in production, and don't want to pay for a cloud HA cluster just to run Rancher. I'm also scripting the install/config with Terraform, so need to not rely on a GUI for setup.

Right now, these two guides exist, but they both instruct you to interact with the Rancher GUI on more than one occasion to install things.
https://docs.harvesterhci.io/v1.1/rancher/csi-driver
https://docs.harvesterhci.io/v1.1/rancher/cloud-provider

**Describe the solution you'd like**
 I'd like for there to be a guide on how to deploy the CSI Driver/Cloud Provider without needing a Rancher instance. 

**What have I tried**
I've tried manually deploying using the `generate_addon.sh` script and manually deploying the manifests under the manifests folder in the `harvester-csi-driver` github. I end up with a couple errors that I can't get past. Having an official guide for how to do this would be a wonderful addition.

**Comment by connorkuehl** [comment]
Just some notes on my investigation along with the issues I encountered some subsequent workarounds. I advise against using any workarounds in a production cluster if it can be helped.

**Environment**
* Single-node Harvester cluster running v1.1.2
* A pre-existing single-node k3s cluster installed to a Harvester VM ("k3s1") in a namespace called "k8s"

1. Make sure you have the kubeconfig for the Harvester cluster AND the guest cluster available/on-hand.
2. Ensure the following tools are installed: `kubectl`, `jq`, `helm`
3. Pull down the latest `generate_addon_csi.sh` (I used [this one](https://raw.githubusercontent.com/harvester/harvester-csi-driver/9cc40b3b9414bbf792d8624d7a878506bc22bf37/deploy/generate_addon_csi.sh))
4. Make `generate_addon_csi.sh` executable (`chmod +x ./generate_addon_csi.sh`)
5. I am designating `k3s` (first arg) as the service account name, `k8s` (second arg) as the Harvester namespace where the guest cluster resides, and I am passing in `k3s` (third arg) to indicate that this is a `k3s` cluster to the `generate_addon_csi.sh` script
6. Using the **Harvester cluster kubeconfig**: run `./generate_addon_csi.sh k3s k8s k3s`
7. Copy everything from the top of the output until just before `########## cloud-init user data ############`, since I only have 1 Harvester node, I am not going to scale out more guest cluster nodes on top of it, so I don't need the `user-data` script.
8. SSH into the guest cluster node(s) (in my case, the Harvester VM named `k3s1`)
9. Make sure the expected directory structure exists (`mkdir /var/lib/rancher/rke2/etc/config-files`)
10. Paste the contents from step 7 into `sudo mkdir /var/lib/rancher/rke2/etc/config-files/cloud-provider-config`, as this file will be mounted into the harvester-csi-driver containers so that they can communicate with the Harvester cluster for volume allocations
11. Back to the host you are running `kubectl` from: add the `harvester` Helm repo if it is not already added (`helm repo add harvester https://charts.harvesterhci.io`)
12. (**Using the guest cluster kubeconfig**) Install the `harvester-csi-driver` chart (`helm install harvester-csi-driver harvester/harvester-csi-driver -n kube-system`) -- I chose to install mine to `kube-system`.
13. Wait for the install to complete
14. Confirm the `harvester` storage class has been added to the guest cluster:

```console
$ kubectl get storageclasses
NAME                   PROVISIONER              RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path    Delete          WaitForFirstConsumer   false                  5d13h
harvester (default)    driver.harvesterhci.io   Delete          Immediate              true                   56m
```

15. Create a PVC (`kubectl apply -f pvc.yaml`):

```yaml
# pvc.yaml
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: jellyfin-pvc-cache
 spec:
   storageClassName: harvester
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 100Gi
```

| ❌ | `kubectl get pvc jellyfin-pvc-cache` shows as Pending, cis-provisioner logs errors |
| - | - |
| logs | I0825 15:04:53.420648       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"jellyfin-pvc-cache", UID:"601c00bf-31f6-4c43-a1d4-133f85bcb78d", APIVersion:"v1", ResourceVersion:"231133", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "harvester": rpc error: code = Internal desc = Post "https://harv1.local.connorkuehl.net/k8s/clusters/local/api/v1/namespaces/k8s/persistentvolumeclaims": x509: certificate signed by unknown authority |
| ⚠️ | workaround: edit `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` and delete the `certificate-authority-data` line from the cluster section; delete the pvc `kubectl delete pvc jellyfin-pvc-cache` and restart the harvester-csi-driver (`kubectl rollout restart daemonset/harvester-csi-driver -n kube-system` |

16. Try re-creating the PVC (`kubectl apply -f pvc.yaml`)

| ❌ | `kubectl get pvc jellyfin-pvc-cache` shows as Pending, cis-provisioner logs errors |
| - | - |
| logs | persistentvolumeclaims is forbidden: User "system:serviceaccount:k8s:k3s" cannot create resource "persistentvolumeclaims" in API group "" in the namespace "k8s" |
| logs | I0825 15:06:34.871720       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"jellyfin-pvc-cache", UID:"b44ca24b-e167-4af6-a5ee-3cdc3cb8d31c", APIVersion:"v1", ResourceVersion:"231468", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "harvester": rpc error: code = Internal desc = persistentvolumeclaims is forbidden: User "system:serviceaccount:k8s:k3s" cannot create resource "persistentvolumeclaims" in API group "" in the namespace "k8s" | |
| ⚠️ | workaround: I noticed the RoleBinding was created in the **Harvester cluster's** `default` namespace, _not_ the `k8s` namespace where the guest cluster is. So setting your kubeconfig to the **Harvester cluster**'s Kubeconfig, I got the role binding with `kubectl get rolebindings -n default k8s-k3s -o yaml` |
| ✅ | Fixed in https://github.com/harvester/harvester-csi-driver/commit/509123316e6150307e0f9c39b0eaef3e678ad914 |

17. ⚠️ Workaround continued: I took the YAML from above and trimmed it down to this:

```yaml
# rb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-k3s
  namespace: k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: harvesterhci.io:cloudprovider
subjects:
- kind: ServiceAccount
  name: k3s
  namespace: k8s
  ```
  
  18. ⚠️ Workaround continued: then I applied it (**still using the Harvester cluster Kubeconfig**, NOT the guest k3s cluster) `kubectl apply -f rb.yaml`)
  
  19. ⚠️ Workaround continued: then started over with my PVC (**now using guest k3s cluster Kubeconfig**) `kubectl delete pvc jellyfin-pvc-cache` and restart the harvester-csi-driver (`kubectl rollout restart daemonset/harvester-csi-driver -n kube-system` and finally `kubectl apply -f pvc.yaml`
  
  20. Finally, confirm the `pvc` gets properly bound (using guest cluster Kubeconfig):
  
  ```console
  $ kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
jellyfin-pvc-cache   Bound    pvc-f8d4ea5f-59c7-4f54-b742-bcb02688c8b6   100Gi      RWO            harvester      40m
```

21. Confirm it gets mounted to the `k3s1` harvester VM when I update my service deployment's pod spec to use the new pvc as a volume mount.

Sorry for the wall of text, but this is everything I encountered. Now I'll take this to the drawing board to see what our bugs are.

**Comment by andyrue** [comment]
This is fantastic. Thanks so much for taking the time to look into this. I'll try to replicate your steps next week.

**Comment by andyrue** [comment]
I don't know why installing the helm chart wasn't more obvious to me...I had done everything right up until that point. That got things to install without error.

However, on step 7 I'm a little unclear about the `user-data` script. I have 3 Harvester nodes. Should I do something with the `user-data` script? 

On step 15, I didn't see any errors in the harvester `csi-provider` pod, and I didn't have a `csi-provider` pod in my guest cluster. I did find that error under the `harvester-csi-driver` pod on my guest cluster though. I removed the `certificate-authority-data` from both of my nodes and restarted the `harvester-csi-driver` daemonset.

I still see the certificate error in the `harvester-csi-driver` pod, and also when describing the pvc. In the `harvester-csi-driver-controllers` I see a number of lines like this:

```
I0828 13:27:51.676583       1 leaderelection.go:346] lock is held by harvester-csi-driver-controllers-58769c5548-tzrnc and has not yet expired
I0828 13:27:51.676641       1 leaderelection.go:248] failed to acquire lease kube-system/external-resizer-driver-harvesterhci-io
```

I don't know if those were there before or not.

The leader pod logs look happy with just `successfully renewed lease kube-system/external-resizer-driver-harvesterhci-io` logs.

I've reinstalled the helm chart and things are in the same state.

I'm running rke2 with k8s 1.25.12 on a two node setup.

**Comment by connorkuehl** [comment]
> However, on step 7 I'm a little unclear about the `user-data` script. I have 3 Harvester nodes. Should I do something with the `user-data` script?

The user-data script automates the creation of the `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` file inside new VMs that you spin up. So if you plan on spinning up new VMs to serve as nodes in your guest k8s cluster, it could be convenient for you to use it. You can copy and paste that part of the document to a cloud-config template under Harvester Dashboard > Advanced > Cloud Config Templates.

Though if you had to delete the `ca` line from the original file, in this case you'll want to base64 encode the edited file and update the user-data to use that instead, since the current base64 encoded blob there probably contains that `ca` line.

> 
> On step 15, I didn't see any errors in the harvester `csi-provider` pod, and I didn't have a `csi-provider` pod in my guest cluster. I did find that error under the `harvester-csi-driver` pod on my guest cluster though. I removed the `certificate-authority-data` from both of my nodes and restarted the `harvester-csi-driver` daemonset.

Yeah, iirc, if you do `kubectl logs -c csi-provisioner harvester-csi-driver-blah` you should be able to see the logs from the `csi-provisioner` container. If you don't use the `-c` switch, it just picks a container to pull logs from.

> 
> I still see the certificate error in the `harvester-csi-driver` pod, and also when describing the pvc. In the `harvester-csi-driver-controllers` I see a number of lines like this:
> 
> ```
> I0828 13:27:51.676583       1 leaderelection.go:346] lock is held by harvester-csi-driver-controllers-58769c5548-tzrnc and has not yet expired
> I0828 13:27:51.676641       1 leaderelection.go:248] failed to acquire lease kube-system/external-resizer-driver-harvesterhci-io
> ```

I think this is harmless, since another pod is the leader I'm assuming.

> 
> I've reinstalled the helm chart and things are in the same state.

Ah, OK, so still not able to create a PVC?

**Comment by andyrue** [comment]
Ok, good to know about the lock errors. 

Correct, I still get this when describing the PVC.

```
Warning  ProvisioningFailed    2s (x2 over 3s)  driver.harvesterhci.io_harvester-csi-driver-controllers-58769c5548-tzrnc_94d9c132-4e5f-4129-a3a7-152f99e08173  failed to provision volume with StorageClass "harvester": rpc error: code = Internal desc = Post "https://10.3.3.10/k8s/clusters/local/api/v1/namespaces/default/persistentvolumeclaims": x509: certificate signed by unknown authority 
Normal   ExternalProvisioning  1s (x3 over 3s)  persistentvolume-controller waiting for a volume to be created, either by external provisioner "driver.harvesterhci.io" or manually created by system administrator
```

My cloud config file looks like this + the user field which has been omitted.

```
apiVersion: v1
clusters:
- cluster:
    server: https://10.3.3.10/k8s/clusters/local
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: rke2-default-local
  name: rke2-default-local
current-context: rke2-default-local
kind: Config
preferences: {}
```

**Comment by connorkuehl** [comment]
> I'm running rke2 with k8s 1.25.12 on a two node setup.

And just to clarify, both rke2 nodes (which are Harvester VMs) both have the `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` file without the CA line and you ran something similar to `kubectl rollout restart ds/harvester-csi-driver` after copying it to both nodes?

**Comment by andyrue** [comment]
That's correct. Files are identical on both nodes and I restarted the daemonset.

**Comment by connorkuehl** [comment]
@andyrue I went to reproduce the manual install steps again and I didn't run into the "unknown authority" issue. At all, I mean. I didn't have to remove the CA line from the generated kubeconfig for the guest k8s cluster VMs this time around.

IIRC, the only thing that I did differently was I took the kubeconfig YAML straight from the node instead of the web UI (i.e., `harvester-d84cc:~ # cat /etc/rancher/rke2/rke2.yaml`) and replaced the localhost `127.0.0.1`IP with my actual VIP to use with the `generate_addon.sh` script. Off the top of my head, I'm not sure why that changed my experience. I'll try and dig a bit deeper later.

Not sure if your configuration is still stuck or if you have the appetite to keep debugging after all this time, but thought I'd throw it out there anyway.

**Comment by connorkuehl** [comment]
![image](https://github.com/harvester/harvester/assets/5227338/0c260ea9-fb10-41f6-8ac0-281fdb5d24ce)

**Comment by IQNeoXen** [comment]
Thanks so much @connorkuehl, worked great :)

**Comment by hoo29** [comment]
To help improve SEO, I had PVCs forever stuck in pending with the PV never appearing. The only logs I could find were in the `harvester-csi-driver-controllers` which said

```text
I0404 13:29:37.596394       1 controller.go:291] Started PVC processing "default/my-pvc"
W0404 13:29:37.596410       1 controller.go:318] PV "" bound to PVC default/my-pvc not found
```
and then nothing else was logged.

Doing this fixed it for me:

> IIRC, the only thing that I did differently was I took the kubeconfig YAML straight from the node instead of the web UI (i.e., `harvester-d84cc:~ # cat /etc/rancher/rke2/rke2.yaml`) and replaced the localhost `127.0.0.1`IP with my actual VIP to use with the `generate_addon.sh` script. Off the top of my head, I'm not sure why that changed my experience. I'll try and dig a bit deeper later.

**Comment by ganawaj** [comment]
> @andyrue I went to reproduce the manual install steps again and I didn't run into the "unknown authority" issue. At all, I mean. I didn't have to remove the CA line from the generated kubeconfig for the guest k8s cluster VMs this time around.
> 
> IIRC, the only thing that I did differently was I took the kubeconfig YAML straight from the node instead of the web UI (i.e., `harvester-d84cc:~ # cat /etc/rancher/rke2/rke2.yaml`) and replaced the localhost `127.0.0.1`IP with my actual VIP to use with the `generate_addon.sh` script. Off the top of my head, I'm not sure why that changed my experience. I'll try and dig a bit deeper later.
> 
> Not sure if your configuration is still stuck or if you have the appetite to keep debugging after all this time, but thought I'd throw it out there anyway.

I ran into this issue as well with a Talos guest cluster, and just used the kubeconfig from the node itself which worked. I'm assuming if its done this way, there's no need to even use the generate_addon_csi.sh script since it's not connecting as the service account it creates. 

The Helm install was enough for the Talos cluster with the kubeconfig from the node, I'm assuming its the same for K3s or any cluster
