### ISSUE TITLE
[BUG] Multi Cluster Button Styles

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4469]
**Describe the bug**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU5XIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4bd9b05913d8bb4c29f612edb41b02e525558b80/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVZXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27fb8575ac92896941b05ea36f3d8fb4b348b00e/image.png)

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by torchiaf** [comment]
The issue is visible only when using Harvester as Rancher embedded plugin; Other UI elements are impacted, not only buttons gap.

![image](https://github.com/harvester/harvester/assets/26394656/06cb47b0-15d6-43ea-9e74-7f2265d58c93)

Found other examples:

![image](https://github.com/harvester/harvester/assets/26394656/6d09de20-279c-421a-ae4b-771c5de1a46d)

![image](https://github.com/harvester/harvester/assets/26394656/a9011eae-5e55-4971-9e90-5a2892f2225a)

![image](https://github.com/harvester/harvester/assets/26394656/21603b80-e25d-4372-82ad-228acb5f1c51)
