### ISSUE TITLE
[BUG] VMDP Image wrong after upgrade to Harvester 1.2.0

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#4534]
**Describe the bug**
Have a windows 2022 VM deployed on top of harvester 1.1.x and then upgrade to Harvester 1.2.0.
VM does NOT start anymore, because the VMDP image assigned is [registry.suse.com/harvester-beta/vmdp:latest](http://registry.suse.com/harvester-beta/vmdp:latest) which is not available air-gapped at all and which is not included in the list of harvester images for harvester 1.2.0.

**To Reproduce**
Create Windows 2022 VM on Harvester 1.1.x and then upgrade harvester to 1.2.0.
Stop and start the VM.

**Expected behavior**
- the tag :latest must not be used at all (requires registry connection and is not reproducible / immutable)
- the image used should be part of the harvester image list so we can add it to the on-premises registry
- we should have a central configuration place to manage the VMDP images used in the environment

**Environment**
 - Harvester ISO version: 1.2.0 (upgrade from 1.0.0 over all intermediate versions to 1.2.0)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): not relevant

**Comment by FrankYang0529** [comment]
Hi @Martin-Weiss, we've changed vmdp image from `latest` to a number version since v1.1.0 ([ref](https://github.com/harvester/harvester/commit/088a020fcd47f3e477a62bb725170c8bd3bf3aaa)). Currently, the vmdp on v1.2.0 harvester is `registry.suse.com/suse/vmdp/vmdp:2.5.4.2`. Could you try to update `virtio-container-disk` in your VM to see whether the VM can be started?

**Comment by FrankYang0529** [comment]
Hi @guangbochen, do you know whether there is mapping between virt-operator and vmdp? For example, virt-operator `0.54.0-150400.3.16.1` needs to use vmdp `2.5.4.2`? If yes, I think we may need a controller to auto update vmdp version for windows VM.

cc @bk201

**Comment by guangbochen** [comment]
VMDP [v2.5.4.2](https://github.com/SUSE/vmdp/releases) is the latest release from the SUSE and it is fully compatible with the current kubevirt v0.54.0 version. Because the VM template follows immutable design so we didn't manage to update the old template to a newer version during the Harvester upgrade, and users will only get the more recent template version in the newly installed Harvester cluster. 

Please consider adding new template during the Harvester upgrade in the future version where applicable; for now, I would suggest we document this limitation on the Harvester doc first; thank you!

**Comment by Martin-Weiss** [comment]
Manually changing the image is a working workaround. But I would expect this either to happen automatically or have something in the upgrade documentation.
And - it seems the image has changed on the VM during an upgrade "automatically" in a wrong way.. that should not have happened.

**Comment by FrankYang0529** [comment]
> Please consider adding new template during the Harvester upgrade in the future version where applicable; for now, I would suggest we document this limitation on the Harvester doc first; thank you!

Yeah, good suggestion. I think we can have a new field `forceRenewDefaultTemplate` on `Upgrade` CRD. If the option is true, we remove old templates and add new one. @bk201 WDYT?

**Comment by FrankYang0529** [comment]
> And - it seems the image has changed on the VM during an upgrade "automatically" in a wrong way.. that should not have happened.

@Martin-Weiss, I can create a Windows VM with `registry.suse.com/harvester-beta/vmdp:latest` container disk on harvester v1.2.0, so we don't need to add a function to automatically update `registry.suse.com/harvester-beta/vmdp:latest` to `registry.suse.com/suse/vmdp/vmdp:2.5.4.2` in existing VMs. The root cause here is that the old image is not available cause of garbage collection.

![Screenshot 2023-09-25 at 3 48 03 PM](https://github.com/harvester/harvester/assets/4927361/58b3fdd6-8d85-4ce5-86cc-8e61c076f4c2)

**Comment by FrankYang0529** [comment]
Currently, harvester doesn't automatically udpate any VM images during the upgrade. The Windows VM may be created before harvester v1.1.0, so the vmdp image is `latest` in it. We used vmdp `latest` in templates before harvester v1.1.0. We have changed it since v1.1.0 (https://github.com/harvester/harvester/commit/088a020fcd47f3e477a62bb725170c8bd3bf3aaa).

**Comment by Martin-Weiss** [comment]
So pre 1.1.0 registry.suse.com/harvester-beta/vmdp:latest was the default? Then we fixed it and did not document this as a mandatory change?
Maybe it is sufficient to document this and for the future add a global setting to change this centrally for all windows VMs?

**Comment by FrankYang0529** [comment]
> So pre 1.1.0 registry.suse.com/harvester-beta/vmdp:latest was the default?

Yes

> Then we fixed it and did not document this as a mandatory change?

Added it to known issue list. (https://github.com/harvester/docs/pull/460)

> for the future add a global setting to change this centrally for all windows VMs?

This is a good idea, so users don't need to add it. However, we don't have a field on `VirtualMachine` CR to indicate whether a VM is Windows. We may be able to leverage the `harvesterhci.io/os` annotation, but the field is optional.

**Comment by bk201** [comment]
Document published:
- https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#8-the-registrysusecomharvester-betavmdplatest-image-is-not-available-in-airgapped-environment
- https://docs.harvesterhci.io/v1.3/vm/create-windows-vm#volumes-tab
