### ISSUE TITLE
[BUG]  Support Bundle missing metadata information in metadata.yaml

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4630]
**Describe the bug**
metadata.yaml in the support bundle is missing content.
It does not have the `issuedescription` for instance if user inputs on web gui modal.

**To Reproduce**
1. Go to generate support bundle
1. Fill out "description"
1. Look at metadata.yaml in zip file - `issuedescription` is entirely empty

**Expected behavior**
Metadata to be transferred from the Web GUI's request payload:
```json{
  "apiVersion": "harvesterhci.io/v1beta1",
  "type": "harvesterhci.io.supportbundle",
  "kind": "SupportBundle",
  "metadata": {
    "name": "bundle-qfp4a",
    "namespace": "harvester-system"
  },
  "spec": {
    "issueURL": "",
    "description": "issue description show up?"
  }
}
```
(which look accurate according to [support bundle creation spec](https://docs.harvesterhci.io/v1.2/api/create-namespaced-support-bundle))
With curl example being something like:
```
curl 'https://192.168.9.115/v1/harvester/harvesterhci.io.supportbundles/harvester-system' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'x-api-csrf: 6eceae0afbadf9ed87444a3167977992' -H 'Origin: https://192.168.9.115' -H 'Connection: keep-alive' -H 'Referer: https://192.168.9.115/dashboard/harvester/c/local/support' -H 'Cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; CSRF=6eceae0afbadf9ed87444a3167977992; R_SESS=token-zxk27:dxws7vqnb49trnbmvvhm84pxlgbzvp5wcr94s25hh6sxsdlsjl7pdx' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '{"apiVersion":"harvesterhci.io/v1beta1","type":"harvesterhci.io.supportbundle","kind":"SupportBundle","metadata":{"name":"bundle-qfp4a","namespace":"harvester-system"},"spec":{"issueURL":"","description":"issue description show up?"}}'
```
With the "expectation" that the `metadata.yaml` in the zip would look something like:
```yaml
bundlename: ""
bundleversion: 0.1.0
kubernetesversion: v1.25.9+rke2r1
projectnamespaceuuid: 09c663e9-9569-4362-9a3e-cc3a2d703f01
bundlecreatedat: "2023-10-18T00:48:22Z"
issueurl: ""
issuedescription: "issue description show up?"
```
Versus, the `issuedescription` in the metadata.yaml being empty, which it is in its current implementation.

**Environment**
 - Harvester ISO version: v1.2.1-rc1
 - Underlying Infrastructure: Dell PowerEdge R720

**Additional context**
![Screenshot from 2023-10-17 17-53-00](https://github.com/harvester/harvester/assets/5370752/4faf6864-0021-419d-a4b6-4e8d05ce8202)

**Comment by bk201** [comment]
@Yu-Jack Please help verify if that's a backend issue, thanks

**Comment by Yu-Jack** [comment]
@bk201 

Yes, it's backend issue because we didn't really fetch CR from k8s. Instead, we got the empty CR we created. Here is code. 

caller 
https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/cluster.go#L46-L59

callee
https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/local_state.go#L16-L28

I think we could make use of k8s api to fetch CR back? But, I'm testing whether it could correctly use k8s api to fetch or not.

---

There is another issue I found about additional printer column issue in harvester project. Here is code.
https://github.com/harvester/harvester/blob/6da66dc6f7bdebf43bd4932eb5128642ec397e51/deploy/charts/harvester-crd/templates/harvesterhci.io_supportbundles.yaml#L23

It should be `.spec.issueURL`. So, I tested it.

Before
![image](https://github.com/harvester/harvester/assets/6960289/5b20f129-e7b2-4497-a680-983e73f15ecb)

After
![image](https://github.com/harvester/harvester/assets/6960289/3a2e39e3-f08b-48fd-a108-8ead0155c14e)

I could open PR later for second issuse.

**Comment by Yu-Jack** [comment]
Update:
Because longhorn-manager also uses the support bundle and has different group of support bundle which is not same as harvester, so we can't just use k8s api to fetch resource. Instead, we pass those information as ENV to make support bundle kit could get right information from harvester or longhorn-mananger.

---
@bk201 I wrote a quick POC to prove it works with k8s api `k.clientSet.RESTClient().Get()`.

![image](https://github.com/harvester/harvester/assets/6960289/ddc5f7cd-1e32-445d-bcbd-cd2bc76ef61a)

After I traced the checking progress flow [1] , I think we could remove [LocalStore](https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/local_state.go) and just use k8s api to fetch CR back because we only invoked api to fetch SupportBundle once. If we have requirement to store locally, we could add it back. For now, it's not used for this situation.
https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/manager.go#L253-L255

**However, I do have a question** about why checking state here https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/manager.go#L177-L185 ? Is that because time lag between creating time of support bundle CR and creating time of support-bundle-kit manager? For example, if support-bundle-kit manager is deployed fast than support bundle CR, the manager couldn't find any support bundle, then need to create fake one? I believe there must be a reason why checking state there.

[1] Just memo, currently, harvester will call support-bundle-kit `/status` to know progress which is from local variable called [`ManagerStatus`](https://github.com/rancher/support-bundle-kit/blob/master/pkg/types/types.go#L39-L46).  After harvester got the progress, harvester will update progress of SupportBundle.

**Comment by irishgordo** [comment]
@bk201  - _to mention,_ I also additionally tested this on:
- v1.2.0
- v1.1.2
- v1.1.1
- v1.1.0
( and currently stopped at v1.1.0)

Example, screenshot, from older version: 

![Screenshot from 2023-10-19 18-47-06](https://github.com/harvester/harvester/assets/5370752/333de463-3d75-495e-8e4b-d25dbe19bed9)

This seems to be present as far back as v1.1.0 release -but have not tested any releases prior to v1.1.0, currently.
I'm not sure if this is a regression because I've not tested older versions, but I will be adding that as a label, and we can remove later if it is not :smile:.

**Comment by irishgordo** [comment]
![Screenshot from 2024-01-30 14-06-02](https://github.com/harvester/harvester/assets/5370752/36c1b12b-c588-4844-962f-a622505c1c72)

This looks good on v1.3.0-rc1 -I'll go ahead and close this out :smile:
