### ISSUE TITLE
[BUG] S390x Drone runner is facing a `Timeout exceeded` error with the support-bundle-kit

### ISSUE THREAD

**Issue by c3y1huang** [harvester/harvester#4642]
**Describe the bug**
S390x Drone runner is facing a `Timeout exceeded` error with the support-bundle-kit. Our retries haven't been successful. https://drone-publish.rancher.io/rancher/support-bundle-kit/210/3/2

**Additional context**
- https://github.com/longhorn/longhorn/issues/6922
- https://github.com/longhorn/longhorn/pull/6920#issuecomment-1774310775

**Comment by innobead** [comment]
@Anarkis Can you help with this? Thanks.

**Comment by innobead** [comment]
cc @bk201 @markhillgit @rebeccazzzz  if having any issues related to s390x, @Anarkis should be able to help.

**Comment by Anarkis** [comment]
- Restarted the build: https://drone-publish.rancher.io/rancher/support-bundle-kit/212/3/2
- forked the repo and modified it (just for s390x ) http://drone-pr.rancher.io/Anarkis/support-bundle-kit/1/1/2

None of the pipelines are failing for the previous reason. 
```
--- PASS: TestVerifyNode (0.58s)
PASS
ok  	github.com/rancher/support-bundle-kit/pkg/simulator/objects	10.598s
FAIL
time="2023-10-23T07:14:49Z" level=fatal msg="exit status 1"
```
Due to the lack of information about the error. I'm starting a bunch of test to know if we face another issue where we can start working on

**Comment by ivan-claire** [comment]
After re-running the pipeline with --verbose and increasing the timeout to 15mins:

https://drone-publish.rancher.io/rancher/support-bundle-kit/222/3/2
I got :
`golangci-lint run --timeout 15m --verbose`

```
Running: golangci-lint run
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/rancher/support-bundle-kit /go/src/github.com/rancher /go/src/github.com /go/src /go / /root]"
level=info msg="[lintersdb] Active 7 linters: [errcheck gosimple govet ineffassign staticcheck typecheck unused]"
level=info msg="[loader] Go packages loading at mode 575 (files|imports|name|deps|exports_file|types_sizes|compiled_files) took 5m55.98238502s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 12.860045ms"
level=info msg="[linters_context/goanalysis] analyzers took 8m29.785592286s with top 10 stages: buildir: 4m23.447226294s, printf: 1m1.927057658s, ctrlflow: 1m0.879506586s, fact_deprecated: 55.031872683s, nilness: 18.976550077s, typedness: 14.969956081s, fact_purity: 14.624954938s, SA5012: 13.967834522s, inspect: 5.474887403s, S1038: 174.048938ms"
level=info msg="[runner] Issues before processing: 41, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): skip_files: 41/41, skip_dirs: 41/41, autogenerated_exclude: 40/41, filename_unadjuster: 41/41, path_prettifier: 41/41, identifier_marker: 40/40, exclude-rules: 0/40, cgo: 41/41, exclude: 40/40"
level=info msg="[runner] processing took 2.162905ms with stages: path_prettifier: 905.937µs, identifier_marker: 725.955µs, autogenerated_exclude: 270.385µs, skip_dirs: 122.664µs, exclude-rules: 118.826µs, cgo: 7.587µs, filename_unadjuster: 4.172µs, nolint: 1.616µs, max_same_issues: 1.544µs, skip_files: 618ns, uniq_by_line: 563ns, path_shortener: 452ns, exclude: 421ns, sort_results: 418ns, diff: 418ns, max_from_linter: 319ns, source_code: 315ns, severity-rules: 297ns, max_per_file_from_linter: 295ns, path_prefixer: 103ns"
level=info msg="[runner] linters took 5m17.982444146s with stages: goanalysis_metalinter: 5m17.979557292s"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 6741 samples, avg is 662.5MB, max is 2096.6MB"
level=info msg="Execution took 11m13.990657456s"
```

- `golangci-lint ` times out when running 7 linters and because by default the number of go routines it runs concurrently depends on the number of CPU cores we have, I've increased the number of minimum  CPUs on the S390x VM ` 4 to 8` .  Hopefully, this help.

- Also, it took 11minutes to run, so maybe increasing the timeout to 15mins will help as well.

**Comment by c3y1huang** [comment]
Any update on this?

**Comment by Yu-Jack** [comment]
Because I also ran into this issue, so I could provide some information and experiment. 

I accidentally opened another duplicated issue here https://github.com/rancher/support-bundle-kit/issues/82 and tested it in this [PR](https://github.com/rancher/support-bundle-kit/pull/83). 

According to the build failed of [233](https://drone-publish.rancher.io/rancher/support-bundle-kit/233) and [234](https://drone-publish.rancher.io/rancher/support-bundle-kit/234), I try to increase timeout of pkg/simulator/etcd/etcd_test.go and golangci-lint to see what happens in that PR, and It worked. 

However, I also tried without any modification in build [238](https://drone-publish.rancher.io/rancher/support-bundle-kit/238), it also worked somehow. But, it didn't build successfully in previous build 231~234. I'm not sure why and that's my trying about this issue.

I think the reason it works somehow because of CPU froms 4 to 8.

**Comment by Anarkis** [comment]
All the issues that we are facing `support-bundle` and `longhorn-engine` are related to the new configuration of the new `s390x` runners.
We are working on it to solve permanently

**Comment by Anarkis** [comment]
Pipelines are working properly (at the moment) https://drone-publish.rancher.io/rancher/support-bundle-kit/239/3/3

Contacted with the person in charge of the `s390x` runners, and shared that we need to go back to the previous config ( to solve future problems).

Will leave this issue open until the change is done.

Please @c3y1huang ping me if you face another time this issue

**Comment by Anarkis** [comment]
Closing the issue. The root cause is known and it has been fixed. More info in https://github.com/longhorn/longhorn/issues/6975
