### ISSUE TITLE
[Question] When will 1.2.1 be available from the Dashboard?

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4665]
When will 1.2.1 be available from the Dashboard?

Is there a status page to chek from my pc when it gets available / is there a way to get new release-info via email (not github release, but "public/ from dashboard")

**Comment by devclef** [comment]
I don't know about when it becomes available automatically -- or a way besides following this repo on github to be notified of a release as a person.

As for harvester itself showing the upgrade button. For me I always use the air gapped method to start it. Specifically kubectl create -f $url for the release. Or create the local file and inspect contents if uncomfortable passing in an external URL on the create command.

Like so;
`kubectl create -f https://releases.rancher.com/harvester/v1.2.1/version.yaml`


I tried in the v1.2.0 release to find a way to trigger harvester itself to notice a 'new' release, but ended up using the above method. 

I assume this is OK, but if someone states otherwise can edit and remove this :)

**Comment by ne0YT** [comment]
@slackspace-io did it go through for you?
I'm sitting at 50% on Upgrading System Service since 5 hours

Upgrading Node is at 0%

Log Download Status:
failed to package the logs

**Comment by Vicente-Cheng** [comment]
Hi @ne0YT, could you try to get the support bundle for your issue?

Reference: https://docs.harvesterhci.io/v1.2/troubleshooting/harvester/#generate-a-support-bundle

**Comment by ne0YT** [comment]
@Vicente-Cheng 
The Cluster I told you about:
direct upload is not possible (25MB limit):
https://transfer.sh/Gt2ESQO0up/supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-10-30T09-57-19Z.zip
and ther's another Cluster (3 nodes) which is also not updating correctly:
first node is updated 100%
2nd node is on Pre-drained since more than 12 hours
System Service is updated 100%
[hvst-upgrade-4sqzs-upgradelog-archive-2023-10-30T09-59-26Z.zip](https://github.com/harvester/harvester/files/13203788/hvst-upgrade-4sqzs-upgradelog-archive-2023-10-30T09-59-26Z.zip)

- a third Cluster went through without any problems.

**Comment by devclef** [comment]
Hi,

Perhaps not the right ticket to add, but to answer your question.

I did have some issues upgrading. Though generally covered by the troubleshooting docs.  Namely around longhorn replicas/instance managers, and SSL/IP SAN issues.

I was one of the reports in 1.2 about the SSL/Cert challenges. I was not surprised when I ran into an issue with SSL. My cluster had embedded rancher enabled, no SSL configured on Harvester itself and only Rancher configured. During upgrade I added SSL params to harvester. 

I did later notice errors being reported in journalctl about rancher complaining about IP SAN issues. The fix was actually editing a local json file to use the hostname and not IP.  Did not confirm if were always present or after I changed SSL settings. I do recall I did not see any errors in any kubectl logs I had checked, and was 'by chance' I did journalctl --since today and saw the looping rancher failing. I did some random grep-for-harvester-ip in various folders until I found a config which an IP.  I can file a bug for this, but thought maybe bad config on my side/did not do any effort to reprorduce. 

Otherwise I had some issue with single replicas stalling nodes (I think anyway). I had shut down these workloads, but at some point concluded they may of been a problem. So I increased their replicas. To be honest, I don't know for a fact it was the problem or not. Was just something harmless to try.


Few unasked for tips beyond the troubleshooting page itself.

- I checked the cluster under More Resources within Harvester's built in rancher or can use kubectl cli if you prefer. That told me some clues which nodes were unhappy. 
- Checking the fleet-local namspace. Specifcially secrets and their annotations can tell you about pre/post drain status of a given node. These annotations is how the node does the pre/post drain steps(I think..)
- tail -f /var/log/containers/* on a problem hv node, looking for clues
- journalctl -f did show things like local rancher failing to connect.
- Checking bundles with kubectl to see if any stuck or transitioning
- Regularly checking for any new pods/jobs with 'upgrade' in their name, and then following them.
- kubectl -f on cattle system rancher logs, tends to be chatty when thing are upset :)



My upgrade mainly got stuck on the second node. Which I impatiently restarted before finding some of the issues above after I had 'given up' finding clues in any of the logs. Then restarting upgrade would hang on first  node and never trigger jobs(or complain lack of). The next day I actually used some pre/post drain kubectl commands to step the upgrade through twice until all nodes returned complete and the upgrade claimed done. Since the first time it started on the second node, not first, which lef tthe install 75% done. So I killed it again, restarted, and then things ran after a single manual kick. I can't recommend my upgrade approach, but i can say i have learned allot how the upgrade works... :)


(I run harvester at home on miniPCs, so far from a enterprise setup. Perhaps I should open bugs but since I am running a non-enterprise setup I often assume quirks are due to non-enterprise hardware/my ignorance and just work through them:X)

**Comment by devclef** [comment]
> @Vicente-Cheng The Cluster I told you about: direct upload is not possible (25MB limit): https://transfer.sh/Gt2ESQO0up/supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-10-30T09-57-19Z.zip and ther's another Cluster (3 nodes) which is also not updating correctly: first node is updated 100% 2nd node is on Pre-drained since more than 12 hours System Service is updated 100% [hvst-upgrade-4sqzs-upgradelog-archive-2023-10-30T09-59-26Z.zip](https://github.com/harvester/harvester/files/13203788/hvst-upgrade-4sqzs-upgradelog-archive-2023-10-30T09-59-26Z.zip)
> 
> * a third Cluster went through without any problems.

A quick glance while on lunch, did you solve these errors?
_evicting pod longhorn-system/instance-manager-e-14dff6ee60579247d175c4a14a89a212
error when evicting pods/"instance-manager-e-14dff6ee60579247d175c4a14a89a212" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
error when evicting pods/"instance-manager-r-14dff6ee60579247d175c4a14a89a212" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
(END)_


They were in this log, cattle-system.rancher-78875cd4b4-2splt.rancher.20231030.log at the end and appears to be the latest file provided. So I'd assume this error is still occurring and not fixed?

I see them in your latest rancher logs. There is steps on the troubleshooting page to determine the cause and fix. I'd also recommend the check.sh script.  --- https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#5-an-upgrade-is-stuck-in-the-pre-drained-state

**Comment by ne0YT** [comment]
> 2nd node is on Pre-drained since more than 12 hours
This Cluster went through afte rI rebooted the 2nd node forcefully using ssh.

The other cluster with the initial problem is still not going through

**Comment by ne0YT** [comment]
@slackspace-io how would you fix it?

**Comment by devclef** [comment]
> @slackspace-io how would you fix it?

I'd check your cattle system rancher logs to see if that disruption is still present, if iti s, that is absolutely a reason why your upgrade is not porgressing.  -- kubectl logs deployment/rancher -n cattle-system 

If you have those errors, or others. I'd follow the steps on that page. A bit tedious, but checking to see which scenario you have going on. You do need to adjust the commands to use your hostnames, pod names, etc. 

I'd run the check.sh script listed to see if any replicas are single. Unless a reason not to, i'd increase them to 3 replicas instead of shutting down the workload. 

I'd exhaust every documented troubleshooting step -- .using the steps to see if you are experiencing the issue even if I don't think i'm having that problem -- to rule it out.  If I've checked all of that and still broken either open a ticket here for help or start being more creative/risky depending on sensitiveness of said cluster :)

I would **not** restart an upgrade beyond the safe point. I would continue digging or waiting for feedback to find the issue or be advised before i'd restart an upgrade that is beyond the 'safe' point per docs.

**Comment by ne0YT** [comment]
the issue went away by rebooting and clicking maintenance mode and uncordoning / cordoning.. 
I let it sit to update for 12 hours initially uninterrupted.. Interrupting it fixed it smh, Idk how.. but now they all report as updated successfully.
