### ISSUE TITLE
[BUG] Can't use data disk measured in terabytes v1.2.1

### ISSUE THREAD

**Issue by MikeTolkachev** [harvester/harvester#4734]
I'm trying to use 4TB nvme drive for data disk and i receive a message:
Disk size is to small. Minimum 100Gi is required.

![photo_2023-11-16_20-15-38 (2)](https://github.com/harvester/harvester/assets/7092820/d5e8a65a-5b38-41fa-890f-dc83303dbc32)

**Comment by connorkuehl** [comment]
What size is your install disk?

**Comment by MikeTolkachev** [comment]
Disk is 120Gi (111 on picture). 
Installation is available if I select the first disk (120) for both installation and data.
![photo_2023-11-16_20-15-38](https://github.com/harvester/harvester/assets/7092820/a9f3c1ce-1d05-4b03-a9c8-ddc9d2958351)

**Comment by tserong** [comment]
I've tried to reproduce this, and I believe you're seeing that error not because of the 4TiB data disk, but because the installation disk is too small. In my testing, v1.2.1 needs at least a 180GiB installation disk if you have a separate data disk.

Here's what I got when I tried a 4TiB data disk:

![harvester-4tb-data-disk](https://github.com/harvester/harvester/assets/754700/0f298620-0748-42d5-b209-e9b57c1362db)

I realise that in your second screenshot (with the installation disk and data disk the same) it doesn't show an error, but what happens if you hit ENTER at that point to try to commence the install? In my case, I don't see an error immediately, but once I hit ENTER on the persistent size field, with a single 120GiB disk, I get the error "Disk size is too small. Minimum 250Gi is required":

![harvester-120g-install-disk](https://github.com/harvester/harvester/assets/754700/642c9461-c6ba-4fc8-8ace-b53592c1bb15)

**Comment by tserong** [comment]
Assuming I'm correct about the above, I suspect we need to make two changes:

1. For clarity, make the error say "Installation disk is too small", rather than "Disk is too small".
2. When using the installation disk for data, ensure the error message appears early, rather than waiting 'til the user hits ENTER at the end.

**Comment by irishgordo** [comment]
This looks good on v1.3.0-rc1 :smile: :+1: 
I'll go ahead and close this out:
![Screenshot from 2024-01-29 10-48-07](https://github.com/harvester/harvester/assets/5370752/85de3107-75f5-4d27-92a9-eac42bda237b)
