### ISSUE TITLE
[FEATURE] Import Windows servers vmdk files for VMware VM machines to Rancher Harvester

### ISSUE THREAD

**Issue by TeomPython** [harvester/harvester#477]
1. It will be extremely helpful to have an option to assign IP, subnet and gateway during initial install of Harvester iso install on a bare-metal server with no DHCP. 
2. Under create new machine option to import Windows servers vmdk files for VMware VM machines to Rancher Harvester.

**Comment by guangbochen** [comment]
the first issue will be tracked on https://github.com/rancher/harvester/issues/367, and for the second one, personally, I think this is a nice feature, but since u can convert the `vmdk` image to `qemu-kvm` supported image format like qcow2, raw so this should be achievable from client-side, but will consider to add it as an enhancement, thanks.

**Comment by yasker** [comment]
The first request has been implemented. The second request is tracked in #2274 . Feel free to follow up with #2274 to see the progress on importing VMDK files.
