### ISSUE TITLE
[Question] How to configure WiFi

### ISSUE THREAD

**Issue by oxr463** [harvester/harvester#480]
I have a Lenovo Mini PC that I installed harvester on. During the installation, I selected `wlan0` for my management interface, but it never allowed me to configure it.

**Comment by yaocw2020** [comment]
Harvester is based on K3OS, which use `connman` to manage network configurations.

**Comment by oxr463** [comment]
I tried the following steps, but they did not work:

1. Create `/etc/wpa_supplicant/wpa_supplicant.conf` file with the following contents:

```txt
ctrl_interface=DIR=/run/wpa_supplicant GROUP=wheel
update_config=1
```

2. Run the following command to start the `wpa_supplicant` daemon:

```sh
wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf
```

3. Use `wpa_cli` to configure network:

```sh
wpa_cli
> scan
> scan_results
# no results listed
> add_network
0
> set_network 0 ssid "[ . . . REDACTED . . . ]"
> set_network 0 psk "[ . . . REDACTED . . . ]"
enable_network 0
0K
```

When I ran `ip a` I saw that the interface was still DOWN. I also don't see much in the `dmesg` output.

**Comment by withinboredom** [comment]
Steps to get wifi working, for anyone who wants to know.

1. Switch to the terminal (ctl+alt+f2)
2. Start connmanctl: `sudo connmanctl`
3. Enable wifi: `enable wifi`
4. Scan and wait for completion: `scan wifi`
5. Look for your SIID: `services`
6. If any SIIDs have spaces in them, you will have issues (#953) -- see below for workaround
7. Enable the connection agent: `agent on`
8. Connect `connect wifi_00904c0df43d_546865204c6162_managed_psk` using the appropriate service name
9. Enter the password and wait for connection to complete.
10. Exit: `quit`
11. You should see the IP address in `ip addr`
12. Switch back to the installer `ctrl+alt+f1`
12. You may have to repeat the `connmanctl` dance after installation

## SIIDs with spaces

You'll need to build a custom image and apply this patch to harvester/harvester-installer to bypass automatic network configuration (since we've manually configured it already):

https://gist.github.com/withinboredom/b540e2fdf780433c8a89c90f51762483

Then run `make`

## Failure to connect to access point

If you check in `dmesg` and find errors related to invalid/missing drivers during network card bringup, you may need to include the wifi drivers in the image. Here's an example patch that allow for a MacBook Pro to be used in a harvester configuration (possibly allowing OSX VMs) with a 5G network (requires changes to work with a 2G network, which are out of scope here):

https://gist.github.com/withinboredom/5639df9c7a877e47ac37ca5cb974c875

**Comment by oxr463** [comment]
@withinboredom thanks for that. Let me try it and see if I can get mine to work.

**Comment by oxr463** [comment]
> @withinboredom thanks for that. Let me try it and see if I can get mine to work.

<s>I don't seem to have `conmanctl`. I think I need to upgrade from Harvester v0.1.0 -> v0.2.0 first.</s>

Nevermind, it was a typo on my part... (I did upgrade to v0.2.0 though).

I now have WiFi configured, but after I unplugged eth0 and rebooted, the "Harvester management URL" became "Unavailable", and the "Current status" still says "Setting up Harvester"

**Comment by n-guitar** [comment]
I too am having trouble setting this up.
I cannot configure WIFI on SUSE Micro.
I'm having trouble figuring out how to connect to the network.

I have checked the following documents.
https://docs.harvesterhci.io/v1.1/troubleshooting/installation/


- Version

![image](https://user-images.githubusercontent.com/27879320/200319980-c054ff22-b806-49d6-81ef-90039e708f21.png)


- Additional

WIFI module is loaded successfully
![image](https://user-images.githubusercontent.com/27879320/200319557-b705e9cc-3599-48c1-b1eb-514f3cb20579.png)

"connman" is not installed
![image](https://user-images.githubusercontent.com/27879320/200320147-4ab5d022-26e9-49bc-9446-5a427e4d5d24.png)

network intarface is down
![image](https://user-images.githubusercontent.com/27879320/200320396-09d78e73-4145-457a-9c09-fc3b00e18f2b.png)

**Comment by krumware** [comment]
This would be nice to have
