### ISSUE TITLE
[BUG] New created VM shows `VirtualMachine generation is 2, but latest observed generation is 1`

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4909]
## Description
New created VM Running but shows `VirtualMachine generation is 2, but latest observed generation is 1`

## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM(ipxe-examples), 2 nodes (8C/16G/500G)
  * **ui-source**: Auto

## To Reproduce
1. Setup Harvester
2. Create VM
   * Disk: **focal-server-cloudimg-amd64.img**
   * Network: **mgmt-vlan1**
3. VM should Running w/o warning message :x: 
   ![image](https://github.com/harvester/harvester/assets/2773781/cb9fdc79-ce58-4069-ad53-573ae119b6b4)

## Support Bundle
[supportbundle_Generation2Msg_2023-12-25T07-30-11Z.zip](https://github.com/harvester/harvester/files/13764790/supportbundle_Generation2Msg_2023-12-25T07-30-11Z.zip)

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/4866.
@FrankYang0529 Please help choose one issue between the two, I feel this issue has a better title.

**Comment by FrankYang0529** [comment]
Sounds good. We can use this one.

Add content from previous issue:

**Is your enhancement related to a problem? Please describe.**

After we updated KubeVirt to v1.0.0, the actual generation is different from expected. The root cause is that we set macaddress to VM and don't restart the VM.

![image](https://github.com/harvester/harvester/assets/4927361/b76487ed-81d7-494c-a53b-d66413c81cba)

![image](https://github.com/harvester/harvester/assets/4927361/9dec64ff-3634-4a27-b2b2-3b8b197339a9)


**Describe the solution you'd like**
In backend, we can set the macaddress when VMI is removed, so VMI can have the same macaddress if users start the VM again.

In frontend, we can suggest users to restart the VM if they try to update vm.Spec and don't restart it.

**Additional context**
https://github.com/harvester/harvester/issues/4758

**Comment by albinsun** [comment]
Provide test result on `v1.3-5f553f98-head`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3-5f553f98-head`
  * Profile: QEMU/KVM, 1 and 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Cases
### Single Node
1. Setup
   * Image `focal-server-cloudimg-amd64.img`
   * VM network `mgmt-vlan1`
1. Create 2 VMs in `default` namespace by **manual** and **VM template** respectively
1. Create 2 VMs in `harvester-public` namespace by **manual** and **VM template** respectively
1. Check VMs   
   * Running w/o error or warning message :heavy_check_mark: 
   * Can Get IP :heavy_check_mark: 
   ![image](https://github.com/harvester/harvester/assets/2773781/34c28aaa-2976-4b55-ab82-890636dea982)
   

### 2 Nodes
1. Setup
   * 2 nodes cluster
     ![image](https://github.com/harvester/harvester/assets/2773781/1f48212b-2b8b-46aa-9215-260e238db360)
   * Image `focal-server-cloudimg-amd64.img`
   * VM network `mgmt-vlan1`
1. Create 2 VMs in `default` namespace by **manual** and **VM template** respectively
1. Create 2 VMs in `harvester-public` namespace by **manual** and **VM template** respectively
1. Check VMs
   * Running w/o error or warning message
   * Can Get IP
   ![image](https://github.com/harvester/harvester/assets/2773781/fed4f329-2bf2-4893-92d6-e7e6120f8635)
