### ISSUE TITLE
[BUG] rancher-logging-crd not found, logging unusable, upgrade fail.

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#4927]
**Describe the bug**
* after upgrading v1.1.1 to v1.1.2,  the logging page in webui not usable (blank page)
* try upgrade to v1.2.1
  * if enable the **upgradelog** checkbox, the upgrade pre check fail, upgrade never start
  * if disable upgradelog, the progress stuck 50% at the "Upgrading System Service"

### webui - logging - Output page
```
Can not find the custom resource definition: harvesterhci.io.logging.output.
```
### before upgrade v1.2.1
```
hv-n0:~ # kubectl get bundles -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 1/1
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-monitoring                        1/1
fleet-local   mcc-rancher-monitoring-crd                    1/1

hv-n0:~ # kubectl get managedchart -A
NAMESPACE     NAME                                      AGE
fleet-local   harvester                                 376d
fleet-local   harvester-crd                             376d
fleet-local   local-managed-system-upgrade-controller   376d
fleet-local   rancher-monitoring                        376d
fleet-local   rancher-monitoring-crd                    376d
```
### upgrade v1.2.1 fail:
```
# kubectl get bundles -A  
NAMESPACE NAME BUNDLEDEPLOYMENTS-READY STATUS  
fleet-local fleet-agent-local 1/1  
fleet-local local-managed-system-agent 1/1  
fleet-local mcc-harvester 1/1  
fleet-local mcc-harvester-crd 1/1  
fleet-local mcc-hvst-upgrade-5x9sc-upgradelog-operator 0/1 ErrApplied(1) [Cluster fleet-local/local: execution error at (rancher-logging/templates/validate-install-crd.yaml:17:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.]  
fleet-local mcc-local-managed-system-upgrade-controller 1/1  
fleet-local mcc-rancher-monitoring 1/1  
fleet-local mcc-rancher-monitoring-crd 1/1
```

**To Reproduce**
1. airgap upgrade from v1.1.1 to v1.1.2
2. webui, click logging menu
3. try upgrade to v1.2.1

**Expected behavior**
* install rancher-logging 
* upgrade to v1.2.1

**Support bundle**
[supportbundle_6d4df720-fd7f-430d-bd20-d59e25058342_2023-12-28T17-46-41Z.zip](https://github.com/harvester/harvester/files/13788423/supportbundle_6d4df720-fd7f-430d-bd20-d59e25058342_2023-12-28T17-46-41Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2
 - Underlying Infrastructure : 3 * dell-R450

**Additional context**
 - v1.x.x live for half year
 - upgrade to v1.1.1, live for one year
 - upgrade to v1.1.2 today
 - upgrade v1.2.1 fail many times

**Comment by Vicente-Cheng** [comment]
Hi @w13915984028, 
Could you help check this? Thanks!

**Comment by w13915984028** [comment]
@fanlix 

The `rancher-logging-crd` `managedchart` is gone. 

Normally, it is not touched daily. For double-check, can you recall any operations on `rancher-logging-crd` ?

**Comment by fanlix** [comment]
```
hv-n0:~ # kubectl edit managedchart -n fleet-local rancher-logging
Error from server (NotFound): managedcharts.management.cattle.io "rancher-logging" not found
hv-n0:~ # kubectl get namespace cattle-logging-system
Error from server (NotFound): namespaces "cattle-logging-system" not found
```

* As doc said, rancher-logging is the basic system used by both rancher and harvester, 
* so, rancher-logging should be created by rancher by default. (in namespace cattle-logging-system)
* rancher-logging-crd is created by rancher-logging.
* There may be more system missing in rancher after v1.1.2 upgrade.

Should I install rancher-logging with helm by hand now? (https://github.com/rancher/charts/tree/main/charts/rancher-logging)

**Comment by w13915984028** [comment]
@fanlix 
It is a bit different with your description.

(1) There are a couple of `managedchart` defined in Harvester installer, they are created at the time the cluster was installed, they are controlled by `harvester-installer`, not `rancher`, even though some names include `rancher`
e.g.
https://github.com/harvester/harvester-installer/blob/cf6d3b74b6891a83bfacb4483285c7638ac9e0b6/pkg/config/templates/rancherd-14-logging-crd.yaml

(2) The `cattle-logging-system` namespace is defined in `harvester` `managedchart`, it is wired the namespace itself is gone.
https://github.com/harvester/harvester-installer/blob/cf6d3b74b6891a83bfacb4483285c7638ac9e0b6/pkg/config/templates/rancherd-10-harvester.yaml#L10

(3) The `rancher-logging` feature has 2 `managedchart`s: `rancher-logging-crd` and `rancher-logging` in versions <=v1.1.2, from v1.2.0, the `rancher-logging` `managedchart` is converted to `rancher-logging` addon automatically https://docs.harvesterhci.io/v1.2/logging/harvester-logging. There is no `rancher-logging` managedchart, only `rancher-logging-crd` managedchart.

(4) At the moment, I guess the `rancher-logging-crd` managedchart and `cattle-logging-system` namespace were deleted due to some unknow  reason/operation, will continue investigate.

The workaround to recover, please create them manually via copy data from above link
(1) create the namespace
(2) create the `rancher-logging-crd managedchart`, replace the logging version `LoggingChartVersion ` with `100.1.3+up3.17.7`
https://github.com/harvester/harvester-installer/blob/v1.1.2/scripts/version-logging, 
https://github.com/harvester/harvester-installer/blob/cf6d3b74b6891a83bfacb4483285c7638ac9e0b6/pkg/config/templates/rancherd-14-logging-crd.yaml

(3) create `rancher-logging managedchart`, replace logging version `LoggingChartVersion`
https://github.com/harvester/harvester-installer/blob/cf6d3b74b6891a83bfacb4483285c7638ac9e0b6/pkg/config/templates/rancherd-15-logging.yaml
(4) create `event-tailer`
https://github.com/harvester/harvester-installer/blob/cf6d3b74b6891a83bfacb4483285c7638ac9e0b6/pkg/config/templates/rancherd-15-logging.yaml#L60

note: when you copy yaml from the above link, remove `resources` line, remove `- ` before `apiVersion:`, reduce indent of all line with 2 spaces.

**Comment by fanlix** [comment]
@w13915984028 thx. after a dozen of problems fixed, my cluster has upgraded to v1.2.1

there is an extra problem with this issue, after step 2&3,   step 4 may fail of empty res.
```
# kubectl get bundles  -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 1/1
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-logging                           0/1                       ErrApplied(1) [Cluster fleet-local/local: execution error at (rancher-logging/templates/validate-install-crd.yaml:17:7): Required CRDs are missing. Please install the corresponding CRD chart before installing this chart.]
fleet-local   mcc-rancher-logging-crd                       0/1                       ErrApplied(1) [Cluster fleet-local/local: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "clusterflows.logging.banzaicloud.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher-logging-crd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-logging-system"]
fleet-local   mcc-rancher-monitoring                        1/1
fleet-local   mcc-rancher-monitoring-crd                    1/1
```

I have to delete all "*.logging.banzaicloud.io" CRD by hand ( they should be the main reason of this issue)
```
kubectl delete crd clusteroutputs.logging.banzaicloud.io
kubectl delete crd clusterflows.logging.banzaicloud.io
kubectl delete crd loggings.logging.banzaicloud.io
```
then clean and redo step 2&3,   wait a long while ,  do step 4.

**Comment by fanlix** [comment]
by the way, when upgrading to v1.2.1, all logging mc changed to add-on
```
delete eventtailer harvester-default  
eventtailer.logging-extensions.banzaicloud.io "harvester-default" deleted  
there are 15 pods in cattle-logging-system will be replaced  
delete managedchart rancher-logging  
managedchart.management.cattle.io "rancher-logging" deleted
...
```

**Comment by w13915984028** [comment]
@fanlix:  Glad to know your cluster is updated.

The failure in step2, is due to the ticking of `enable upgrade logging` when clicking upgrade button, it will install some `rancher-logging-crd` related CRDs if they are not there; then when you create the `rancher-logging-crd managedchart` manually, the system complains the conflict, it needs the ownership. After you deleting them manually, the conflict is away.

Per your words: `after upgrading v1.1.1 to v1.1.2, the logging page in webui not usable (blank page)`, to now, I suspect that the upgrading processing from v1.1.1 to v1.1.2 removed the `rancher-logging-crd` and `rancher-logging managedchart` for some unknown reason. It was done from `fleet-agent (POD) -> helm (api call, not cli)` when it tried to upgrade the `managedchart`. I will continue the investigation on this.

Thanks for reporting the issue.
