### ISSUE TITLE
[BUG] VMRestore to new VM doesn't work if there is VMSnapshot

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4954]
**Describe the bug**
After https://github.com/harvester/harvester/issues/4604, we deny VMRestore request with deletion policy if there is a VMSnapshot. It introduces a new issue - if we don't specify `DeletionPolicy`, the VMRestore can't work when there is a VMSnapshot. The root cause is that we only check whether deletion policy is `retain`, but not empty.

**To Reproduce**
1. Create a VM.
2. Create a VMBackup and VMSnapshot.
3. Restore VMBackup to a new VM and it can't work.

**Expected behavior**
VMBackup to a new VM can work.

**Environment**
 - Harvester ISO version: master-22d9e700-head

**Additional context**
Thanks @TachunLin for finding the issue.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-0c47319a-head` (24/01/10). Close this issue.

### Result
- [x] 1. Can restore vm backup to create a new vm when already setup vm backup and snapshot on it. 

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>


    https://github.com/harvester/harvester/assets/29251855/e791dc5a-c011-4a2a-9c91-1b0c7d193d24
    
    ![image](https://github.com/harvester/harvester/assets/29251855/390b028a-7f0b-4326-979b-a935ab9159a9)


    </details>


- [x] 1. Can restore vm backup to replace existing vm (retain volume) when already setup vm backup and snapshot on it. 

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>


    ![image](https://github.com/harvester/harvester/assets/29251855/72f9d169-778e-4df4-824a-93f4f688d098)
    
    
    https://github.com/harvester/harvester/assets/29251855/425347ea-7d23-4835-b14d-bbac73774f75


    </details>

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `master-0c47319a-head` (24/01/10)

### Verify Steps
<details><summary>Execution Steps</summary>

  1. Prepare a 3 nodes Harvester cluster
  2. Create a vm named vm1 
  3. Setup nfs backup target
  4. Create a backup for the vm1
  5. Create a snapshot for the vm1
  6. Restore the backup of vm1 to create a new VM
  7. Check can restore vm correctly
  8. Shutdown vm1, 
  9. Restore the backup of vm to replace the existing vm
  10. Select Retain volume
  11. Check can restore vm correctly.

</details>

**Comment by TachunLin** [comment]
Create tests pr [#1384](https://github.com/harvester/tests/pull/1384) 

#### Test result (Trigger locally and execute test on remote ecm lab machine)

1. Test can **PASS** all test cases in the `TestBackupRestoreWithSnapshot` class  
  ![image](https://github.com/user-attachments/assets/ddf9ff31-4c3c-4987-94d3-3f130a08419a)

2. Test can **PASS** most of the test cases in the `test_4_vm_backup_restore.py` file
  ![image](https://github.com/user-attachments/assets/add5c9be-a838-4bd1-8807-ea97a8c9a142)

* In order to not affect all existing test cases in the `TestBackupRestore` and `TestBackupRestoreOnMigration`  and `TestMultipleBackupRestore` , consider the stability and future test scalability, thus I create a separate class for the
