### ISSUE TITLE
[Doc] Add fstrim related article

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4988]
**Is your doc request related to a problem? Please describe or add related issue ID.**
We need to take care of the fstrim operation on the VM side.
It will have a huge side effect on the guest cluster scenario.

Related issue: https://github.com/harvester/harvester/issues/4739

**Describe the solution you'd like**
Create a KB for it.

**Comment by Martin-Weiss** [comment]
IMO this needs to go to the release notes and known issues list ASAP. VMs going to pause/unpause due to a standard / default setting within the guest OS is 100% unexpected and especially if this causes production impact a knowledge base article is too reactive and not pro-active for such a problem.

And - the fix needs to be delivered ASAP as well..

**Comment by Vicente-Cheng** [comment]
KB already updated here: https://harvesterhci.io/kb/the_potential_risk_with_filesystem_trim
Close as complete.

**Comment by Martin-Weiss** [comment]
@Vicente-Cheng - do we know if this is fixed in Harvester 1.2.2 and Harvester 1.3.1? Can we get this info added to the doc?

**Comment by Vicente-Cheng** [comment]
Hi @Martin-Weiss, 

Harvester v1.2.2 and v1.3.1 and the corresponding LH fixed this issue.
v1.2.2 -> LH v1.5.5
v1.3.1 -> LH v1.6.2

Two fstrim related issues are fixed.
[[BUG] Executing fstrim while rebuilding causes IO errors](https://github.com/longhorn/longhorn/issues/7103#top)
[[BUG] potential risk to unmap a negative number](https://github.com/longhorn/longhorn/issues/8235#top)

**Comment by Martin-Weiss** [comment]
@Vicente-Cheng  - could you update the KB article with the info and recommendation "fixed in versions ... please upgrade to ..." ?

**Comment by Vicente-Cheng** [comment]
Hi @Martin-Weiss, 

@jillian-maroket helped update the KB with the above PR.
Could you also check it?

**Comment by Martin-Weiss** [comment]
@Vicente-Cheng - for me this looks good. Just a minor thing - maybe I just would add one more note for 1.2.0 and state "upgrade to 1.2.1 and then to 1.2.2 " - or maybe just state "fixed in 1.2.2 and newer and 1.3.1 and newer"..

<img width="533" alt="image" src="https://github.com/user-attachments/assets/285db1a6-e1cd-4df5-9f51-c1d961fe4cdc">

**Comment by jillian-maroket** [comment]
![Screenshot 2024-07-16 at 10 20 18 PM](https://github.com/user-attachments/assets/e715552e-3ff1-45ac-a221-1598d686d8a0)

@Martin-Weiss I have replaced the table.
@Vicente-Cheng I'm off the rest of the week. Lucas can help with the PR if more changes are required.
