### ISSUE TITLE
[BUG] should display errors when VM image upload fails

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5014]
**Describe the bug**

It is possible to upload a VM image from the local Harvester UI via the web browser (not the proxy connection). It is not possible to upload a VM image through Rancher UI via a web browser. The request never reaches Harvester. The request is terminated by the rke2 nginx ingress with the error 413 "request too big". The user does not see ANY error. The progress bar stays at 0% forever. The only location to look for the error is the web browser developer tools on the network tab.

**To Reproduce**
1- From within Rancher that has Harvester 1.1.2 cluster imported, go to Virtualization management
2- Go to Harvester cluster
3- Try uploading an image file from your machine

**Expected behavior**

When the upload is not working UI should display an error. Ideally.

**Environment**
Rancher Cluster:
Rancher version: 2.7.6
Number of nodes: 3 masters, 2 workers
Node OS version: Ubuntu 20.04

Downstream Cluster:
Number of Downstream clusters:
Node OS:
RKE/RKE2/K3S version: rke2 1.25.13
Kubernetes version:
CNI:

Harvester 1.1.2

**Additional context**

**Comment by torchiaf** [comment]
Reopen for QA tests

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
To notice this bug is very hard to reproduce and verify via dashboard UI, thus we leverage API calls to make upload failed.

![image](https://github.com/harvester/harvester/assets/5169694/5caf74b2-7c3b-4762-bdc7-2ea822824593)
![image](https://github.com/harvester/harvester/assets/5169694/7715134f-3599-476a-854f-88e2e91b565e)


Test Information
----
* Environment: **qemu/KVM 2 node**
* Harvester Version: **v1.3.0-rc4**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.8.1**


### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Clone [test repo](https://github.com/harvester/tests) and install backend test required libs
4. Fill in `VIP`, `password` and `file_path` in follow code snippet then execute it
```python3
from pathlib import Path
from harvester_api import API
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
api = API.login('<VIP>', 'admin', '<password>', ssl_verify=False)

name = 'for_issue_5014'
namespace = 'default'
file = Path('<file_path>').expanduser()
data = api.images.create_data(name, "", "", "upload", namespace)
api.images.create("", namespace, json=data)
kwargs = dict(params=dict(action="upload", size=file.stat().st_size/2), files=dict(chuck=file.open('rb')))

api.images._create(api.images.UPLOAD_fmt.format(uid=name, ns=namespace), raw=True, **kwargs)
```
5. Login to Dashboard, there should have an image named `for_issue_5014`
6. The image should displays `Failed` _state_ and error message
7. Access Harvester dashboard via Rancher
8. The image should displays as Harvester dashboard
