### ISSUE TITLE
[BUG] Parallel Provisioning of Harvester VMs Sees Each VM Get The Same IPV4

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5032]
**Describe the bug**
Given the scenario of a user has:
- 3 separate terraform projects
- 3 separate respective state files 
- 3 separate VMs w/ NICs, etc.
- Each NIC on each VM is assigned a unique MAC Address

User opens 3 separate terminals.
User fires off:
```
TF_LOG=TRACE terraform apply -var-file="env/local.tfvars" -auto-approve   
```

All VMs come up online with the same IPv4 address.

**To Reproduce**
1. Build 3 different small terraform projects, w/ 3 corresponding state files, for 3 separate VMs ( each having a NIC that has a different MAC address )
1. Run TF Apply
1. All VMs come up online with the same IPv4 address

**Expected behavior**
To have parallel provisioning of resources in Harvester, the VMs that get created, not encounter issues where each VM's IP Address is the same as the next.

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure: HP-DL360
 
**Additional context**

![Screenshot from 2024-01-25 18-05-00](https://github.com/harvester/harvester/assets/5370752/fd125e91-d451-476c-93c0-73b6284a0143)
![Screenshot from 2024-01-25 18-05-58](https://github.com/harvester/harvester/assets/5370752/f92547f4-baa4-4fc6-ab54-8e57feb1fc45)

**Comment by mingshuoqiu** [comment]
What's the UUID of each created VM? Please check the output of command `dmidecode -t system | grep UUID` on each VM.

**Comment by irishgordo** [comment]
Hi @mingshuoqiu  thanks for that check and the insight :smile:  - they all have different UUIDs as I believe we would expect :smile: :+1: 
Please see attached screen grab.
cc: @bk201 
![Screenshot from 2024-01-25 23-56-07](https://github.com/harvester/harvester/assets/5370752/9446b310-f43b-4276-993a-99dd64fc7a60)

**Comment by mingshuoqiu** [comment]
Could you run `systemctl status systemd-networkd` on 3 VMs? It will show timestamp information and I wondering if they directly issue DHCPREQUEST at the same time w/o DHCPDISCOVER phase.

**Comment by irishgordo** [comment]
I'm pretty sure that's sort of what's happening - I was trying a few workarounds with something like in the cloud-init something like:

```yaml
      bootcmd:
        - /usr/bin/sleep $(/usr/bin/shuf -i 1-100 -n 1)
```
But realized the cloud-img I'm leveraging doesn't by default have the [ shuf from GNU core-utils ](https://www.gnu.org/software/coreutils/manual/html_node/shuf-invocation.html) - so I'd need to rebuild the cloud-img with that baked in.
Additionally, thinking something like a rc.local file could be implemented:
```shell
#!/bin/sh
# add your commands
# call your scripts here

/usr/bin/sleep $(/usr/bin/shuf -i 1-100 -n 1)
/usr/sbin/ip link set enp1s0 up
/usr/sbin/dhclient -v enp1s0
# last line must be exit 0
exit 0
```
A VM still with 5 others provisioning at the same time, they do have a non-zero chance of hitting the "same" random number on sleeping... I guess the thought would be is creating that space of time would allow for some VMs to come up, making the DHCP calls before others do...
But perhaps a time gap can be created in provisioning them like:
VM1: 0 Min Delay
VM2: 3 Min Delay
VM3: 6 Min Delay
VM4: 9 Min Delay
VM5: 12 Min Delay
VM6: 15 Min Delay

versus trying to stand all of them up at once.
@mingshuoqiu  do you have any suggestions to handling multiple VMs trying to issue the same DHCP calls at the same time?  Are there some built in mechanisms for them to cycle talking to the DHCP server that's native to the network, waiting / asking / re-asking? 
Maybe looping something like:
```
/usr/sbin/dhclient -v enp1s0
```
Over a few times? 

Perhaps parallel provisioning isn't needed in my current use-case as well.
Thanks again for the insight!
I'll cross-validate that they're issuing the DHCP calls at the same time, I beleive they are.

**Comment by mingshuoqiu** [comment]
Actually, I believe it's pretty much the DHCP server's fault to assign the same address even it the renewal happen almost at the same time. So that's why I need to see the `systemd-networkd`'s log to see what happens. I assume all of 3 get the same IP with the same lease in the very beginning. When the lease time hit 50% (T1), they should 
VM1  --> unicast DHCP request  --> receive DHCP ack  --> get IP1
VM2 --> unicast DHCP request  --> expect a DHCP NACK here since IP1 allocated  --> broadcast DHCP discover --> get IP2
VM3 --> should follow the same path with VM2

It this case, DHCP server seems never NACK the DHCP request for IP1, so the VM2/3 will never broadcast DHCP discover to get new IP from the DHCP server. 

Maybe you can try `dhclient -r` to release before a normal `dhclient`. `dhclien -r` will release the current IP so the next request from VM will be broadcast DHCP DISCOVERY to ask for a new IP instead of DHCP REQUST for simply renewal.

If they're still the same...We may need to know what the DHCP server is and check  how it works.

**Comment by irishgordo** [comment]
@mingshuoqiu  - thanks so much for that mention - it was more on the infrastructure side than anything else :smile:  :+1: - I'm going to go ahead and close this out. Thanks again for the help on this :+1: :smile: :100:
