### ISSUE TITLE
[BUG] Preflight check doesn't allow value between `MinCPUTest` and `MinCPUProd`

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5034]
**Describe the bug**
After https://github.com/harvester/harvester/issues/1154, we have CPU and memory check in harvester-installer. There are `MinCPUTest` and `MinCPUProd` limitation. However, we don't really allow the value between `MinCPUTest` and `MinCPUProd`. The better way is to add a setting to say whether this is Test or Prod environment and use related setting to check it.

https://github.com/harvester/harvester-installer/blob/b07508107980ad02c5ad669fb020300aca016cfe/pkg/preflight/checks.go#L45-L52

https://github.com/harvester/harvester-installer/blob/b07508107980ad02c5ad669fb020300aca016cfe/pkg/preflight/checks.go#L93-L99

**To Reproduce**
Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) to create a Harvester cluster. The default setting is 8 CPU and 16 RAM. Without `harvester.install.skipchecks=true`, this setting can't provision a test cluster.

**Expected behavior**
Check the limitation by environment.

**Environment**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Comment by tserong** [comment]
This is intentional. My understanding was that the focus of the preflight check feature was to warn (or fail) if you don't meet _production_ requirements. That's why `harvester.install.skipchecks=true` exists - it's to allow you to skip the checks if any production requirements aren't met, and that includes running in a test environment.

I guess what I'm trying to say is: is it really worth the effort to add a separate setting to distinguish between test and production environments, given the checks can already be disabled if necessary? The wording of the warning messages varies depending on whether you've met testing requirements or not, so you can still tell whether you've met testing requirements even if the checks are disabled.

**Comment by FrankYang0529** [comment]
Hi @tserong, thanks for the respond. Yeah, I agree that we don't need to add another setting to check it. We can close the issue. Thanks!

**Comment by tserong** [comment]
Thanks @FrankYang0529!
