### ISSUE TITLE
[BUG] containerd-registry setting doesn't work

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5187]
**Describe the bug**

Setting the [containerd-registry](https://docs.harvesterhci.io/v1.2/advanced/index/#containerd-registry) setting doesn't work in V1.3.0-rc3.

**To Reproduce**
1. Go to settings.
2. Edit the `containerd_registry` setting:
    ![截圖 2024-02-21 下午5 13 26](https://github.com/harvester/harvester/assets/1691518/4a8a9818-22cc-4875-bbc4-3ecc1105d2a6)
3. Save.
4. log in to nodes and check the `/etc/rancher/rke2/registries.yaml` file, the endpoint is not set correctly:
    ```
    # cat /etc/rancher/rke2/registries.yaml
    {"configs":{},"mirrors":{"docker.io":{}}}
    ```

**Expected behavior**

mirror should be set correctly.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Not quite sure if this is related to Rancher bump (to v2.8.2).

**Comment by bk201** [comment]
@connorkuehl Can you help check this issue?

**Comment by connorkuehl** [comment]
Harvester's github.com/rancher/wharfie dependency was recently upgraded and it turns out that module introduced a breaking change for the wharfie.Registry struct[1], which is what the Harvester settings controller uses to unmarshal the JSON payload from the Harvester dashboard where the containerd-registry settings are entered into. As a result, the backend has now broken its API contract with the Harvester frontend.

Previously, it did not have any json field tags for the struct members, so the encoding/json package defaults to using the exported field names (`Endpoints` instead of `endpoints`).

The new version of wharfie has added json field tags for these structs. For example, `Endpoints` is now `endpoint`, which is not backwards compatible with previous versions of the module.

This is the payload that the Harvester dashboard sends when saving the value:

```
{\"Mirrors\":{\"cr.example.com\":{\"Endpoints\":[\"https://cr.example.com:5000\"],\"Rewrites\":{}}}}
```

Since the wharfie module changed the struct tags for JSON unmarshaling, it does not use `Endpoints` since it now expects only `endpoint`.

I converted the original HTTP request from the dashboard into a curl request, but this time I updated the JSON field names to use the ones that are in the wharfie module's Registry struct:

```
"value":"{\"mirrors\":{\"cr.example.com\":{\"endpoint\":[\"https://cr.example.com:5000\"],\"Rewrites\":{}}}}"}
```

The curl request succeeded and the values were written correctly to the registries.yaml:

```console
harv1-130-rc3:~ # cat /etc/rancher/rke2/registries.yaml 
{"configs":{},"mirrors":{"cr.example.com":{"endpoint":["https://cr.example.com:5000"]}}}
```

To resolve, we will need to update the Harvester dashboard to use the new json field tags for the new version of the wharfie module: https://pkg.go.dev/github.com/rancher/wharfie@v0.6.5/pkg/registries#Registry

[1] https://github.com/harvester/harvester/commit/6687a6be3#diff-c9ae2ac8ca36c77313e61fb5a1bffcc789d55ef58fbb52bac2220aff81f8a3bc

**Comment by brandond** [comment]
The keys must be lowercase as shown in the docs:
 * https://docs.rke2.io/install/containerd_registry_configuration#registries-configuration-file
*  https://docs.k3s.io/installation/private-registry#registries-configuration-file

k3s/rke2/rancher-system-agent deserialize it as yaml, which is how it is documented. json is a subset of yaml, so that PR added json tags so that it can be properly serialized by Rancher's provisioning framework (and other tools) as json, and then deserialized as yaml.

It sounds like Harvester started serializing it as json before that PR was merged, without checking to see if the output was actually compatible with other products.

**Comment by connorkuehl** [comment]
@bk201 @torchiaf I can update the backend to continue to use the old capitalization on the JSON keys, which means we could close this ticket as there would be no frontend work required. In fact, I'd prefer to do that, since there is no technical advantage for Harvester in using the new JSON key representation.

I'm going to submit a PR to do just that. However, if you prefer otherwise, I also have a branch that is able to "migrate" the containerd-registry setting's old JSON "schema" with the capitalized keys into the newer keys. Let me know if that is the case and I will open a PR with that branch.

**Comment by bk201** [comment]
Thanks, @connorkuehl, let's close this one and use https://github.com/harvester/harvester/issues/5190 instead.
