### ISSUE TITLE
[FEATURE] Support Longhorn v2 data engine - Experimental

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5274]
**Is your feature request related to a problem? Please describe.**
Longhorn v2 engine use the raw device as backend device.
node-disk-manager now only supports provision filesystem for longhorn backend
we should add a capability to provision raw devices and fill related fields to longhorn node.

**Describe the solution you'd like**
Add another provision behavior for the raw device

**Describe alternatives you've considered**

**Additional context**
https://longhorn.io/docs/1.6.0/v2-data-engine/quick-start/#enable-v2-data-engine

**Comment by innobead** [comment]
1.5 will use Longhorn 1.8 or 1.9 which should have a more stable v2 engine.

**Comment by Vicente-Cheng** [comment]
Briefly list the following items for this feature:
- [ ] OS side, we need hugepage and corresponding kernel module (REF: https://github.com/harvester/os2/pull/98)
- [ ] NDM side, this is an entry point because we need to format the physical backend for the Longhorn v2 volume (NDM will decompose the provisioned for `longhornv1`, `longhornv2` and `lvm` on v1.4.0)
- [ ] UI part
- [ ] MISC stuff (like the Longhorn v2 engine did not support live migration. We need to forbid this operation on the harvester side)

cc @Yu-Jack, @bk201, @innobead @derekbit @ibrokethecloud

**Comment by w13915984028** [comment]
Besides the above list, a few questions:
(1) Will v1 and v2 are supported at the same time? When true, which one will be the default one on Harvester. Is this a global setting or local setting against volume/disk or both ?
(2) From user perspective, what's the change when creating images/volumes/storageclass/vms?
(3) Upgrade path.

The `require/HEP` label was added, guess the HEP will have detailed user stories.

**Comment by Vicente-Cheng** [comment]
>(1) Will v1 and v2 are supported at the same time? When true, which one will be the default one on Harvester. Is this a global setting or local setting against volume/disk or both ?

Yeah, we should have capability provision v1 or v2 in the same time (but will use different physical disk)
We should not have any setting for it. It is determined when adding storage. 

>(2) From user perspective, what's the change when creating images/volumes/storageclass/vms?

It should not have any change.

>(3) Upgrade path.

It should not be affected.

I thought we would have more detailed information with HEP so we could discuss it later with HEP.

**Comment by tserong** [comment]
> Yeah, we should have capability provision v1 or v2 in the same time (but will use different physical disk)
> We should not have any setting for it. It is determined when adding storage.

What about during initial system installation when choosing the data disk?

**Comment by tserong** [comment]
I'm presently working on a HEP for this, but in the meantime wanted to post some notes in response to some items above.

> OS side, we need hugepage and corresponding kernel module (REF: https://github.com/harvester/os2/pull/98)

We may not want to default to enabling hugepages everywhere, because if I'm reading https://www.kernel.org/doc/html/latest/admin-guide/mm/hugetlbpage.html correctly where it says "Pages that are used as huge pages are reserved inside the kernel and cannot be used for other purposes", this means we'd lose 2GiB RAM on every node, even if the V2 engine isn't enabled.

> > > (1) Will v1 and v2 are supported at the same time? When true, which one will be the default one on Harvester. Is this a global setting or local setting against volume/disk or both ?
> >
> > Yeah, we should have capability provision v1 or v2 in the same time (but will use different physical disk)
> > We should not have any setting for it. It is determined when adding storage.
> 
> What about during initial system installation when choosing the data disk?

We have to continue to support v1 at the same time as v2, and the default data disk needs to remain using the v1 engine. This is because VM images - and volumes based on VM images - use the Longhorn backing image feature, which is not yet supported by the v2 engine.

> (2) From user perspective, what's the change when creating images/volumes/storageclass/vms?

- Images remain using the v1 engine (at least for now), so no change there.
- There needs to be a new storage class for the v2 engine. Maybe we can create one automatically to save the user having to do so.
- When creating volumes, it's just a matter of choosing the v2 storage class.
- No change to creating VMs (they use whatever volumes you tell them to).

Also, in case anyone wishes to manually enable the v2 data engine on an existing Harvester v1.3.x cluster, here's my notes:

- You will need at least one extra disk on each node you wish to use the v2 engine on. The default data disk (/var/lib/harvester/defaultdisk) remains using the v1 engine and cannot be switched to v2.
- You will want access to the Longhorn GUI. If you haven't already done so, you can get it from the Harvester GUI by going to Harvester > Admin User > Preferences > Enable Extension Developer Features, then Harvester > Support > Access Embedded Longhorn UI.
- For each node:
  - Add /oem/93_spdk.yaml from https://github.com/harvester/os2/pull/98 and reboot to apply those settings
  - ssh in and run the longhorn environment check script `bash -c "$(curl -sfL https://raw.githubusercontent.com/longhorn/longhorn/v1.6.2/scripts/environment_check.sh)" -s -s` (yes, that's _two_ `-s` on the end, necessary to enable the spdk checks which verify nvme and uio kernel modules are present, and hugepages are enabled). Everything should pass, except it'll complain cryptsetup isn't found. That's expected as we don't support encrypted volumes on Harvester yet.
- Enable the v2 data engine. From the Longhorn GUI, that's Setting > General > V2 Data Engine checkbox. Note that this will allocate a whole CPU core to the v2 instance manager on each node.
- Add the disk(s) to longhorn. This can be done via `kubectl edit` or the longhorn GUI as described in https://longhorn.io/docs/1.6.2/v2-data-engine/quick-start/#add-disks-to-nodelonghornio. I'd recommend using `/dev/disk/by-id/...` paths if possible.
- Add a v2 storageclass. This can be done with `kubectl apply` as described at https://longhorn.io/docs/1.6.2/v2-data-engine/quick-start/#create-a-storageclass or you can use the Harvester GUI under Advanced > Storage Classes. You'll need to use the "Add Parameter" button to add the "dataEngine: v2" parameter. Also make sure "Migratable" is set to "No" (AFAIK that's not supported yet -- see https://github.com/longhorn/longhorn/issues/6361)
- ~Now, any volume you create from the Harvester Volumes screen, using the storage class you created in the step above, will use the v2 data engine. You can then attach those v2 volumes to VMs and see how fast it goes :wink:~ Don't create volumes in Harvester as it will currently always create RWX PVCs, which don't work correctly with the V2 engine if the storageclass is nonmigratable. Instead, use `kubectl create` to create a PVC using the longhorn v2 storage class with `accessModes` set to `ReadWriteOnce`. Or, use a migratable storage class, but bear in mind that migration isn't actually supported.
- NOTE: you cannot use the v2 data engine for image storage (it does't support backing images yet). Images you upload/download into Harvester still use the v1 data engine. This means when you boot a VM from an image, its root disk is running on the v1 data engine. It's only additional volumes attached to the VMs that get to use v2.

**Comment by bk201** [comment]
Note the feature state is changed from "Preview" to "Experimental".

**Comment by albinsun** [comment]
# Test Plan (WIP) 
1. 2 nodes 
1. 3 nodes witness


## Environment
* `harvester-v1.4.0-rc3`
  * Profile:

  * ui-source: `Auto`

## Prerequisite
1. <details>
   <summary> Prerequisite
   </summary>
   </details>


## Scenario
### Toggle V2 Data Engine
1. <details>
   <summary> :white_circle: Enable on all nodes by <code>longhorn-v2-data-engine-enabled</code> setting
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Enable on some nodes by <code>node.longhorn.io/disable-v2-data-engine</code> label
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Switch ordering of 1) and 2) should not affect the result
   </summary>
   </details>


### Attach Disk using Longhorn V2 (CSI) Provisioner
1. <details>
   <summary> :white_circle: Node w/ V2 data engine enabled can attach disk using Longhorn V2 (CSI) Provisioner.
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Node w/o V2 data engine enabled can NOT attach disk using Longhorn V2 (CSI) Provisioner but only the default one.
   </summary>
   </details>


### Create Storage Class and Unbound Volume
1. <details>
   <summary> :white_circle: Create a storage class <i>sc-lhv2</i> using Longhorn V2 (CSI) Provisioner
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Create a volume using <i>sc-lhv2</i>
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Volume replica behavior? 
   </summary>
   </details>


### Bound Volume
#### pre-defined
1. <details>
   <summary> :white_circle: Create a VM with pre-defined lhv2 volume
   </summary>

   1. Create VM
   1. Gen test data with md5sum on disk-0 (default)
   1. Gen test data with md5sum on disk-1 (lhv2)
   1. Reboot VM, data does not broken
   </details>

1. <details>
   <summary> :white_circle: Backup-Restore
   </summary>

   </details>

1. <details>
   <summary> :white_circle: Snapshot-Restore
   </summary>

   </details>

#### on-demand
1. <details>
   <summary> :white_circle: Create a VM with on-demand lhv2 volume
   </summary>

   1. Create VM
   1. Gen test data with md5sum on disk-0 (lhv2)
   1. Gen test data with md5sum on disk-1 (default)
   1. Reboot VM, data does not broken
   </details>

1. <details>
   <summary> :white_circle: Backup-Restore
   </summary>

   </details>

1. <details>
   <summary> :white_circle: Snapshot-Restore
   </summary>

   </details>

### Rancher Integration
1. <details>
   <summary> :white_circle: Provision RKE2 cluster by Rancher
   </summary>
   </details>

**Comment by khushboo-rancher** [comment]
Just leaving a note for testing, v2 volume performance should be faster than v1

**Comment by albinsun** [comment]
Following scenarios test ok on local ipxe-example env.:
1. Toggle V2 Data Engine
2. Attach Disk using Longhorn V2 (CSI) Provisioner
3. Create Storage Class and Unbound Volume
4. Create VM

Will perform Backup Restore on later.


## Environment
* `harvester-v1.4.0-rc4`
  * Profile: 3 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`


## Prerequisite
1. <details>
   <summary> Setup a 3 nodes  cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/1b3dc494-3d2f-4dda-a547-28a8765cb034)
   </details>

1. <details>
   <summary> Extra disk w/ WWN on each nodes
   </summary>

   Ref. https://github.com/harvester/harvester/issues/5446#issuecomment-2112177685
   ![image](https://github.com/user-attachments/assets/4d9eaac3-c22e-4c46-8c37-0b18207a7d2f)
   </details>

1. <details>
   <summary> Create image <i>ubuntu-22.04-server-cloudimg-amd64.img</i>
   </summary>

   ![image](https://github.com/user-attachments/assets/af5f8e53-c76b-4c07-bafe-c6ff89a94872)
   </details>

1. <details>
   <summary> Create VM network <i>mgmt-vlan1</i>
   </summary>

   ![image](https://github.com/user-attachments/assets/c021a2e2-7099-47a8-b598-db3f6a026047)
   </details>

1. <details>
   <summary> Setup backup target
   </summary>
   
   ![image](https://github.com/user-attachments/assets/55995dbb-df6f-4b66-bc05-e9f0a92e80d6)
   </details>



## Test Scenarios
### Toggle V2 Data Engine
1. <details>
   <summary> :green_circle: V2 engine should be diabled on each nodes by default
   </summary>

   * Harvester
     ![image](https://github.com/user-attachments/assets/c509bef3-905d-414a-be89-9d5e0ea1ef4b)

   * Longhorn
     ![image](https://github.com/user-attachments/assets/e5d1e153-cc5b-4245-9886-26aa26c9b87a)

   * _/oem/99_settings.yaml_
     ![image](https://github.com/user-attachments/assets/76cab6f6-e55c-42da-acb3-2021c839b069)

   * Kernel module `vfio_pci`, `uio_pci_generic` and `nvme_tcp`
     ![image](https://github.com/user-attachments/assets/7853e15d-5cde-4991-9ae7-a93fb80df2db)

   * `/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages`
     ![image](https://github.com/user-attachments/assets/f9fb0ce8-3ea5-462b-b015-499df62cd147)
   </details>


1. <details>
   <summary> :green_circle: Disable LHv2 engine on <i>node-0</i> and <i>node-2</i> in advance 
   </summary>

   * Disable on _node-0_
     ![image](https://github.com/user-attachments/assets/69835ec2-9080-4bf2-85ca-a10fa43a3a72)
   * Disable on _node-2_
     ![image](https://github.com/user-attachments/assets/c116f61f-6292-421e-81fc-5bc91c191c76)
   </details>


1. <details>
   <summary> :green_circle: Enable LHv2 engine and should only take effect on <i>node-1</i>
   </summary>

   * Harvester
     ![image](https://github.com/user-attachments/assets/c5d714f6-47ce-4d23-84c8-1eff8a8d5615)

   * Longhorn
     ![image](https://github.com/user-attachments/assets/05fbe144-cd17-4bde-ac42-e43723be48b9)

   * _/oem/99_settings.yaml_
     ![image](https://github.com/user-attachments/assets/81c18c45-99ea-4f9d-a84d-72a67914a13a)

   * Kernel module `vfio_pci`, `uio_pci_generic` and `nvme_tcp`
     ![image](https://github.com/user-attachments/assets/e587083e-d8c2-4254-8a0c-82730a3de59c)

   * `/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages`
     ![image](https://github.com/user-attachments/assets/d0e9e855-1ef5-4137-b6fa-545c479621ad)
   </details>


1. <details>
   <summary> :green_circle: Enable on <i>node-2</i> by removing label (left <i>node-0</i> disabled)
   </summary>

   * _/oem/99_settings.yaml_
     ![image](https://github.com/user-attachments/assets/ea4bd7c3-7a33-47ea-a9ae-ed2d2a87efcd)

   * Kernel module `vfio_pci`, `uio_pci_generic` and `nvme_tcp`
     ![image](https://github.com/user-attachments/assets/47b105fb-ddbc-4e5d-b669-7d7d047cf148)

   * `/sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages`
     ![image](https://github.com/user-attachments/assets/4823204f-b26b-41a7-8f48-b31d50f92d69)
   </details>



### Attach Disk using Longhorn V2 (CSI) Provisioner
1. <details>
   <summary> :yellow_circle: <i>node-0</i> should NOT be able to attach disk using LHv2 Provisioner but LHv1
   </summary>

   * Not be able to provision LHv2 disk
     ![image](https://github.com/user-attachments/assets/bf8fd58c-08c3-462c-8eb9-f17e3a3263ed)
   * Provision extra disk as LHv1
     ![image](https://github.com/user-attachments/assets/49268b47-9cd8-470d-becc-4c0484d48c84)
   </details>

   > Works on virtual SCSI disk in ipxe-example env. but hit problem in baremetal one.
   > harvester/harvester/issues/6861


1. <details>
   <summary> :yellow_circle: Format extra disk on <i>node-1</i> and <i>node-2</i> before attach with LHv2 provisioner
   </summary>

   ![image](https://github.com/user-attachments/assets/2f536ed7-0b7a-4f2e-be25-42d46a7d9cde)
   </details>

   > Need to format manually cuz no Force Format option like LHv1
   > harvester/harvester/issues/6859

1. <details>
   <summary> :green_circle: <i>node-1</i> and <i>node-2</i> can attach disk using LHv2 Provisioner.
   </summary>

   * _node-1_
     ![image](https://github.com/user-attachments/assets/078d52b3-f935-4b0c-9739-3af0c1fda132)
   * _node-2_
     ![image](https://github.com/user-attachments/assets/be5e5f02-b61d-4d45-9ade-b29ae6ebb944)

   * Longhorn
     ![image](https://github.com/user-attachments/assets/9725e0c0-d477-444b-84d2-96ee4bf7ecf7)
   </details>



### Create Storage Class and Unbound Volume
1. <details>
   <summary> :green_circle: Create a storage class <i>lhv2-r2</i> using Longhorn V2 (CSI) Provisioner
   </summary>

   * The **Migratable** and **Volume Encryption** radio buttons should be automatically set to "No".
    ![image](https://github.com/user-attachments/assets/3ae2f42c-6f8f-4bd0-a74f-90a4e748eabd)
   * Created
     ![image](https://github.com/user-attachments/assets/7a016c6b-b83c-4f49-952c-06c1a0d53d39)
   </details>


1. <details>
   <summary> :green_circle: Create <i>lhv2-r2</i> volume (New) <i>predefined-lhv2</i>
   </summary>

   * Harvester
     ![image](https://github.com/user-attachments/assets/cafb9e95-65ef-4e0e-9bf3-a03a4ddeb6d2)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/f560bd83-dbd2-4527-887d-80a5f5519bfe)
   </details>



### Create VM
1. <details>
   <summary> :green_circle: Create a VM with extra volume <i>predefined-lhv2</i>
   </summary>

   * Create VM
     ![image](https://github.com/user-attachments/assets/2d0be9b5-b889-4185-a43c-c49391b8e61b)
   * Format <i>predefined-lhv2</i> as EXT4
     ![image](https://github.com/user-attachments/assets/81b4e27a-55c8-458e-ad0c-6c6540fd9867)
   * Gen test data with md5sum on both disks
     ![image](https://github.com/user-attachments/assets/d110141c-dd07-4101-8858-da99b24d3e3a)
   * Reboot VM, data does not broken
     ![image](https://github.com/user-attachments/assets/8327ca3c-cfdf-4cdb-9a7d-ac3d75c08106)
   </details>

1. <details>
   <summary> :green_circle: Create a VM with extra volume <i>ondemand-lhv2</i>
   </summary>

   * Create VM
     ![image](https://github.com/user-attachments/assets/79c2c939-4740-4d47-a988-6394814df4e2)
   * Format <i>predefined-lhv2</i> as EXT4
     ![image](https://github.com/user-attachments/assets/2d8b808d-35b6-41f7-a8bd-19f7d81d6d6d)
   * Gen test data with md5sum on both disks
     ![image](https://github.com/user-attachments/assets/524f0f96-f2b3-4ffb-a090-8d5adda2a98e)
   * Reboot VM, data does not broken
     ![image](https://github.com/user-attachments/assets/52e0144c-9d63-48c0-aa81-d2367fe3b982)
   </details>

**Comment by albinsun** [comment]
Provide test result about backup-restore and Rancher integration with opened issue.


## Environment
* `harvester-v1.4.0-rc4`
  * Profile: 2 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`
* `rancher-v2.9.2`
  * Profile: Single node AMD64 QEMU/KVM
  * K3s Channel: `v1.29`


## Prerequisite
1. <details>
   <summary> Setup a 2 nodes cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/3f478e61-7f52-4f99-bfcd-fd71c4de841d)
   </details>

1. <details>
   <summary> Extra disk w/ WWN on each nodes
   </summary>

   Ref. https://github.com/harvester/harvester/issues/5446#issuecomment-2112177685
   ![image](https://github.com/user-attachments/assets/fa6e35d8-f157-4948-9b09-637239b773fa)
   </details>

1. Create image _ubuntu-22.04-server-cloudimg-amd64.img_
1. Create VM network _mgmt-vlan1_

1. <details>
   <summary> Setup backup target
   </summary>
   
   ![image](https://github.com/user-attachments/assets/2cc72ca2-c26b-455f-ae48-e5f52db8caa6)
   </details>

1. <details>
   <summary> Enable LHv2 engine, and disable on <i>node-0</i>
   </summary>
   
   * Harvester
     ![image](https://github.com/user-attachments/assets/3ee62e99-0093-4fbe-a9c8-ac8d9358eb02)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/ab72874b-4680-4089-a180-6b27afdf3fdd)
   </details>

1. <details>
   <summary> Add disk w/ LHv2 provisioner on <i>node-1</i> and create storage class for it
   </summary>
   
   * Disk
     ![image](https://github.com/user-attachments/assets/135f439e-d9f1-41e2-a712-c75dac1e4049)
   * Storage Class
     ![image](https://github.com/user-attachments/assets/8f8817fa-aaf5-48d4-af57-1bb215b09f76)
   </details>



## Test Scenarios
### Create VM with LHv1 rootdisk and LHv2 extradisk
1. <details>
   <summary> :green_circle: vm-virtio
   </summary>

   * Mount disk
     ![image](https://github.com/user-attachments/assets/06f5f1fa-b413-466d-b9d6-8392bfa120df)
   * Gen test data
     ![image](https://github.com/user-attachments/assets/3a3eb2ab-c2c0-45f6-a337-8cfc09fb85e1)
   * Reboot and data does not broken
     ![image](https://github.com/user-attachments/assets/99dcca8e-c2b1-4f74-a855-33730ead571d)
   </details>

1. <details>
   <summary> :green_circle: vm-sata
   </summary>

   * Mount disk
     ![image](https://github.com/user-attachments/assets/06f5f1fa-b413-466d-b9d6-8392bfa120df)
   * Gen test data
     ![image](https://github.com/user-attachments/assets/3a3eb2ab-c2c0-45f6-a337-8cfc09fb85e1)
   * Reboot and data does not broken
     ![image](https://github.com/user-attachments/assets/99dcca8e-c2b1-4f74-a855-33730ead571d)

   </details>

1. <details>
   <summary> :green_circle: vm-scsi
   </summary>

   * Mount disk
     ![image](https://github.com/user-attachments/assets/06f5f1fa-b413-466d-b9d6-8392bfa120df)
   * Gen test data
     ![image](https://github.com/user-attachments/assets/3a3eb2ab-c2c0-45f6-a337-8cfc09fb85e1)
   * Reboot and data does not broken
     ![image](https://github.com/user-attachments/assets/99dcca8e-c2b1-4f74-a855-33730ead571d)
   </details>


### Backup Restore (node-0 disable LHv2)
1. <details>
   <summary> :black_circle: Snapshot VM and snapshot
   </summary>

   Track on harvester/harvester/issues/6710
   </details>

   > Not support yet

1. <details>
   <summary> :red_circle: Backup VM
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a24a2794-e992-4d8d-8e31-9accffe5efe2)
   * longhorn-manager on <i>node-0</i>
     ![image](https://github.com/user-attachments/assets/0ebd7e20-c636-455d-9bcc-f3253f4fb486)
   * longhorn-manager on <i>node-1</i>
     ![image](https://github.com/user-attachments/assets/9ee288ff-0be3-44be-ad0b-492a34db992a)
   </details>

   > Fail if <i>node-0</i> not enable LHv2 engine
   > harvester/harvester/issues/6866

### Backup Restore (All node enables LHv2)
1. <details>
   <summary> :green_circle: Backup VM
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8ef64b89-163a-4bf4-8ef3-2b6a30c94ced)
   </details>

1. <details>
   <summary> :green_circle: Restore New
   </summary>

   * Restore
     ![image](https://github.com/user-attachments/assets/79ea0a3e-8de3-42cb-9026-d8fdbb70f18f)
   * `Running` and data is not broken
     ![image](https://github.com/user-attachments/assets/c023c016-cab0-4716-87b3-ff834bc70651)
   * Volume storage class is correct
     ![image](https://github.com/user-attachments/assets/b49351bd-d595-4951-96f8-6d4524368508)
   </details>

1. <details>
   <summary> :green_circle: Restore Replace
   </summary>

   * Restore
     ![image](https://github.com/user-attachments/assets/e8971ea3-01ff-443a-a81e-38310da506af)
   * `Running` and data is not broken
     ![image](https://github.com/user-attachments/assets/e8a59302-5298-4277-9346-719f7c39655a)
   * Volume storage class is correct
     ![image](https://github.com/user-attachments/assets/fe1762b0-456e-459f-a9b1-601c2f52a9a1)
   </details>

### Migrate
1. <details>
   <summary> :black_circle: Live Migrate
   </summary>

   </details>

   > Not support yet

1. <details>
   <summary> :green_circle: Stop and start on different node
   </summary>

   * Current VM running on _node-0_
     ![image](https://github.com/user-attachments/assets/4340f574-4b3f-4d6b-9e5d-aec324ff1c90)
   * Stop VM
     ![image](https://github.com/user-attachments/assets/630c7624-28c3-47d0-86ac-df122ce8bdf7)
   * Cordon _node-0_
     ![image](https://github.com/user-attachments/assets/15412ba4-3c15-42fc-9477-93f2e14348c9)
   * Start VM, should `Running` on _node-1_ and data is not broken
     ![image](https://github.com/user-attachments/assets/82ead585-ce1c-425c-9aab-d1ce2237e293)
   </details>



### Rancher Integration
1. <details>
   <summary> :green_circle: Provision RKE2 cluster with extra <b>LHv1</b> disk
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e8ebef31-f821-46c0-a095-2c9c0d4028e3)
   </details>

1. <details>
   <summary> :red_circle: Provision RKE2 cluster with extra <b>LHv2</b> disk
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f89e107c-bf1e-44d7-b4ae-d52e83d61844)
   </details>

   >  virt-launcher stuck at `ContainerCreating` due to `FailedMapVolume`
   > harvester/harvester/issues/6868

1. <details>
   <summary> :white_circle: Scale Up and scale down
   </summary>
   </details>

**Comment by albinsun** [comment]
Provide some negtive tests, looks good.


## Environment
* `harvester-v1.4.0-rc4`
  * Profile: 2 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`

## Disable LHv2 engine on a node w/ running VM w/ LHv2 volume 
1. <details>
   <summary> :green_circle: Disable LHv2 ening on the node VM <code>Running</code>
   </summary>
   
   * VM running on node-1  
     ![image](https://github.com/user-attachments/assets/32162869-9dc1-442e-96a8-863853d426a3)
   * Volume status
     ![image](https://github.com/user-attachments/assets/1450e87b-32fd-4f26-b96a-b4fd898f6db9)
   * Disbale LHv2 engine on node-1
     ![image](https://github.com/user-attachments/assets/a78b873a-1d0e-4075-bc21-fb5c3b4abe06)
   </details>

1. <details>
   <summary> :green_circle: Disk should becomes not <code>Ready</code> and VM is not `Running` (Due to not support live migration yet)
   </summary>
   
   * Disk not Ready
     ![image](https://github.com/user-attachments/assets/0c3614d6-7e24-4ff1-a813-d7b76bedefdf)
   * Volume status
     ![image](https://github.com/user-attachments/assets/5189b37c-35c9-46bc-a211-f2740511ac72)
   * VM becomes `Starting` due to `FailedAttachVolume`
     ![image](https://github.com/user-attachments/assets/8418d5c7-b793-48df-a38f-b6d80e619cd2)
   </details>
   
1. <details>
   <summary> :green_circle: Enable LHv2 Engine again
   </summary>
   
   * Enable LHv2 engine on node-1 again
     ![image](https://github.com/user-attachments/assets/533399b9-c3e0-4cbe-ac38-33b38e7748ec)
   * LHv2 Disk should be Ready
     ![image](https://github.com/user-attachments/assets/a751c293-850e-4aa6-891a-ec1706fb2721)
   </details>

1. <details>
   <summary> :yellow_circle: VM should be <code>Running</code> again
   </summary>
   
   * VM still `Starting`
     `![image](https://github.com/user-attachments/assets/8418d5c7-b793-48df-a38f-b6d80e619cd2)
   * Reboot VM bring it back and data looks fine
     ![image](https://github.com/user-attachments/assets/31934161-1e8e-4e58-acec-7b0737508fa4)
   </details>
   
   > VM still `Starting` but reboot brings it back and data looks fine.
   

## Unexpectedly delete LHv2 disk on a node which has running VM w/ LHv2 volume 
1. <details>
   <summary> :green_circle: Remove LHv2 disk on the node which VM <code>Running</code>
   </summary>
    
   * VM on node-0
     ![image](https://github.com/user-attachments/assets/826664c0-745c-425d-ad9f-3a618c2aa371)
   * Volume status
     ![image](https://github.com/user-attachments/assets/f116c700-5049-4ed2-b621-4a2e43075161)
   * Follow https://docs.harvesterhci.io/v1.4/host/#remove-disks to delete disk
     ![image](https://github.com/user-attachments/assets/84831ec4-60e0-4382-928b-8178dfaae9e3)
     ![image](https://github.com/user-attachments/assets/aa0ca492-2d4d-4247-8f84-06ee6ebaedfd)
   </details>
   
1. <details>
   <summary> :green_circle: VM should still accessible but with unhealthy volume
   </summary>
   
   * Check VM status, still running and data not broken
     ![image](https://github.com/user-attachments/assets/89c39493-b5d7-4be5-a67e-f8f301f45670)
   * Volume status
     ![image](https://github.com/user-attachments/assets/d5a9bc6c-f97f-4505-8829-e2c53165ba4f)
   </details>

1. <details>
   <summary> :green_circle: Adding the LHv2 disk back, volume replica should be satisfied again.
   </summary>
   
   * Adding the disk back
     ![image](https://github.com/user-attachments/assets/3f972a66-337d-4d44-bcca-7c30137f5c24)
   * Volume replica satisfy again
     ![image](https://github.com/user-attachments/assets/4934b25c-8f6d-4686-9566-b0071100c03c)
   </details>
    


## Upgrade from `v1.3.2`
> Test along with single node upgrade release testing.

**Comment by albinsun** [comment]
Summrize scenarios test result
1. :green_circle: Toggle V2 Data Engine
1. :red_circle: Attach Disk using Longhorn V2 (CSI) Provisioner
   * https://github.com/harvester/harvester/issues/6861
     > Works in ipxe-example but hit problem in baremetal env.
1. :green_circle: Create Storage Class and Unbound Volume
1. :green_circle: Create VM with extra LHv2 volume and differnt bus
1. :red_circle: Backup Restore
   * harvester#6866
1. :green_circle: Migrate (Off and start on the other node)
1. :yellow_circle: Rancher Integration
   * harvester#6868
1. :green_circle:  Negtive cases
   * Disable LHv2 engine on a node w/ running VM w/ LHv2 volume
   * Unexpectedly delete LHv2 disk on a node which has running VM w/ LHv2 volume

**Comment by albinsun** [comment]
Close as the main feature works and trace related ticket respecctively.
