### ISSUE TITLE
[ENHANCEMENT] Remove Simplified Chinese translations

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5388]
**Is your enhancement related to a problem? Please describe.**
Because Simplified Chinese is not maintained anymore ([reference](https://github.com/harvester/harvester/issues/5384#issuecomment-2003465811)), we could remove the entry which changes language.

If we don't plan to remove it, it might cause bad user experience which there would be a lot of untranslated words in Simplified Chinese over the time, including documentation.

**Describe the solution you'd like**
Only remove the entry instead of removing all translated words.

**Describe alternatives you've considered**
If there is no possible to add Simplified Chinese back, actually we could remove all translated words.

**Additional context**
None

**Comment by Yu-Jack** [comment]
@bk201 Besides dashboard, I think we should also remove Simplified Chinese in documentation, WDYT?

**Comment by bk201** [comment]
I think it will be more consistent if we also drop the doc translation. We can bring it back if we have contributors in the future.

**Comment by a110605** [comment]
Discussed with Neil MacDougall, we only remove Chinese translation in harvester dashboard but keep it exist in rancher dashboard for now. 

Since Rancher dashboard still has Chinese translation, we need to check with product manager whether to remove it or not. 

Note. harvester Rancher embedded mode uses translation files ([shell/store/i18n.js](https://github.com/rancher/dashboard/blob/master/shell/store/i18n.js), [shell/assets/translations/*.yaml](https://github.com/rancher/dashboard/tree/master/shell/assets/translations)) from rancher code base. 

cc @torchiaf , @bk201.

**Comment by brandboat** [comment]
Test OK on [v1.4.0-rc2](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc2), close as fixed.

## Environment
* [v1.4.0-rc2](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc2)
  * Profile: 1 node QEMU/KVM (8C/16G/250G)
  * ui-source: `Auto`
* rancher/rancher:v2.9.1

## Test Steps
✅  Go to harvester login page, user is unable to change translation at the bottom left corner.
![image](https://github.com/user-attachments/assets/8c1731a7-aa3c-4ae6-a5e4-e15fb493e6cc)
✅ Login harvester -> there is no language preference at the bottom of navigation side bar.
 ![image](https://github.com/user-attachments/assets/79833b68-5fa1-4dd7-9703-e75adac9ce9d)
✅ Go to Preferences, there is no language translation dropdown.
![image](https://github.com/user-attachments/assets/a1180684-2f2b-4957-bac2-cdfa1ec418f0)
✅ Rancher embedded harvester UI still has simplified Chinese translation
![image](https://github.com/user-attachments/assets/996bc0b9-2a43-4dfa-a02c-995192299a9c)
