### ISSUE TITLE
[BUG] Harvester is flooded with Terminating VMs if namespace is out of storage quota

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5433]
**Describe the bug**
Harvester is flooded with Terminating VMs if the namespace is out of storage quota.

Harvester tries creating VM, fails, creates one another, fails again, and so on. The VMs are stuck in Terminating state, and the Rancher GUI becomes very slow quickly after hundreds of these VMs.

**To Reproduce**

- Create a cluster in a namespace with enough quota
- Adjust the namespace storage quota to have less available storage than the root disk of a new VM. CPU and memory quota must be plenty, enough to be extended with a VM.
- Scale up the pool

**Expected behavior**
To be clarified

**Environment**
- Harvester 1.2.1
- Underlying Infrastructure: Baremetal

**Comment by TachunLin** [comment]
Verifying **failed** on `v1.4-eaf3009a-head` (24/11/05) and `v1.4.0-rc5` on Rancher v2.8.5 and v2.8.9. 
Move the issue to implement for further investigation. 

### Test Result on Rancher v2.9.2
<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation on virtual machine creation $~~$</summary>

1. When we create the second vm to exceed the namespace quota, it would prompt error message to prevent to proceed

  ```
  admission webhook "validator.harvesterhci.io" denied the request: storage insufficient resources due to resource quota
  ```
  
  ![image](https://github.com/user-attachments/assets/4d32b17e-b522-44f8-a353-3e448f9f88ee)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation when clone virtual machine and change volume size $~~$</summary>

1. When we edit the volume size of the cloned vm to exceed the namespace quota, it would prompt error message to prevent to proceed 

  ![image](https://github.com/user-attachments/assets/001bb4c8-f510-4719-b681-ad4b10f716a0)

2. When we change the volume size to not exceed the namespace quota, it could change correctly

  ![image](https://github.com/user-attachments/assets/9a3946c7-98d6-42cb-81d4-b4e103aef955)


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation when clone virtual machine with clone volume size $~~$</summary>

1. When we clone a vm with volume to the new one but exceed the namespace quota, it would prompt error message to prevent to proceed

![image](https://github.com/user-attachments/assets/18f3fe16-e8fa-4c35-8f8b-7ba7cf822a53)



 </details>

### Test Result on Rancher v2.8.5 (with v1.4-head) 
<details><summary>$\color{red}{\textsf{Failed}}$ Test namespace resource quota limitation on virtual machine creation $~~$</summary>

Track in issue: #6953 

1. When we try to create the namespace on Rancher v2.8.5, it can't load the namespace creation page content well

![image](https://github.com/user-attachments/assets/363c7ef7-3edb-479f-8678-9882abf03b5f)


2. If we enter something and click create, it would prompt the failure

  ![image](https://github.com/user-attachments/assets/fbf56f0a-de92-4751-bc78-5f1944de0c95)
  
  ```
  Failed to parse body: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
  ```



 </details>


### Test Result on Rancher v2.8.9 (with Harvester v1.4.0-rc5)
<details><summary>$\color{red}{\textsf{Failed}}$ Test namespace resource quota limitation on virtual machine creation $~~$</summary>

Track in issue: #6953 

1. When we try to create the namespace on Rancher v2.8.5, it can't load the namespace creation page content well too.

![image](https://github.com/user-attachments/assets/a78763df-54a4-4d52-94ca-30085587ef6d)


2. If we enter something and click create, it would prompt the failure

  ![image](https://github.com/user-attachments/assets/bdbd33aa-d39b-4cb8-8d7f-e719c45b877b)
  
  ```
  Failed to parse body: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}
  ```

https://github.com/user-attachments/assets/4f5cd32e-2ce7-404a-bf16-f058ac99e9b3




 </details>

### Test Information
* Test Environment: Single and three nodes kvm machines
* Harvester version: 

### Verify Steps
<details><summary> Test namespace resource quota limitation on virtual machine creation </summary>

1. Import Harvester to Rancher
2. Access Harvester from Rancher virtualization management 
3. Go to `Projects/Namespaces` and create a new project `test-project`
4. In the Resource Quotas tab, add Storage Reservation and use 20000 MiB as project limit and 12000 MiB as namespace default limit
  ![image](https://github.com/user-attachments/assets/b0a52f0e-06a7-4700-879c-bbbd09638bbc)

5. Create a new namespace named `quota-test` in the previously created project. Take over the suggested resource quota of `12 GiB`.

  ![image](https://github.com/user-attachments/assets/368c52f3-ff59-4b27-a8f1-91e6304806d5)


6. Create a new VM with the namespace `quota-test`. In Volumes, make sure the volume occupies 10 GiB.

  ![image](https://github.com/user-attachments/assets/f3539ab2-6ec5-4b02-bbcb-ab96b2b90ea0)


7. Create a second VM with the same parameters and press Create.
8. The second VM shouldn't be created and an error message should be displayed at the top of the form.

</details>

<details><summary> Test namespace resource quota limitation when clone virtual machine and change volume size </summary>

1. Import Harvester to Rancher
2. Access Harvester from Rancher virtualization management 
3. Go to `Projects/Namespaces` and create a new project `test-project`
4. In the Resource Quotas tab, add Storage Reservation and use 20000 MiB as project limit and 12000 MiB as namespace default limit

5. Create a new namespace named `quota-test` in the previously created project. Take over the suggested resource quota of `12 GiB`.



6. Create a new VM `vm` with the namespace `quota-test`. In Volumes, make sure the volume occupies `5 GiB`.

  ![image](https://github.com/user-attachments/assets/a1216d22-efa0-4b06-b11d-bb0d4795df88)


7. Create a second VM named `vm2` by cloning from `vm1`. 

8. Check the clone volume data checkbox.
![image](https://github.com/user-attachments/assets/e3a0f9c2-43c9-410c-ad3a-53dc08a4bb33)

9. The VM should be created and started. All should be fine.
10. Edit VM `vm2` by choosing Edit Config in the action menu.
11.  Go to the Volumes tab and change the Size field from `5 GiB` to `7 GiB`
12.  An admission webhook error should be displayed at the top saying `admission webhook "validator.harvesterhci.io" denied the request: storage insufficient resources due to resource quota`
13. Change the Size to `6 GiB` and press Save. 
14. An error message please stop the VM before resizing volumes should be displayed at the top.
![image](https://github.com/user-attachments/assets/193c2485-fd77-4679-a6c8-5297bba095af)

15. Stop VM `vm2` and repeat step 13 
16. This time the modification should be applied without an error.

</details>



<details><summary> Test namespace resource quota limitation when clone virtual machine with volume data </summary>

1. Import Harvester to Rancher
2. Access Harvester from Rancher virtualization management 
3. Go to `Projects/Namespaces` and create a new project `test-project`
4. In the Resource Quotas tab, add Storage Reservation and use 20000 MiB as project limit and 12000 MiB as namespace default limit

5. Create a new namespace named `quota-test` in the previously created project. Take over the suggested resource quota of `12 GiB`.



6. Create a new VM `vm1` with the namespace `quota-test`. In Volumes, make sure the volume occupies `7 GiB`.

  ![image](https://github.com/user-attachments/assets/0491528b-ccda-4642-ba4f-09a2b48a9348)

7. Press Create. The VM should be created and started. All should be fine.
8. Stop the `vm1` vm
9. Clone the `vm1` to `vm2` vm 
10. Check the `clone volume data` checkbox in the displayed dialog. 
11. An error message should be displayed: `admission webhook "validator.harvesterhci.io" denied the request: storage insufficient resources due to resource quota.`

</details>

**Comment by TachunLin** [comment]
When verify this issue on Rancher `v2.8.5` and `v2.8.9` with latest Harvester `v1.4-head` and `v1.4.0-rc5`.

I found when I try to create namespace under the created project, it can't load the page content and create namespace 

  ![image](https://github.com/user-attachments/assets/867c57ed-3ea9-4fa6-bd10-6e4a105ba63f)


  https://github.com/user-attachments/assets/0d4859af-dc76-4cd2-9c17-ce588893caf2

I create another issue #6953 to track. 

@votdev, @torchiaf, 
Could you help to check whether the issue comes from backend or frontend. Thanks.

**Comment by TachunLin** [comment]
After use yaml template to create namespace to bypass blocker #6953 
Retest **PASS** on `v1.4.0-rc5` with Rancher `v2.8.9`. Close this issue.

### Test Result on Rancher v2.8.9
<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation on virtual machine creation $~~$</summary>

1. When we create the second vm to exceed the namespace quota, it would prompt error message to prevent to proceed

  ```
  admission webhook "validator.harvesterhci.io" denied the request: storage insufficient resources due to resource quota
  ```
  
  ![image](https://github.com/user-attachments/assets/a486c790-7ab9-4691-8e04-2bbf07ad1ac1)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation when clone virtual machine and change volume size $~~$</summary>

1. When we edit the volume size of the cloned vm to exceed the namespace quota, it would prompt error message to prevent to proceed 

  ![image](https://github.com/user-attachments/assets/fe32cf2d-3578-4d33-902c-7ea0d9a0b362)


2. When we change the volume size to not exceed the namespace quota, it could change correctly

  ![image](https://github.com/user-attachments/assets/dee1cd7b-a000-4f7f-8170-3fadc6163fb0)


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Test namespace resource quota limitation when clone virtual machine with clone volume size $~~$</summary>

1. When we clone a vm with volume to the new one but exceed the namespace quota, it would prompt error message to prevent to proceed

  ![image](https://github.com/user-attachments/assets/1d977092-ec2a-4f59-ac3f-d0c0357aa2d2)



 </details>





### Test Information
* Test Environment: Single and three nodes kvm machines
* Harvester version: v1.4.0-rc5
* Rancher version: v2.8.9

### Verify Steps

<details><summary> Workaround to create namespace on Rancher v2.8.x </summary>

1. Prepare the following namespace yaml template ( From the working environment) 

  ```
  apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      field.cattle.io/containerDefaultResourceLimit: '{}'
      field.cattle.io/projectId: c-m-vlxx7wwp:p-8ksw8
      field.cattle.io/resourceQuota: '{"limit":{"requestsStorage":"12000Mi"}}'
      lifecycle.cattle.io/create.namespace-auth: "true"
    labels:
      field.cattle.io/projectId: p-8ksw8
      kubernetes.io/metadata.name: quota-test
    name: quota-test
  ```

2. Replace the `field.cattle.io/projectId` and ` field.cattle.io/projectId` to your existing environment 

3. Access Harvester node and switch to root 
4. Use `kubectl create -f {file.yaml} to create the namespace.  

</details>

<details><summary> Test step </summary>

  Refer to https://github.com/harvester/harvester/issues/5433#issuecomment-2457021671

</details>
