### ISSUE TITLE
[Question] CPU Usage no data on the vm metrics

### ISSUE THREAD

**Issue by charnet1019** [harvester/harvester#5439]
mode: Standalone
harvester version: 1.3.0

![image](https://github.com/harvester/harvester/assets/18616254/111a98d2-8d93-4bf1-ba97-3b0b15262fa0)
![image](https://github.com/harvester/harvester/assets/18616254/1da78fd8-c6a4-4e07-bdea-c1ecf5bf9ba3)

**Comment by Yu-Jack** [comment]
Hi @charnet1019 , thank you for raising this issue. According to https://github.com/kubevirt/kubevirt/blob/v1.1.0/docs/metrics.md, the reason is metric name should be `kubevirt_vmi_vcpu_seconds_total` instead of `kubevirt_vmi_vcpu_seconds`.

Current workaround way you could follow:

For `Harvester VM Dashboard` Dashboard

1. Find the `cattle-dashboards/harvester-vm-dashboard` in ConfigMap
2. Change `kubevirt_vmi_vcpu_seconds` to `kubevirt_vmi_vcpu_seconds_total` in L74.

For `Harvester VM Info Detail` Dashboard

1. Find the `cattle-dashboards/harvester-vm-detail-dashboard` in ConfigMap
2. Change `kubevirt_vmi_vcpu_seconds` to `kubevirt_vmi_vcpu_seconds_total` in L80 and between L594 and L635.
3. Change `kubevirt_vmi_storage_read_times_ms_total` to `kubevirt_vmi_storage_read_times_seconds_total` in L313.
4. Change `kubevirt_vmi_storage_write_times_ms_total` to `kubevirt_vmi_storage_write_times_seconds_total` in L321.

**Comment by charnet1019** [comment]
Resolved, thanks.
