### ISSUE TITLE
network ui related changes

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#545]
1.  Add vlan configuration on the setting page
2.  When the network configuration is all unavailable, the create button should be unavailable
3.  If the network (vlan) configuration is useful in the vm, when the network is not available, you need to add prompt information to the vm list
4.  Delete the state in the network page

**Comment by DoNotSayYes** [comment]
1. If the default NIC value does not match any of the NICs of the host, an error message will appear
![image](https://user-images.githubusercontent.com/57614736/112814128-86cb1780-90b1-11eb-94d7-315a65c786e5.png)
2. Editing the default NIC value will not be applied to any node, users are required to disable the VLAN setting and enable it again so that the new value could be applied to all nodes. 
3. Users are also allowed to choose the NIC by editing the node individually.
4. Users cannot create a VLAN until at least one of the nodes' NIC is configured correctly.
5. VLANs only can be created or deleted, and also can be viewed details, no other actions are available.
