### ISSUE TITLE
[BUG] Deleting the cluster will not synchronize the deletion of the load balancer

### ISSUE THREAD

**Issue by zerchin** [harvester/harvester#5522]
**Describe the bug**
Create an RKE2 cluster based on the Harvester provider on the Rancher UI. Create a service of type "load balancer". We can see on the Harvester UI that a load balancer has been synchronously created. However, if the cluster is directly deleted at this time, it cannot be synchronously deleted in the "load balancer" of the "Harvester UI".

**Environment**
 - Harvester ISO version: v1.2.1
 - Rancher: v2.7.9

**Comment by niusmallnan** [comment]
@rebeccazzzz I'm an enterprise customer. We pay for Harvester support from SUSE.
I don't think this is a community issue, we opened a SCC ticket for something similar. The support team confirmed that this was a bug.

Can you please review this issue and check if it can be included in the milestone?

**Comment by w13915984028** [comment]
This issue is similar to https://github.com/harvester/harvester/issues/2825, we already have an enhancement request to upstream Rancher https://github.com/rancher/rancher/issues/46025

When a guest cluster is deleted, only Rancher knows this, the harvester-cloud-provider, harvester-cis-driver have no knowledge. 

It caused those issues: customized LB&IP, volume are not removed on Harvester.

We need to cooperate with Rancher to have interface like `ClusterDelete`.

FYI @votdev @FrankYang0529 @Vicente-Cheng @starbops

**Comment by w13915984028** [comment]
Duplicated with #1460 , track with the former.
