### ISSUE TITLE
[BUG] `guaranteed-engine-manager-cpu` and `guaranteed-replica-manager-cpu` settings are no longer supported

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5568]
**Describe the bug**

Longhorn's `guaranteed-engine-manager-cpu` and `guaranteed-replica-manager-cpu` settings are [no longer supported](https://longhorn.io/docs/1.5.4/deploy/important-notes/#instance-managers-consolidated) and replaced by [guaranteed-instance-manager-cpu](https://longhorn.io/docs/1.5.4/references/settings/#guaranteed-instance-manager-cpu).

Note this applies to the upcoming v1.2.2 release (Longhorn v1.5.5) and v1.3.0 (Longhorn v1.6.0). v1.2.1 still uses Longhorn v1.4.3 and doesn't have this issue.

**To Reproduce**
1. Install the harvester with the two configurations:
- https://docs.harvesterhci.io/v1.3/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedenginemanagercpu
- https://docs.harvesterhci.io/v1.3/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedreplicamanagercpu
2. These settings don't take effect.

**Expected behavior**

- We should support configuring the CPU on instance-manager pod with the [guaranteed-instance-manager-cpu](https://longhorn.io/docs/1.5.4/references/settings/#guaranteed-instance-manager-cpu) setting.
- We should update the document.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
@albinsun It looks like all v1.3/v1.2 backport issues are all verified. Can you also help check this main issue?

**Comment by albinsun** [comment]
## Test Result
Test **FAIL** as behavior is not identical to `v1.3`/`v1.2`.


### Environment
* `harvester-v1.4.0-dev-20240918`
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: `Auto`


### Prerequisite
1. <details>
   <summary> VM => ⋮ => Migrate 
   </summary>
  
   * Check 1
     SCREENSHOT
   </details>


### Scenarios
#### w/o `guaranteedInstanceManagerCPU`
1. <details open>
   <summary> :yellow_circle: No any configs -> cpu should be <code>960m</code> (8 x 1000m x 0.12 (default value))
   </summary>
   
   > `842 / 0.12 / 1000 ~ 7.02`
   > Behavior not the same as `v1.3.1`
   * v1.4
     ![image](https://github.com/user-attachments/assets/e5411cad-ca27-461d-9962-04037b71c079)
   * v1.3.1
     ![image](https://github.com/harvester/harvester/assets/2773781/6f18db2b-0540-4848-b682-2022d8f3869f)
     Ref. https://github.com/harvester/harvester/issues/5571#issuecomment-2137125624
   </details>

1. <details>
   <summary> :white_circle: Even with <code>guaranteedEngineManagerCPU</code> & <code>guaranteedReplicaManagerCPU</code> -> cpu should still <code>960m</code>
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>


#### w/ `guaranteedInstanceManagerCPU`
1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: 10</code> -> cpu should be <code>800m</code> (8 x 1000m x 0.10)
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>

1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: 13</code> -> cpu should be <code>960m</code> (8 x 1000m x 0.12)
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>

1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: 12</code> -> cpu should be <code>960m</code> (8 x 1000m x 12)
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>

1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: 0</code> -> Not to explicit requests CPU limit
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>

1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: q</code> -> Should error due to non-integer
   </summary>
  
   * Check 1
     SCREENSHOT
   * Check 2 :x:
     > :warning:: Fail due to reason  
     SCREENSHOT
   </details>


### Supportbundle


### Note
1. ...


### QA Check List
- [ ] Labels: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
- [ ] Update corresponding tests ticket lables


[^1]: https://docs.harvesterhci.io/v1.4/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedinstancemanagercpu
[^2]: https://docs.harvesterhci.io/v1.3/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedenginemanagercpu
[^3]: https://docs.harvesterhci.io/v1.3/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedreplicamanagercpu

**Comment by albinsun** [comment]
Hi @w13915984028 ,
We found the behavior is not indentical to `v1.3`/`v1.2`.
Using the same 8 cpus, I get `842m` (`7.02 x 1000m x 0.12`) on `v1.4` instead of `960m` (`8 x 1000m x 0.12`) on `v1.3`/`v1.2`.
Is this expected?

cc. @bk201

**Comment by w13915984028** [comment]
@albinsun The differences should be related to `node usable CPU`, in each version (with different rke2&k8s) the node usable CPU may vary as  k8s reserves some CPU for itself at first,  when LH  tries to get a percentage CPU from the node, it is based on the `kubeNode.Status.Allocatable.Cpu`, not the physical available CPU on the node.  

For the validation, we can compare: the LH CPU with `[guaranteed-instance-manager-cpu]` and without (use the default value) in the same version, with bigger `guaranteed-instance-manager-cpu` LH get more CPU.

Comparing the absolute CPU value between different releases can be an reference. LH is not requesting an absolute value, but a percentage, there could be differences on the final computed value.

thanks.

LH CPU resources calculation code, there looks no change.

```
allocatableMilliCPU := float64(kubeNode.Status.Allocatable.Cpu().MilliValue())
```

https://github.com/longhorn/longhorn-manager/blob/a3768493385042b65da343d569daa9e977ebf928/controller/controller_manager.go#L273

https://github.com/longhorn/longhorn-manager/blob/3dde300284b4a7ca8dfa1c2757ee2c2613c766be/controller/controller_manager.go#L161

**Comment by albinsun** [comment]
Test **PASS**, close as fixed.


### Environment
* `harvester-v1.4.0-dev-20240918`
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: `Auto`
  * Allocatable CPU: `7.02`


### Scenarios
#### w/o `guaranteedInstanceManagerCPU`
1. <details>
   <summary> No any configs -> cpu should be <code>842m</code> :heavy_check_mark: 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e5411cad-ca27-461d-9962-04037b71c079)
   </details>

  > 7.02 x 1000m x 0.12 (default)

1. <details>
   <summary> Even with <code>guaranteedEngineManagerCPU</code> & <code>guaranteedReplicaManagerCPU</code> -> cpu should still <code>842m</code> :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/eddd8e17-cabb-4cdd-af18-e6d9524c2074)
   </details>

   > 7.02 x 1000m x 0.12 (default)

#### w/ `guaranteedInstanceManagerCPU`
1. <details>
   <summary>  <code>guaranteedInstanceManagerCPU: 10</code> -> cpu should be <code>702m</code> :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/3f902f51-ee2e-4672-a420-808f9de3a2e7)
   </details>

   > 7.02 x 1000m x 0.10

1. <details>
   <summary> <code>guaranteedInstanceManagerCPU: 13</code> -> cpu should be <code>842m</code> :heavy_check_mark: 
   </summary> 
   
   * PXE Server
     ![image](https://github.com/user-attachments/assets/d282c4c2-91c8-498c-868a-1d409df9cf79)
   * Harvester
     ![image](https://github.com/user-attachments/assets/526c55be-5d02-4eda-949e-fb28bd534d60)
   </details>

   > 7.02 x 1000m x 0.12 (default)


1. <details>
   <summary> <code>guaranteedInstanceManagerCPU: 0</code> -> Not to explicit requests CPU limit :heavy_check_mark: 
   </summary>
  
   * PXE
     ![image](https://github.com/user-attachments/assets/697bace6-275a-4f9a-846c-ba714b30bdcb)
   * Harvester
     ![image](https://github.com/user-attachments/assets/8553a3f1-9030-433a-aabd-f7de1557cce0)
   </details>

1. <details>
   <summary> :white_circle: <code>guaranteedInstanceManagerCPU: q</code> -> Should error due to non-integer :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/8bf39474-75c3-4901-be3e-5ca3b4e13d44)
   </details>


### Reference
1. https://docs.harvesterhci.io/v1.4/install/harvester-configuration#installharvesterlonghorndefault_settingsguaranteedinstancemanagercpu
2. https://longhorn.io/docs/1.7.1/references/settings/#guaranteed-instance-manager-cpu


### QA Check List
- [x] Labels: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
- [x] Update corresponding tests ticket lables
