### ISSUE TITLE
[FEATURE] Image upload

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#570]
We want to support users to upload images from the local desktop to the Harvester cluster.

**Comment by yaocw2020** [comment]
It has been supported in v0.2.0.

**Comment by yasker** [comment]
@yaocw2020 with the removal of MinIO, we won't able to support it anymore in v0.2.0.

**Comment by vtolstov** [comment]
Why minio remived?

**Comment by yasker** [comment]
@vtolstov Since MinIO is one more thing to maintain. We need to start MinIO in HA mode, and operate it. Also we need to support the component by ourselves if it's a part of stack. We once had an issue with MinIO lost service temporarily during certain circumstances, and have to rely on the upstream MinIO to fix it after a month.

With MinIO only used as an image store, and now Longhorn is able to store the information about the image (by using the backing image feature), we want to replace MinIO's image repo functionality with Longhorn itself.

**Comment by vtolstov** [comment]
Nice, thank you for explaining

**Comment by penghuima** [comment]
Before using the V0.1 version to create virtual machines, I was curious why users could not use local virtual machine images to create virtual machines, and there are two storage systems, MinIO, and longhorn, in the architecture of Harvester. MinIO, which is only used to store images. At that time, I wondered if longhorn could not be used to store images instead of MinIO.  I did not guess that MinIO would be banned in v0.2, which was shocked, but not so surprising.

**Comment by guangbochen** [comment]
this will depends on https://github.com/longhorn/longhorn/issues/2404

**Comment by ArtiePeterson** [comment]
> We want to support users to upload images from the local desktop to the Harvester cluster.

Awesome..

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head. Validated with ISO and live image.

**Comment by xeruf** [comment]
This should be adjusted: https://harvesterhci.io/import-image/
