### ISSUE TITLE
[FEATURE] Recurring snapshot/backup setup

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#572]
We should recommend and provide a way for the users to backup VM data periodly.

**Comment by weihanglo** [comment]
A possible user experience may be:

- When a user want to create a recurring backup
    1. A user goes to "Cron Jobs" page on the web UI.
    2. Then the user selects "create backup" job type and a dialog shows up.
    3. The user inputs [cron format] and select a VM to backup.
    4. The backup will start in schedule.
- A user also can check job status from the "Cron Jobs" page
   - A user can read their statuses directly.
   - A user can also read information of past jobs
 
Of course, we can  leverage `Job` and `CronJob`, which are K8s resource, so we just need to add cronjob actions API. No additional CR needed. We can tweak those statuses in a user-friendly to hide some implementation details as well.

Since [CronJobs] GA in K8s 1.21, the problem is, how much flexibility do we provide to users?

[CronJobs]: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
[cron format]: https://en.wikipedia.org/wiki/Cron

**Comment by yasker** [comment]
FYI: Longhorn already provides a scheduled backup mechanism.

**Comment by weihanglo** [comment]
That would be great if we can reuse Longhorn's [recurring job] feature by specifying longhorn volume `volume.spec.recurringJobs`. And because Longhorn already [validates recurring jobs input], we might want to patch the volume directly from Harvester web UI via RESTful API.

The questions are:

1. Do we accept highly coupling between Longhorn and Harvester web UI? Or should we introduce a new API to separate UI from implementation details? For the latter, we'll need to do input validation (including cron format) again for a true separation.
2. Usually, a VM might contain multiple volumes. In Harvester we treat custom resource `vmbackup` as a "volume group" for one-to-many VM-volume mapping. If we decide to use Longhorn recurring feature, we would need another way to maintain the relation between VM backup cronjobs and longhorn recurring jobs.

Note that we might want to specify [`AllowRecurringJobWhileVolumeDetached` setting] if using Longhorn's recurring backup feature.

Ref: https://longhorn.io/docs/1.1.2/snapshots-and-backups/scheduling-backups-and-snapshots/

[recurring job]: https://github.com/longhorn/longhorn-manager/blob/8583569b46ebd1288214cc726ace0dd54117cdb3/types/resource.go#L163-L169
[validates recurring jobs input]: https://github.com/longhorn/longhorn-manager/blob/8583569b46ebd1288214cc726ace0dd54117cdb3/manager/volume.go#L801-L832
[`AllowRecurringJobWhileVolumeDetached` setting]: https://github.com/longhorn/longhorn-manager/blob/8583569b46ebd1288214cc726ace0dd54117cdb3/controller/volume_controller.go#L2826-L2836

**Comment by weihanglo** [comment]
### Some snapshots from Longhorn UI

<details>

<summary>A button to show recurring job for each longhorn volume in volume page.</summary>

<img width="788" alt="image" src="https://user-images.githubusercontent.com/14314532/125542072-34c4ab01-b0b1-4948-bc8a-6c4cdc808b72.png">

</details>

<details>

<summary>Popup to show/add recurring jobs</summary>

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/14314532/125542104-be60e1cb-b9ea-41b4-b52b-e09397e62df8.png">

</details>

<details>

<summary>Cron format validation</summary>

<img width="930" alt="image" src="https://user-images.githubusercontent.com/14314532/125542109-9404cd21-4619-44f1-85f0-d043989c3386.png">

</details>

**Comment by yasker** [comment]
Push to post v1.0 GA.

**Comment by dseralathan** [comment]
@yasker @guangbochen 

is there any possibility to schedule VM backup  from Harvester GUI or CLI  from control plane node ? 

I would like to take daily backup of VMs and delete  the  last backup  with retention period of 3 days ..

**Comment by frankoonk** [comment]
Is there any progress on this?

**Comment by ne0YT** [comment]
in the meantime maybe it's possible by interacting with longhorn directly using some script on a vm?

**Comment by bk201** [comment]
> in the meantime maybe it's possible by interacting with longhorn directly using some script on a vm?

@ne0YT the backup action needs to start from Harvester because each Vm can contains many volumes. Harvester controller will maintain needed metadata in the backup store.

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/2756, I'll keep https://github.com/harvester/harvester/issues/2756 since it contains a more detail description and I'll link back Weihang's comment.

**Comment by abonillabeeche** [comment]
With this on 1.4, we need to solidify the strategy. I would be OK if the backup job is done via the Longhorn UI if the resulting backup shows up in Harvester. Or we copy the recurring features of Longhorn into Harvester,

**Comment by bk201** [comment]
We need to add known issue for https://github.com/longhorn/longhorn/issues/8742
