### ISSUE TITLE
[FEATURE] Soft reboot/shutdown

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#574]
We should support a graceful soft reboot/shutdown from the UI, to allow the VM and filesystem on it to have a chance to shutdown properly.

Guest agent might be required.

**Comment by weihanglo** [comment]
Given that KubeVirt already has [graceful shutdown feature] by specifying`VMspec.terminationGracePeriodSeconds`. The graceful shutdown is implemented as [ACPI power button signal]. And the force shutdown uses [`VIR_DOMAIN_DESTROY_GRACEFUL`] from libvirt, which equals sending SIGTERM to VM.

However, only [VM stop API] respects this value. [VM restart API] currently doesn't support graceful shutdown ([^1] [^2]) because K8s has not yet supported CRD graceful shutdown. But after diving into KubeVirt and doing some e2e tests , I found that a VM restart also respects `terminationGracePeriodSeconds`. Therefore, only the VM restart API blocks calls with a grace period greater than 0. The VM graceful restart itself would not be affected if VM has already been set with a `terminationGracePeriodSeconds` value.

The problem would be: **Does `terminationGracePeriodSeconds` meet our needs?** If this `terminationGracePeriodSeconds` is enough, then the next step is adding a new input field in Web UI. Since frontend can POST/PUT virtualmachine API directly, IMO there is no need to add code in Harvester backend. 

I may miss something important. Feel free to comment.

[graceful shutdown feature]: https://git.io/JCEZP
[ACPI power button signal]: https://git.io/JCEZZ
[`VIR_DOMAIN_DESTROY_GRACEFUL`]: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDestroyFlagsValues
[vm stop API]: https://kubevirt.io/api-reference/v0.43.0/operations.html#_v1stop
[VM restart API]: https://kubevirt.io/api-reference/v0.43.0/operations.html#_v1restart
[^1]: https://git.io/JCEnT
[^2]: https://git.io/JCEnc

**Comment by weihanglo** [comment]
Some facts

- [default grace period is 30 seconds](https://git.io/JCEY9)
- KubeVirt does not expose `guest-shutdown` qemu guest agent command as an shutdown option for any RESTful API

**Comment by futuretea** [comment]
link to https://github.com/kubevirt/kubevirt/issues/6669
Related PR: https://github.com/kubevirt/kubevirt/pull/6670

**Comment by nunix** [comment]
Hi team,

I'm currently seeing this behavior (not shutting down the VM) for Linux and Windows VMs.
I've tweaked the settings to reach a sort of middle ground, however the Harvester UI is not reflecting the "true" state of the VM.

Here is what I did and which results I have:
- Create/Modify a VM > edit the YAML config
- Replace the `spec.running` by `spec.runStrategy`
```yaml
...
spec:
  runStrategy: RerunOnFailure
...
```
- Add the KubeVirt `spec.spec.domain.features.acpi` capability
```yaml
...
spec:
  spec:
    domain:
      features:
        acpi:
          enabled: true
...
```
- Start/Connect to the VM
- Shutdown the VM

Results:
While the VM will correctly shutdown, Harvester UI will "hang" on `Starting` with the message `Virt-launcher pod is terminating`.
The `kubectl get pods` will show the VM pod as `Completed`  and `kubectl get vm` will show the VM as `Stopped`:
![image](https://user-images.githubusercontent.com/905874/151219354-c18d8655-0078-4c43-bd55-76ab0f15ef29.png)


Additional notes/hints:
When the VM is stopped, if I click on `Stop` and check the VM config, I can see that `spec.runStrategy` has switched to `halted`.


I hope this is clear 😄

**Comment by yasker** [comment]
@nunix Thanks for the info.

For shutting down VM to work correctly **from inside the VM**, a few takeaways here:
1. To prevent the VM from automatically being restarted, seems the `runStrategy: RerunOnFailure` is better.
2. `ACPI` has to be enabled to ensure the hypervisor can control/know the power cycle.
3. The VM pod seems will get into the `Completed` state and that's not being detected correctly by the Harvester, so it's stuck in `creating` in the UI.

Though the original issue was targeting shut down/reboot the VM gracefully **from the Harvester UI**, I do think we have a different issue here. I think a more accurate description of your issue would be `shutdown from inside the VM result in VM rebooting`?

**Comment by futuretea** [comment]
@DaiYuzeng for the UI part: added an action "softreboot" to virtualmachine.

UI prompt:
en: `Soft Reboot`
zh: `安全重启`

**Comment by DaiYuzeng** [comment]
PR from UI side merged, could you do a test, if there isn't any issue, move this issue to `Ready for testing`, thanks! @futuretea

**Comment by DaiYuzeng** [comment]
And could you confirm the checklist, thanks! @futuretea

**Comment by futuretea** [comment]
Test plan:
1. Create a VM
2. Waiting for the VM to become `Ready`
3. Exec the `softreboot` action through `Soft Reboot`
![image](https://user-images.githubusercontent.com/15064560/156735325-33434831-6f80-49f8-9f56-a93f2a91a1ac.png)
4. The VM will be rebooted (user can see that from console)

**Comment by lanfon72** [comment]
@futuretea do we also implement _soft shutdown_ function? Or will it be implemented in another issue?

**Comment by futuretea** [comment]
@lanfon72 according to https://github.com/harvester/harvester/issues/574#issuecomment-878978345 and https://github.com/harvester/harvester/issues/574#issuecomment-1059199246, our `Stop` action already  is soft shutdown

**Comment by futuretea** [comment]
The current logic for restart is："set termincationGracePeriod and delete the VMI pod to trigger a forced restart"

For the new `softreboot` action, it doesn't need to rebuild pod, no pod IP change, no need to reschedule, remount storage, faster restart time.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-da3f1778-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create a VM and wait until its state becomes **Running**
4. Open Web VNC and login to the VM
5. Click **Soft Reboot** function in the VM's functions
6. The Web VNC should not disconnected
7. The **IP Address** of the VM should not change
8. The **State** of the VM should not change

**Comment by fanlix** [comment]
* `Stop` = `soft stop`
* `Restart` = `soft stop` + `delete pod` + `create pod` + `mount disk, new nic/ip` + `normal start` 
* `Soft Reboot` = `soft stop` + `normal start`  (fast)
* os shutdown/reboot = nothing with vm
