### ISSUE TITLE
[BUG] Constantly switching the physical NIC of the node will cause an error to set the physical NIC of the node

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#594]
**Describe the bug**
Occasional, with a higher chance of occurrence
**To Reproduce**
1. Enable vlan setting, default physical NIC fill in eth0
2. Go to the network settings of the host node
3. Set eth1 as the physical NIC
4. Reset eth0 as the physical NIC
5. Repeat steps 3 and 4

![image.png](https://images.zenhubusercontent.com/6045fac39bfd93ea415d99ee/5d844409-e92f-4bed-b969-1ef3d07a9af9)
![image.png](https://images.zenhubusercontent.com/6045fac39bfd93ea415d99ee/f4dcdc15-742a-40c5-9f3d-abae525335cf)

**Environment:**
 - Harvester ISO version: master-c5a265d5-head
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
as long as the network configuration is matched with the last configured NIC this would be OK.
From the UI side, this is because when the user is constantly updating the object the WebSocket may not be able to receive the latest modified object instantly, and the error message already elaborates the reason.

**Comment by TangStone** [comment]
Validation passed in version master-95a5828a-head
