### ISSUE TITLE
[Question] Multi disk and raid controller setup

### ISSUE THREAD

**Issue by siku4** [harvester/harvester#6023]
Hi, 

I can't find any official recommendations or references about the physical hard disk or raid/storage controller setup. Maybe I'm just overlooking it.

We have several physical servers, each equipped with two system disks (3.84TB) and 4 data disks (7.68TB) via a hardware RAID controller. For the system volumes, we have created a RAID 1 with the two 3.84TB SSDs per server. 
For the Data Volume (VM Data / K8s Volumes) we want to use the remaining 7.68TB SSDs. Since Longhorn says it acts like a network RAID controller and creates corresponding redundancy of the later volumes through the distribution of multiple replicas to different physical disks, our plan is to configure the data SSDs on each RAID controller as JBOD and pass them directly to Harvester. But what confuses us now:

* We are performing an automatic installation via PXE, but we can only specify a single data disk in the configuration file. Adding further data disks requires manual intervention in the UI. Is there a way to automate this?
* In the[ Longhorn documentation](https://longhorn.io/docs/1.6.2/best-practices/#disk-space-management) it is recommended to aggregate the different disks into a single partition using LVM. Is it then advisable to pass each SSD directly through to Harvester? In view of this, does it not make sense to create a hardware RAID (e.g. RAID5) and also benefit from the functionalities of the RAID controller such as the detection of broken disks and automatic replacement (hot-spare)? In addition, we would then no longer have to add additional hard disks manually after the installation.

What are your multi disk setups and experiences?

**Comment by Vicente-Cheng** [comment]
Hi @siku4,

Thanks for raising this issue, we have a similar issue here: https://github.com/harvester/harvester/issues/3183
We will provide some documents on this topic with v1.4.0.

Here are some replies to your questions.

>We are performing an automatic installation via PXE, but we can only specify a single data disk in the configuration file. Adding further data disks requires manual intervention in the UI. Is there a way to automate this?

The Harvester manages the raw device through node-disk-manager. To automate this, you can use the [auto-disk-provision-paths](https://docs.harvesterhci.io/v1.3/advanced/index/#auto-disk-provision-paths-experimental).

>In the[ Longhorn documentation](https://longhorn.io/docs/1.6.2/best-practices/#disk-space-management) it is recommended to aggregate the different disks into a single partition using LVM. Is it then advisable to pass each SSD directly through to Harvester? In view of this, does it not make sense to create a hardware RAID (e.g. RAID5) and also benefit from the functionalities of the RAID controller such as the detection of broken disks and automatic replacement (hot-spare)? In addition, we would then no longer have to add additional hard disks manually after the installation.

Currently, the harvester node-disk-manager cannot provision the LVM as a Longhorn backend disk (For some reason, maybe we could do it in a later release). Hardware raid is the first choice if you want to aggregate the disk. As you mentioned, hardware raid benefits various features with a raid controller. It is simple if you use hardware raid because, from the system view, it looks like a raw device as usual. We could add it easily, whether on installation or through UI.

BTW, as a trade-off, you will take a potential risk with the raid rebuild (the large raid takes more time to rebuild and performance degrades). This is compared with using a single SSD directly.

**Comment by siku4** [comment]
Hi @Vicente-Cheng,

thanks for your detailed answer and linking the similar issue.

If I understand you right aggregating data disks using a hardware raid ist definitively a practicable setup and does not lead to any conflicts with Longhorns internal redundancy mechanisms, except in the case of a raid rebuild? I guess the problem here is that Longhorn is not able to detect a poor performance caused by the raid rebuild and thus does not "switch" the volume to one of the other replicas?

**Comment by Vicente-Cheng** [comment]
> Hi @Vicente-Cheng,
> 
> thanks for your detailed answer and linking the similar issue.
> 
> If I understand you right aggregating data disks using a hardware raid ist definitively a practicable setup and does not lead to any conflicts with Longhorns internal redundancy mechanisms, except in the case of a raid rebuild? I guess the problem here is that Longhorn is not able to detect a poor performance caused by the raid rebuild and thus does not "switch" the volume to one of the other replicas?

Hi @siku4, sorry for the late reply.

Yeah, as you mentioned, the main issue I'm worried about is the degraded performance when the raid is rebuilt. That might cause the volume performance to degrade.

For others, I thought using a hardware raid might be okay.
