### ISSUE TITLE
[BUG] generate_addon_csi.sh uses wrong kubeconfig server

### ISSUE THREAD

**Issue by dfaltum** [harvester/harvester#6118]
**Describe the bug**
If you're following [this](https://docs.harvesterhci.io/v1.3/rancher/csi-driver/#deploy-harvester-csi-driver) guide, you may experience some trouble with the generated kubeconfig. 

**To Reproduce**
If you run this script via Rancher provided kubeconfig or via SSH from the Harvester CP node, the following line will give you an incorrect kubectl server. For example:
```
++ kubectl config view -o 'jsonpath={.clusters[?(@.name == "default")].cluster.server}'
+ ENDPOINT=https://127.0.0.1:6443
```

**Expected behavior**
The kubeconfig file should contain an IP address that is reachable from outside of the cluster.

**Comment by Vicente-Cheng** [comment]
Hi @dfaltum,

Thanks for raising this issue.
I do some checks with that.

I would like to know where you executed this script.
On the Harvester cluster or the downstream cluster?

I thought the document was not very clear because the purpose was that we should run this script on the downstream cluster. And using the kubeconfig of the host harvester cluster.

**Comment by dfaltum** [comment]
Hi @Vicente-Cheng,
First, I've tried the script with an SSH login to the Harvester cluster. I also tried using the Harvester kubeconfig file provided by Rancher. So both approaches are problematic.

**Comment by Vicente-Cheng** [comment]
Hi @dfaltum, 

Thanks for the explanation.
I checked with the latest kubeconfig download from the rancher UI.

You are right. This should be fixed by your PR.
Thanks again for your fix!

**Comment by dfaltum** [comment]
https://github.com/harvester/harvester-csi-driver/pull/40 merged
