### ISSUE TITLE
[BUG] Loss of upstream Rancher cluster causes Harvester LB instability

### ISSUE THREAD

**Issue by Daemonslayer2048** [harvester/harvester#6135]
**Describe the bug**
If a Harvester guest cluster looses access to Rancher MCM the load balancer will begin to "bounce". The guest clusters kube-vip deployment will attempt to ensure the loadbalancer and for a short period become unavailable. This appears to be related to the use of Project scoped IP Pools as Harvester itself does not appear to share this concept with Rancher. 

**To Reproduce**
1. Create a Project scoped IP Pool. 
2. Consume IP via a loadbalancer in guest cluster
3. Disable Rancher MCM 
4. Observe load balancer begin bouncing 

**Expected behavior**
I expected the load balancer to continue working even if Rancher MCM goes down. 

**Support bundle**
N/A this cluster has been destroyed, can be reproduced upon request. 

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with commodity hardware

**Additional context**

**Comment by starbops** [comment]
Hi @Daemonslayer2048

Thank you for reporting. However, I'm unable to reproduce the case you mentioned by temporarily scaling down the Rancher Manager deployment to 0 in my own environment (with external Rancher v2.8.4 + Harvester v1.3.1 + guest RKE2 v1.28.10). Could you provide more information like the exact Kubernetes distribution you're using (e.g. RKE2) and its version? If possible, please help reproduce the issue and try to [collect the support bundle on the Harvester cluster](https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle) and also [collect the logs in the guest RKE2 cluster](https://www.suse.com/support/kb/doc/?id=000020191) so that we can better look into it.

**Comment by Daemonslayer2048** [comment]
Hey @starbops 

I apologize for the late response, I can test this by the end of the week and get you the relevant logs.

**Comment by Daemonslayer2048** [comment]
Well shoot, after many hours of attempting to reproduce the "bug" I am unable to do so in my new environment. Closing as I can't reproduce it myself.
