### ISSUE TITLE
[BUG] create vm failed after upgrade kubevirt to 1.2.0

### ISSUE THREAD

**Issue by Faker523** [harvester/harvester#6180]
**Describe the bug**

want to test the vm memory hotplug,so upgrade kubevirt to 1.2,but after upgrade, create vm failed by harvester
**To Reproduce**
1. upgrade kubevirt to 1.2
2. crate vm by using harvester dashboard

**Expected behavior**

create vm success
**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): lenovo
![企业微信截图_17210910908991](https://github.com/user-attachments/assets/b1cd85b2-9b55-46a2-8ba8-b1a373f02299)

**Additional context**

**Comment by Faker523** [comment]
anyone can help me ?

**Comment by FrankYang0529** [comment]
Hi @Faker523, we don't encourage to bump dependence by yourself, because it's not fully run e2e test for the combination. The CPU / Memory hotplug will be introduced in v1.5.0 (https://github.com/harvester/harvester/issues/5835). In Harvester v1.3.0, we already use KubeVirt v1.1.0. Memory hotplug was introduced in KubeVirt v1.1. Probably, you can follow this document to enable it.

https://kubevirt.io/user-guide/compute/memory_hotplug/

**Comment by Faker523** [comment]
@FrankYang0529  you mean harvester1.3.0 support KubeVirt v1.1.0. Memory hotplug？ but i do it as the https://kubevirt.io/user-guide/compute/memory_hotplug/, but i meet a problem,
 configuration:
    vmRolloutStrategy: "LiveUpdate"
    the config can not been insert into the kv kubevirt

** <nil>: Invalid value: "The edited file failed validation": ValidationError(KubeVirt.spec.configuration): unknown field "vmRolloutStrategy" in io.kubevirt.v1.KubeVirt.spec.configuration**

**Comment by Yu-Jack** [comment]
Hi @Faker523, I think this https://github.com/kubevirt/kubevirt/issues/11900 might be helpful

**Comment by FrankYang0529** [comment]
Hi @Yu-Jack, thanks for your link.

@Faker523, yeah, it's better to wait for KubeVirt v1.2, because there is some redesign. Also, we need some UI enhancement in Harvester. I tried the feature in Harvester v1.3.0. Although the VM can be migrated, it doesn't get correct memory in the VM.

1. Update KubeVirt CR.
```shell
kubectl --namespace harvester-system patch kv kubevirt -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates", "value": ["VMLiveUpdateFeatures"]}]' --type='json'
kubectl --namespace harvester-system patch kv kubevirt -p='[{"op": "add", "path": "/spec/workloadUpdateStrategy/workloadUpdateMethods", "value": ["LiveMigrate"]}]' --type='json'
```
2. Create a VM with cpu/memory/volume setup, but not click `Create` button. Please click `Edit as YAML` button.
3. In VM YAML, add following to VM spec. The `maxGuest` is the biggest memory which can be set in the VM. VM can't be live migrated to memory which is more than `maxGuest`.
```yaml
liveUpdateFeatures:
  memory:
    maxGuest: 2Gi
```
4. In VM YAML, add following to VM `spec.template.spec.domain`. The value is the initial memory for the VM.
```yaml
        memory:
          guest: 900Mi
```
5. In VM YAML, remove `spec.template.spec.domain.resources.limits.memory`.
6. Click `Create` button.
7. After VM is running, you can update memory:
```shell
kubectl patch vm vm-test -p='[{"op": "replace", "path": "/spec/template/spec/domain/memory/guest", "value": "1800Mi"}]' --type='json'
```
8. The result is not good on my cluster:
```shell
> kubectl get vmi vm-test -o json | jq .status.memory
{
  "guestAtBoot": "900Mi",
  "guestCurrent": "900Mi",
  "guestRequested": "1800Mi"
}
```

**Comment by Faker523** [comment]
@Yu-Jack  thank you ， i will try it

**Comment by Faker523** [comment]
@FrankYang0529  ok， i will test it using kubevirt1.1.0 today

**Comment by Faker523** [comment]
@FrankYang0529  btw, when harvester will support kubevirt 1.2.0?
