### ISSUE TITLE
[BUG] Deleting virtual machine restore CR makes restoring VM can't restart

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6207]
**Describe the bug**
Directly deleting `virtualmachinerestore` CR makes resotring VM can't restart

**To Reproduce**
1. Creating backup for a VM
2. Restoring backup to a new VM
3. Deleting the related `virtualmachinerestore` CR with `kubectl`
4. Restarting the restored VM
5. The restarting will be rejected with `Error
start virtual machine <restored VM> failed, persistentvolumeclaims "<restored PVC>" not found`

**Environment**
 - Harvester ISO version: master-head (`8b80f821f9da22a678ecef018a01d0fe241715a4`)

**Additional context**
The restoring VM's pvc has `ownerReferences` points to the matched CR `virtualmahcinerestore`, for example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ....
  name: restore-vm-b1-434fd2c1-fd7a-4c0f-bda7-9ac31becef13-disk-0
  namespace: default
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineRestore
    name: restore-vm-b1-5xcnx
    uid: 434fd2c1-fd7a-4c0f-bda7-9ac31becef13
  resourceVersion: "100298"
  uid: c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
spec:
  accessModes:
  - ReadWriteMany
  ....
  storageClassName: longhorn-image-l8mlc
  volumeMode: Block
  volumeName: pvc-c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
```

so once the `virtualmachinerestore` CR is deleted, the PVC will turn into `Terminating` status. If the restoring VM is stopped, the PVC will be completely deleted.

**Comment by bk201** [comment]
set priority to 2 because the `virtualmachinerestore` resources are not available in the GUI.

**Comment by brandboat** [comment]
Test OK on [v1.4.0-dev-20240918](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918), close as fixed.

## Environment
* [`v1.4.0-dev-20240918`](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`

## Test Steps
- Creating backup for a VM
- Restoring backup to a new VM `test2`
- Deleting the related VirtualMachineRestore CR by kubectl, and deletion operation was rejected, console print error `The request is invalid: spec.target.name: The restore can't be removed because the restored VM test2 exists`, work as expected.
  <img width="979" alt="image" src="https://github.com/user-attachments/assets/954f3f1a-97bf-43fa-9b36-87a172addf5a">
- After deleted VM `test2`, related VirtualMachineRestore CR was removed either.
