### ISSUE TITLE
[BUG] Unable to add new disk

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#6531]
### Describe the bug
Unable to add new disk
![image](https://github.com/user-attachments/assets/3e2778be-c1a5-4e26-8171-4c7864ed475b)
![image](https://github.com/user-attachments/assets/05a5cf15-15d6-4aad-a3a6-8a4643c8751e)
![image](https://github.com/user-attachments/assets/4e40b1a3-046c-4296-bf53-bb3b719f4776)
![image](https://github.com/user-attachments/assets/e20da73e-4b38-4a9d-b446-efc9d6ce8822)

### To Reproduce
1. Install Harvester with any nodes having additional disks
2. Edit Host page to add new disk

### Expected behavior
Disk should added successfully

## Environment:
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**
 - Harvester ISO version: **v1.4.0-dev-20240830**
 - **ui-source** Option: **Auto**

### Additional context
The screenshot in `v1.3.2` (same configuration in qemu/KVM)
![image](https://github.com/user-attachments/assets/479417a0-699f-4943-8198-6540e96051db)

**Comment by khushboo-rancher** [comment]
@lanfon72 Is this happening on 1.3.2 also? Is this regression?

**Comment by tserong** [comment]
From the screenshot it looks like node-disk-manager has picked up a dm device, which we actually don't want it to be doing. This is probably because multipath is enabled in the initrd, which has since been fixed by https://github.com/harvester/harvester-installer/pull/831, but even so, we still need to make sure NDM doesn't use dm devices. I'm working in this area ATM anyway, so I'll take this for further investigation /cc @Vicente-Cheng @ibrokethecloud

**Comment by albinsun** [comment]
Looks ok in `v1.3.2`
![image](https://github.com/user-attachments/assets/0860355b-707d-45f5-80e6-fceeea5fb3d9)

**Comment by Vicente-Cheng** [comment]
As @tserong mentioned, this regression is introduced with external root disk support (because we need the multipath) and fixed by the PR https://github.com/harvester/harvester-installer/pull/831.

However, for the NDM side, we could improve by skipping the dm device. We could create another issue for this enhancement.

**Comment by tserong** [comment]
Yeah, the issue is to do with how we map WWNs back through `/dev/disk/by-id/` paths in `ResolvePersistentDevPath()` in NDM when multipath is active.

@lanfon72 if you've still got that system running, I'd be interested to see the output of `kubectl -n longhorn-system get bds -o yaml`. I suspect you'll see something like this:

```
- apiVersion: harvesterhci.io/v1beta1
  kind: BlockDevice
  ...
  spec:
    devPath: /dev/sda
    ...
  status:
    deviceStatus:
      ...
      devPath: /dev/dm-0
```

...which indicates that it picked up the device originally from `/dev/sda`, then later got confused by multipath being active (which is why `status.deviceStatus.devPath` shows `/dev/dm-0`).

This won't be a problem for the next sprint release (because of the fix @Vicente-Cheng mentioned), but I will still do some work to improve `ResolvePersistentDevPath()`.

**Comment by lanfon72** [comment]
> Yeah, the issue is to do with how we map WWNs back through `/dev/disk/by-id/` paths in `ResolvePersistentDevPath()` in NDM when multipath is active.
> 
> @lanfon72 if you've still got that system running, I'd be interested to see the output of `kubectl -n longhorn-system get bds -o yaml`. I suspect you'll see something like this:
> 
> ```
> - apiVersion: harvesterhci.io/v1beta1
>   kind: BlockDevice
>   ...
>   spec:
>     devPath: /dev/sda
>     ...
>   status:
>     deviceStatus:
>       ...
>       devPath: /dev/dm-0
> ```
> 
> ...which indicates that it picked up the device originally from `/dev/sda`, then later got confused by multipath being active (which is why `status.deviceStatus.devPath` shows `/dev/dm-0`).
> 
> This won't be a problem for the next sprint release (because of the fix @Vicente-Cheng mentioned), but I will still do some work to improve `ResolvePersistentDevPath()`.

I think the problem is:
1. the disk path is not correct. (user will expect some path like `/dev/sda`)
2. disk added, but information of storage/path/scheduling  is not available.

The output of `kubectl -n longhorn-system get bds -o yaml`:
![image](https://github.com/user-attachments/assets/e90834ee-6751-4091-83d1-488a901bae33)

but `wwn` is *unknown*, which is not a correct value. (we did input `WWN` for the additional disk)

**Comment by tserong** [comment]
Thanks @lanfon72. The WWN would have been there originally, but it gets wiped in a subsequent update when `status.deviceStatus.devPath` changes to `/dev/dm-0`. I've traced this through the code, now I just need to fix it :-)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/ad0af8d2-674b-4b92-919d-734274ed4405)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps
- Follow *Steps to reproduce* in https://github.com/harvester/harvester/issues/6531#issue-2514752402
