### ISSUE TITLE
[QUESTION] Replacing Harvester node, how to handle the disc with Longhorn replicas?

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#6537]
I have Harvester 1.3.1 cluster:
- 2 baremetal Dell Precision master&workers, each having 2 NVMe drives 1TB. One is OS & Longhorn storage and, second - Longhorn storage.
- witness node on VM, no storage.

Now I bought new Dell Precision with GPU card, and want to replace one master&worker node.
AND I want to use NVMe drive from my existing node in the new node: both of 1TB drives.

How can I do that?

The easiest way:
- drain & stop Dell Precision node
- move NVMe drives to new node
- install Harvester on new node, format all NVMe drives.
- let Longhorn replicate the data from the, which still in the cluster.

That should work. But during the installation I would have only one node with data and ALL data will need to be replicated after the installation to new node.

Would it be more efficient to NOT to format NVMe drive with Longhorn replicas and let Harvester or Longhorn recognize existing data on it? Will that work?

**Comment by Vicente-Cheng** [comment]
Hi @SlavikCA,

So, the `new Dell Precision with GPU card` only has one disk, and you would like to move the NVME from the old machine to this new machine, right?

I thought your procedure looked correct.

>Would it be more efficient to NOT to format NVMe drive with Longhorn replicas and let Harvester or Longhorn recognize existing data on it? Will that work?

No, because the disk will be in the new `nodes.longhorn.io`. The replica cannot be reused w/o any manual config.


Did you know your whole data usage on NVME disk?
If the usage is smaller than the default disk of the new machine, I thought we could try the below stpes.
1. join the new node to the cluster -> we have 3 nodes + 1 witness.
2. set the nvme (on the old machine) to unschedulable (on Longhorn UI)
3. remove the replicas on the above nvme, and these replicas should be moved to the default disk on the new node
4. move nvme to the new node (physically) it should take a short time, so the replica should be back
5. repeat the steps 2 and 3 for the default disk on the old machine
6. and it should move these replicas to the nvme (now on the new machine)
7. check there is no replica on the old machine, then you can remove it.

What do you think about the above steps?

**Comment by SlavikCA** [comment]
I think the steps you suggested make sense.
But in my case, the new system has much smaller NVMe, so I can't follow that way.

I tried to shutdown one existing node, move NVMe and install new node.
But when I shutdown the node - the cluster stopped working. I can't figure out why... I tried to reboot nodes, nothing helped. etcd doesn't come up, api doesn't come up...

So, I'm restoring from backup now

**Comment by Vicente-Cheng** [comment]
Hi @SlavikCA, I am curious this situation.
Did you mean you have three node clusters (2 master + 1 witness), and the cluster is down when you just shutdown one master?

This should not happen.
We verified this operation. Could you try to reproduce it?

I would like to take a look at this. Thanks!

**Comment by dfaltum** [comment]
Hi @SlavikCA,
Perhaps you had a fourth node in the past which was deleted (but not from the etcd members)?
