### ISSUE TITLE
[BUG] Users should not be allowed to delete the admin user

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#670]
**Describe the bug**
Users should not be allowed to delete the admin user

**To Reproduce**
1. Go to the Users page
2. Choose admin user and delete it

**Result**
Admin user can be deleted, harvester is not accessible without any existing user.
![image](https://user-images.githubusercontent.com/57614736/114122564-17f88480-9923-11eb-8f82-de71811a5682.png)
![image](https://user-images.githubusercontent.com/57614736/114123304-a0c3f000-9924-11eb-9f43-f7e5131bbd9c.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by guangbochen** [comment]
since we are going to remove the harvester users and using the Rancher users only, so it should be fine to allow admin users to delete the users as ensure default admin is supported by Rancher https://rancher.com/docs/rancher/v2.x/en/faq/technical/#i-deleted-deactivated-the-last-admin-how-can-i-fix-it
