### ISSUE TITLE
[BUG] Fail to Add disk with LHv2 Provisioner

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6861]
**Describe the bug**
Fail to add SCSI and NVME disk using LHv2 Provisioner

**To Reproduce**
1. Enable LHv2 Engine in Settings
   * Harvester
     ![image](https://github.com/user-attachments/assets/62e3125e-8ab8-4e6b-8d27-1eb5655060ca)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/262d77a8-a59c-4f51-b015-75924ab0e5eb)

1. :x: Add /dev/sdb disk with LHv2 Provisioner
   ![image](https://github.com/user-attachments/assets/f709d124-22e9-40cf-bbdb-9292ae258d95)

1. :x: Add NVME disk with LHv2 Provisioner
   ![image](https://github.com/user-attachments/assets/9e160e7f-121a-4541-810e-af65a5a636aa)

**Expected behavior**
Disk should be able to add using LHv2 Prosisioner

**Support bundle**
[supportbundle_9aca9f59-bed0-4893-a649-fa43153cba67_2024-10-23T10-14-14Z.zip](https://github.com/user-attachments/files/17489257/supportbundle_9aca9f59-bed0-4893-a649-fa43153cba67_2024-10-23T10-14-14Z.zip)

**Environment**
 - Harvester ISO version: `v1.4.0-rc3`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with HPE ProLiantDL360Gen9

**Additional context**
1. Longhorn Nodes
   ![image](https://github.com/user-attachments/assets/4c88b056-f91b-46d2-abc2-3d4ad82bce7f)

**Comment by albinsun** [comment]
Retest on `v1.4.0-rc4` with `mkfs.ext4 -E nodiscard /target/disk`, successfully add NVME this time but still fail on SCSI disk with block size error.
Note that delete disk also fails.


## Environment
* `harvester-v1.4.0-rc4`
  * Profile: Single node AMD64 Bare-metal
  * ui-source: `Auto`


## Test Steps
1. <details>
   <summary> :green_circle: Enable LHv2 data engine
   </summary>
   
   * Harvester
     ![image](https://github.com/user-attachments/assets/5e8e371d-6787-4b13-89fa-35e6c0bbd1fb)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/d2a4e238-c946-471d-b103-a052d45f99be)
   </details>


1. <details>
   <summary> :green_circle: Add NVME disk
   </summary>
   
   * Format
     ![image](https://github.com/user-attachments/assets/0b53f54a-a296-4505-b751-43198ea91ea4)
   * Add 
     ![image](https://github.com/user-attachments/assets/e806f120-f58d-4372-aecc-57922b09d001)
   * Disk State
     ![image](https://github.com/user-attachments/assets/bde0afe6-d958-4e7d-95c2-012e69bb5fa7)
   </details>

1. <details>
   <summary> :red_circle: Add SCSI disk
   </summary>
   
   * :heavy_check_mark: Format and Add from UI
     ![image](https://github.com/user-attachments/assets/22ca5ca9-5c3b-4007-8ac5-93bc1fade2f1)
   * :heavy_check_mark: Add
     ![image](https://github.com/user-attachments/assets/284096fe-a886-4b0b-8b36-d56533f7a7af)
   * :x: Disk State
     * Host
       ![image](https://github.com/user-attachments/assets/6c85990e-3353-4ce7-af83-b757954e7fe3)
     * instance-manager
       ![image](https://github.com/user-attachments/assets/090879fe-ae3a-48d5-8cd4-64957b701e21)
     * blockdevice
       ![image](https://github.com/user-attachments/assets/17db90c8-f5f7-4229-be59-6f475cbba59c)
   </details>

   > [longhorn-instance-manager] ... *ERROR*: Disk size 1799797127168 is not a multiple of block size 4096


1. <details>
   <summary> :red_circle: Delete SCSI disk
   </summary>
   
   * :heavy_check_mark: Delete from UI
     ![image](https://github.com/user-attachments/assets/c58d1e8b-8e5c-4ddf-ab8c-6920226eada4)
   * :x: instance-manager
     ![image](https://github.com/user-attachments/assets/ddde189f-0386-4f25-903b-82600f806ba6)
   * blockdevice
     ![image](https://github.com/user-attachments/assets/9f038d81-5063-4090-8d4b-940c4bd248e9)
   </details>

   > [longhorn-instance-manager] ... msg="Failed to get lvstore with UUID or disk name ...
   > [longhorn-instance-manager] ... level=error msg="Failed to delete disk" ...



## Logs
[supportbundle_FailToAddScsiWithLhv2_2024-10-23T14-33-01Z.zip](https://github.com/user-attachments/files/17493622/supportbundle_FailToAddScsiWithLhv2_2024-10-23T14-33-01Z.zip)

**Comment by tserong** [comment]
When adding SCSI disks, Longhorn will use the aio bdev driver, which AIUI from a discussion with @damiasan assumes a block size of 4096 bytes, and thus requires the device to be an exact multiple of 4096 bytes. I don't know if this is documented anywhere, but AFAIK this is not something we can fix or change in harvester.

The disk deletion behaviour is correct under the circumstances. The disk was never completely added to longhorn, which is why we get the "failed to delete disk" errors in the instance manager log.

The device will remain in the list of block devices, as it is still attached to the system. When you add a disk using the harvester GUI, it changes the block device state from Unprovisioned to Provisioned, and the new disk appears in the Longhorn GUI. If you later delete the disk using the harvester GUI, it changes the block device state from Provisioned back to Unprovisioned, and the disk disappears from the Longhorn GUI. But it will always remain in that list of block devices, unless you physically remove or detach the disk.

**Comment by bk201** [comment]
4096 is by design, please check https://github.com/longhorn/go-spdk-helper/blob/main/pkg/spdk/client/advanced.go#L17

**Comment by tserong** [comment]
OK, I have reproduced the controller scan error here in a VM:

````
[2024-10-30 04:12:17.322755] nvme.c: 821:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2024-10-30 04:12:17.322777] bdev_nvme.c:6263:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 0000:00:02.0)
````

This appears to be a red herring. It only occurs in my testing on v1.4.0-rc3 (node-disk-manager v0.7.5) if there is _already_ a filesystem on the nvme device when the device is provisioned. It does not occur if the disk is completely blank (no filesystem) - in this case the disk provisions just fine. It also does not occur on harvester v1.4.0-rc4 or newer (node-disk-manager v0.7.6+), because that version of NDM includes the call to wipefs when provisioning the disk (https://github.com/harvester/node-disk-manager/pull/157)

Here's what should work:

1. Completely blank NVMe device (with no filesystem created at all), should still be recognised by node-disk-manager and shown in the list of devices to add, provided the NVMe device has a WWN. It should be possible to provision this disk for LHv2 without running `mkfs.ext4` on it first.
2. An NVMe device with an existing filesystem should also work, because it'll be wiped anyway by NDM as part of the provisioning process.

We need to re-test the above two scenarios on v1.4.0-rc4 or newer on real hardware just to be sure (my test was on VMs)

**Comment by tserong** [comment]
> 4096 is by design, please check https://github.com/longhorn/go-spdk-helper/blob/main/pkg/spdk/client/advanced.go#L17

Just to add to my earlier comment on this topic, 4096 only applies to the aio bdev driver, so, virtual SCSI disks, SSDs, any disk with a WWN that node-disk-manager recognises but that's not actually an NVMe. For NVMe devices, Longhorn defaults to the nvme bdev driver which picks up the block size of the underlying device, so will work fine whatever the size is.

**Comment by DamiaSan** [comment]
If you have an NVMe device attached by the kernel, running SPDK  script `setup.sh` should detach the device from the kernel driver so that SPDK could attach to it ... But I don't know if this is true also if an existing filesystem is present on the device ...

**Comment by albinsun** [comment]
Retest on `v1.4-daf68d56-head` without `mkfs.ext4 -E nodiscard /target/disk` this time and works as expected, close ticket.


## Environment
* `harvester-v1.4-daf68d56-head`
  * Profile: Single node AMD64 Bare-metal
  * ui-source: `Auto`


## Test Steps
1. <details>
   <summary> :green_circle: Enable LHv2 data engine
   </summary>
   
   * Harvester
     ![image](https://github.com/user-attachments/assets/be399399-3f95-4c6a-9095-77dbbcfe6bfd)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/507fb44d-0e10-428f-8d8c-0f7d22a55bbb)

   </details>


1. <details>
   <summary> :green_circle: Should be able to add a NVME disk
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d355bce3-bbf8-4e9f-85b2-2e1ecdc03b94)
   </details>

1. <details>
   <summary> :green_circle: Should fail to add a non-4096 bytes multiples SCSI disk
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d355bce3-bbf8-4e9f-85b2-2e1ecdc03b94)
   </details>

1. <details>
   <summary> :green_circle: Create VM with extra volume using LHv2 disk
   </summary>
   
   * VM
     ![image](https://github.com/user-attachments/assets/1216af0b-ba3e-41bc-9120-9bcc172c434d)
   * Volume
     ![image](https://github.com/user-attachments/assets/73d1094e-3a2f-4b15-b482-373092b22120)
   </details>

1. <details>
   <summary> :green_circle: Reboot and data still valid.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/36cfde90-fbf7-4cf0-9af7-8210c9565af8)
   </details>

1. <details>
   <summary> :red_circle: Create VM with extra volume using LHv2 disk
   </summary>
   
   ![image](https://github.com/user-attachments/assets/88b460df-689d-4401-a7ae-95f5207f1f14)
   </details>

   > Trace by #6868
