### ISSUE TITLE
[BUG] UI VM Labels function seems not working

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6877]
**Describe the bug**

When validating issue https://github.com/harvester/harvester/issues/6727#issuecomment-2437954704, noticed that:

UI VM Labels function seems not working

**To Reproduce**

A manually added label is not shown on UI
![image](https://github.com/user-attachments/assets/92ea4b84-e18e-467b-abca-5b2b3326a2a0)

![image](https://github.com/user-attachments/assets/e9dea455-197e-401a-a7bb-675c4cbc2ff4)

**Expected behavior**

The add label function should be well.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.4.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
cc @torchiaf @a110605 @TachunLin @khushboo-rancher @bk201 

I put this issue on v1.5.0 for now, but it looks to be better solved on v1.4.0, thanks.

**Comment by torchiaf** [comment]
@w13915984028 I think you are adding the label in `metadata.labels` but instanceLabels come from `spec.template.metadata.labels`.
Also, consider that `harvesterhci.io/maintain-mode-strategy` is explicity removed from the Instance Labels tab since it's the source field of the Migratable checkbox field. In any case, it'll be visible in the YAML.

**Comment by w13915984028** [comment]
![image](https://github.com/user-attachments/assets/1c0d07a6-fab0-42ba-9e77-5084a5254731)

**Comment by w13915984028** [comment]
OK, just confirmed this label is configured via the option:

![image](https://github.com/user-attachments/assets/882ded46-4e9a-4441-a116-670e8209e753)
