### ISSUE TITLE
[BUG] Nvidia Driver runtime crashes, because it can't install the driver, can't enable SR-IOV GPU Devices

### ISSUE THREAD

**Issue by vidosits** [harvester/harvester#7000]
**Describe the bug**
The nvidia-driver-runtime container crashes with on Harvester 1.3 with the NVIDIA-GRID-Linux-KVM-550.127.06-550.127.05-553.24 host driver.

Chart version for the nvidia-driver-toolkit is harvester/nvidia-driver-runtime version=0.4.1.
The image repository and tag is gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240822

The error from the pod is

```
ERROR: Unable to load the kernel module 'nvidia-vgpu-vfio.ko'.  This happens most frequently when this kernel module was built against the wrong or improperly configured kernel sources, with a version of gcc that differs from the one used to build the target kernel, or if another driver, such as nouveau, is present and prevents the NVIDIA kernel module from obtaining ownership of the NVIDIA device(s), or no NVIDIA device installed in this system is supported by this NVIDIA Linux graphics driver release.

Please see the log entries 'Kernel module load error' and 'Kernel messages' at the end of the file '/var/log/nvidia-installer.log' for more information.


ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

Kernel module compilation complete.
Kernel module load error: No such file or directory
Kernel messages:
[ 8092.606206] nvidia_vgpu_vfio: Unknown symbol mdev_register_driver (err -2)
[ 8092.606220] nvidia_vgpu_vfio: Unknown symbol mtype_get_type_group_id (err -2)
[ 8092.708166] nvidia-nvlink: Unregistered Nvlink Core, major device number 511
[ 8159.119306] nvidia: externally supported module, setting X kernel taint flag.
[ 8159.122261] nvidia-nvlink: Nvlink Core is being initialized, major device number 511
[ 8159.122267] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  550.127.06  Wed Oct  9 12:31:27 UTC 2024
[ 8159.506546] nvidia_vgpu_vfio: Unknown symbol mtype_get_parent_dev (err -2)
[ 8159.506587] nvidia_vgpu_vfio: Unknown symbol mdev_parent_dev (err -2)
[ 8159.506604] nvidia_vgpu_vfio: Unknown symbol mdev_unregister_driver (err -2)
```

**To Reproduce**
1. Install nvidia-driver-runtime addon
2. Set image to gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240822
3. Upgrade chart version with `helm upgrade -n harvester-system --reuse-values nvidia-driver-toolkit harvester/nvidia-driver-runtime --version=0.4.1`
4. Nvidia driver runtime pod starts, but enters a crash loop after a while

**Expected behavior**
We should be able to enable the SR-IOV GPU devices after the above installation.

**Support bundle**
bundle is too big to upload

Tokens, passwords, and secrets are automatically removed from support bundles. If you feel it's not appropriate to share the bundle files publicly, please consider:
- Wait for a developer to reach you and provide the bundle file by any secure method.
- Join our Slack community (https://rancher-users.slack.com/archives/C01GKHKAG0K) to provide the bundle.
- Send the bundle to harvester-support-bundle@suse.com with the correct issue ID.  -->

**Environment**
 - Harvester ISO version:  1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Gigabyte G482-Z54, 8x RTX A6000

**Additional context**
The 8x A6000-s show up in SR-IOV GPU Devices screen, but they can't be enabled. The pci-device-controller pod has more info, says it can't find the nvidia-driver-ctr container, I'm guessing because the above runtime container crashes.
![image](https://github.com/user-attachments/assets/0cd4ef0d-8ed4-4b1c-a5cf-a1798ec93179)
We tried following the suggestions from issue #6487

**Comment by vidosits** [comment]
Support bundle sent in an email to harvester-support-bundle@suse.com

**Comment by samueldewever** [comment]
I Will test the new version tomorrow on our labo to see if i can reproduce it

**Comment by samueldewever** [comment]
@vidosits 
I have tested the new NVIDIA version in our lab and it works without an issue

Questions:
a) Are you doing an upgrade from previous version? If yes, its important that you first stop all VMs with VGPU, go on the host, rmmod the nvidia_vfio_vfio and afterwards nvidia. As long thats not done, the upgrade will fail as it will not be able to unload the kernel modules on the host (at a reboot of the host it should also run properly)

b) Can you confirm that you are pointing towards the vGPU file (NVIDIA-Linux-x86_64-550.127.06-vgpu-kvm.run) and NOT the guest drivers

c) However the error doesn't seems fully related, I noticed on our side that this version also installs additional firmware drivers and loads these on the host. Have a look to https://github.com/harvester/harvester/issues/6487 , as you might need the same overlay network on the host to make sure it is going to work. This should be fixed with the release of 1.4.0

I have tested on 1.3.2 in combination with Nvidia chart 0.4.1 and image rancher/harvester-nvidia-driver-toolkit v1.3-20240904

**Comment by vidosits** [comment]
Hey @samueldewever ,

Thanks for taking a look.

a) Not an upgrade, although we have tried multiple combinations of the container image *and the helm chart*. In Harvester 1.3.0 I think by default the helm chart is 0.1.1, which we have upgraded to v0.4.1.

The more interesting question to me is the rmmod-ing of the nvidia_vfio_vfio. We have not done any of that. We enabled the nvidia-container-toolkit addon with the host drivers + the container. No VM is currently running with any vGPU-s or even PCI passthroughs. And the host has been restarted multiple times after that. Do we still need to do any of that?
lsmod | grep -i nvidia comes back empty, I don't think anything is loaded, but I may be wrong.

b) Yeah, the .run files come from a "Host_Drivers" directory of the unzipped KVM driver from the Nvidia enterprise site

c) By overlay network, you mean the overlay fs you made [here](https://github.com/harvester/harvester/issues/6487#issuecomment-2384192708) with the systemd unit? 
There's a comment [here](https://github.com/harvester/harvester/issues/6487#issuecomment-2387247970) that suggests to follow that, although the v0.4.1 chart maps /lib/firmware into the daemonset. I'm wondering if we still need the systemd unit then? Is the chart's v0.4.1 incompatible with Harvester's v1.3.0?

**Comment by samueldewever** [comment]
> c) By overlay network, you mean the overlay fs you made [here](https://github.com/harvester/harvester/issues/6487#issuecomment-2384192708) with the systemd unit?

@vidosits 
when lsmod nvidia is empty , they are indeed not loaded. 

The overlay is still needed untill version 1.4.0. The problem is that without the overlay, your pod will not be able to write into /lib/firmware as on the host /lib/firmware is read only filesystem (Suse Linux enterprise micro); 

My guess is that actually the installation fails because he can't write that object to /lib/firmware because he will get read-only filesystem back. 

Is the POD actually booting or failing during boot? In case it boots, you could get into the pod console and run the installer manually to see where it fails
You could access the pod via https://xxx/dashboard/c/local/explorer/pod/ . Then search for the nvidia-driver-runtime on your host.

**Comment by vidosits** [comment]
Thanks, makes sense. We're upgrading our cluster from v1.3.0 -> v1.3.1 -> v1.3.2. Once it's done, we'll add the systemd unit and make /lib/firmware writable for the pod.

The pod starts, downloads the .run file from the HTTP server, installs it, but then exits with an error message saying nvidia.ko could not be loaded and then restarts.

Once the update is done, I'll report back with the exact logs, although they may already be contained in the support bundle that we've sent, I'm not exactly sure.

**Comment by samueldewever** [comment]
> Thanks, makes sense. We're upgrading our cluster from v1.3.0 -> v1.3.1 -> v1.3.2. Once it's done, we'll add the systemd unit and make /lib/firmware writable for the pod.
> 
> The pod starts, downloads the .run file from the HTTP server, installs it, but then exits with an error message saying nvidia.ko could not be loaded and then restarts.
> 
> Once the update is done, I'll report back with the exact logs, although they may already be contained in the support bundle that we've sent, I'm not exactly sure.

Perfect. 
I don't have access to your support bundle, as I am not from suse, but happy to have a look in case it would not work ,as we had issues with nvidia-driver as well recently and have spend quit some time in debugging, so its still fresh in my head ;-)

**Comment by bk201** [comment]
@vidosits I can confirm a support bundle has been received. Thanks.

**Comment by ibrokethecloud** [comment]
the likely issue is the wrong image being used. the bundle indicates you are using a custom image i built `gmehta3/harvester-nvidia-driver-toolkit:v1.3-20240822`

The driver toolkit image is built to work specifically with a particular version of harvester  and this is to ensure the kernel headers etc match the exact version of the Harvester OS. In this case the error is valid likely because kernel headers are a different version from the underlying OS.

Can you please try the install with  image`rancher/harvester-nvidia-driver-toolkit:v1.3-20240307`, which was the container image built for 1.3.0

**Comment by vidosits** [comment]
Thanks @ibrokethecloud , In the meantime we've upgraded to Harvester v1.3.2, is the `rancher/harvester-nvidia-driver-toolkit:v1.3-20240307` image version still the best one to use or is there one specifically for v1.3.2?

**Comment by samueldewever** [comment]
> rancher/harvester-nvidia-driver-toolkit v1.3-20240904

We run rancher/harvester-nvidia-driver-toolkit v1.3-20240904 on our current 1.3.2 release.

**Comment by vidosits** [comment]
Okay, so, it all works now :tada: :
- We've upgraded to Harvester v1.3.2
- /lib/firmware has an overlay so it's writable on the host. I can see the `nvidia` firmware directory in it, which was created by the `nvidia-driver-toolkit`
- Running `v0.4.1` version of the chart
- The image is `rancher/harvester-nvidia-driver-toolkit:v1.3-20240904`
- We can see **and enable** the SR-IOV GPU Devices on their respective screen
![image](https://github.com/user-attachments/assets/b38bb8fa-ab59-4615-8ca9-63b39f6ef5c8)

- The `nvidia-driver-toolkit` container's log does not indicate any errors. No crashes, no restarts, just a nice reassuring output of:
```
Post-install sanity check passed.

Installation of the NVIDIA Accelerated Graphics Driver for Linux-x86_64 (version: 550.127.06) is now complete.

running nvidia vgpud
Creating '/dev/char' directory
```

And we can see and enable vGPUs:

![image](https://github.com/user-attachments/assets/49d3fa21-5e58-4920-a59a-f141bd6285aa)


Thank you @samueldewever , @ibrokethecloud  and @bk201
