### ISSUE TITLE
[DOC] README.md > Harvester > Overview > ISO - link reports Page Not Found

### ISSUE THREAD

**Issue by simonfogliato** [harvester/harvester#7202]
[DOC] README.md > Harvester > Overview > ISO - link reports Page Not Found

https://github.com/harvester/harvester?tab=readme-ov-file#overview

The ISO link "https://docs.harvesterhci.io/latest/install/index" in step 1 goes to "Page Not Found".

```
Page Not Found
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

**Comment by Yu-Jack** [comment]
Hi @simonfogliato , thank you for contribution. 

I think we should modify the harvester/docs instead of README in harvester/harvester. We have a [redirection rule in harvester/docs](https://github.com/harvester/docs/blob/0a760e324169c0a6cb56fd9e81dbeba5f1c6cc0a/docusaurus.config.js#L267-L271). So, we need to add a new rule to redirect from `/latest/install/index` to `/v1.4/install/index`.

cc @bk201 @jillian-maroket, do you know why we missed adding a redirection rule  from `/latest/install/index` to `/v1.4/install/index`? I'm just curious. If you’re not certain about the reason, we can just add it back.

**Comment by jillian-maroket** [comment]
@Yu-Jack @bk201 Adding redirect rules wasn't part of the process that I learned during project handover. I don't edit the config file unless I'm adding a new doc version or troubleshooting search-related issues.

IMO, the harvester/harvester readme shouldn't contain information that already exists in the doc. That readme is for the repository and not the entire project.

**Comment by Yu-Jack** [comment]
@jillian-maroket Got it, then I think we can modify this description if we need to. We should probably also consider that some users might directly refer to this readme for installation or other usages. Alternatively, even we could remove most of content and guide users to check our documentation first. 

> **Easy to install:** Since Harvester ships as a bootable appliance image, you can install it directly on a bare metal server with the ISO(https://github.com/harvester/harvester/releases) image or automatically install it using iPXE scripts(https://docs.harvesterhci.io/latest/install/pxe-boot-install).

**Comment by bk201** [comment]
Thanks, @simonfogliato, the PR https://github.com/harvester/harvester/pull/7211 is merged.
