### ISSUE TITLE
[Question] Assigning multiple network to VM breaks external access

### ISSUE THREAD

**Issue by rrrai** [harvester/harvester#758]
**Describe the bug**
Create VM (tested on Focal Ubuntu 20.04 server)
Assign multiple network Virtio (10.x.x.x) and external Vlan with static IP. This is home network. Router set to assign IP's from 192.167.1.XX and Harvester Hosts/VM have 192.168.0.XX to use. On starting the VM's they can be accessed from outside but cannot ping any machines from VM's

**To Reproduce**
1. Setup a VM with network config as show below
![image](https://user-images.githubusercontent.com/50937667/115984380-82890180-a56c-11eb-9831-e743c8c7c8bb.png)
![image](https://user-images.githubusercontent.com/50937667/115984454-c1b75280-a56c-11eb-8724-990f49f2983f.png)
2. Start the VM's and access from console or SSH. 
SSH access using static IP
![image](https://user-images.githubusercontent.com/50937667/115984552-3d190400-a56d-11eb-9498-e64422486d37.png)
![image](https://user-images.githubusercontent.com/50937667/115984586-849f9000-a56d-11eb-8b34-898cd2831d53.png)
Console access
![image](https://user-images.githubusercontent.com/50937667/115984877-cf6dd780-a56e-11eb-916e-5f803049a033.png)
3. removing default routing entry for internal network 10.x does not fix this issue. Only removing default for external IP 192.x.

**Expected behavior**
1. At a minimum make changes to routing table sticky so they do not disappear on reboot or if the node is recreated by harvester.
2. Improved routing configuration during setup

**Log**

**Environment:**
 - Harvester ISO version: v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal ): BM with NUC and dell M4800. 

**Additional context**

**Comment by futuretea** [comment]
@rrrai  Since the route of static network has higher priority (metric=0）than the route of dhcp network (metric=100)
So `ping google.com` will go through vlan100 network (I guess vlan id = 100, and the router or switch did not allow it to pass)Finally, the dns request fails.
You can test this by `ping google.com -I enp1s0` and `ping google.com -I enp2s0`

Here are some solutions：
option 1:  remove the default route for the vlan100 network, but it reappears after restarting the virtual machine
option 2: configure route by cloud-init, See [cloud-init-network-route](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#route)
option 3: configure the router or switch to allow packets with vlan id = 100 to pass through
option 4: use vlan1 (vlan id=1)

**Comment by rrrai** [comment]
@futuretea Thanks for the help. We should change this from bug to a question
Implemented option 2 and 4.
Added vlan1
![image](https://user-images.githubusercontent.com/50937667/116002697-8d6d8180-a5c0-11eb-85b9-0a8931883e18.png)
Created new vm 
![image](https://user-images.githubusercontent.com/50937667/116002733-bdb52000-a5c0-11eb-8b96-62fe7a245906.png)
network:
  version: 1
  config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: static
        address: 192.168.0.42/23
        gateway: 192.168.1.1
        dns_nameservers:
          - 192.168.1.1
          - 8.8.8.8
          - 8.8.4.4
          - 208.67.222.222
          - 208.67.220.220
      - type: route
        destination: 192.168.0.0/23
        gateway: 192.168.1.1
        metric: 1

Worked like a charm
![image](https://user-images.githubusercontent.com/50937667/116002824-14baf500-a5c1-11eb-897f-33d465e4640c.png)

Thanks again
