### ISSUE TITLE
[BUG] Can't edit the config of the host if saved after 30 sec or more.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#827]
**Describe the bug**
The host page doesn't allow modification if save button is clicked after 30 secs.

**To Reproduce**
1. Go to hosts page.
2. Click edit config.
3. Change the description.
4. Click save button after at least 30 sec.

<img width="1529" alt="Screen Shot 2021-05-05 at 4 36 49 PM" src="https://user-images.githubusercontent.com/60111667/117223278-3175da80-adc2-11eb-8628-245d2ce21ee6.png">

**Environment:**
 - Harvester ISO version:  0.2.0-rc5
 - Installation Mode: ISO/app-mode - ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Note**
Haven't checked which parameter is getting change in short span of time and causing the problem.

**Comment by guangbochen** [comment]
This is because the backup controller is still reconciling the object while the user clicks to edit the object, this is a common issue for both rancher and the harvester dashboard, as a temporary workaround user will need to cancel and click edit again.

As an enhancement, we may add a `refresh` button at the end of the message to allow the user to refresh the object without leaving/reloading the page manually.

**Comment by guangbochen** [comment]
close as this is a rancher dashboard common behaviour.
