### ISSUE TITLE
Website doesn't show up well on mobile

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#853]
![Screenshot_20210511-111222](https://user-images.githubusercontent.com/3344618/117864640-e0df0100-b249-11eb-9cc0-2995b1bb9f99.png)

![Screenshot_20210511-111215](https://user-images.githubusercontent.com/3344618/117864649-e3d9f180-b249-11eb-95cb-4d75ba616519.png)

**Comment by noahgildersleeve** [comment]
Tested landing at [harvester](https://harvesterhci.io) page with safari Mobile on iOS `14.5.1`. It looked good. Are we just wanting to verify that the responsive page looks good on mobile? I ask because at a tablet resolution the text looks a little odd because it’s left-aligned instead of center. However, I’m not sure if that is in scope, or if that is the desired design.
![Greenshot 2021-06-04 09 57 41](https://user-images.githubusercontent.com/83787952/120837597-c122bc00-c51b-11eb-9c87-053bca9db8c8.png)

**Comment by juadk** [comment]
In addition, it looks good with brave and chrome on Android 11 too.

**Comment by guangbochen** [comment]
I think this is looking fine, let me know if u have any additional concerns.

**Comment by noahgildersleeve** [comment]
Closing as done.
