### ISSUE TITLE
[Question] Run on top of existing baremetal k8s clustee

### ISSUE THREAD

**Issue by michaelandrepearce** [harvester/harvester#880]
I have existing baremetal k8s cluster with longhorn. Can i deploy longhorn on top of an existing baremetal cluster. So i can get VM support on an existing bare metal cluster.

**Comment by guangbochen** [comment]
Yes, you can test it using the [dev-mode installation](https://docs.harvesterhci.io/v0.2/dev/dev-mode/#option-1-install-using-helm), however, because this is a development mode so you may encounter different issues and need to fix them accordingly. 

for example some [pre-requisites](https://docs.harvesterhci.io/v0.2/dev/dev-mode/#requirements) of the installation.

**Comment by michaelandrepearce** [comment]
Will that become a maintained way of running it properly though? E.g. supported setup once support is available

**Comment by michaelandrepearce** [comment]
As in we are already heavily invested in rancher and longhorn with support and running on baremetal for perf reasons, but simply want to run some legacy vms we cannot migrate to containers on our baremetal rancher/longhorn setup

**Comment by guangbochen** [comment]
Unfortunately, Harvester is primarily focusing on bare-metal deployment with ISO image installation mode; the helm chart is only to be kept for dev and testing purposes for now, thanks.
