### ISSUE TITLE
[FEATURE] Support installing guest agent in template

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#885]
**Is your feature request related to a problem? Please describe.**

The VM template doesn't support installing guest agent by version 0.2.0. 
![image](https://user-images.githubusercontent.com/7421463/118934109-901f8480-b97c-11eb-990d-5265b5b79301.png)

**Describe the solution you'd like**

Add a box to support installing the guest agent.

**Describe alternatives you've considered**

**Additional context**

**Comment by n313893254** [comment]
![image](https://user-images.githubusercontent.com/18737885/125422378-a3878250-e55c-4732-a372-7119fc078058.png)
It's done.

**Comment by johnliu55tw** [comment]
## Note: To verify whether the guest agent is installed and enabled
- **Operating System** and **Kernel Release** in VM detail should correctly show the information
  ![image](https://user-images.githubusercontent.com/5047724/135587520-e2710ce1-d6a1-4c91-b968-3b14723c4028.png)
- Log into the VM and check whether service `qemu-guest-agent.service` is enabled and running
- Restart the VM and check whether the guest agent is running

## Test info
- Verified Harvester version: v0.3.0-rc1
- VM image for this test:
  - Ubuntu 20.04: http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img
  - openSUSE Leap 15.3: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2
  - CentOS 8: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2

## Test cases
For each OS image:
- Create VM template with guest agent installation enabled
  - [x] While creating the VM template, users can select "Install guest agent" in "Advanced Options" tab
- Create a VM from the VM Template with guest agent enabled
  - Create a VM from "Virtual Machines" page
    - [x] The VM should have guest agent installed and enabled
  - Create a VM from "Templates" page
    - [x] The VM should have guest agent installed and enabled

## Test results
- Ubuntu 20.04: Passed
- openSUSE Leap 15.3: Passed
- CentOS 8: **Failed**
  - With "Install guest agent" checked, the VM would have the latest `qemu-guest-agent` installed and running (checked via `systemctl`). However, the GUI shows "Guest agent required":
  ![image](https://user-images.githubusercontent.com/5047724/135799270-7de2ace2-db87-4dac-9b28-2dca39c979a0.png) Bug: https://github.com/harvester/harvester/issues/1344

## Comments
### Install guest agent is not select when using VM Templates
While creating the VM, selecting the VM template automatically populates "Cloud Config -> User Data" area for installing the guest agent. However, the checkbox of "Install guest agent" is **not** checked automatically:
![image](https://user-images.githubusercontent.com/5047724/135589619-007d3ae1-8a11-42fb-9b47-8fd8b3999101.png)
### openSUSE Leap 15.3 and CentOS 8 both have `qemu-guest-agent` package installed regardless of Cloud Config
Create a VM with the abovementioned openSUSE Leap 15.3 and CentOS 8 images would have package `qemu-guest-agent` installed automatically regardless of whether "Install guest agent" is selected.

### CentOS 8 with "Install guest agent" enabled cannot show correct information from the guest agent

Sometimes the GUI failed to show _Operating System_ and _Kernel Release_ information correctly (https://github.com/harvester/harvester/issues/1344). However, this bug is not related to this feature because qemu-guest-agent is installed correctly on the VM.

**Comment by yasker** [comment]
@johnliu55tw It's fine if the VM template already contains the guest agent installation as a part of the template.

Can you also test opensuse leap? as well as centos.

If we found issue regarding certain OS, please file another issue to track those.

**Comment by johnliu55tw** [comment]
@yasker Additionally verified on these image and updated the comment above:
- openSUSE Leap 15.3: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2
- CentOS 8: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2

CentOS 8 has a weird behavior (https://github.com/harvester/harvester/issues/1344) but it's unrelated to this feature IMO so I'm closing this feature. Let me know if you have any other comments.
