### ISSUE TITLE
[FEATURE] Add ability to remove/reassign the first volume on a VM

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#905]
**Is your feature request related to a problem? Please describe.**

Add ability to reassign the first volume of a VM to an existing volume during VM creation.
**Describe the solution you'd like**

You should be able to change the first volume of a new VM during creation besides changing the template
**Describe alternatives you've considered**

You could also add the ability to remove the first entry and add another one. There could be validation that you need at least one volume to be able to create the VM.
**Additional context**

If you want to make a VM with an existing volume you can't add the default volume since you can't make it point to an existing volume and you can't remove it. That means that every VM with an existing volume has to have another volume that doesn't do anything. I've been assigning them to CDRoms.
![Greenshot 2021-05-26 10 19 01](https://user-images.githubusercontent.com/83787952/119719643-e3328500-be1d-11eb-9840-9e29ccc5e3ce.png)
.

**Comment by guangbochen** [comment]
By design, the first volume will always be the VM image volume, in order to support users to customize the first volume, we should:
- allow the user to either add or delete the first volumes from the UI, but at least one image volume or existing volume is required when creating a new VM.
- users can only add the first volume with the type of existing image volume or a VM image
- users can't change the image either from the basics tab or volumes tab if it is an existing image volume
- when the user modifies the images, set the filetype to `cd-rom` when the OS image name is ended with the`.iso` extension.

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Verified as fixed.
