### ISSUE TITLE
[BUG] Migrate button should say migrate not create

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#906]
**Describe the bug**

The button to complete a live migration says create, not migrate
**To Reproduce**
1. Take a turned on VM
2. Select migrate from the triple dot menu
3. Check label on button
**Expected behavior**

The button should say migrate
**Support bundle**

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL160G9

**Additional context**
The button seems to work fine, but the label should be updated.
![119910231-8b724780-bf0b-11eb-8627-1a9ca2687d78](https://user-images.githubusercontent.com/83787952/120042275-9934d500-bfbe-11eb-8006-cc292447bc84.jpg)

**Comment by juadk** [comment]
Tested successfully in build master-6d5c7df2-head ​with ISO mode and 5 nodes cluster.
![Screenshot from 2021-06-16 16-45-13](https://user-images.githubusercontent.com/6025636/122241159-9f81e700-cec2-11eb-82ef-c6b1db72acb3.png)
The label is now Migrate instead of Create.

After clicking on Migrate, the VM moved to the selected node successfully.
