### ISSUE TITLE
[BUG] Guest agent install configuration is covered

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#908]
**Describe the bug**

The guest agent install configuration will be covered if users check the box for installing the guest agent before choosing a cloud-init template.
![image](https://user-images.githubusercontent.com/7421463/119946425-31d05280-bfc9-11eb-8018-c96868e76844.png)

**To Reproduce**
1. Go to the create Virtual Machine page.
2. Go to the advanced options tab.
3. Check the box for installing the guest agent.
4. Choose the cloud-init template.

**Expected behavior**

The guest agent install configuration is always not be covered.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by yasker** [comment]
There is a PR related to this issue. Let's check if it has been fixed yet. If not, we can punt it to v1.0.0.

**Comment by TachunLin** [comment]
@yasker 
After checking, this issue still exists on v0.3.0-rc1 and newer. 
Move it to review pipeline for considering punt to v1.0.0 milestone

### Result
if users check the box "**installing guest agent**" before choosing a predefined user data template. 
The guest agent install configuration will be covered

### Test Information
***
* Test Environment: bare metal 3 nodes and qemu/KVM 1 nodes
* Harvester version: v0.3.0-rc1, master-82506f55-head

### Verify Steps
Pre-requisite: Create user data cloud-config template 

1. Open Create Virtual Machine page. 
2. Click Advanced Options
3. Check "install guest agent" 
4. Choose the cloud-init user data template.

***
For replication steps please refer to short video clip 
[Guest_agent_config_covered](https://drive.google.com/file/d/1AEoi3udfIx6F7cKADiyqyRW0iSdETGFR/view?usp=sharing)

**Comment by yasker** [comment]
Move to v1.0.0 due to validation failed in v0.3.0.

**Comment by TachunLin** [comment]
@WuJun2016 
Verified on master-d05a6cc7-head. Move this issue to review stage
Since It looks like the install guest agent configuration can still be covered by cloud-init template with check box auto unchecked

I think we need to confirm with @yaocw2020 if the following result is the expected behavior. 

### Result
Now the guest agent install configuration will be checked as default 
![image](https://user-images.githubusercontent.com/29251855/138996790-49a4d40a-45da-43a1-a249-b3366a5d597f.png) 

if we select the user data template, the guest install configuration will be covered
And the install guest agent check box will be auto unchecked 
![image](https://user-images.githubusercontent.com/29251855/138997023-be49fe1e-104d-4d54-8813-729f47e953a6.png)

Check the install guest agent again it will append configuration to existing cloud-init template
![image](https://user-images.githubusercontent.com/29251855/138997447-9425235f-6750-4aa1-94cb-bb4722c75558.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-d05a6cc7-head


### Verify Steps

Pre-requisite: Create user data cloud-config template

1. Open Create Virtual Machine page.
2. Click Advanced Options
3. Choose the cloud-init user data template.
4. Check the install guest agent

**Comment by WuJun2016** [comment]
I think that's what we want:
We now install the quest agent by default
If the user selects a template, we will judge whether the template has quest agent installed according to the content in the template. If so, the checkbox of guest agent will be checked automatically, otherwise the checkbox will be cancelled.  @TachunLin   cc @yaocw2020

**Comment by TachunLin** [comment]
@WuJun2016, I agree with the design concept.  
I think this issue depends on @yaocw2020, @guangbochen can agree with the current behavior then proceed to next step.

**Comment by guangbochen** [comment]
the above UX is looking good to me, please feel free to close it @TachunLin .

**Comment by TachunLin** [comment]
Close this issue since we have finalized agreement to the UX design
