### ISSUE TITLE
[FEATURE] Add Harvester API extension to the Rancher API

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#922]
**Is your feature request related to a problem? Please describe.**
Add Harvester API extension to the Rancher API, so that Rancher can do reverse proxy of the Harvester API

**Describe the solution you'd like**
Uses Rancher APIExtension mechanism to provide rancher and Harvester API integration

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by gitlawr** [comment]
These are the issues I've found so far
~~1. I'm trying to register an apiRoot with id `v1/harvester`, so that APIs are served under /v1/harvester/some.apigroup.io.resources while the rest like schemas is compatible.~~
~~The `X-API-URL-Prefix` header is added as `/v1/harvester` in https://github.com/rancher/rancher/blob/92b822fb2e1437a7bacb7a5a65ab5fc02608a7f3/pkg/api/steve/aggregation/aggregation.go#L103
Then it becomes the prefix in https://github.com/rancher/apiserver/blob/f943376c4b42cd1c38acc4bd085aa7bf44305b64/pkg/urlbuilder/base.go#L14
As a result, the `/v1/harvester` path is duplicated and the resource link becomes `https://<server-url>/v1/harvester/v1/harvester/some.apigroup.resources`~~
![image](https://user-images.githubusercontent.com/5697937/123079866-e89be300-d44e-11eb-9f03-37148b0227aa.png)

~~I would expect the prefix to be `/k8s/cluster/c-xxx`~~
Fixed in master

~~2. The aggregation client reports~~
~~time="2021-06-21T03:29:18Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.8, not 10.43.45.61"~~
Edit: Fixed in the latest master


~~3. I try to import harvester with embedded rancher to a central Rancher to test how that works. Cluster importing is not working on master-head(blocked by https://github.com/rancher/dashboard/issues/3120)~~ Edit: it works in master-c7f3cce7d50351db4f5d31493b172b1249799e5b-head

**Comment by yasker** [comment]
cc @ibuildthecloud

**Comment by gitlawr** [comment]
To test:
1. Install Harvester. Set the rancher-enabled setting to true. Check that Harvester APIs are served under both `<Rancher_URL>/k8s/clusters/local/v1/harvester` and `<Rancher_URL>/v1/harvester`
2. Install Harvester. Install an external Rancher(master-head). Import the Harvester cluster to the external Rancher. Check that Harvester APIs are served under `<Rancher_URL>/k8s/clusters/<cluster-id>/v1/harvester`
3. Do sanity check on the extension Harvester APIs. Check that CRUD virtualmachines/calling VM actions works.
4. Check authn/z on the APIs. Create Rancher users with different roles(admin,cluster member, project owner/member,readonly, etc.) and check that their access to the APIs comply with their permissions.
5. Check that basic operations in the UI are not broken.

**Comment by yasker** [comment]
@gitlawr 
> 4. Check authn/z on the APIs. Create Rancher users with different roles(admin,cluster member, project owner/member,readonly, etc.) and check that their access to the APIs comply with their permissions.

On test step 4: does it apply to both embedded Rancher and MCM (Multi-Cluster Management/external) Rancher?

**Comment by noahgildersleeve** [comment]
Tested with Rancher at master-head and harvester at master-ff3c1994-head. Import of harvester backend rancher was imported successfully into separate rancher install done via Docker install on `rancher/rancher:master-head`.  Tested at
1. <Rancher_URL>/k8s/clusters/local/v1/harvester`  on harvester rancher
2. `<Rancher_URL>/v1/harvester` on harvester rancher
3. `<Rancher_URL>/k8s/clusters/<cluster-id>/v1/harvester` on separate rancher

Created new VMs and verified that they showed up properly in both rancher instances.

**Comment by gitlawr** [comment]
To clarify, step 4 refers to the external Rancher users/APIs. Per discussion, we only support a single admin user in embedded Rancher.

**Comment by juadk** [comment]
Tested with Rancher at `master-head` and harvester at `master-ff3c1994-head`.
1. `<Rancher_URL>/k8s/clusters/local/v1/harvester` and `<Rancher_URL>/v1/harvester` OK
![image](https://user-images.githubusercontent.com/6025636/125041242-d352c580-e098-11eb-9aa3-d474b748de73.png)
![image](https://user-images.githubusercontent.com/6025636/125041330-e9f91c80-e098-11eb-89d8-c4ad656615a2.png)
2. With External Rancher:
curl to `https://<External_Rancher_URL/k8s/clusters/c-m-d6802fa2/v1/harvester` with API token
![image](https://user-images.githubusercontent.com/6025636/125041765-6855be80-e099-11eb-9614-5c0b60f55610.png)
3. Tested VMs creation, stop/start, restart, backup, restore, live migration
4. - Create a user in the external Rancher UI
![image](https://user-images.githubusercontent.com/6025636/125082665-cac5b380-e0c7-11eb-9924-74e2237dd61f.png)
Then, I added my user1  as a cluster member of the harvester cluster and I played by attributing different roles like:
![image](https://user-images.githubusercontent.com/6025636/125085291-b636ea80-e0ca-11eb-9e58-4d4c2baa9201.png)

**Base roles:**
      - Cluster owner / [cluster_owner_role.txt](https://github.com/harvester/harvester/files/6791648/cluster_owner_role.txt)
      - Cluster member / [cluster_member_role.txt](https://github.com/harvester/harvester/files/6791647/cluster_member_role.txt)
**Custom roles: (one by one)**
      - Create Projects / [create_project_role.txt](https://github.com/harvester/harvester/files/6791646/create_project_role.txt)
      - Manage Storage / [manage_storage_role.txt](https://github.com/harvester/harvester/files/6791645/manage_storage_role.txt)
      - Manage Cluster Backups / [cluster_backup_role.txt](https://github.com/harvester/harvester/files/6791642/cluster_backup_role.txt)
      - Manage Nodes / [manage_node_role.txt](https://github.com/harvester/harvester/files/6791644/manage_node_role.txt)
      - View Nodes / [view_node_role.txt](https://github.com/harvester/harvester/files/6791643/view_node_role.txt)

After each role assignment, I queried the API with my user API token to see how the permissions changed, from what I saw it looked good. You can check all the API responses above as attachments.
For instance, when I attached the Manage storage role, I saw the `persistentvolumes` link appeared in the API response. However, I didn't notice any difference between "Manage Nodes" and "View Nodes".

5. Check those basic operations in the UI are not broken.
Create / delete images: :heavy_check_mark: 
Create / delete volumes: :heavy_check_mark: 
Virtual machines and backup already checked above :heavy_check_mark: 
Create / delete / edit namespace: :heavy_check_mark: 
Enable maintenance mode for a node where a VM is hosted: :heavy_check_mark: 
  The VM's status changed to migrated

I don't close the issue right now, @gitlawr @noahgildersleeve. please,  tell me if it's ok for you, it was a hard time to understand the tests around APIs :smile:
