### ISSUE TITLE
Error connecting to Websocket message after only a few minutes

### ISSUE THREAD

**Issue by wjimenez5271** [harvester/harvester#967]
**Describe the bug**
After logging into the UI, I get a "Error connecting to Websocket" after only a few minutes of being logged in. Harvester v0.2.0
![Screen Shot 2021-06-21 at 3 07 38 PM](https://user-images.githubusercontent.com/322834/122833994-afbf0b00-d2a2-11eb-8acf-4d7eaa7e9f4a.png)

**Comment by WuJun2016** [comment]
@DaiYuzeng    Because we need merge to the upstream branch, our Harvester's notification component may not be needed, but whether to delete it depends on you. You can communicate with Vincent whether we should keep it (the upstream branch uses the growl component). Can you help refactor this part of the code.  thanks

**Comment by guangbochen** [comment]
close as of v0.3.0, please feel to re-open it if u encounter a similar issue.
